# Bibliotecas

## Sistema (os, makedirs, glob)

In [5]:
import os
from os import makedirs
from os import listdir
import glob

## Básicos (numpy, math, display, locale, time, random, re)

In [6]:
# !python -m pip install jupyter


# !python -m pip install IPython
from IPython.display import display

import math

# !python -m pip install numpy
import numpy as np

import locale
# locale.setlocale(locale.LC_ALL, "pt_BR.UTF-8")  # Use "" for auto, or force e.g. to "en_US.UTF-8"

import time
from datetime import datetime, timedelta, date

from pandas.tseries.offsets import BDay # para os dias úteis
# today = datetime.datetime.today()
# print(today - BDay(4)) # 4 dias úteis atrás

# # !python -m pip install random
import random
random.seed(42)

# !python -m pip install regex
import re

## Leitura e análise de dados (Excel, Pandas, Spark)

In [7]:
# !python -m pip install findspark

# !python -m pip install openpyxl
# import openpyxl

# !python -m pip install xlsxwriter
# import xlsxwriter

# !python -m pip install xlrd
# import xlrd

# !python -m pip install python-calamine
# import python_calamine


# !python -m pip install pandas
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
# pd.set_option('display.float_format', lambda x: '%.2f' % x)

## Finanças (yfinance, mplfinance)

In [8]:
# https://pypi.org/project/yfinance/
# https://github.com/ranaroussi/yfinance/wiki/Ticker

!python -m pip install yfinance
import yfinance as yf

!python -m pip install mplfinance
import mplfinance as mpf

# # Em R
# # https://cran.r-project.org/web/packages/BatchGetSymbols/index.html

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: yfinance in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (0.2.54)
Requirement already satisfied: pandas>=1.3.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: requests>=2.31 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2025.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (3.17.9)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (4.13.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from pandas>=1.3.0->yfinance) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (2025.1.31)
Requirement already satisfied: six>=1.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mplfinance in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (0.12.10b0)
Requirement already satisfied: matplotlib in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from mplfinance) (3.10.1)
Requirement already satisfied: pandas in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from mplfinance) (2.2.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (2.2.3)
Requirement already satisfied: packaging>=20.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from pandas->mplfinance) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from pandas->mplfinance) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib->mplfinance) (1.17.0)

## Visualização (matplotlib, seaborn, plotly)

In [ ]:
# !python -m pip install matplotlib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib import ticker
from matplotlib.ticker import FormatStrFormatter, StrMethodFormatter

# !python -m pip install seaborn
import seaborn as sns

# !python -m pip install plotly
# import plotly.graph_objects as go
# import plotly.express as px
# from plotly.subplots import make_subplots

# !python -m pip install graphviz
# import graphviz

Defaulting to user installation because normal site-packages is not writeable
Collecting graphviz
  Downloading graphviz-0.20.3-py3-none-any.whl.metadata (12 kB)
Downloading graphviz-0.20.3-py3-none-any.whl (47 kB)
Installing collected packages: graphviz
Successfully installed graphviz-0.20.3

# Funções

### Agrupar cada coluna (_agrupamento_cada_coluna_)

In [10]:
def agrupamento_cada_coluna(
    bd, 
    coluna_completa, 
    colunas_ignoradas = [], 
    ascending = False,
    imprime_tabelas = True,
    ):
    
    from IPython.display import display

    campos_com_erro = []
    dict_campos = {}

    colunas = bd.columns.drop(coluna_completa)

    if len(colunas_ignoradas) > 0:
        colunas = colunas.drop(colunas_ignoradas)
    
    for coluna in colunas:
        try: 
            temp_coluna = bd.fillna("(vazio)").groupby(coluna).count()[[coluna_completa]].rename(columns = {coluna_completa: "Quantidade"}).sort_values("Quantidade", ascending = ascending)

            if ascending == False:
                temp_coluna["%"] = temp_coluna["Quantidade"]/temp_coluna["Quantidade"].sum()
                temp_coluna["% acumulado"] = temp_coluna["%"].cumsum()
            
            if imprime_tabelas == True:
                display(temp_coluna)
                
            dict_campos[coluna] = temp_coluna
            # limpa(temp_coluna)
        
        except:
            campos_com_erro.append(coluna)
            #print("Campo " + coluna + " deu erro =/")
    
    return [campos_com_erro, dict_campos]

### Elimina colunas NA (_elimina_colunas_NA_)

In [11]:
def elimina_colunas_NA(
    base,
    imprime_colunas_vazias = False,
    imprime_colunas_completas = False,
    imprime_colunas_parciais = False,
    remove_da_base = True,
    retorna_parciais = False
    ):

    tamanho_da_base = len(base)

    colunas_vazias = []
    colunas_completas = []
    colunas_parciais = []

    for coluna in base.columns:
        tamanho_da_coluna = len(base[base[coluna].isna()])
        if tamanho_da_coluna == tamanho_da_base:
            # print(coluna)
            colunas_vazias.append(coluna)
        elif tamanho_da_coluna == 0:
            colunas_completas.append(coluna)
        else:
            colunas_parciais.append(coluna)

    if imprime_colunas_vazias == True:
        if len(colunas_vazias) == 0:
            print("Não há colunas NA")
        else:
            print("Colunas vazias: " + str(colunas_vazias))
            
    if imprime_colunas_completas == True:
        if len(colunas_completas) == 0:
            print("Não há colunas completas")
        else:
            print("Colunas completas: " + str(colunas_completas))
    
    if imprime_colunas_parciais == True:
        if len(colunas_parciais) == 0:
            print("Não há colunas parciais")
        else:
            print("Colunas parciais: " + str(colunas_parciais))

    if remove_da_base == True:
        base = base.drop(colunas_vazias, axis = 1)
    
    if retorna_parciais == True:
        return [base, colunas_parciais]
    else:
        return base

### Análise exploratória básica de todos os campos da base - MUITO ÚTIL (_analise_exploratoria_)

In [12]:
def analise_exploratoria(
    bd,
    imprime_todas_colunas = False,
    imprime_info_colunas = True,
    imprime_colunas_vazias = False,
    imprime_colunas_completas = False,
    imprime_colunas_parciais = False,
    remove_da_base = True,
    retorna_parciais = False,
    # detalhar_colunas_parciais = True,
    colunas_ignoradas = []
    ):

    # COMEÇANDO PELAS COLUNAS DISPONÍVEIS E INFO
    if imprime_todas_colunas == True:
        display(bd.columns)
    
    if imprime_info_colunas == True:
        for i in range(int(np.ceil(len(bd.columns)/20))):
            display(bd.iloc[:, (i*20):min((i+1)*20, len(bd.columns))].info())

    # DETALHAMENTO DE QUAIS COLUNAS SÃO NA OU PARCIAIS
    if retorna_parciais == True:
        [bd_semNA, colunas_parciais] = elimina_colunas_NA(
            bd,
            imprime_colunas_vazias = imprime_colunas_vazias,
            imprime_colunas_completas = imprime_colunas_completas,
            imprime_colunas_parciais = imprime_colunas_parciais,
            remove_da_base = remove_da_base,
            retorna_parciais = True
        )

        print(colunas_parciais)

        # if detalhar_colunas_parciais == True:
            # for coluna in colunas_parciais:
                # print(coluna)
                # print("# " + coluna + ": " + str(len(colunas_parciais[colunas_parciais[coluna].isna()])))
    else:
        colunas_parciais = []

        bd_semNA = elimina_colunas_NA(
            bd,
            imprime_colunas_vazias = imprime_colunas_vazias,
            imprime_colunas_completas = imprime_colunas_completas,
            imprime_colunas_parciais = imprime_colunas_parciais,
            remove_da_base = remove_da_base,
            retorna_parciais = retorna_parciais
        )

    [campos_com_erro, colunas_agrupadas] = agrupamento_cada_coluna(
        bd.reset_index(), 
        coluna_completa = bd_semNA.drop(colunas_parciais, axis = 1).reset_index().columns[0],
        colunas_ignoradas = colunas_ignoradas
    )
    
    if retorna_parciais == True:
        return [bd_semNA, colunas_parciais, colunas_agrupadas, campos_com_erro]
    else:
        return [bd_semNA, colunas_agrupadas, campos_com_erro]

## Treinamento de modelos (_treina_e_roda_modelo_)

In [167]:
def treina_e_roda_modelo(
    dados,
    colunas_treino,
    coluna_resultado,
    
    estimador = "SVC",
    proporcao = 0.25,
    SEED = 42,
    print_tamanho = True,
    print_score = True,
    print_confusion_matrix = False,
    
    DummyClassifier__estrategia = None,
    
    DecisionTreeClassifier__retornar_visualizacao = False,
    DecisionTreeClassifier__max_depth = None,
    
    RandomForestClassifier__n_estimators = 100,
    
    feature_selection = None,
    scaler = None,
):
    from sklearn.model_selection import train_test_split
    # from sklearn.preprocessing import StandardScaler
    
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier
    # from sklearn.svm import LinearSVC
    from sklearn.svm import SVC
    from sklearn.naive_bayes import MultinomialNB
    from sklearn.dummy import DummyClassifier
    
    # from sklearn.metrics import accuracy_score
    from sklearn.metrics import confusion_matrix
    from sklearn.tree import export_graphviz
    import graphviz
    import os
    os.environ["PATH"] += os.pathsep + 'C:/Program Files/Graphviz/bin' # https://stackoverflow.com/questions/35064304/runtimeerror-make-sure-the-graphviz-executables-are-on-your-systems-path-aft

    np.random.seed(SEED)


    # DIVIDE A BASE NAS PORÇÕES DE TESTE E TREINO, X E Y
    [original_x_treino, original_x_teste, y_treino, y_teste] = train_test_split(
        dados.loc[:, colunas_treino],
        dados.loc[:, coluna_resultado],
        test_size = proporcao,
        # stratify = dados.loc[:, coluna_resultado] # mesma proporção de y
    )
    
    
    # SELECIONA AS FEATURES COM BASE NO ARGUMENTO E REESCALA SE NECESSÁRIO
    if feature_selection is not None:
        feature_selection.fit(original_x_treino, y_treino)
        x_treino = feature_selection.transform(original_x_treino)
        x_teste = feature_selection.transform(original_x_teste)
        
    if (scaler is None) | ((estimador is not None) * (estimador != "DecisionTreeClassifier")): # Não é necessário reescalar para árvore de decisão
        if feature_selection is None:
            x_treino = original_x_treino
            x_teste = original_x_teste
    else:
        if feature_selection is None:
            scaler.fit(original_x_treino)
            x_treino = scaler.transform(original_x_treino)
            x_teste = scaler.transform(original_x_teste)
        else:
            scaler.fit(x_treino)
            x_treino = scaler.transform(x_treino)
            x_teste = scaler.transform(x_teste)


    # IMPRIME O TAMANHO DE CADA PORÇÃO
    if print_tamanho == True:
        print("Tamanho treino: " + str(len(x_treino)))
        print("Tamanho teste: " + str(len(x_teste)))

    

    # INSTANCIA O ESTIMADOR ESCOLHIDO. SE NÃO HOUVER ESTIMADOR, RETORNA APENAS AS PORÇÕES SELECIONADAS E REESCALADAS
    if estimador is None:
        return [
            [original_x_treino, original_x_teste, y_treino, y_teste], 
            [x_treino, x_teste],
            feature_selection
        ]

    elif estimador == "SVC":
        modelo = SVC(gamma = "auto")
    
    elif estimador == "RandomForestClassifier":
        # print(estimador)
        modelo = RandomForestClassifier(n_estimators = RandomForestClassifier__n_estimators)
        print(modelo)

    elif estimador == "DecisionTreeClassifier":
        if DecisionTreeClassifier__max_depth is None:
            modelo = DecisionTreeClassifier()
        else:
            modelo = DecisionTreeClassifier(max_depth = DecisionTreeClassifier__max_depth)

    elif estimador == "MultinomialNB":
        modelo = MultinomialNB()
        
    elif estimador == "Dummy":
        if DummyClassifier__estrategia is None:  
            modelo = DummyClassifier()
        else:
            modelo = DummyClassifier(strategy = DummyClassifier__estrategia)
        
    else:
        return print("Estimador " + estimador + " não encontrado")
    
    
    # TREINA O ESTIMADOR ESCOLHIDO
    try:
        modelo.fit(x_treino, y_treino)
        print(modelo)
    except ValueError:
        return [print("Não foi possível treinar o modelo escolhido"), modelo]

    # AVALIA O MODELO
    
    # previsoes = modelo.predict(x_teste)
    # taxa_de_acerto = accuracy_score(y_teste, previsoes)

    taxa_de_acerto = modelo.score(x_teste, y_teste)
    
    if print_score == True:
        print("Taxa de acerto do modelo " + estimador + ": {:.2%}".format(taxa_de_acerto))
        
    if print_confusion_matrix == True:
        matriz_confusao = confusion_matrix(y_teste, modelo.predict(x_teste))
        # print(matriz_confusao)
        sns.set(font_scale = 2)
        sns.heatmap(matriz_confusao, annot = True, fmt = "d").set(xlabel = "Predição", ylabel = "Real")
        plt.show()
    
    # RETORNA VISÃO GRÁFICA PARA O DECISION TREE CLASSIFIER
    if (DecisionTreeClassifier__retornar_visualizacao == True) * (estimador == "DecisionTreeClassifier"):
        # return export_graphviz(modelo, out_file = None)
        dot_data = export_graphviz(
            modelo, 
            feature_names = colunas_treino,
            filled = True,
            rounded = True,
            class_names = ["Não", "Sim"]
        )
        grafico = graphviz.Source(dot_data)
        return grafico
    
    # RETORNA BASES E MODELO PARA OUTROS ESTIMADORES
    return [
        modelo, 
        [original_x_treino, original_x_teste, y_treino, y_teste], 
        [x_treino, x_teste], 
        feature_selection,
        # previsoes, 
        taxa_de_acerto
    ]

# Leitura dos dados

In [13]:
var_caminho = r"C:\Users\ricardopeloi\OneDrive - falconi365\Data Science\O_Mais_Novo_Day_Trader_do_Brasil\o_mais_novo_day_trader_do_brasil\Bases"
# var_arquivo = r"\Bases\Lista de ações Análise 2025-03-16.xlsx"

lista_arquivos = listdir(var_caminho)
lista_arquivos_analises = []
for arquivo in lista_arquivos:
    if arquivo.find(" Análise") > 0:
        lista_arquivos_analises.append(datetime.strptime(arquivo.split(" Análise ")[1].split(".xls")[0], "%Y-%m-%d"))

var_arquivo_mais_recente = "/Lista de ações Análise " + max(lista_arquivos_analises).strftime("%Y-%m-%d") + ".xlsx"
# print(var_arquivo_mais_recente)

bd_dados_completos = pd.read_excel(var_caminho + var_arquivo_mais_recente).set_index("Ticker")
bd_dados_completos

,Nome da Empresa,Volume no último dia útil (lido em 30/03/2025),industry,sector,fullTimeEmployees,dividendRate,dividendYield,exDividendDate,payoutRatio,beta,...,2025-03-28; Low,2025-03-28; Close,2025-03-28; Volume,2025-03-28; Dividends,2025-03-28; Stock Splits,2025-03-28; HLC,Alfa HLC; últimos 13 dias,Alfa HLC; últimos 55 dias,Martelos,Tipos de Martelos
Ticker,,,,,,,,,,,,,,,,,,,,,
IFCM3,Infracommerce,131606600,Specialty Business Services,Industrials,"2,462.00",NaN,NaN,NaN,0.00,0.54,...,0.08,0.11,131606600,0.00,0,0.10,0.00,0.00,"2025-02-03, 2025-02-04, 2025-02-05, 2025-02-06...","Subida, Subida, Subida, Subida, Subida, Subida..."
HAPV3,Hapvida,68474600,Insurance - Life,Financial Services,NaN,NaN,NaN,"1,640,649,600.00",0.00,0.72,...,2.23,2.30,68474600,0.00,0,2.29,0.01,-0.01,"2025-02-10, 2025-02-13, 2025-02-17, 2025-02-19...","Subida, Subida, Subida, Descida, Subida, Subid..."
COGN3,Cogna,63030500,Education & Training Services,Consumer Defensive,"24,187.00",NaN,NaN,"1,574,294,400.00",0.00,1.13,...,2.01,2.12,63030500,0.00,0,2.09,0.03,0.01,"2025-02-03, 2025-02-04, 2025-02-07, 2025-02-12...","Subida, Descida, Subida, Descida, Descida, Sub..."
CVCB3,CVC,43117200,Travel Services,Consumer Cyclical,NaN,NaN,NaN,"1,577,318,400.00",0.00,NaN,...,2.17,2.26,43119000,0.00,0,2.28,0.04,0.01,"2025-02-10, 2025-02-27, 2025-03-05, 2025-03-12...","Subida, Subida, Subida, Subida, Subida, Descid..."
ITSA4,Itaúsa,40890700,Conglomerates,Industrials,NaN,0.80,8.31,"1,748,822,400.00",0.26,0.69,...,9.55,9.62,40891100,0.00,0,9.63,0.06,0.02,"2025-02-03, 2025-02-10, 2025-02-11, 2025-02-17...","Descida, Subida, Subida, Subida, Descida, Subi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BOBR4,Bombril,29000,Household & Personal Products,Consumer Defensive,"2,390.00",NaN,NaN,NaN,0.00,1.10,...,1.68,1.74,29000,0.00,0,1.73,0.00,-0.01,"2025-02-03, 2025-02-04, 2025-02-17, 2025-02-24...","Subida, Descida, Descida, Subida, Subida, Subi..."
RAPT3,Randon,27700,Farm & Heavy Construction Machinery,Industrials,"16,727.00",0.05,0.58,"1,746,144,000.00",0.29,1.11,...,8.04,8.08,27700,0.00,0,8.19,-0.00,0.01,"2025-02-05, 2025-03-10, 2025-03-12, 2025-03-13...","Subida, Subida, Subida, Subida, Descida, Subida,"
OIBR4,Oi,26900,Telecom Services,Communication Services,NaN,NaN,NaN,"1,380,499,200.00",0.00,1.75,...,7.56,7.56,26900,0.00,0,7.78,-0.02,-0.01,"2025-02-11, 2025-02-14, 2025-02-20, 2025-02-21...","Descida, Descida, Descida, Subida, Descida, Su..."
LOGN3,Log-In,24900,Marine Shipping,Industrials,NaN,NaN,NaN,"1,237,334,400.00",0.00,0.69,...,20.65,21.06,24900,0.00,0,20.97,-0.01,0.02,"2025-02-04, 2025-02-12, 2025-03-06, 2025-03-07...","Subida, Subida, Subida, Subida, Descida,"
NGRD3,Neogrid,24600,Software - Application,Technology,NaN,0.14,0.61,"1,713,744,000.00",1.30,0.47,...,21.47,22.37,24600,0.00,0,22.18,0.03,0.11,"2025-02-05, 2025-02-06, 2025-03-05, 2025-03-11...","Subida, Descida, Descida, Subida, Subida, Desc..."

# Análise Exploratória

## Confirmar se coluna Ticker está duplicada

In [14]:
bd_dados_completos[[item for item in bd_dados_completos.columns.to_list() if "Ticker" in item]]

Empty DataFrame
Columns: []
Index: [IFCM3, HAPV3, COGN3, CVCB3, ITSA4, ABEV3, VAMO3, VALE3, MGLU3, GFSA3, BBDC4, ITUB4, PETR4, B3SA3, POMO4, LREN3, USIM5, NTCO3, ASAI3, PETZ3, BBAS3, BHIA3, RAIZ4, ANIM3, CCRO3, RAIL3, CMIG4, ELET3, AZUL4, JHSF3, MRVE3, LWSA3, AMOB3, AMER3, CSNA3, SIMH3, CSAN3, VBBR3, GGBR4, BEEF3, CBAV3, RADL3, CRFB3, CPLE6, PCAR3, BPAC11, EQTL3, GOAU4, ECOR3, BRFS3, RENT3, TIMS3, LJQQ3, BRAV3, PETR3, RCSL4, OIBR3, JBSS3, MOVI3, GMAT3, BBDC3, CYRE3, CMIN3, YDUQ3, SUZB3, ARML3, KLBN11, AURE3, SMFT3, RAPT4, EMBR3, GOLL4, ENEV3, AZEV4, MRFG3, CPLE3, ONCO3, VVEO3, WEGE3, PRIO3, BRKM5, STBP3, CXSE3, ALOS3, MULT3, FLRY3, UGPA3, GGPS3, HYPE3, RDOR3, VIVA3, SEER3, SAPR4, LIGT3, BBSE3, BRAP4, INTB3, KLBN4, SANB11, CEAB3, ...]

[252 rows x 0 columns]

## Remover outras colunas que possam se repetir (uma para cada dia)

In [15]:
lista_ignorados_datas = ["Ticker" , "HLC" , "Stock Splits" , "Dividends" , "Volume" , "Close" , "Low" , "High" , "Open"]
# lista_ignorados_datas[0]

lista_colunas_ignoradas_datas = []
for ignorado_datas in lista_ignorados_datas:
    lista_colunas_ignoradas_datas.append([item for item in bd_dados_completos.columns.to_list() if ignorado_datas in item])
# lista_colunas_ignoradas_datas

In [16]:
## Essas colunas já foram removidas no arquivo 'receber_lista_atualizada_tickers.py'

# lista_ignorados = ["industryKey", "industryDisp", "sectorKey", "volume",
#                    "sectorDisp", "regularMarketVolume", "SandP52WeekChange"]

# # lista_colunas_ignoradas_datas = []
# for ignorado_datas in lista_ignorados_datas:
#     lista_ignorados = lista_ignorados + [item for item in bd_dados_completos.columns.to_list() if ignorado_datas in item]
# print(lista_ignorados)


[bd_semNA, colunas_parciais, colunas_agrupadas, campos_com_erro] = analise_exploratoria(
    # bd_dados_completos.drop(lista_ignorados, axis = 1),
    bd_dados_completos,
    imprime_todas_colunas = False,
    # imprime_info_colunas = True,
    imprime_info_colunas = False,
    imprime_colunas_vazias = False,
    imprime_colunas_completas = False,
    imprime_colunas_parciais = False,
    # remove_da_base = True,
    retorna_parciais = True,
    # detalhar_colunas_parciais = True,
    colunas_ignoradas = []
    )

['fullTimeEmployees', 'dividendRate', 'dividendYield', 'exDividendDate', 'payoutRatio', 'beta', 'trailingPE', 'forwardPE', 'priceToSalesTrailing12Months', 'profitMargins', 'trailingEps', 'forwardEps', 'lastSplitFactor', 'lastSplitDate', 'enterpriseToRevenue', 'enterpriseToEbitda', 'lastDividendValue', 'lastDividendDate', 'recommendationMean', 'numberOfAnalystOpinions', 'totalCash', 'totalCashPerShare', 'ebitda', 'totalDebt', 'quickRatio', 'currentRatio', 'totalRevenue', 'debtToEquity', 'revenuePerShare', 'returnOnAssets', 'returnOnEquity', 'grossProfits', 'freeCashflow', 'operatingCashflow', 'earningsGrowth', 'revenueGrowth', 'grossMargins', 'ebitdaMargins', 'epsTrailingTwelveMonths', 'epsForward', 'epsCurrentYear', 'priceEpsCurrentYear']

                 Quantidade    %  % acumulado
Nome da Empresa
Banco Santander           3 0.01         0.01
Taesa                     3 0.01         0.02
Sanepar                   3 0.01         0.04
Klabin                    3 0.01         0.05
Eletrobras                2 0.01         0.06
...                     ...  ...          ...
Wilson Sons               1 0.00         0.98
Wiz Soluções              1 0.00         0.99
YDUQS                     1 0.00         0.99
Zamp                      1 0.00         1.00
Ânima Educação            1 0.00         1.00

[228 rows x 3 columns]

                                                Quantidade    %  % acumulado
Volume no último dia útil (lido em 30/03/2025)
47000                                                    2 0.01         0.01
172600                                                   2 0.01         0.02
465100                                                   2 0.01         0.02
27700                                                    1 0.00         0.03
24900                                                    1 0.00         0.03
...                                                    ...  ...          ...
40890700                                                 1 0.00         0.98
43117200                                                 1 0.00         0.99
63030500                                                 1 0.00         0.99
68474600                                                 1 0.00         1.00
131606600                                                1 0.00         1.00

[249 rows x 3 columns]

                                         Quantidade    %  % acumulado
industry
Banks - Regional                                 13 0.05         0.05
Real Estate Services                             12 0.05         0.10
Real Estate - Development                        11 0.04         0.14
Utilities - Renewable                            10 0.04         0.18
Utilities - Regulated Electric                    9 0.04         0.22
...                                             ...  ...          ...
Personal Services                                 1 0.00         0.98
Specialty Chemicals                               1 0.00         0.99
Utilities - Independent Power Producers           1 0.00         0.99
Travel Services                                   1 0.00         1.00
Trucking                                          1 0.00         1.00

[86 rows x 3 columns]

                        Quantidade    %  % acumulado
sector
Industrials                     49 0.19         0.19
Consumer Cyclical               37 0.15         0.34
Utilities                       28 0.11         0.45
Basic Materials                 25 0.10         0.55
Real Estate                     24 0.10         0.65
Financial Services              23 0.09         0.74
Consumer Defensive              19 0.08         0.81
Healthcare                      17 0.07         0.88
Communication Services          11 0.04         0.92
Technology                      11 0.04         0.97
Energy                           8 0.03         1.00

                   Quantidade    %  % acumulado
fullTimeEmployees
 (vazio)                  163 0.65         0.65
6,047.00                    3 0.01         0.66
55,646.00                   3 0.01         0.67
4,396.00                    2 0.01         0.68
16,027.00                   2 0.01         0.69
...                       ...  ...          ...
64,616.00                   1 0.00         0.98
87,000.00                   1 0.00         0.99
100,000.00                  1 0.00         0.99
126,832.00                  1 0.00         1.00
190,000.00                  1 0.00         1.00

[78 rows x 3 columns]

              Quantidade    %  % acumulado
dividendRate
 (vazio)              65 0.26         0.26
0.07                   6 0.02         0.28
0.59                   5 0.02         0.30
0.05                   5 0.02         0.32
0.80                   5 0.02         0.34
...                  ...  ...          ...
4.64                   1 0.00         0.98
5.64                   1 0.00         0.99
4.94                   1 0.00         0.99
5.77                   1 0.00         1.00
7.49                   1 0.00         1.00

[114 rows x 3 columns]

               Quantidade    %  % acumulado
dividendYield
 (vazio)               65 0.26         0.26
0.91                    2 0.01         0.27
1.78                    2 0.01         0.27
7.54                    2 0.01         0.28
13.15                   2 0.01         0.29
...                   ...  ...          ...
18.94                   1 0.00         0.98
24.06                   1 0.00         0.99
46.93                   1 0.00         0.99
120.86                  1 0.00         1.00
142.42                  1 0.00         1.00

[178 rows x 3 columns]

                  Quantidade    %  % acumulado
exDividendDate
 (vazio)                  20 0.08         0.08
1,735,776,000.00           9 0.04         0.12
1,743,465,600.00           7 0.03         0.14
1,741,219,200.00           7 0.03         0.17
1,745,971,200.00           7 0.03         0.20
...                      ...  ...          ...
1,746,489,600.00           1 0.00         0.98
1,747,872,000.00           1 0.00         0.99
1,746,576,000.00           1 0.00         0.99
1,748,217,600.00           1 0.00         1.00
1,751,241,600.00           1 0.00         1.00

[121 rows x 3 columns]

             Quantidade    %  % acumulado
payoutRatio
0.00                 73 0.29         0.29
 (vazio)              7 0.03         0.32
0.29                  3 0.01         0.33
0.28                  2 0.01         0.34
0.30                  2 0.01         0.35
...                 ...  ...          ...
2.05                  1 0.00         0.98
2.91                  1 0.00         0.99
31.95                 1 0.00         0.99
95.32                 1 0.00         1.00
162.73                1 0.00         1.00

[165 rows x 3 columns]

          Quantidade    %  % acumulado
beta
 (vazio)          42 0.17         0.17
0.61               4 0.02         0.18
0.44               3 0.01         0.19
0.54               3 0.01         0.21
0.45               3 0.01         0.22
...              ...  ...          ...
1.72               1 0.00         0.98
1.90               1 0.00         0.99
1.92               1 0.00         0.99
1.93               1 0.00         1.00
1.96               1 0.00         1.00

[184 rows x 3 columns]

            Quantidade    %  % acumulado
trailingPE
 (vazio)            57 0.23         0.23
inf                  3 0.01         0.24
7.00                 2 0.01         0.25
5.61                 2 0.01         0.25
0.13                 1 0.00         0.26
...                ...  ...          ...
76.09                1 0.00         0.98
136.12               1 0.00         0.99
95.50                1 0.00         0.99
595.00               1 0.00         1.00
409.00               1 0.00         1.00

[192 rows x 3 columns]

           Quantidade    %  % acumulado
forwardPE
 (vazio)           33 0.13         0.13
-43.38              1 0.00         0.13
-22.33              1 0.00         0.14
-29.81              1 0.00         0.14
-13.07              1 0.00         0.15
...               ...  ...          ...
32.29               1 0.00         0.98
39.90               1 0.00         0.99
45.15               1 0.00         0.99
54.12               1 0.00         1.00
96.08               1 0.00         1.00

[220 rows x 3 columns]

               Quantidade    %  % acumulado
averageVolume
9091                    1 0.00         0.00
10490                   1 0.00         0.01
14973                   1 0.00         0.01
23828                   1 0.00         0.02
31231                   1 0.00         0.02
...                   ...  ...          ...
34817015                1 0.00         0.98
41993765                1 0.00         0.99
44708371                1 0.00         0.99
46116620                1 0.00         1.00
102985360               1 0.00         1.00

[252 rows x 3 columns]

                     Quantidade    %  % acumulado
averageVolume10days
7790                          1 0.00         0.00
8770                          1 0.00         0.01
14700                         1 0.00         0.01
17130                         1 0.00         0.02
25350                         1 0.00         0.02
...                         ...  ...          ...
41591950                      1 0.00         0.98
44306720                      1 0.00         0.99
46867860                      1 0.00         0.99
53936270                      1 0.00         1.00
143869130                     1 0.00         1.00

[252 rows x 3 columns]

                         Quantidade    %  % acumulado
averageDailyVolume10Day
7790                              1 0.00         0.00
8770                              1 0.00         0.01
14700                             1 0.00         0.01
17130                             1 0.00         0.02
25350                             1 0.00         0.02
...                             ...  ...          ...
41591950                          1 0.00         0.98
44306720                          1 0.00         0.99
46867860                          1 0.00         0.99
53936270                          1 0.00         1.00
143869130                         1 0.00         1.00

[252 rows x 3 columns]

              Quantidade    %  % acumulado
marketCap
251978832              2 0.01         0.01
33797842944            2 0.01         0.02
60792600               1 0.00         0.02
66151352               1 0.00         0.02
71075808               1 0.00         0.03
...                  ...  ...          ...
245710979072           1 0.00         0.98
322096824320           1 0.00         0.99
322097152000           1 0.00         0.99
509514416128           1 0.00         1.00
509515890688           1 0.00         1.00

[250 rows x 3 columns]

                              Quantidade    %  % acumulado
priceToSalesTrailing12Months
1.15                                   2 0.01         0.01
0.85                                   2 0.01         0.02
0.04                                   1 0.00         0.02
0.04                                   1 0.00         0.02
0.04                                   1 0.00         0.03
...                                  ...  ...          ...
12.84                                  1 0.00         0.98
15.43                                  1 0.00         0.99
441.25                                 1 0.00         0.99
441.25                                 1 0.00         1.00
 (vazio)                               1 0.00         1.00

[250 rows x 3 columns]

                 Quantidade    %  % acumulado
fiftyDayAverage
4.33                      2 0.01         0.01
0.28                      1 0.00         0.01
0.07                      1 0.00         0.02
0.72                      1 0.00         0.02
0.82                      1 0.00         0.02
...                     ...  ...          ...
55.51                     1 0.00         0.98
57.77                     1 0.00         0.99
66.00                     1 0.00         0.99
97.50                     1 0.00         1.00
123.58                    1 0.00         1.00

[251 rows x 3 columns]

                      Quantidade    %  % acumulado
twoHundredDayAverage
0.16                           1 0.00         0.00
0.30                           1 0.00         0.01
0.80                           1 0.00         0.01
0.90                           1 0.00         0.02
0.96                           1 0.00         0.02
...                          ...  ...          ...
52.96                          1 0.00         0.98
57.28                          1 0.00         0.99
57.98                          1 0.00         0.99
92.15                          1 0.00         1.00
108.66                         1 0.00         1.00

[252 rows x 3 columns]

                            Quantidade    %  % acumulado
trailingAnnualDividendRate
0.00                               146 0.58         0.58
0.27                                 3 0.01         0.59
0.28                                 3 0.01         0.60
0.85                                 3 0.01         0.62
0.45                                 3 0.01         0.63
...                                ...  ...          ...
2.79                                 1 0.00         0.98
3.04                                 1 0.00         0.99
2.86                                 1 0.00         0.99
3.66                                 1 0.00         1.00
4.76                                 1 0.00         1.00

[89 rows x 3 columns]

                             Quantidade    %  % acumulado
trailingAnnualDividendYield
0.00                                146 0.58         0.58
0.00                                  1 0.00         0.58
0.00                                  1 0.00         0.59
0.01                                  1 0.00         0.59
0.01                                  1 0.00         0.60
...                                 ...  ...          ...
0.14                                  1 0.00         0.98
0.15                                  1 0.00         0.99
0.15                                  1 0.00         0.99
0.16                                  1 0.00         1.00
0.17                                  1 0.00         1.00

[107 rows x 3 columns]

               Quantidade    %  % acumulado
profitMargins
0.02                    3 0.01         0.01
0.09                    3 0.01         0.02
0.23                    3 0.01         0.04
0.23                    3 0.01         0.05
0.46                    3 0.01         0.06
...                   ...  ...          ...
0.75                    1 0.00         0.98
1.51                    1 0.00         0.99
0.85                    1 0.00         0.99
118.83                  1 0.00         1.00
 (vazio)                1 0.00         1.00

[226 rows x 3 columns]

             Quantidade    %  % acumulado
trailingEps
0.96                  4 0.02         0.02
0.83                  4 0.02         0.03
0.00                  3 0.01         0.04
1.09                  3 0.01         0.06
2.11                  3 0.01         0.07
...                 ...  ...          ...
9.85                  1 0.00         0.98
12.29                 1 0.00         0.99
390.81                1 0.00         0.99
116,683.32            1 0.00         1.00
 (vazio)              1 0.00         1.00

[196 rows x 3 columns]

            Quantidade    %  % acumulado
forwardEps
 (vazio)            35 0.14         0.14
2.01                 5 0.02         0.16
0.29                 4 0.02         0.17
0.94                 4 0.02         0.19
0.78                 4 0.02         0.21
...                ...  ...          ...
7.84                 1 0.00         0.98
8.04                 1 0.00         0.99
8.52                 1 0.00         0.99
11.94                1 0.00         1.00
16.06                1 0.00         1.00

[171 rows x 3 columns]

                 Quantidade    %  % acumulado
lastSplitFactor
(vazio)                  99 0.39         0.39
2:1                      24 0.10         0.49
3:1                      20 0.08         0.57
4:1                      10 0.04         0.61
11:10                    10 0.04         0.65
1:10                      9 0.04         0.68
1:5                       7 0.03         0.71
5:1                       5 0.02         0.73
10:1                      4 0.02         0.75
1:4                       4 0.02         0.76
1:500                     4 0.02         0.78
5:4                       4 0.02         0.79
1:55                      3 0.01         0.81
110:100                   3 0.01         0.82
1:1000                    3 0.01         0.83
21:20                     3 0.01         0.84
130:100                   2 0.01         0.85
105:100                   2 0.01         0.86
1:20                      2 0.01         0.87
1:6                       2 0.01         0.87
11.295:10                 2 0.01         0.88
12:10                     2 0.01         0.89
121.2108:100              1 0.00         0.89
125:100                   1 0.00         0.90
104:100                   1 0.00         0.90
10:100                    1 0.00         0.90
1.139045:1                1 0.00         0.91
1.025076:1                1 0.00         0.91
111.5213:100              1 0.00         0.92
1.142:1                   1 0.00         0.92
100:1                     1 0.00         0.92
1.25:1                    1 0.00         0.93
1:250                     1 0.00         0.93
1:25                      1 0.00         0.94
1:7.50476                 1 0.00         0.94
1:7                       1 0.00         0.94
1:30                      1 0.00         0.95
1:100                     1 0.00         0.95
1:11                      1 0.00         0.96
1:17                      1 0.00         0.96
21:1                      1 0.00         0.96
1:9                       1 0.00         0.97
30:1                      1 0.00         0.97
26:25                     1 0.00         0.98
20:1                      1 0.00         0.98
4:100                     1 0.00         0.98
6:1                       1 0.00         0.99
6:5                       1 0.00         0.99
80:40                     1 0.00         1.00
8:1                       1 0.00         1.00

                  Quantidade    %  % acumulado
lastSplitDate
 (vazio)                  99 0.39         0.39
1,397,520,000.00           3 0.01         0.40
1,401,667,200.00           3 0.01         0.42
1,615,507,200.00           3 0.01         0.43
1,715,040,000.00           3 0.01         0.44
...                      ...  ...          ...
1,721,606,400.00           1 0.00         0.98
1,728,345,600.00           1 0.00         0.99
1,724,716,800.00           1 0.00         0.99
1,733,961,600.00           1 0.00         1.00
1,744,675,200.00           1 0.00         1.00

[123 rows x 3 columns]

                     Quantidade    %  % acumulado
enterpriseToRevenue
 (vazio)                      8 0.03         0.03
0.18                          2 0.01         0.04
0.42                          2 0.01         0.05
0.87                          2 0.01         0.06
1.47                          2 0.01         0.06
...                         ...  ...          ...
11.90                         1 0.00         0.98
14.19                         1 0.00         0.99
16.12                         1 0.00         0.99
16.14                         1 0.00         1.00
251.47                        1 0.00         1.00

[238 rows x 3 columns]

                    Quantidade    %  % acumulado
enterpriseToEbitda
 (vazio)                    22 0.09         0.09
4.75                         2 0.01         0.10
4.49                         2 0.01         0.10
4.51                         2 0.01         0.11
4.62                         2 0.01         0.12
...                        ...  ...          ...
39.39                        1 0.00         0.98
61.71                        1 0.00         0.99
66.69                        1 0.00         0.99
68.07                        1 0.00         1.00
135.33                       1 0.00         1.00

[227 rows x 3 columns]

              Quantidade    %  % acumulado
52WeekChange
-0.90                  1 0.00         0.00
-0.88                  1 0.00         0.01
-0.84                  1 0.00         0.01
-0.79                  1 0.00         0.02
-0.77                  1 0.00         0.02
...                  ...  ...          ...
0.78                   1 0.00         0.98
0.94                   1 0.00         0.99
0.99                   1 0.00         0.99
1.05                   1 0.00         1.00
7.58                   1 0.00         1.00

[252 rows x 3 columns]

                   Quantidade    %  % acumulado
lastDividendValue
 (vazio)                   21 0.08         0.08
0.02                        2 0.01         0.09
0.01                        2 0.01         0.10
0.05                        2 0.01         0.11
0.05                        2 0.01         0.12
...                       ...  ...          ...
2.82                        1 0.00         0.98
3.48                        1 0.00         0.99
62.10                       1 0.00         0.99
227.52                      1 0.00         1.00
304.87                      1 0.00         1.00

[223 rows x 3 columns]

                  Quantidade    %  % acumulado
lastDividendDate
 (vazio)                  21 0.08         0.08
1,735,776,000.00           9 0.04         0.12
1,745,798,400.00           8 0.03         0.15
1,741,219,200.00           7 0.03         0.18
1,745,971,200.00           7 0.03         0.21
...                      ...  ...          ...
1,747,872,000.00           1 0.00         0.98
1,751,241,600.00           1 0.00         0.99
1,750,377,600.00           1 0.00         0.99
1,747,958,400.00           1 0.00         1.00
1,766,102,400.00           1 0.00         1.00

[125 rows x 3 columns]

                    Quantidade    %  % acumulado
recommendationMean
 (vazio)                   103 0.41         0.41
2.00                        15 0.06         0.47
1.75                         6 0.02         0.49
1.33                         6 0.02         0.52
3.00                         5 0.02         0.54
...                        ...  ...          ...
3.40                         1 0.00         0.98
3.75                         1 0.00         0.99
3.46                         1 0.00         0.99
3.80                         1 0.00         1.00
3.77                         1 0.00         1.00

[81 rows x 3 columns]

                   Quantidade    %  % acumulado
recommendationKey
none                      103 0.41         0.41
buy                        81 0.32         0.73
strong_buy                 32 0.13         0.86
hold                       30 0.12         0.98
underperform                6 0.02         1.00

                         Quantidade    %  % acumulado
numberOfAnalystOpinions
 (vazio)                         56 0.22         0.22
13.00                            28 0.11         0.33
11.00                            18 0.07         0.40
1.00                             18 0.07         0.48
9.00                             16 0.06         0.54
12.00                            15 0.06         0.60
8.00                             12 0.05         0.65
3.00                             12 0.05         0.69
14.00                            12 0.05         0.74
2.00                             10 0.04         0.78
4.00                             10 0.04         0.82
7.00                             10 0.04         0.86
10.00                            10 0.04         0.90
5.00                              8 0.03         0.93
6.00                              7 0.03         0.96
15.00                             7 0.03         0.99
16.00                             2 0.01         1.00
18.00                             1 0.00         1.00

                    Quantidade    %  % acumulado
totalCash
750,976,000.00               3 0.01         0.01
214,821,388,288.00           3 0.01         0.02
7,530,208,256.00             3 0.01         0.04
1,800,756,992.00             3 0.01         0.05
287,950,016.00               2 0.01         0.06
...                        ...  ...          ...
24,173,735,936.00            1 0.00         0.98
38,637,752,320.00            1 0.00         0.99
281,067,880,448.00           1 0.00         0.99
424,292,319,232.00           1 0.00         1.00
 (vazio)                     1 0.00         1.00

[228 rows x 3 columns]

                   Quantidade    %  % acumulado
totalCashPerShare
 (vazio)                    8 0.03         0.03
1.24                        3 0.01         0.04
1.19                        3 0.01         0.06
28.80                       3 0.01         0.07
0.73                        3 0.01         0.08
...                       ...  ...          ...
25.53                       1 0.00         0.98
45.46                       1 0.00         0.99
50.90                       1 0.00         0.99
58.98                       1 0.00         1.00
74.33                       1 0.00         1.00

[221 rows x 3 columns]

                   Quantidade    %  % acumulado
ebitda
 (vazio)                   17 0.07         0.07
7,366,554,112.00            3 0.01         0.08
2,223,948,032.00            3 0.01         0.09
2,608,715,008.00            3 0.01         0.10
1,711,689,984.00            2 0.01         0.11
...                       ...  ...          ...
17,859,926,016.00           1 0.00         0.98
26,715,762,688.00           1 0.00         0.99
23,460,323,328.00           1 0.00         0.99
73,358,000,128.00           1 0.00         1.00
35,569,000,448.00           1 0.00         1.00

[217 rows x 3 columns]

                      Quantidade    %  % acumulado
totalDebt
6,631,334,912.00               3 0.01         0.01
9,894,993,920.00               3 0.01         0.02
14,917,152,768.00              3 0.01         0.04
41,562,439,680.00              3 0.01         0.05
295,217,528,832.00             3 0.01         0.06
...                          ...  ...          ...
72,965,177,344.00              1 0.00         0.98
134,926,999,552.00             1 0.00         0.99
283,816,001,536.00             1 0.00         0.99
1,032,465,481,728.00           1 0.00         1.00
 (vazio)                       1 0.00         1.00

[226 rows x 3 columns]

            Quantidade    %  % acumulado
quickRatio
 (vazio)            17 0.07         0.07
0.60                 3 0.01         0.08
1.48                 3 0.01         0.09
1.68                 3 0.01         0.10
0.41                 2 0.01         0.11
...                ...  ...          ...
3.25                 1 0.00         0.98
3.85                 1 0.00         0.99
5.10                 1 0.00         0.99
5.89                 1 0.00         1.00
6.36                 1 0.00         1.00

[210 rows x 3 columns]

              Quantidade    %  % acumulado
currentRatio
 (vazio)              17 0.07         0.07
0.63                   4 0.02         0.08
0.51                   3 0.01         0.10
2.04                   3 0.01         0.11
1.78                   3 0.01         0.12
...                  ...  ...          ...
4.74                   1 0.00         0.98
5.21                   1 0.00         0.99
6.84                   1 0.00         0.99
6.84                   1 0.00         1.00
7.10                   1 0.00         1.00

[207 rows x 3 columns]

                    Quantidade    %  % acumulado
totalRevenue
58,112,253,952.00            3 0.01         0.01
6,848,219,136.00             3 0.01         0.02
3,718,138,112.00             3 0.01         0.04
19,645,999,104.00            3 0.01         0.05
67,026,657,280.00            3 0.01         0.06
...                        ...  ...          ...
148,860,960,768.00           1 0.00         0.98
206,004,994,048.00           1 0.00         0.99
251,226,357,760.00           1 0.00         0.99
416,951,992,320.00           1 0.00         1.00
 (vazio)                     1 0.00         1.00

[227 rows x 3 columns]

              Quantidade    %  % acumulado
debtToEquity
 (vazio)              29 0.12         0.12
61.24                  3 0.01         0.13
142.59                 3 0.01         0.14
481.20                 3 0.01         0.15
25.61                  2 0.01         0.16
...                  ...  ...          ...
650.55                 1 0.00         0.98
843.49                 1 0.00         0.99
1,002.59               1 0.00         0.99
34,532.31              1 0.00         1.00
41,196.19              1 0.00         1.00

[206 rows x 3 columns]

                 Quantidade    %  % acumulado
revenuePerShare
 (vazio)                 12 0.05         0.05
3.60                      3 0.01         0.06
7.79                      3 0.01         0.07
4.53                      3 0.01         0.08
3.23                      3 0.01         0.10
...                     ...  ...          ...
102.30                    1 0.00         0.98
154.51                    1 0.00         0.99
164.76                    1 0.00         0.99
188.18                    1 0.00         1.00
286.30                    1 0.00         1.00

[218 rows x 3 columns]

                Quantidade    %  % acumulado
returnOnAssets
0.04                     3 0.01         0.01
0.01                     3 0.01         0.02
 (vazio)                 3 0.01         0.04
0.07                     3 0.01         0.05
0.07                     3 0.01         0.06
...                    ...  ...          ...
0.15                     1 0.00         0.98
0.17                     1 0.00         0.99
0.19                     1 0.00         0.99
0.24                     1 0.00         1.00
0.31                     1 0.00         1.00

[224 rows x 3 columns]

                Quantidade    %  % acumulado
returnOnEquity
 (vazio)                14 0.06         0.06
0.15                     3 0.01         0.07
0.25                     3 0.01         0.08
0.18                     3 0.01         0.09
0.15                     3 0.01         0.10
...                    ...  ...          ...
0.52                     1 0.00         0.98
0.61                     1 0.00         0.99
0.64                     1 0.00         0.99
0.70                     1 0.00         1.00
0.89                     1 0.00         1.00

[216 rows x 3 columns]

                    Quantidade    %  % acumulado
grossProfits
9,203,239,936.00             3 0.01         0.01
2,536,808,960.00             3 0.01         0.02
3,957,832,960.00             3 0.01         0.04
6,302,000,128.00             3 0.01         0.05
55,812,861,952.00            3 0.01         0.06
...                        ...  ...          ...
20,001,755,136.00            1 0.00         0.98
74,686,996,480.00            1 0.00         0.99
62,772,998,144.00            1 0.00         0.99
101,466,669,056.00           1 0.00         1.00
 (vazio)                     1 0.00         1.00

[227 rows x 3 columns]

                   Quantidade    %  % acumulado
freeCashflow
 (vazio)                   19 0.08         0.08
-4,716,692,992.00           3 0.01         0.09
2,452,208,128.00            3 0.01         0.10
-360,252,864.00             3 0.01         0.11
-861,329,344.00             2 0.01         0.12
...                       ...  ...          ...
9,815,608,320.00            1 0.00         0.98
19,344,275,456.00           1 0.00         0.99
11,183,279,104.00           1 0.00         0.99
41,687,126,016.00           1 0.00         1.00
41,630,875,648.00           1 0.00         1.00

[214 rows x 3 columns]

                    Quantidade    %  % acumulado
operatingCashflow
 (vazio)                     4 0.02         0.02
7,425,327,104.00             3 0.01         0.03
1,540,337,024.00             3 0.01         0.04
2,775,021,056.00             3 0.01         0.05
-53,418,307,584.00           3 0.01         0.06
...                        ...  ...          ...
20,604,426,240.00            1 0.00         0.98
26,099,034,112.00            1 0.00         0.99
23,556,999,168.00            1 0.00         0.99
62,312,546,304.00            1 0.00         1.00
50,198,999,040.00            1 0.00         1.00

[225 rows x 3 columns]

                Quantidade    %  % acumulado
earningsGrowth
 (vazio)                99 0.39         0.39
0.05                     3 0.01         0.40
-0.37                    3 0.01         0.42
0.13                     3 0.01         0.43
0.76                     3 0.01         0.44
...                    ...  ...          ...
10.06                    1 0.00         0.98
25.79                    1 0.00         0.99
26.38                    1 0.00         0.99
33.88                    1 0.00         1.00
155.25                   1 0.00         1.00

[132 rows x 3 columns]

               Quantidade    %  % acumulado
revenueGrowth
 (vazio)                7 0.03         0.03
0.14                    4 0.02         0.04
0.13                    4 0.02         0.06
0.05                    3 0.01         0.07
0.06                    3 0.01         0.08
...                   ...  ...          ...
0.90                    1 0.00         0.98
1.25                    1 0.00         0.99
1.39                    1 0.00         0.99
1.54                    1 0.00         1.00
1.65                    1 0.00         1.00

[187 rows x 3 columns]

              Quantidade    %  % acumulado
grossMargins
0.00                  14 0.06         0.06
0.14                   3 0.01         0.07
0.58                   3 0.01         0.08
0.68                   3 0.01         0.09
0.32                   3 0.01         0.10
...                  ...  ...          ...
0.93                   1 0.00         0.98
0.96                   1 0.00         0.99
0.98                   1 0.00         0.99
0.98                   1 0.00         1.00
 (vazio)               1 0.00         1.00

[218 rows x 3 columns]

               Quantidade    %  % acumulado
ebitdaMargins
0.00                   17 0.07         0.07
0.60                    3 0.01         0.08
0.38                    3 0.01         0.09
0.37                    3 0.01         0.10
-0.32                   2 0.01         0.11
...                   ...  ...          ...
0.73                    1 0.00         0.98
0.77                    1 0.00         0.99
0.84                    1 0.00         0.99
0.96                    1 0.00         1.00
 (vazio)                1 0.00         1.00

[217 rows x 3 columns]

                  Quantidade    %  % acumulado
operatingMargins
1.15                       3 0.01         0.01
0.34                       3 0.01         0.02
0.14                       3 0.01         0.04
0.54                       3 0.01         0.05
-0.25                      2 0.01         0.06
...                      ...  ...          ...
0.98                       1 0.00         0.98
1.81                       1 0.00         0.99
1.84                       1 0.00         0.99
2.36                       1 0.00         1.00
4.66                       1 0.00         1.00

[227 rows x 3 columns]

                         Quantidade    %  % acumulado
epsTrailingTwelveMonths
0.96                              4 0.02         0.02
0.83                              4 0.02         0.03
0.00                              3 0.01         0.04
1.09                              3 0.01         0.06
2.11                              3 0.01         0.07
...                             ...  ...          ...
9.85                              1 0.00         0.98
12.29                             1 0.00         0.99
390.81                            1 0.00         0.99
116,683.32                        1 0.00         1.00
 (vazio)                          1 0.00         1.00

[196 rows x 3 columns]

            Quantidade    %  % acumulado
epsForward
 (vazio)            35 0.14         0.14
2.01                 5 0.02         0.16
0.29                 4 0.02         0.17
0.94                 4 0.02         0.19
0.78                 4 0.02         0.21
...                ...  ...          ...
7.84                 1 0.00         0.98
8.04                 1 0.00         0.99
8.52                 1 0.00         0.99
11.94                1 0.00         1.00
16.06                1 0.00         1.00

[171 rows x 3 columns]

                Quantidade    %  % acumulado
epsCurrentYear
 (vazio)                76 0.30         0.30
0.49                     2 0.01         0.31
2.40                     2 0.01         0.32
0.16                     2 0.01         0.33
1.02                     2 0.01         0.33
...                    ...  ...          ...
5.95                     1 0.00         0.98
6.83                     1 0.00         0.99
7.60                     1 0.00         0.99
8.84                     1 0.00         1.00
10.71                    1 0.00         1.00

[168 rows x 3 columns]

                     Quantidade    %  % acumulado
priceEpsCurrentYear
 (vazio)                     77 0.31         0.31
-250.41                       1 0.00         0.31
-48.67                        1 0.00         0.31
-53.18                        1 0.00         0.32
-5.59                         1 0.00         0.32
...                         ...  ...          ...
36.39                         1 0.00         0.98
48.73                         1 0.00         0.99
83.06                         1 0.00         0.99
96.07                         1 0.00         1.00
134.06                        1 0.00         1.00

[176 rows x 3 columns]

                       Quantidade    %  % acumulado
fiftyDayAverageChange
0.44                            2 0.01         0.01
-4.56                           1 0.00         0.01
-5.18                           1 0.00         0.02
-3.73                           1 0.00         0.02
-3.48                           1 0.00         0.02
...                           ...  ...          ...
3.59                            1 0.00         0.98
5.48                            1 0.00         0.99
5.93                            1 0.00         0.99
6.00                            1 0.00         1.00
7.19                            1 0.00         1.00

[251 rows x 3 columns]

                              Quantidade    %  % acumulado
fiftyDayAverageChangePercent
-0.33                                  1 0.00         0.00
-0.24                                  1 0.00         0.01
-0.20                                  1 0.00         0.01
-0.19                                  1 0.00         0.02
-0.17                                  1 0.00         0.02
...                                  ...  ...          ...
0.39                                   1 0.00         0.98
0.48                                   1 0.00         0.99
0.58                                   1 0.00         0.99
0.67                                   1 0.00         1.00
1.39                                   1 0.00         1.00

[252 rows x 3 columns]

                            Quantidade    %  % acumulado
twoHundredDayAverageChange
-14.82                               1 0.00         0.00
-9.99                                1 0.00         0.01
-7.04                                1 0.00         0.01
-6.11                                1 0.00         0.02
-5.39                                1 0.00         0.02
...                                ...  ...          ...
7.10                                 1 0.00         0.98
9.24                                 1 0.00         0.99
10.83                                1 0.00         0.99
11.44                                1 0.00         1.00
13.40                                1 0.00         1.00

[252 rows x 3 columns]

                                   Quantidade    %  % acumulado
twoHundredDayAverageChangePercent
-0.66                                       1 0.00         0.00
-0.62                                       1 0.00         0.01
-0.46                                       1 0.00         0.01
-0.45                                       1 0.00         0.02
-0.44                                       1 0.00         0.02
...                                       ...  ...          ...
0.30                                        1 0.00         0.98
0.36                                        1 0.00         0.99
0.39                                        1 0.00         0.99
0.46                                        1 0.00         1.00
1.28                                        1 0.00         1.00

[252 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-03; Open
2.63                       2 0.01         0.01
1.93                       2 0.01         0.02
1.56                       2 0.01         0.02
5.14                       2 0.01         0.03
5.60                       2 0.01         0.04
...                      ...  ...          ...
54.18                      1 0.00         0.98
59.85                      1 0.00         0.99
62.55                      1 0.00         0.99
93.99                      1 0.00         1.00
134.00                     1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-03; High
1.59                       2 0.01         0.01
1.40                       2 0.01         0.02
2.73                       2 0.01         0.02
5.26                       2 0.01         0.03
5.68                       2 0.01         0.04
...                      ...  ...          ...
54.56                      1 0.00         0.98
59.90                      1 0.00         0.99
63.51                      1 0.00         0.99
96.19                      1 0.00         1.00
134.00                     1 0.00         1.00

[245 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-03; Low
1.29                      2 0.01         0.01
1.31                      2 0.01         0.02
2.21                      2 0.01         0.02
2.61                      2 0.01         0.03
5.43                      2 0.01         0.04
...                     ...  ...          ...
53.21                     1 0.00         0.98
58.06                     1 0.00         0.99
62.03                     1 0.00         0.99
93.93                     1 0.00         1.00
124.19                    1 0.00         1.00

[240 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-03; Close
5.48                        4 0.02         0.02
0.95                        2 0.01         0.02
1.75                        2 0.01         0.03
1.40                        2 0.01         0.04
0.67                        1 0.00         0.04
...                       ...  ...          ...
53.47                       1 0.00         0.98
59.42                       1 0.00         0.99
62.45                       1 0.00         0.99
96.19                       1 0.00         1.00
124.32                      1 0.00         1.00

[246 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-03; Volume
1700                         1 0.00         0.00
2800                         1 0.00         0.01
3100                         1 0.00         0.01
3400                         1 0.00         0.02
3700                         1 0.00         0.02
...                        ...  ...          ...
32339300                     1 0.00         0.98
42468600                     1 0.00         0.99
43098500                     1 0.00         0.99
45100900                     1 0.00         1.00
79876500                     1 0.00         1.00

[252 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-03; Dividends
0.00                          250 0.99         0.99
0.02                            1 0.00         1.00
0.02                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-03; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-03; HLC
0.66                      2 0.01         0.01
10.08                     2 0.01         0.02
0.31                      1 0.00         0.02
0.72                      1 0.00         0.02
0.94                      1 0.00         0.03
...                     ...  ...          ...
53.75                     1 0.00         0.98
59.13                     1 0.00         0.99
62.66                     1 0.00         0.99
95.44                     1 0.00         1.00
127.50                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-04; Open
1.34                       3 0.01         0.01
1.55                       3 0.01         0.02
5.74                       3 0.01         0.04
3.30                       2 0.01         0.04
2.22                       2 0.01         0.05
...                      ...  ...          ...
53.57                      1 0.00         0.98
59.42                      1 0.00         0.99
62.45                      1 0.00         0.99
96.01                      1 0.00         1.00
122.82                     1 0.00         1.00

[241 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-04; High
1.34                       3 0.01         0.01
1.61                       2 0.01         0.02
1.82                       2 0.01         0.03
2.28                       2 0.01         0.04
5.74                       2 0.01         0.04
...                      ...  ...          ...
54.18                      1 0.00         0.98
59.60                      1 0.00         0.99
62.71                      1 0.00         0.99
97.59                      1 0.00         1.00
122.82                     1 0.00         1.00

[239 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-04; Low
1.19                      2 0.01         0.01
1.48                      2 0.01         0.02
2.61                      2 0.01         0.02
1.87                      2 0.01         0.03
1.55                      2 0.01         0.04
...                     ...  ...          ...
53.47                     1 0.00         0.98
57.18                     1 0.00         0.99
59.89                     1 0.00         0.99
95.65                     1 0.00         1.00
118.49                    1 0.00         1.00

[242 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-04; Close
1.55                        3 0.01         0.01
5.31                        3 0.01         0.02
1.04                        2 0.01         0.03
1.41                        2 0.01         0.04
1.31                        2 0.01         0.05
...                       ...  ...          ...
53.63                       1 0.00         0.98
57.46                       1 0.00         0.99
59.92                       1 0.00         0.99
97.59                       1 0.00         1.00
120.03                      1 0.00         1.00

[239 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-04; Volume
900                          1 0.00         0.00
2600                         1 0.00         0.01
5200                         1 0.00         0.01
7300                         1 0.00         0.02
11700                        1 0.00         0.02
...                        ...  ...          ...
34290300                     1 0.00         0.98
36005500                     1 0.00         0.99
40751400                     1 0.00         0.99
45029300                     1 0.00         1.00
120439600                    1 0.00         1.00

[252 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-04; Dividends
0.00                          250 0.99         0.99
0.02                            1 0.00         1.00
0.02                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-04; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-04; HLC
1.02                      2 0.01         0.01
3.48                      2 0.01         0.02
0.31                      1 0.00         0.02
0.66                      1 0.00         0.02
0.72                      1 0.00         0.03
...                     ...  ...          ...
53.76                     1 0.00         0.98
58.08                     1 0.00         0.99
60.84                     1 0.00         0.99
96.94                     1 0.00         1.00
120.45                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-05; Open
1.36                       2 0.01         0.01
1.52                       2 0.01         0.02
2.26                       2 0.01         0.02
1.58                       2 0.01         0.03
1.57                       2 0.01         0.04
...                      ...  ...          ...
53.93                      1 0.00         0.98
60.22                      1 0.00         0.99
61.50                      1 0.00         0.99
97.20                      1 0.00         1.00
121.00                     1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-05; High
1.41                       2 0.01         0.01
1.55                       2 0.01         0.02
2.64                       2 0.01         0.02
1.66                       2 0.01         0.03
5.43                       2 0.01         0.04
...                      ...  ...          ...
54.54                      1 0.00         0.98
61.01                      1 0.00         0.99
66.58                      1 0.00         0.99
97.95                      1 0.00         1.00
122.60                     1 0.00         1.00

[246 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-05; Low
0.65                      2 0.01         0.01
1.34                      2 0.01         0.02
1.40                      2 0.01         0.02
1.28                      2 0.01         0.03
1.48                      2 0.01         0.04
...                     ...  ...          ...
53.88                     1 0.00         0.98
59.50                     1 0.00         0.99
61.01                     1 0.00         0.99
96.59                     1 0.00         1.00
119.88                    1 0.00         1.00

[241 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-05; Close
1.40                        3 0.01         0.01
1.09                        2 0.01         0.02
1.45                        2 0.01         0.03
2.45                        2 0.01         0.04
2.24                        2 0.01         0.04
...                       ...  ...          ...
54.04                       1 0.00         0.98
59.69                       1 0.00         0.99
66.37                       1 0.00         0.99
97.84                       1 0.00         1.00
121.11                      1 0.00         1.00

[242 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-05; Volume
3300                         2 0.01         0.01
108100                       2 0.01         0.02
5500                         1 0.00         0.02
6400                         1 0.00         0.02
9500                         1 0.00         0.03
...                        ...  ...          ...
42185200                     1 0.00         0.98
44027830                     1 0.00         0.99
44675800                     1 0.00         0.99
55017400                     1 0.00         1.00
96725900                     1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-05; Dividends
0                             252 1.00         1.00

                          Quantidade    %  % acumulado
2025-02-05; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-05; HLC
1.55                      2 0.01         0.01
0.29                      1 0.00         0.01
0.07                      1 0.00         0.02
0.71                      1 0.00         0.02
0.72                      1 0.00         0.02
...                     ...  ...          ...
54.15                     1 0.00         0.98
60.07                     1 0.00         0.99
64.65                     1 0.00         0.99
97.46                     1 0.00         1.00
121.20                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-06; Open
1.55                       3 0.01         0.01
1.46                       3 0.01         0.02
1.39                       3 0.01         0.04
1.50                       2 0.01         0.04
1.16                       2 0.01         0.05
...                      ...  ...          ...
54.03                      1 0.00         0.98
59.70                      1 0.00         0.99
66.01                      1 0.00         0.99
97.41                      1 0.00         1.00
121.15                     1 0.00         1.00

[235 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-06; High
1.50                       2 0.01         0.01
1.58                       2 0.01         0.02
1.21                       2 0.01         0.02
2.65                       2 0.01         0.03
0.73                       1 0.00         0.04
...                      ...  ...          ...
54.25                      1 0.00         0.98
60.22                      1 0.00         0.99
66.21                      1 0.00         0.99
98.09                      1 0.00         1.00
122.30                     1 0.00         1.00

[248 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-06; Low
0.65                      2 0.01         0.01
1.38                      2 0.01         0.02
1.51                      2 0.01         0.02
2.21                      2 0.01         0.03
5.42                      2 0.01         0.04
...                     ...  ...          ...
53.26                     1 0.00         0.98
59.60                     1 0.00         0.99
63.63                     1 0.00         0.99
96.75                     1 0.00         1.00
119.87                    1 0.00         1.00

[245 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-06; Close
1.53                        2 0.01         0.01
1.50                        2 0.01         0.02
2.27                        2 0.01         0.02
5.40                        2 0.01         0.03
0.73                        1 0.00         0.04
...                       ...  ...          ...
54.10                       1 0.00         0.98
60.09                       1 0.00         0.99
64.50                       1 0.00         0.99
97.77                       1 0.00         1.00
120.03                      1 0.00         1.00

[248 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-06; Volume
4400                         2 0.01         0.01
56600                        2 0.01         0.02
56900                        2 0.01         0.02
3900                         1 0.00         0.03
5000                         1 0.00         0.03
...                        ...  ...          ...
42761730                     1 0.00         0.98
45483400                     1 0.00         0.99
62327700                     1 0.00         0.99
72965100                     1 0.00         1.00
83469300                     1 0.00         1.00

[249 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-06; Dividends
0                             252 1.00         1.00

                          Quantidade    %  % acumulado
2025-02-06; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-06; HLC
0.07                      1 0.00         0.00
0.28                      1 0.00         0.01
0.66                      1 0.00         0.01
0.68                      1 0.00         0.02
0.72                      1 0.00         0.02
...                     ...  ...          ...
53.87                     1 0.00         0.98
59.97                     1 0.00         0.99
64.78                     1 0.00         0.99
97.54                     1 0.00         1.00
120.73                    1 0.00         1.00

[252 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-07; Open
1.53                       4 0.02         0.02
1.29                       3 0.01         0.03
1.42                       2 0.01         0.04
3.40                       2 0.01         0.04
2.27                       2 0.01         0.05
...                      ...  ...          ...
54.10                      1 0.00         0.98
60.02                      1 0.00         0.99
64.25                      1 0.00         0.99
97.51                      1 0.00         1.00
120.81                     1 0.00         1.00

[239 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-07; High
1.06                       2 0.01         0.01
1.31                       2 0.01         0.02
1.39                       2 0.01         0.02
1.30                       2 0.01         0.03
2.68                       2 0.01         0.04
...                      ...  ...          ...
54.37                      1 0.00         0.98
60.10                      1 0.00         0.99
65.20                      1 0.00         0.99
98.58                      1 0.00         1.00
122.18                     1 0.00         1.00

[241 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-07; Low
1.26                      3 0.01         0.01
1.47                      2 0.01         0.02
2.41                      2 0.01         0.03
2.59                      2 0.01         0.04
5.35                      2 0.01         0.04
...                     ...  ...          ...
53.16                     1 0.00         0.98
59.15                     1 0.00         0.99
62.30                     1 0.00         0.99
95.87                     1 0.00         1.00
119.52                    1 0.00         1.00

[245 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-07; Close
5.60                        3 0.01         0.01
1.27                        2 0.01         0.02
0.66                        2 0.01         0.03
1.52                        2 0.01         0.04
1.60                        2 0.01         0.04
...                       ...  ...          ...
53.51                       1 0.00         0.98
59.52                       1 0.00         0.99
62.30                       1 0.00         0.99
96.51                       1 0.00         1.00
121.33                      1 0.00         1.00

[239 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-07; Volume
1200                         1 0.00         0.00
1300                         1 0.00         0.01
2100                         1 0.00         0.01
2900                         1 0.00         0.02
6700                         1 0.00         0.02
...                        ...  ...          ...
34977500                     1 0.00         0.98
38916130                     1 0.00         0.99
50253200                     1 0.00         0.99
127519900                    1 0.00         1.00
129620600                    1 0.00         1.00

[252 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-07; Dividends
0.00                          251 1.00         1.00
0.10                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-07; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-07; HLC
1.58                      2 0.01         0.01
2.22                      2 0.01         0.02
0.65                      1 0.00         0.02
0.67                      1 0.00         0.02
0.72                      1 0.00         0.03
...                     ...  ...          ...
53.68                     1 0.00         0.98
59.59                     1 0.00         0.99
63.27                     1 0.00         0.99
96.99                     1 0.00         1.00
121.01                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-10; Open
1.37                       2 0.01         0.01
5.25                       2 0.01         0.02
5.41                       2 0.01         0.02
4.45                       2 0.01         0.03
5.49                       2 0.01         0.04
...                      ...  ...          ...
53.77                      1 0.00         0.98
60.01                      1 0.00         0.99
62.30                      1 0.00         0.99
97.43                      1 0.00         1.00
121.35                     1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-10; High
1.30                       3 0.01         0.01
5.50                       3 0.01         0.02
4.59                       3 0.01         0.04
1.55                       2 0.01         0.04
3.56                       2 0.01         0.05
...                      ...  ...          ...
54.01                      1 0.00         0.98
60.10                      1 0.00         0.99
62.70                      1 0.00         0.99
97.69                      1 0.00         1.00
128.73                     1 0.00         1.00

[236 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-10; Low
0.65                      2 0.01         0.01
1.01                      2 0.01         0.02
1.26                      2 0.01         0.02
1.43                      2 0.01         0.03
1.49                      2 0.01         0.04
...                     ...  ...          ...
53.37                     1 0.00         0.98
58.83                     1 0.00         0.99
60.75                     1 0.00         0.99
96.34                     1 0.00         1.00
121.35                    1 0.00         1.00

[240 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-10; Close
1.61                        3 0.01         0.01
3.47                        2 0.01         0.02
1.28                        2 0.01         0.03
5.26                        2 0.01         0.04
5.40                        2 0.01         0.04
...                       ...  ...          ...
53.78                       1 0.00         0.98
59.35                       1 0.00         0.99
60.97                       1 0.00         0.99
97.16                       1 0.00         1.00
122.11                      1 0.00         1.00

[243 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-10; Volume
0                            2 0.01         0.01
900                          1 0.00         0.01
2600                         1 0.00         0.02
3900                         1 0.00         0.02
5000                         1 0.00         0.02
...                        ...  ...          ...
41443710                     1 0.00         0.98
49092000                     1 0.00         0.99
50519600                     1 0.00         0.99
59840500                     1 0.00         1.00
62060600                     1 0.00         1.00

[251 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-10; Dividends
0                             252 1.00         1.00

                          Quantidade    %  % acumulado
2025-02-10; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-10; HLC
1.27                      2 0.01         0.01
0.27                      1 0.00         0.01
0.07                      1 0.00         0.02
0.66                      1 0.00         0.02
0.72                      1 0.00         0.02
...                     ...  ...          ...
53.72                     1 0.00         0.98
59.43                     1 0.00         0.99
61.47                     1 0.00         0.99
97.06                     1 0.00         1.00
124.06                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-11; Open
5.45                       3 0.01         0.01
1.26                       2 0.01         0.02
1.35                       2 0.01         0.03
5.59                       2 0.01         0.04
8.06                       2 0.01         0.04
...                      ...  ...          ...
53.78                      1 0.00         0.98
59.69                      1 0.00         0.99
61.06                      1 0.00         0.99
97.49                      1 0.00         1.00
123.58                     1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-11; High
5.83                       3 0.01         0.01
1.33                       2 0.01         0.02
8.35                       2 0.01         0.03
5.49                       2 0.01         0.04
1.04                       2 0.01         0.04
...                      ...  ...          ...
54.07                      1 0.00         0.98
59.69                      1 0.00         0.99
61.32                      1 0.00         0.99
98.58                      1 0.00         1.00
124.84                     1 0.00         1.00

[245 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-11; Low
1.26                      2 0.01         0.01
0.65                      2 0.01         0.02
1.27                      2 0.01         0.02
3.40                      2 0.01         0.03
5.45                      2 0.01         0.04
...                     ...  ...          ...
52.40                     1 0.00         0.98
58.46                     1 0.00         0.99
59.62                     1 0.00         0.99
97.17                     1 0.00         1.00
120.00                    1 0.00         1.00

[242 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-11; Close
1.28                        2 0.01         0.01
1.29                        2 0.01         0.02
3.55                        2 0.01         0.02
2.51                        2 0.01         0.03
5.44                        2 0.01         0.04
...                       ...  ...          ...
53.43                       1 0.00         0.98
58.93                       1 0.00         0.99
60.12                       1 0.00         0.99
98.05                       1 0.00         1.00
120.00                      1 0.00         1.00

[245 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-11; Volume
2100                         1 0.00         0.00
4700                         1 0.00         0.01
8600                         1 0.00         0.01
9900                         1 0.00         0.02
11700                        1 0.00         0.02
...                        ...  ...          ...
40337300                     1 0.00         0.98
44826000                     1 0.00         0.99
45279931                     1 0.00         0.99
87651000                     1 0.00         1.00
123582800                    1 0.00         1.00

[252 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-11; Dividends
0.00                          250 0.99         0.99
0.41                            1 0.00         1.00
0.60                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-11; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-11; HLC
1.02                      2 0.01         0.01
0.29                      1 0.00         0.01
0.07                      1 0.00         0.02
0.66                      1 0.00         0.02
0.69                      1 0.00         0.02
...                     ...  ...          ...
53.12                     1 0.00         0.98
59.03                     1 0.00         0.99
60.35                     1 0.00         0.99
97.93                     1 0.00         1.00
121.61                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-12; Open
1.43                       2 0.01         0.01
0.66                       2 0.01         0.02
1.49                       2 0.01         0.02
1.29                       2 0.01         0.03
3.55                       2 0.01         0.04
...                      ...  ...          ...
53.00                      1 0.00         0.98
58.70                      1 0.00         0.99
59.65                      1 0.00         0.99
96.70                      1 0.00         1.00
122.00                     1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-12; High
1.29                       2 0.01         0.01
1.28                       2 0.01         0.02
1.75                       2 0.01         0.02
6.10                       2 0.01         0.03
5.42                       2 0.01         0.04
...                      ...  ...          ...
53.32                      1 0.00         0.98
58.77                      1 0.00         0.99
59.96                      1 0.00         0.99
97.86                      1 0.00         1.00
123.00                     1 0.00         1.00

[245 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-12; Low
0.66                      2 0.01         0.01
1.26                      2 0.01         0.02
0.97                      2 0.01         0.02
2.27                      2 0.01         0.03
2.76                      2 0.01         0.04
...                     ...  ...          ...
52.65                     1 0.00         0.98
57.40                     1 0.00         0.99
58.97                     1 0.00         0.99
96.06                     1 0.00         1.00
118.35                    1 0.00         1.00

[241 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-12; Close
1.48                        2 0.01         0.01
1.28                        2 0.01         0.02
5.58                        2 0.01         0.02
5.38                        2 0.01         0.03
5.31                        2 0.01         0.04
...                       ...  ...          ...
52.73                       1 0.00         0.98
57.97                       1 0.00         0.99
59.50                       1 0.00         0.99
97.06                       1 0.00         1.00
121.04                      1 0.00         1.00

[246 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-12; Volume
16600                        2 0.01         0.01
401400                       2 0.01         0.02
1900                         1 0.00         0.02
3200                         1 0.00         0.02
4600                         1 0.00         0.03
...                        ...  ...          ...
49153196                     1 0.00         0.98
77267800                     1 0.00         0.99
111466700                    1 0.00         0.99
123782500                    1 0.00         1.00
143711300                    1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-12; Dividends
0.00                          251 1.00         1.00
0.67                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-12; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-12; HLC
0.99                      2 0.01         0.01
1.50                      2 0.01         0.02
4.54                      2 0.01         0.02
20.80                     2 0.01         0.03
0.72                      1 0.00         0.04
...                     ...  ...          ...
52.86                     1 0.00         0.98
58.05                     1 0.00         0.99
59.48                     1 0.00         0.99
96.99                     1 0.00         1.00
120.80                    1 0.00         1.00

[248 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-13; Open
1.15                       2 0.01         0.01
1.28                       2 0.01         0.02
1.48                       2 0.01         0.02
2.32                       2 0.01         0.03
4.42                       2 0.01         0.04
...                      ...  ...          ...
52.79                      1 0.00         0.98
58.02                      1 0.00         0.99
59.77                      1 0.00         0.99
96.46                      1 0.00         1.00
122.00                     1 0.00         1.00

[239 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-13; High
1.85                       3 0.01         0.01
1.33                       2 0.01         0.02
1.80                       2 0.01         0.03
1.52                       2 0.01         0.04
1.17                       2 0.01         0.04
...                      ...  ...          ...
53.68                      1 0.00         0.98
59.54                      1 0.00         0.99
60.67                      1 0.00         0.99
98.99                      1 0.00         1.00
124.01                     1 0.00         1.00

[241 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-13; Low
1.27                      3 0.01         0.01
5.53                      2 0.01         0.02
5.85                      2 0.01         0.03
6.12                      2 0.01         0.04
8.12                      2 0.01         0.04
...                     ...  ...          ...
52.62                     1 0.00         0.98
57.54                     1 0.00         0.99
59.20                     1 0.00         0.99
96.46                     1 0.00         1.00
121.06                    1 0.00         1.00

[241 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-13; Close
4.47                        3 0.01         0.01
1.32                        2 0.01         0.02
1.77                        2 0.01         0.03
1.43                        2 0.01         0.04
3.53                        2 0.01         0.04
...                       ...  ...          ...
53.68                       1 0.00         0.98
59.23                       1 0.00         0.99
60.48                       1 0.00         0.99
98.82                       1 0.00         1.00
121.50                      1 0.00         1.00

[240 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-13; Volume
3193000                      2 0.01         0.01
2200                         1 0.00         0.01
1400                         1 0.00         0.02
3200                         1 0.00         0.02
6200                         1 0.00         0.02
...                        ...  ...          ...
24475800                     1 0.00         0.98
44812400                     1 0.00         0.99
45647400                     1 0.00         0.99
57930700                     1 0.00         1.00
90636600                     1 0.00         1.00

[251 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-13; Dividends
0                             252 1.00         1.00

                          Quantidade    %  % acumulado
2025-02-13; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-13; HLC
0.07                      1 0.00         0.00
0.26                      1 0.00         0.01
0.68                      1 0.00         0.01
0.72                      1 0.00         0.02
0.76                      1 0.00         0.02
...                     ...  ...          ...
53.33                     1 0.00         0.98
58.77                     1 0.00         0.99
60.12                     1 0.00         0.99
98.09                     1 0.00         1.00
122.19                    1 0.00         1.00

[252 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-14; Open
1.32                       2 0.01         0.01
0.79                       2 0.01         0.02
1.74                       2 0.01         0.02
1.42                       2 0.01         0.03
5.34                       2 0.01         0.04
...                      ...  ...          ...
53.86                      1 0.00         0.98
59.34                      1 0.00         0.99
60.76                      1 0.00         0.99
99.00                      1 0.00         1.00
121.54                     1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-14; High
1.01                       2 0.01         0.01
0.90                       2 0.01         0.02
3.13                       2 0.01         0.02
1.80                       2 0.01         0.03
2.00                       2 0.01         0.04
...                      ...  ...          ...
57.69                      1 0.00         0.98
59.60                      1 0.00         0.99
60.95                      1 0.00         0.99
101.60                     1 0.00         1.00
123.25                     1 0.00         1.00

[241 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-14; Low
0.72                      3 0.01         0.01
1.25                      2 0.01         0.02
3.44                      2 0.01         0.03
1.42                      2 0.01         0.04
2.39                      2 0.01         0.04
...                     ...  ...          ...
53.59                     1 0.00         0.98
57.65                     1 0.00         0.99
60.07                     1 0.00         0.99
98.79                     1 0.00         1.00
121.54                    1 0.00         1.00

[240 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-14; Close
1.28                        2 0.01         0.01
1.77                        2 0.01         0.02
10.30                       2 0.01         0.02
14.67                       2 0.01         0.03
20.40                       2 0.01         0.04
...                       ...  ...          ...
57.08                       1 0.00         0.98
58.85                       1 0.00         0.99
60.35                       1 0.00         0.99
101.60                      1 0.00         1.00
122.04                      1 0.00         1.00

[247 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-14; Volume
70800                        2 0.01         0.01
38400                        2 0.01         0.02
8700                         1 0.00         0.02
18700                        1 0.00         0.02
22200                        1 0.00         0.03
...                        ...  ...          ...
46583100                     1 0.00         0.98
46996800                     1 0.00         0.99
49803200                     1 0.00         0.99
51594000                     1 0.00         1.00
142875600                    1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-14; Dividends
0                             252 1.00         1.00

                          Quantidade    %  % acumulado
2025-02-14; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-14; HLC
1.77                      2 0.01         0.01
0.27                      1 0.00         0.01
0.07                      1 0.00         0.02
0.72                      1 0.00         0.02
0.74                      1 0.00         0.02
...                     ...  ...          ...
56.12                     1 0.00         0.98
58.70                     1 0.00         0.99
60.46                     1 0.00         0.99
100.66                    1 0.00         1.00
122.28                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-17; Open
1.40                       2 0.01         0.01
0.97                       2 0.01         0.02
1.71                       2 0.01         0.02
1.97                       2 0.01         0.03
3.94                       2 0.01         0.04
...                      ...  ...          ...
57.29                      1 0.00         0.98
58.99                      1 0.00         0.99
60.39                      1 0.00         0.99
101.60                     1 0.00         1.00
122.15                     1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-17; High
0.76                       2 0.01         0.01
1.35                       2 0.01         0.02
1.55                       2 0.01         0.02
3.83                       2 0.01         0.03
5.90                       2 0.01         0.04
...                      ...  ...          ...
57.99                      1 0.00         0.98
59.17                      1 0.00         0.99
60.92                      1 0.00         0.99
101.90                     1 0.00         1.00
122.78                     1 0.00         1.00

[245 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-17; Low
1.48                      2 0.01         0.01
1.24                      2 0.01         0.02
1.34                      2 0.01         0.02
3.09                      2 0.01         0.03
5.90                      2 0.01         0.04
...                     ...  ...          ...
56.80                     1 0.00         0.98
57.48                     1 0.00         0.99
58.78                     1 0.00         0.99
100.32                    1 0.00         1.00
120.64                    1 0.00         1.00

[244 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-17; Close
0.73                        3 0.01         0.01
1.34                        3 0.01         0.02
1.51                        2 0.01         0.03
3.25                        2 0.01         0.04
5.50                        2 0.01         0.05
...                       ...  ...          ...
56.85                       1 0.00         0.98
57.81                       1 0.00         0.99
60.47                       1 0.00         0.99
100.69                      1 0.00         1.00
122.00                      1 0.00         1.00

[243 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-17; Volume
1700                         1 0.00         0.00
6500                         1 0.00         0.01
8300                         1 0.00         0.01
14400                        1 0.00         0.02
16000                        1 0.00         0.02
...                        ...  ...          ...
44579600                     1 0.00         0.98
49607700                     1 0.00         0.99
49849848                     1 0.00         0.99
51927800                     1 0.00         1.00
96701300                     1 0.00         1.00

[252 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-17; Dividends
0                             252 1.00         1.00

                          Quantidade    %  % acumulado
2025-02-17; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-17; HLC
1.17                      2 0.01         0.01
0.28                      1 0.00         0.01
0.07                      1 0.00         0.02
0.67                      1 0.00         0.02
0.73                      1 0.00         0.02
...                     ...  ...          ...
57.21                     1 0.00         0.98
58.15                     1 0.00         0.99
60.06                     1 0.00         0.99
100.97                    1 0.00         1.00
121.81                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-18; Open
1.35                       3 0.01         0.01
0.73                       2 0.01         0.02
2.06                       2 0.01         0.03
5.26                       2 0.01         0.04
4.22                       2 0.01         0.04
...                      ...  ...          ...
56.80                      1 0.00         0.98
58.02                      1 0.00         0.99
60.50                      1 0.00         0.99
100.93                     1 0.00         1.00
124.00                     1 0.00         1.00

[241 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-18; High
1.28                       2 0.01         0.01
1.39                       2 0.01         0.02
2.55                       2 0.01         0.02
5.40                       2 0.01         0.03
6.69                       2 0.01         0.04
...                      ...  ...          ...
57.54                      1 0.00         0.98
58.22                      1 0.00         0.99
60.75                      1 0.00         0.99
101.25                     1 0.00         1.00
124.00                     1 0.00         1.00

[242 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-18; Low
19.02                     3 0.01         0.01
1.25                      2 0.01         0.02
0.69                      2 0.01         0.03
2.01                      2 0.01         0.04
5.46                      2 0.01         0.04
...                     ...  ...          ...
56.46                     1 0.00         0.98
57.34                     1 0.00         0.99
59.79                     1 0.00         0.99
99.38                     1 0.00         1.00
120.21                    1 0.00         1.00

[243 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-18; Close
0.73                        2 0.01         0.01
1.35                        2 0.01         0.02
1.26                        2 0.01         0.02
1.50                        2 0.01         0.03
5.79                        2 0.01         0.04
...                       ...  ...          ...
56.46                       1 0.00         0.98
57.70                       1 0.00         0.99
60.48                       1 0.00         0.99
100.05                      1 0.00         1.00
120.21                      1 0.00         1.00

[247 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-18; Volume
64600                        2 0.01         0.01
908400                       2 0.01         0.02
3157200                      2 0.01         0.02
3100                         1 0.00         0.03
2400                         1 0.00         0.03
...                        ...  ...          ...
58285600                     1 0.00         0.98
60855600                     1 0.00         0.99
64963400                     1 0.00         0.99
67192900                     1 0.00         1.00
82033900                     1 0.00         1.00

[249 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-18; Dividends
0.00                          246 0.98         0.98
0.60                            2 0.01         0.98
0.08                            1 0.00         0.99
0.12                            1 0.00         0.99
0.33                            1 0.00         1.00
1.44                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-18; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-18; HLC
0.73                      2 0.01         0.01
19.35                     2 0.01         0.02
0.28                      1 0.00         0.02
0.67                      1 0.00         0.02
0.73                      1 0.00         0.03
...                     ...  ...          ...
56.82                     1 0.00         0.98
57.75                     1 0.00         0.99
60.34                     1 0.00         0.99
100.23                    1 0.00         1.00
121.47                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-19; Open
0.73                       3 0.01         0.01
5.25                       3 0.01         0.02
3.76                       2 0.01         0.03
1.72                       2 0.01         0.04
3.21                       2 0.01         0.05
...                      ...  ...          ...
55.99                      1 0.00         0.98
57.53                      1 0.00         0.99
60.10                      1 0.00         0.99
99.38                      1 0.00         1.00
120.41                     1 0.00         1.00

[241 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-19; High
5.25                       3 0.01         0.01
1.34                       2 0.01         0.02
3.90                       2 0.01         0.03
5.85                       2 0.01         0.04
1.27                       2 0.01         0.04
...                      ...  ...          ...
56.69                      1 0.00         0.98
58.57                      1 0.00         0.99
61.20                      1 0.00         0.99
99.87                      1 0.00         1.00
121.18                     1 0.00         1.00

[245 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-19; Low
5.94                      3 0.01         0.01
5.05                      3 0.01         0.02
0.69                      2 0.01         0.03
1.28                      2 0.01         0.04
5.49                      2 0.01         0.05
...                     ...  ...          ...
54.50                     1 0.00         0.98
57.34                     1 0.00         0.99
59.90                     1 0.00         0.99
98.41                     1 0.00         1.00
118.65                    1 0.00         1.00

[240 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-19; Close
1.27                        2 0.01         0.01
0.73                        2 0.01         0.02
1.32                        2 0.01         0.02
3.77                        2 0.01         0.03
3.03                        2 0.01         0.04
...                       ...  ...          ...
54.72                       1 0.00         0.98
58.07                       1 0.00         0.99
60.88                       1 0.00         0.99
99.02                       1 0.00         1.00
120.84                      1 0.00         1.00

[242 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-19; Volume
114000                       2 0.01         0.01
2500                         1 0.00         0.01
200                          1 0.00         0.02
6600                         1 0.00         0.02
9600                         1 0.00         0.02
...                        ...  ...          ...
38104400                     1 0.00         0.98
41412200                     1 0.00         0.99
43702000                     1 0.00         0.99
62698800                     1 0.00         1.00
73077800                     1 0.00         1.00

[251 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-19; Dividends
0                             252 1.00         1.00

                          Quantidade    %  % acumulado
2025-02-19; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-19; HLC
5.57                      2 0.01         0.01
0.27                      1 0.00         0.01
0.06                      1 0.00         0.02
0.73                      1 0.00         0.02
0.73                      1 0.00         0.02
...                     ...  ...          ...
55.30                     1 0.00         0.98
57.99                     1 0.00         0.99
60.66                     1 0.00         0.99
99.10                     1 0.00         1.00
120.22                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-20; Open
5.70                       3 0.01         0.01
1.30                       2 0.01         0.02
3.22                       2 0.01         0.03
3.87                       2 0.01         0.04
0.90                       2 0.01         0.04
...                      ...  ...          ...
54.92                      1 0.00         0.98
58.07                      1 0.00         0.99
61.00                      1 0.00         0.99
98.55                      1 0.00         1.00
119.99                     1 0.00         1.00

[241 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-20; High
5.74                       3 0.01         0.01
5.32                       2 0.01         0.02
8.90                       2 0.01         0.03
10.98                      2 0.01         0.04
0.73                       1 0.00         0.04
...                      ...  ...          ...
55.98                      1 0.00         0.98
58.13                      1 0.00         0.99
61.57                      1 0.00         0.99
99.47                      1 0.00         1.00
120.99                     1 0.00         1.00

[247 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-20; Low
1.26                      3 0.01         0.01
0.72                      2 0.01         0.02
1.66                      2 0.01         0.03
8.31                      2 0.01         0.04
5.51                      2 0.01         0.04
...                     ...  ...          ...
54.36                     1 0.00         0.98
57.47                     1 0.00         0.99
60.20                     1 0.00         0.99
97.62                     1 0.00         1.00
119.03                    1 0.00         1.00

[243 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-20; Close
0.72                        2 0.01         0.01
1.26                        2 0.01         0.02
1.29                        2 0.01         0.02
1.27                        2 0.01         0.03
2.27                        2 0.01         0.04
...                       ...  ...          ...
55.57                       1 0.00         0.98
57.67                       1 0.00         0.99
61.23                       1 0.00         0.99
98.64                       1 0.00         1.00
120.21                      1 0.00         1.00

[244 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-20; Volume
19700                        2 0.01         0.01
2700                         1 0.00         0.01
1600                         1 0.00         0.02
4600                         1 0.00         0.02
5900                         1 0.00         0.02
...                        ...  ...          ...
44076800                     1 0.00         0.98
54915100                     1 0.00         0.99
76934000                     1 0.00         0.99
88971000                     1 0.00         1.00
97669500                     1 0.00         1.00

[251 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-20; Dividends
0.00                          251 1.00         1.00
0.01                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-20; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-20; HLC
0.06                      1 0.00         0.00
0.26                      1 0.00         0.01
0.65                      1 0.00         0.01
0.71                      1 0.00         0.02
0.72                      1 0.00         0.02
...                     ...  ...          ...
55.30                     1 0.00         0.98
57.76                     1 0.00         0.99
61.00                     1 0.00         0.99
98.58                     1 0.00         1.00
120.08                    1 0.00         1.00

[252 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-21; Open
1.29                       3 0.01         0.01
1.27                       3 0.01         0.02
0.72                       2 0.01         0.03
1.75                       2 0.01         0.04
2.29                       2 0.01         0.05
...                      ...  ...          ...
55.73                      1 0.00         0.98
57.92                      1 0.00         0.99
61.33                      1 0.00         0.99
98.98                      1 0.00         1.00
121.79                     1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-21; High
1.31                       4 0.02         0.02
1.15                       2 0.01         0.02
0.92                       2 0.01         0.03
2.64                       2 0.01         0.04
2.29                       2 0.01         0.05
...                      ...  ...          ...
55.98                      1 0.00         0.98
58.27                      1 0.00         0.99
61.86                      1 0.00         0.99
99.42                      1 0.00         1.00
121.79                     1 0.00         1.00

[241 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-21; Low
1.25                      2 0.01         0.01
3.54                      2 0.01         0.02
2.92                      2 0.01         0.02
4.38                      2 0.01         0.03
30.81                     2 0.01         0.04
...                     ...  ...          ...
55.40                     1 0.00         0.98
57.08                     1 0.00         0.99
58.78                     1 0.00         0.99
97.45                     1 0.00         1.00
119.19                    1 0.00         1.00

[246 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-21; Close
1.10                        2 0.01         0.01
1.26                        2 0.01         0.02
1.29                        2 0.01         0.02
3.45                        2 0.01         0.03
3.84                        2 0.01         0.04
...                       ...  ...          ...
55.98                       1 0.00         0.98
57.50                       1 0.00         0.99
58.98                       1 0.00         0.99
98.55                       1 0.00         1.00
120.60                      1 0.00         1.00

[245 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-21; Volume
300900                       2 0.01         0.01
254100                       2 0.01         0.02
6500                         1 0.00         0.02
9300                         1 0.00         0.02
9900                         1 0.00         0.03
...                        ...  ...          ...
37134700                     1 0.00         0.98
45757000                     1 0.00         0.99
88654700                     1 0.00         0.99
90187000                     1 0.00         1.00
94029400                     1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-21; Dividends
0.00                          249 0.99         0.99
0.05                            1 0.00         0.99
0.09                            1 0.00         1.00
2.31                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-21; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-21; HLC
1.28                      2 0.01         0.01
1.26                      2 0.01         0.02
8.41                      2 0.01         0.02
0.27                      1 0.00         0.03
0.58                      1 0.00         0.03
...                     ...  ...          ...
55.78                     1 0.00         0.98
57.62                     1 0.00         0.99
59.87                     1 0.00         0.99
98.47                     1 0.00         1.00
120.53                    1 0.00         1.00

[249 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-24; Open
1.29                       2 0.01         0.01
1.25                       2 0.01         0.02
1.63                       2 0.01         0.02
3.60                       2 0.01         0.03
8.40                       2 0.01         0.04
...                      ...  ...          ...
55.92                      1 0.00         0.98
57.55                      1 0.00         0.99
59.30                      1 0.00         0.99
99.30                      1 0.00         1.00
121.00                     1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-24; High
1.51                       2 0.01         0.01
3.87                       2 0.01         0.02
2.38                       2 0.01         0.02
1.73                       2 0.01         0.03
5.46                       2 0.01         0.04
...                      ...  ...          ...
56.37                      1 0.00         0.98
57.85                      1 0.00         0.99
60.15                      1 0.00         0.99
99.30                      1 0.00         1.00
125.87                     1 0.00         1.00

[245 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-24; Low
1.42                      3 0.01         0.01
1.63                      2 0.01         0.02
2.60                      2 0.01         0.03
2.18                      2 0.01         0.04
4.05                      2 0.01         0.04
...                     ...  ...          ...
55.32                     1 0.00         0.98
56.89                     1 0.00         0.99
57.88                     1 0.00         0.99
96.76                     1 0.00         1.00
121.00                    1 0.00         1.00

[242 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-24; Close
4.37                        2 0.01         0.01
4.30                        2 0.01         0.02
5.38                        2 0.01         0.02
0.26                        1 0.00         0.03
0.81                        1 0.00         0.03
...                       ...  ...          ...
55.47                       1 0.00         0.98
57.03                       1 0.00         0.99
59.89                       1 0.00         0.99
97.03                       1 0.00         1.00
121.73                      1 0.00         1.00

[249 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-24; Volume
5500                         1 0.00         0.00
8400                         1 0.00         0.01
9700                         1 0.00         0.01
10000                        1 0.00         0.02
10900                        1 0.00         0.02
...                        ...  ...          ...
37945600                     1 0.00         0.98
42173000                     1 0.00         0.99
45299900                     1 0.00         0.99
58518400                     1 0.00         1.00
119456400                    1 0.00         1.00

[252 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-24; Dividends
0.00                          251 1.00         1.00
0.02                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-24; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-24; HLC
3.82                      2 0.01         0.01
0.27                      1 0.00         0.01
0.06                      1 0.00         0.02
0.71                      1 0.00         0.02
0.81                      1 0.00         0.02
...                     ...  ...          ...
55.72                     1 0.00         0.98
57.26                     1 0.00         0.99
59.31                     1 0.00         0.99
97.70                     1 0.00         1.00
122.87                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-25; Open
4.27                       3 0.01         0.01
1.42                       2 0.01         0.02
3.42                       2 0.01         0.03
6.98                       2 0.01         0.04
3.80                       2 0.01         0.04
...                      ...  ...          ...
55.15                      1 0.00         0.98
57.64                      1 0.00         0.99
60.96                      1 0.00         0.99
97.79                      1 0.00         1.00
122.02                     1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-25; High
8.59                       3 0.01         0.01
1.23                       2 0.01         0.02
1.98                       2 0.01         0.03
2.28                       2 0.01         0.04
5.42                       2 0.01         0.04
...                      ...  ...          ...
56.31                      1 0.00         0.98
57.65                      1 0.00         0.99
62.85                      1 0.00         0.99
99.16                      1 0.00         1.00
123.06                     1 0.00         1.00

[242 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-25; Low
1.37                      2 0.01         0.01
1.77                      2 0.01         0.02
2.13                      2 0.01         0.02
5.34                      2 0.01         0.03
5.26                      2 0.01         0.04
...                     ...  ...          ...
54.75                     1 0.00         0.98
56.67                     1 0.00         0.99
60.46                     1 0.00         0.99
96.94                     1 0.00         1.00
117.33                    1 0.00         1.00

[245 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-25; Close
8.30                        3 0.01         0.01
2.85                        2 0.01         0.02
5.34                        2 0.01         0.03
5.87                        2 0.01         0.04
4.22                        2 0.01         0.04
...                       ...  ...          ...
54.93                       1 0.00         0.98
56.84                       1 0.00         0.99
60.62                       1 0.00         0.99
97.90                       1 0.00         1.00
120.20                      1 0.00         1.00

[242 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-25; Volume
31500                        2 0.01         0.01
303800                       2 0.01         0.02
7900                         1 0.00         0.02
9000                         1 0.00         0.02
9800                         1 0.00         0.03
...                        ...  ...          ...
36948900                     1 0.00         0.98
41440200                     1 0.00         0.99
47453300                     1 0.00         0.99
76158600                     1 0.00         1.00
105924100                    1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-25; Dividends
0.00                          251 1.00         1.00
0.11                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-25; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-25; HLC
1.20                      2 0.01         0.01
0.26                      1 0.00         0.01
0.06                      1 0.00         0.02
0.71                      1 0.00         0.02
0.83                      1 0.00         0.02
...                     ...  ...          ...
55.19                     1 0.00         0.98
57.05                     1 0.00         0.99
61.31                     1 0.00         0.99
98.00                     1 0.00         1.00
120.20                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-26; Open
1.41                       2 0.01         0.01
1.91                       2 0.01         0.02
5.34                       2 0.01         0.02
4.34                       2 0.01         0.03
3.80                       2 0.01         0.04
...                      ...  ...          ...
55.22                      1 0.00         0.98
57.20                      1 0.00         0.99
61.22                      1 0.00         0.99
98.54                      1 0.00         1.00
120.00                     1 0.00         1.00

[245 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-26; High
1.41                       2 0.01         0.01
1.44                       2 0.01         0.02
1.14                       2 0.01         0.02
1.30                       2 0.01         0.03
1.92                       2 0.01         0.04
...                      ...  ...          ...
55.52                      1 0.00         0.98
57.35                      1 0.00         0.99
62.49                      1 0.00         0.99
98.70                      1 0.00         1.00
122.04                     1 0.00         1.00

[243 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-26; Low
1.72                      2 0.01         0.01
2.08                      2 0.01         0.02
5.97                      2 0.01         0.02
5.20                      2 0.01         0.03
8.95                      2 0.01         0.04
...                     ...  ...          ...
54.59                     1 0.00         0.98
56.74                     1 0.00         0.99
60.71                     1 0.00         0.99
95.83                     1 0.00         1.00
119.03                    1 0.00         1.00

[246 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-26; Close
4.19                        3 0.01         0.01
1.10                        2 0.01         0.02
1.41                        2 0.01         0.03
0.81                        2 0.01         0.04
16.40                       2 0.01         0.04
...                       ...  ...          ...
54.59                       1 0.00         0.98
57.04                       1 0.00         0.99
61.45                       1 0.00         0.99
96.30                       1 0.00         1.00
120.64                      1 0.00         1.00

[245 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-26; Volume
16900                        2 0.01         0.01
13100                        1 0.00         0.01
11000                        1 0.00         0.02
13700                        1 0.00         0.02
15500                        1 0.00         0.02
...                        ...  ...          ...
40056600                     1 0.00         0.98
40355500                     1 0.00         0.99
51824900                     1 0.00         0.99
79612200                     1 0.00         1.00
134316800                    1 0.00         1.00

[251 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-26; Dividends
0.00                          250 0.99         0.99
0.03                            1 0.00         1.00
1.90                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-26; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-26; HLC
5.83                      2 0.01         0.01
0.26                      1 0.00         0.01
0.06                      1 0.00         0.02
0.69                      1 0.00         0.02
0.81                      1 0.00         0.02
...                     ...  ...          ...
54.90                     1 0.00         0.98
57.04                     1 0.00         0.99
61.55                     1 0.00         0.99
96.94                     1 0.00         1.00
120.57                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-27; Open
1.10                       2 0.01         0.01
0.82                       2 0.01         0.02
1.74                       2 0.01         0.02
2.09                       2 0.01         0.03
1.56                       2 0.01         0.04
...                      ...  ...          ...
54.33                      1 0.00         0.98
57.06                      1 0.00         0.99
64.21                      1 0.00         0.99
96.59                      1 0.00         1.00
120.64                     1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-27; High
1.42                       2 0.01         0.01
2.20                       2 0.01         0.02
7.45                       2 0.01         0.02
5.48                       2 0.01         0.03
12.18                      2 0.01         0.04
...                      ...  ...          ...
54.85                      1 0.00         0.98
57.84                      1 0.00         0.99
70.31                      1 0.00         0.99
97.10                      1 0.00         1.00
122.84                     1 0.00         1.00

[246 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-27; Low
4.24                      3 0.01         0.01
2.09                      2 0.01         0.02
3.37                      2 0.01         0.03
1.72                      2 0.01         0.04
1.33                      2 0.01         0.04
...                     ...  ...          ...
53.91                     1 0.00         0.98
56.84                     1 0.00         0.99
62.72                     1 0.00         0.99
95.57                     1 0.00         1.00
120.64                    1 0.00         1.00

[241 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-27; Close
1.11                        2 0.01         0.01
1.36                        2 0.01         0.02
3.38                        2 0.01         0.02
1.76                        2 0.01         0.03
1.52                        2 0.01         0.04
...                       ...  ...          ...
54.19                       1 0.00         0.98
57.17                       1 0.00         0.99
68.90                       1 0.00         0.99
95.82                       1 0.00         1.00
121.70                      1 0.00         1.00

[239 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-27; Volume
12300                        2 0.01         0.01
43500                        2 0.01         0.02
13100                        1 0.00         0.02
14700                        1 0.00         0.02
15300                        1 0.00         0.03
...                        ...  ...          ...
48084000                     1 0.00         0.98
53797700                     1 0.00         0.99
66169900                     1 0.00         0.99
96915200                     1 0.00         1.00
129693500                    1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-27; Dividends
0.00                          250 0.99         0.99
0.23                            2 0.01         1.00

                          Quantidade    %  % acumulado
2025-02-27; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-27; HLC
7.24                      2 0.01         0.01
0.26                      1 0.00         0.01
0.06                      1 0.00         0.02
0.68                      1 0.00         0.02
0.80                      1 0.00         0.02
...                     ...  ...          ...
54.31                     1 0.00         0.98
57.28                     1 0.00         0.99
67.31                     1 0.00         0.99
96.16                     1 0.00         1.00
121.73                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-28; Open
1.11                       3 0.01         0.01
1.54                       2 0.01         0.02
1.76                       2 0.01         0.03
1.39                       2 0.01         0.04
5.91                       2 0.01         0.04
...                      ...  ...          ...
53.84                      1 0.00         0.98
56.96                      1 0.00         0.99
68.03                      1 0.00         0.99
95.55                      1 0.00         1.00
123.01                     1 0.00         1.00

[241 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-28; High
1.41                       3 0.01         0.01
1.27                       2 0.01         0.02
1.13                       2 0.01         0.03
4.37                       2 0.01         0.04
5.75                       2 0.01         0.04
...                      ...  ...          ...
54.03                      1 0.00         0.98
57.28                      1 0.00         0.99
70.05                      1 0.00         0.99
96.34                      1 0.00         1.00
128.21                     1 0.00         1.00

[240 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-28; Low
10.91                     3 0.01         0.01
1.65                      2 0.01         0.02
5.66                      2 0.01         0.03
5.55                      2 0.01         0.04
7.96                      2 0.01         0.04
...                     ...  ...          ...
53.08                     1 0.00         0.98
56.05                     1 0.00         0.99
67.80                     1 0.00         0.99
94.37                     1 0.00         1.00
122.23                    1 0.00         1.00

[242 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-28; Close
3.56                        3 0.01         0.01
1.13                        2 0.01         0.02
1.35                        2 0.01         0.03
1.39                        2 0.01         0.04
1.98                        2 0.01         0.04
...                       ...  ...          ...
53.08                       1 0.00         0.98
56.31                       1 0.00         0.99
69.72                       1 0.00         0.99
94.98                       1 0.00         1.00
125.17                      1 0.00         1.00

[236 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-28; Volume
2300                         1 0.00         0.00
3900                         1 0.00         0.01
17800                        1 0.00         0.01
18300                        1 0.00         0.02
18500                        1 0.00         0.02
...                        ...  ...          ...
84387200                     1 0.00         0.98
91028700                     1 0.00         0.99
104972500                    1 0.00         0.99
226148900                    1 0.00         1.00
703389500                    1 0.00         1.00

[252 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-28; Dividends
0.00                          249 0.99         0.99
0.11                            1 0.00         0.99
0.19                            1 0.00         1.00
1.23                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-28; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-28; HLC
1.68                      2 0.01         0.01
10.04                     2 0.01         0.02
0.54                      1 0.00         0.02
0.69                      1 0.00         0.02
0.76                      1 0.00         0.03
...                     ...  ...          ...
53.40                     1 0.00         0.98
56.55                     1 0.00         0.99
69.19                     1 0.00         0.99
95.23                     1 0.00         1.00
125.20                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-05; Open
5.68                       3 0.01         0.01
2.16                       2 0.01         0.02
2.74                       2 0.01         0.03
1.39                       2 0.01         0.04
5.50                       2 0.01         0.04
...                      ...  ...          ...
54.04                      1 0.00         0.98
56.19                      1 0.00         0.99
72.00                      1 0.00         0.99
94.80                      1 0.00         1.00
125.17                     1 0.00         1.00

[241 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-05; High
1.22                       2 0.01         0.01
1.72                       2 0.01         0.02
1.79                       2 0.01         0.02
5.17                       2 0.01         0.03
5.57                       2 0.01         0.04
...                      ...  ...          ...
54.11                      1 0.00         0.98
56.61                      1 0.00         0.99
76.15                      1 0.00         0.99
95.12                      1 0.00         1.00
132.04                     1 0.00         1.00

[243 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-05; Low
1.34                      3 0.01         0.01
1.10                      2 0.01         0.02
3.30                      2 0.01         0.03
1.63                      2 0.01         0.04
1.13                      2 0.01         0.04
...                     ...  ...          ...
53.31                     1 0.00         0.98
55.13                     1 0.00         0.99
71.61                     1 0.00         0.99
93.19                     1 0.00         1.00
123.59                    1 0.00         1.00

[241 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-05; Close
5.29                        3 0.01         0.01
1.09                        2 0.01         0.02
1.37                        2 0.01         0.03
1.39                        2 0.01         0.04
3.30                        2 0.01         0.04
...                       ...  ...          ...
53.50                       1 0.00         0.98
55.37                       1 0.00         0.99
75.85                       1 0.00         0.99
94.11                       1 0.00         1.00
126.29                      1 0.00         1.00

[238 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-05; Volume
20000                        2 0.01         0.01
7400                         2 0.01         0.02
5800                         1 0.00         0.02
1500                         1 0.00         0.02
12500                        1 0.00         0.03
...                        ...  ...          ...
41379800                     1 0.00         0.98
46942500                     1 0.00         0.99
48552000                     1 0.00         0.99
54086900                     1 0.00         1.00
77802900                     1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-05; Dividends
0.00                          247 0.98         0.98
0.02                            2 0.01         0.99
0.05                            2 0.01         1.00
0.30                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-05; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-05; HLC
1.69                      2 0.01         0.01
0.24                      1 0.00         0.01
0.06                      1 0.00         0.02
0.69                      1 0.00         0.02
0.77                      1 0.00         0.02
...                     ...  ...          ...
53.64                     1 0.00         0.98
55.70                     1 0.00         0.99
74.54                     1 0.00         0.99
94.14                     1 0.00         1.00
127.31                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-06; Open
1.04                       2 0.01         0.01
1.67                       2 0.01         0.02
1.39                       2 0.01         0.02
2.65                       2 0.01         0.03
5.25                       2 0.01         0.04
...                      ...  ...          ...
53.55                      1 0.00         0.98
55.64                      1 0.00         0.99
75.55                      1 0.00         0.99
94.69                      1 0.00         1.00
128.00                     1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-06; High
1.41                       3 0.01         0.01
5.47                       3 0.01         0.02
1.72                       2 0.01         0.03
0.86                       2 0.01         0.04
2.95                       2 0.01         0.05
...                      ...  ...          ...
54.40                      1 0.00         0.98
55.85                      1 0.00         0.99
76.37                      1 0.00         0.99
95.32                      1 0.00         1.00
139.34                     1 0.00         1.00

[240 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-06; Low
2.60                      2 0.01         0.01
1.35                      2 0.01         0.02
2.42                      2 0.01         0.02
5.35                      2 0.01         0.03
3.91                      2 0.01         0.04
...                     ...  ...          ...
53.46                     1 0.00         0.98
54.69                     1 0.00         0.99
74.09                     1 0.00         0.99
93.60                     1 0.00         1.00
125.27                    1 0.00         1.00

[242 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-06; Close
0.85                        2 0.01         0.01
1.37                        2 0.01         0.02
1.15                        2 0.01         0.02
2.08                        2 0.01         0.03
1.78                        2 0.01         0.04
...                       ...  ...          ...
54.09                       1 0.00         0.98
55.16                       1 0.00         0.99
74.72                       1 0.00         0.99
94.16                       1 0.00         1.00
127.50                      1 0.00         1.00

[247 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-06; Volume
18800                        2 0.01         0.01
75000                        2 0.01         0.02
4200                         1 0.00         0.02
5100                         1 0.00         0.02
7000                         1 0.00         0.03
...                        ...  ...          ...
40524500                     1 0.00         0.98
44187500                     1 0.00         0.99
47585600                     1 0.00         0.99
47749600                     1 0.00         1.00
66517100                     1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-06; Dividends
0.00                          242 0.96         0.96
0.01                            2 0.01         0.97
0.05                            2 0.01         0.98
0.02                            1 0.00         0.98
0.02                            1 0.00         0.98
0.04                            1 0.00         0.99
0.10                            1 0.00         0.99
0.27                            1 0.00         1.00
0.48                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-06; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-06; HLC
3.66                      2 0.01         0.01
9.18                      2 0.01         0.02
0.51                      1 0.00         0.02
0.68                      1 0.00         0.02
0.78                      1 0.00         0.03
...                     ...  ...          ...
53.98                     1 0.00         0.98
55.23                     1 0.00         0.99
75.06                     1 0.00         0.99
94.36                     1 0.00         1.00
130.70                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-07; Open
5.90                       3 0.01         0.01
2.08                       2 0.01         0.02
1.36                       2 0.01         0.03
4.00                       2 0.01         0.04
5.42                       2 0.01         0.04
...                      ...  ...          ...
53.88                      1 0.00         0.98
54.82                      1 0.00         0.99
74.57                      1 0.00         0.99
93.20                      1 0.00         1.00
129.15                     1 0.00         1.00

[239 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-07; High
0.91                       2 0.01         0.01
1.06                       2 0.01         0.02
1.43                       2 0.01         0.02
4.35                       2 0.01         0.03
4.17                       2 0.01         0.04
...                      ...  ...          ...
55.20                      1 0.00         0.98
55.65                      1 0.00         0.99
74.90                      1 0.00         0.99
96.82                      1 0.00         1.00
134.60                     1 0.00         1.00

[239 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-07; Low
5.07                      3 0.01         0.01
1.17                      2 0.01         0.02
0.86                      2 0.01         0.03
5.49                      2 0.01         0.04
5.23                      2 0.01         0.04
...                     ...  ...          ...
53.46                     1 0.00         0.98
54.45                     1 0.00         0.99
72.80                     1 0.00         0.99
92.95                     1 0.00         1.00
128.31                    1 0.00         1.00

[243 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-07; Close
1.16                        2 0.01         0.01
1.04                        2 0.01         0.02
1.19                        2 0.01         0.02
2.69                        2 0.01         0.03
1.87                        2 0.01         0.04
...                       ...  ...          ...
54.88                       1 0.00         0.98
55.34                       1 0.00         0.99
73.68                       1 0.00         0.99
96.19                       1 0.00         1.00
132.88                      1 0.00         1.00

[238 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-07; Volume
3200                         1 0.00         0.00
7400                         1 0.00         0.01
7800                         1 0.00         0.01
8200                         1 0.00         0.02
13500                        1 0.00         0.02
...                        ...  ...          ...
30190400                     1 0.00         0.98
36134200                     1 0.00         0.99
40884800                     1 0.00         0.99
41638200                     1 0.00         1.00
97225000                     1 0.00         1.00

[252 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-07; Dividends
0.00                          248 0.98         0.98
0.19                            1 0.00         0.99
0.27                            1 0.00         0.99
0.45                            1 0.00         1.00
0.47                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-07; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-07; HLC
0.06                      1 0.00         0.00
0.25                      1 0.00         0.01
0.53                      1 0.00         0.01
0.68                      1 0.00         0.02
0.78                      1 0.00         0.02
...                     ...  ...          ...
54.51                     1 0.00         0.98
55.15                     1 0.00         0.99
73.79                     1 0.00         0.99
95.32                     1 0.00         1.00
131.93                    1 0.00         1.00

[252 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-10; Open
1.20                       2 0.01         0.01
1.18                       2 0.01         0.02
1.85                       2 0.01         0.02
3.84                       2 0.01         0.03
5.87                       2 0.01         0.04
...                      ...  ...          ...
54.23                      1 0.00         0.98
55.01                      1 0.00         0.99
73.16                      1 0.00         0.99
95.58                      1 0.00         1.00
132.88                     1 0.00         1.00

[241 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-10; High
1.24                       2 0.01         0.01
3.78                       2 0.01         0.02
2.29                       2 0.01         0.02
1.47                       2 0.01         0.03
3.89                       2 0.01         0.04
...                      ...  ...          ...
54.55                      1 0.00         0.98
55.69                      1 0.00         0.99
74.82                      1 0.00         0.99
97.38                      1 0.00         1.00
137.00                     1 0.00         1.00

[244 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-10; Low
1.14                      3 0.01         0.01
1.36                      2 0.01         0.02
1.78                      2 0.01         0.03
5.80                      2 0.01         0.04
5.86                      2 0.01         0.04
...                     ...  ...          ...
53.25                     1 0.00         0.98
54.68                     1 0.00         0.99
72.92                     1 0.00         0.99
95.34                     1 0.00         1.00
131.65                    1 0.00         1.00

[240 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-10; Close
0.88                        2 0.01         0.01
1.19                        2 0.01         0.02
1.18                        2 0.01         0.02
1.37                        2 0.01         0.03
1.24                        2 0.01         0.04
...                       ...  ...          ...
53.99                       1 0.00         0.98
55.59                       1 0.00         0.99
74.25                       1 0.00         0.99
96.84                       1 0.00         1.00
134.95                      1 0.00         1.00

[240 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-10; Volume
126400                       2 0.01         0.01
2300                         1 0.00         0.01
1900                         1 0.00         0.02
7600                         1 0.00         0.02
10300                        1 0.00         0.02
...                        ...  ...          ...
35037200                     1 0.00         0.98
39247100                     1 0.00         0.99
42234700                     1 0.00         0.99
50198700                     1 0.00         1.00
78062300                     1 0.00         1.00

[251 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-10; Dividends
0.00                          251 1.00         1.00
2.14                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-10; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-10; HLC
4.15                      2 0.01         0.01
0.25                      1 0.00         0.01
0.06                      1 0.00         0.02
0.69                      1 0.00         0.02
0.78                      1 0.00         0.02
...                     ...  ...          ...
53.93                     1 0.00         0.98
55.32                     1 0.00         0.99
74.00                     1 0.00         0.99
96.52                     1 0.00         1.00
134.53                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-11; Open
1.21                       2 0.01         0.01
0.91                       2 0.01         0.02
3.43                       2 0.01         0.02
2.21                       2 0.01         0.03
1.75                       2 0.01         0.04
...                      ...  ...          ...
54.08                      1 0.00         0.98
55.68                      1 0.00         0.99
74.35                      1 0.00         0.99
96.47                      1 0.00         1.00
135.04                     1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-11; High
1.20                       2 0.01         0.01
1.21                       2 0.01         0.02
1.76                       2 0.01         0.02
1.55                       2 0.01         0.03
1.30                       2 0.01         0.04
...                      ...  ...          ...
54.72                      1 0.00         0.98
56.10                      1 0.00         0.99
74.35                      1 0.00         0.99
96.80                      1 0.00         1.00
136.46                     1 0.00         1.00

[237 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-11; Low
1.35                      3 0.01         0.01
10.40                     3 0.01         0.02
1.15                      2 0.01         0.03
2.35                      2 0.01         0.04
2.67                      2 0.01         0.05
...                     ...  ...          ...
53.41                     1 0.00         0.98
54.74                     1 0.00         0.99
72.75                     1 0.00         0.99
94.96                     1 0.00         1.00
133.00                    1 0.00         1.00

[236 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-11; Close
1.37                        2 0.01         0.01
1.19                        2 0.01         0.02
1.74                        2 0.01         0.02
5.27                        2 0.01         0.03
4.05                        2 0.01         0.04
...                       ...  ...          ...
54.44                       1 0.00         0.98
55.13                       1 0.00         0.99
73.22                       1 0.00         0.99
95.94                       1 0.00         1.00
133.87                      1 0.00         1.00

[245 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-11; Volume
50700                        2 0.01         0.01
4600                         1 0.00         0.01
1500                         1 0.00         0.02
12300                        1 0.00         0.02
13700                        1 0.00         0.02
...                        ...  ...          ...
32659900                     1 0.00         0.98
35459700                     1 0.00         0.99
43087500                     1 0.00         0.99
47997200                     1 0.00         1.00
59563500                     1 0.00         1.00

[251 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-11; Dividends
0.00                          251 1.00         1.00
0.19                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-11; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-11; HLC
1.18                      2 0.01         0.01
3.78                      2 0.01         0.02
0.51                      1 0.00         0.02
0.69                      1 0.00         0.02
0.78                      1 0.00         0.03
...                     ...  ...          ...
54.19                     1 0.00         0.98
55.32                     1 0.00         0.99
73.44                     1 0.00         0.99
95.90                     1 0.00         1.00
134.44                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-12; Open
3.75                       3 0.01         0.01
1.18                       2 0.01         0.02
2.76                       2 0.01         0.03
4.00                       2 0.01         0.04
3.67                       2 0.01         0.04
...                      ...  ...          ...
54.50                      1 0.00         0.98
55.15                      1 0.00         0.99
73.13                      1 0.00         0.99
95.92                      1 0.00         1.00
133.30                     1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-12; High
0.90                       2 0.01         0.01
1.19                       2 0.01         0.02
1.20                       2 0.01         0.02
1.40                       2 0.01         0.03
3.90                       2 0.01         0.04
...                      ...  ...          ...
54.50                      1 0.00         0.98
55.35                      1 0.00         0.99
74.15                      1 0.00         0.99
97.24                      1 0.00         1.00
136.50                     1 0.00         1.00

[239 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-12; Low
1.17                      3 0.01         0.01
0.84                      2 0.01         0.02
1.35                      2 0.01         0.03
1.23                      2 0.01         0.04
1.16                      2 0.01         0.04
...                     ...  ...          ...
53.15                     1 0.00         0.98
54.48                     1 0.00         0.99
72.41                     1 0.00         0.99
95.29                     1 0.00         1.00
131.04                    1 0.00         1.00

[234 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-12; Close
1.86                        3 0.01         0.01
3.71                        3 0.01         0.02
1.18                        2 0.01         0.03
2.22                        2 0.01         0.04
3.38                        2 0.01         0.05
...                       ...  ...          ...
53.76                       1 0.00         0.98
54.75                       1 0.00         0.99
72.96                       1 0.00         0.99
95.77                       1 0.00         1.00
131.04                      1 0.00         1.00

[239 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-12; Volume
74500                        2 0.01         0.01
6200                         1 0.00         0.01
5300                         1 0.00         0.02
11100                        1 0.00         0.02
11600                        1 0.00         0.02
...                        ...  ...          ...
31708500                     1 0.00         0.98
38219900                     1 0.00         0.99
39894000                     1 0.00         0.99
46499100                     1 0.00         1.00
54749900                     1 0.00         1.00

[251 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-12; Dividends
0.00                          249 0.99         0.99
0.07                            1 0.00         0.99
0.29                            1 0.00         1.00
0.67                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-12; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-12; HLC
1.25                      2 0.01         0.01
5.23                      2 0.01         0.02
0.51                      1 0.00         0.02
0.68                      1 0.00         0.02
0.86                      1 0.00         0.03
...                     ...  ...          ...
53.80                     1 0.00         0.98
54.86                     1 0.00         0.99
73.17                     1 0.00         0.99
96.10                     1 0.00         1.00
132.86                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-13; Open
1.17                       3 0.01         0.01
1.00                       2 0.01         0.02
1.38                       2 0.01         0.03
0.87                       2 0.01         0.04
3.38                       2 0.01         0.04
...                      ...  ...          ...
53.88                      1 0.00         0.98
54.70                      1 0.00         0.99
73.00                      1 0.00         0.99
96.33                      1 0.00         1.00
131.04                     1 0.00         1.00

[240 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-13; High
7.15                       3 0.01         0.01
1.18                       2 0.01         0.02
0.89                       2 0.01         0.03
3.42                       2 0.01         0.04
3.00                       2 0.01         0.04
...                      ...  ...          ...
54.86                      1 0.00         0.98
55.16                      1 0.00         0.99
74.50                      1 0.00         0.99
98.00                      1 0.00         1.00
131.31                     1 0.00         1.00

[239 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-13; Low
1.12                      2 0.01         0.01
1.84                      2 0.01         0.02
5.16                      2 0.01         0.02
5.18                      2 0.01         0.03
4.28                      2 0.01         0.04
...                     ...  ...          ...
53.70                     1 0.00         0.98
54.15                     1 0.00         0.99
72.83                     1 0.00         0.99
94.12                     1 0.00         1.00
125.50                    1 0.00         1.00

[245 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-13; Close
1.18                        2 0.01         0.01
1.16                        2 0.01         0.02
1.19                        2 0.01         0.02
2.72                        2 0.01         0.03
1.61                        2 0.01         0.04
...                       ...  ...          ...
54.31                       1 0.00         0.98
54.50                       1 0.00         0.99
73.85                       1 0.00         0.99
97.79                       1 0.00         1.00
130.99                      1 0.00         1.00

[241 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-13; Volume
71600                        2 0.01         0.01
2700                         1 0.00         0.01
500                          1 0.00         0.02
10500                        1 0.00         0.02
10800                        1 0.00         0.02
...                        ...  ...          ...
35174100                     1 0.00         0.98
35316500                     1 0.00         0.99
63416600                     1 0.00         0.99
111595000                    1 0.00         1.00
154407600                    1 0.00         1.00

[251 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-13; Dividends
0                             252 1.00         1.00

                          Quantidade    %  % acumulado
2025-03-13; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-13; HLC
1.19                      2 0.01         0.01
0.25                      1 0.00         0.01
0.07                      1 0.00         0.02
0.72                      1 0.00         0.02
0.84                      1 0.00         0.02
...                     ...  ...          ...
54.44                     1 0.00         0.98
54.45                     1 0.00         0.99
73.73                     1 0.00         0.99
96.64                     1 0.00         1.00
129.27                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-14; Open
2.70                       3 0.01         0.01
9.20                       3 0.01         0.02
1.63                       2 0.01         0.03
5.29                       2 0.01         0.04
5.43                       2 0.01         0.05
...                      ...  ...          ...
54.55                      1 0.00         0.98
55.20                      1 0.00         0.99
74.55                      1 0.00         0.99
98.83                      1 0.00         1.00
132.48                     1 0.00         1.00

[241 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-14; High
0.87                       2 0.01         0.01
1.22                       2 0.01         0.02
1.80                       2 0.01         0.02
3.93                       2 0.01         0.03
3.80                       2 0.01         0.04
...                      ...  ...          ...
54.68                      1 0.00         0.98
56.41                      1 0.00         0.99
76.13                      1 0.00         0.99
99.38                      1 0.00         1.00
132.48                     1 0.00         1.00

[241 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-14; Low
6.88                      3 0.01         0.01
0.85                      2 0.01         0.02
1.62                      2 0.01         0.03
2.17                      2 0.01         0.04
3.74                      2 0.01         0.04
...                     ...  ...          ...
53.97                     1 0.00         0.98
55.16                     1 0.00         0.99
73.69                     1 0.00         0.99
97.00                     1 0.00         1.00
128.33                    1 0.00         1.00

[238 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-14; Close
1.19                        2 0.01         0.01
1.21                        2 0.01         0.02
1.74                        2 0.01         0.02
5.44                        2 0.01         0.03
5.82                        2 0.01         0.04
...                       ...  ...          ...
54.14                       1 0.00         0.98
56.29                       1 0.00         0.99
74.88                       1 0.00         0.99
99.30                       1 0.00         1.00
130.44                      1 0.00         1.00

[244 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-14; Volume
3500                         1 0.00         0.00
5300                         1 0.00         0.01
11500                        1 0.00         0.01
12200                        1 0.00         0.02
13100                        1 0.00         0.02
...                        ...  ...          ...
65704800                     1 0.00         0.98
102081900                    1 0.00         0.99
105449100                    1 0.00         0.99
111755000                    1 0.00         1.00
126026800                    1 0.00         1.00

[252 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-14; Dividends
0.00                          251 1.00         1.00
1.58                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-14; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-14; HLC
1.18                      2 0.01         0.01
1.20                      2 0.01         0.02
12.57                     2 0.01         0.02
0.27                      1 0.00         0.03
0.51                      1 0.00         0.03
...                     ...  ...          ...
54.26                     1 0.00         0.98
55.95                     1 0.00         0.99
74.90                     1 0.00         0.99
98.56                     1 0.00         1.00
130.42                    1 0.00         1.00

[249 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-17; Open
1.20                       3 0.01         0.01
1.18                       2 0.01         0.02
1.45                       2 0.01         0.03
1.76                       2 0.01         0.04
1.73                       2 0.01         0.04
...                      ...  ...          ...
54.23                      1 0.00         0.98
56.29                      1 0.00         0.99
75.44                      1 0.00         0.99
99.79                      1 0.00         1.00
131.51                     1 0.00         1.00

[236 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-17; High
1.44                       2 0.01         0.01
1.54                       2 0.01         0.02
7.20                       2 0.01         0.02
7.95                       2 0.01         0.03
3.98                       2 0.01         0.04
...                      ...  ...          ...
55.76                      1 0.00         0.98
57.24                      1 0.00         0.99
78.18                      1 0.00         0.99
100.80                     1 0.00         1.00
131.63                     1 0.00         1.00

[245 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-17; Low
0.86                      3 0.01         0.01
1.17                      2 0.01         0.02
1.18                      2 0.01         0.03
2.15                      2 0.01         0.04
5.45                      2 0.01         0.04
...                     ...  ...          ...
54.02                     1 0.00         0.98
56.14                     1 0.00         0.99
74.76                     1 0.00         0.99
98.76                     1 0.00         1.00
127.00                    1 0.00         1.00

[242 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-17; Close
0.91                        2 0.01         0.01
1.20                        2 0.01         0.02
1.76                        2 0.01         0.02
5.87                        2 0.01         0.03
5.82                        2 0.01         0.04
...                       ...  ...          ...
54.66                       1 0.00         0.98
57.10                       1 0.00         0.99
77.41                       1 0.00         0.99
100.60                      1 0.00         1.00
127.00                      1 0.00         1.00

[243 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-17; Volume
11200                        2 0.01         0.01
41400                        2 0.01         0.02
477400                       2 0.01         0.02
15500                        1 0.00         0.03
2000                         1 0.00         0.03
...                        ...  ...          ...
41312900                     1 0.00         0.98
49697100                     1 0.00         0.99
65684100                     1 0.00         0.99
87512900                     1 0.00         1.00
89758000                     1 0.00         1.00

[249 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-17; Dividends
0.00                          250 0.99         0.99
0.13                            1 0.00         1.00
0.22                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-17; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-17; HLC
30.00                     2 0.01         0.01
9.40                      2 0.01         0.02
0.56                      1 0.00         0.02
0.72                      1 0.00         0.02
0.88                      1 0.00         0.03
...                     ...  ...          ...
54.55                     1 0.00         0.98
56.83                     1 0.00         0.99
76.78                     1 0.00         0.99
100.05                    1 0.00         1.00
128.54                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-18; Open
12.12                      3 0.01         0.01
1.20                       2 0.01         0.02
2.20                       2 0.01         0.03
0.88                       2 0.01         0.04
2.45                       2 0.01         0.04
...                      ...  ...          ...
55.03                      1 0.00         0.98
57.20                      1 0.00         0.99
77.03                      1 0.00         0.99
100.60                     1 0.00         1.00
129.97                     1 0.00         1.00

[236 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-18; High
1.84                       3 0.01         0.01
1.79                       2 0.01         0.02
5.35                       2 0.01         0.03
3.99                       2 0.01         0.04
5.92                       2 0.01         0.04
...                      ...  ...          ...
56.39                      1 0.00         0.98
57.56                      1 0.00         0.99
78.38                      1 0.00         0.99
100.81                     1 0.00         1.00
139.68                     1 0.00         1.00

[242 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-18; Low
9.40                      4 0.02         0.02
0.86                      3 0.01         0.03
1.21                      2 0.01         0.04
7.36                      2 0.01         0.04
4.02                      2 0.01         0.05
...                     ...  ...          ...
54.20                     1 0.00         0.98
56.62                     1 0.00         0.99
77.03                     1 0.00         0.99
99.46                     1 0.00         1.00
127.00                    1 0.00         1.00

[239 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-18; Close
1.23                        3 0.01         0.01
1.83                        3 0.01         0.02
1.48                        2 0.01         0.03
0.92                        2 0.01         0.04
4.90                        2 0.01         0.05
...                       ...  ...          ...
55.01                       1 0.00         0.98
57.52                       1 0.00         0.99
78.03                       1 0.00         0.99
100.27                      1 0.00         1.00
130.53                      1 0.00         1.00

[240 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-18; Volume
10900                        2 0.01         0.01
623400                       2 0.01         0.02
3200                         1 0.00         0.02
5600                         1 0.00         0.02
8600                         1 0.00         0.03
...                        ...  ...          ...
41377000                     1 0.00         0.98
55635800                     1 0.00         0.99
112067000                    1 0.00         0.99
144028500                    1 0.00         1.00
160199000                    1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-18; Dividends
0.00                          249 0.99         0.99
0.01                            1 0.00         0.99
0.04                            1 0.00         1.00
0.18                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-18; Stock Splits
0.00                             250 0.99         0.99
1.10                               2 0.01         1.00

                 Quantidade    %  % acumulado
2025-03-18; HLC
1.24                      2 0.01         0.01
3.93                      2 0.01         0.02
0.57                      1 0.00         0.02
0.73                      1 0.00         0.02
0.89                      1 0.00         0.03
...                     ...  ...          ...
54.74                     1 0.00         0.98
57.23                     1 0.00         0.99
77.81                     1 0.00         0.99
100.18                    1 0.00         1.00
132.40                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-19; Open
1.83                       3 0.01         0.01
1.22                       2 0.01         0.02
1.05                       2 0.01         0.03
4.62                       2 0.01         0.04
5.50                       2 0.01         0.04
...                      ...  ...          ...
55.20                      1 0.00         0.98
57.35                      1 0.00         0.99
78.20                      1 0.00         0.99
100.99                     1 0.00         1.00
132.78                     1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-19; High
1.31                       2 0.01         0.01
1.43                       2 0.01         0.02
1.24                       2 0.01         0.02
1.06                       2 0.01         0.03
5.03                       2 0.01         0.04
...                      ...  ...          ...
56.17                      1 0.00         0.98
57.55                      1 0.00         0.99
79.83                      1 0.00         0.99
103.25                     1 0.00         1.00
132.78                     1 0.00         1.00

[240 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-19; Low
0.97                      2 0.01         0.01
1.40                      2 0.01         0.02
0.90                      2 0.01         0.02
1.22                      2 0.01         0.03
2.20                      2 0.01         0.04
...                     ...  ...          ...
54.80                     1 0.00         0.98
56.85                     1 0.00         0.99
77.97                     1 0.00         0.99
100.03                    1 0.00         1.00
123.01                    1 0.00         1.00

[241 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-19; Close
5.94                        3 0.01         0.01
11.35                       3 0.01         0.02
8.30                        2 0.01         0.03
1.41                        2 0.01         0.04
5.51                        2 0.01         0.05
...                       ...  ...          ...
55.50                       1 0.00         0.98
57.42                       1 0.00         0.99
79.29                       1 0.00         0.99
102.65                      1 0.00         1.00
124.27                      1 0.00         1.00

[240 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-19; Volume
198500                       2 0.01         0.01
391600                       2 0.01         0.02
5100                         1 0.00         0.02
5400                         1 0.00         0.02
8800                         1 0.00         0.03
...                        ...  ...          ...
49304200                     1 0.00         0.98
50241400                     1 0.00         0.99
51574700                     1 0.00         0.99
58590200                     1 0.00         1.00
202496800                    1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-19; Dividends
0.00                          248 0.98         0.98
0.12                            1 0.00         0.99
0.28                            1 0.00         0.99
0.73                            1 0.00         1.00
2.30                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-19; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-19; HLC
1.26                      2 0.01         0.01
3.98                      2 0.01         0.02
0.55                      1 0.00         0.02
0.74                      1 0.00         0.02
0.91                      1 0.00         0.03
...                     ...  ...          ...
55.27                     1 0.00         0.98
57.27                     1 0.00         0.99
79.03                     1 0.00         0.99
101.98                    1 0.00         1.00
126.69                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-20; Open
11.35                      3 0.01         0.01
1.02                       2 0.01         0.02
1.40                       2 0.01         0.03
4.89                       2 0.01         0.04
5.25                       2 0.01         0.04
...                      ...  ...          ...
55.50                      1 0.00         0.98
57.04                      1 0.00         0.99
79.30                      1 0.00         0.99
102.63                     1 0.00         1.00
123.00                     1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-20; High
0.94                       2 0.01         0.01
1.35                       2 0.01         0.02
1.43                       2 0.01         0.02
1.26                       2 0.01         0.03
5.76                       2 0.01         0.04
...                      ...  ...          ...
56.27                      1 0.00         0.98
57.49                      1 0.00         0.99
79.33                      1 0.00         0.99
103.07                     1 0.00         1.00
123.99                     1 0.00         1.00

[241 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-20; Low
1.23                      2 0.01         0.01
0.90                      2 0.01         0.02
4.42                      2 0.01         0.02
3.74                      2 0.01         0.03
6.30                      2 0.01         0.04
...                     ...  ...          ...
54.76                     1 0.00         0.98
56.78                     1 0.00         0.99
72.72                     1 0.00         0.99
101.44                    1 0.00         1.00
119.21                    1 0.00         1.00

[244 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-20; Close
11.86                       3 0.01         0.01
1.26                        2 0.01         0.02
1.42                        2 0.01         0.03
7.80                        2 0.01         0.04
5.57                        2 0.01         0.04
...                       ...  ...          ...
55.84                       1 0.00         0.98
57.24                       1 0.00         0.99
73.96                       1 0.00         0.99
101.93                      1 0.00         1.00
122.00                      1 0.00         1.00

[243 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-20; Volume
700                          1 0.00         0.00
1800                         1 0.00         0.01
10400                        1 0.00         0.01
11200                        1 0.00         0.02
12300                        1 0.00         0.02
...                        ...  ...          ...
34125100                     1 0.00         0.98
34793900                     1 0.00         0.99
42754900                     1 0.00         0.99
46921900                     1 0.00         1.00
525875200                    1 0.00         1.00

[252 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-20; Dividends
0                             252 1.00         1.00

                          Quantidade    %  % acumulado
2025-03-20; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-20; HLC
1.90                      2 0.01         0.01
10.54                     2 0.01         0.02
0.55                      1 0.00         0.02
0.74                      1 0.00         0.02
0.91                      1 0.00         0.03
...                     ...  ...          ...
55.62                     1 0.00         0.98
57.17                     1 0.00         0.99
75.34                     1 0.00         0.99
102.15                    1 0.00         1.00
121.73                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-21; Open
1.27                       2 0.01         0.01
1.42                       2 0.01         0.02
7.78                       2 0.01         0.02
5.69                       2 0.01         0.03
5.60                       2 0.01         0.04
...                      ...  ...          ...
56.04                      1 0.00         0.98
56.95                      1 0.00         0.99
73.78                      1 0.00         0.99
102.34                     1 0.00         1.00
122.35                     1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-21; High
1.47                       2 0.01         0.01
1.42                       2 0.01         0.02
1.30                       2 0.01         0.02
1.54                       2 0.01         0.03
4.50                       2 0.01         0.04
...                      ...  ...          ...
56.16                      1 0.00         0.98
57.45                      1 0.00         0.99
75.99                      1 0.00         0.99
102.34                     1 0.00         1.00
125.68                     1 0.00         1.00

[239 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-21; Low
1.04                      2 0.01         0.01
1.06                      2 0.01         0.02
1.47                      2 0.01         0.02
1.68                      2 0.01         0.03
4.42                      2 0.01         0.04
...                     ...  ...          ...
54.26                     1 0.00         0.98
56.83                     1 0.00         0.99
73.23                     1 0.00         0.99
100.01                    1 0.00         1.00
120.33                    1 0.00         1.00

[236 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-21; Close
3.90                        3 0.01         0.01
1.10                        2 0.01         0.02
1.27                        2 0.01         0.03
5.63                        2 0.01         0.04
3.76                        2 0.01         0.04
...                       ...  ...          ...
54.35                       1 0.00         0.98
57.45                       1 0.00         0.99
74.76                       1 0.00         0.99
101.35                      1 0.00         1.00
122.23                      1 0.00         1.00

[242 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-21; Volume
5800                         2 0.01         0.01
261000                       2 0.01         0.02
4300                         1 0.00         0.02
5700                         1 0.00         0.02
10300                        1 0.00         0.03
...                        ...  ...          ...
56803000                     1 0.00         0.98
61175700                     1 0.00         0.99
66960300                     1 0.00         0.99
74318800                     1 0.00         1.00
104525400                    1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-21; Dividends
0.00                          251 1.00         1.00
0.14                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-21; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-21; HLC
5.67                      2 0.01         0.01
0.28                      1 0.00         0.01
0.08                      1 0.00         0.02
0.72                      1 0.00         0.02
0.91                      1 0.00         0.02
...                     ...  ...          ...
54.92                     1 0.00         0.98
57.24                     1 0.00         0.99
74.66                     1 0.00         0.99
101.23                    1 0.00         1.00
122.75                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-24; Open
3.62                       3 0.01         0.01
1.27                       2 0.01         0.02
1.12                       2 0.01         0.03
5.07                       2 0.01         0.04
7.56                       2 0.01         0.04
...                      ...  ...          ...
54.46                      1 0.00         0.98
57.95                      1 0.00         0.99
74.75                      1 0.00         0.99
101.80                     1 0.00         1.00
124.80                     1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-24; High
2.20                       2 0.01         0.01
3.66                       2 0.01         0.02
3.64                       2 0.01         0.02
1.75                       2 0.01         0.03
3.80                       2 0.01         0.04
...                      ...  ...          ...
54.77                      1 0.00         0.98
58.24                      1 0.00         0.99
74.85                      1 0.00         0.99
101.80                     1 0.00         1.00
124.96                     1 0.00         1.00

[241 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-24; Low
1.44                      2 0.01         0.01
1.03                      2 0.01         0.02
1.11                      2 0.01         0.02
1.43                      2 0.01         0.03
2.17                      2 0.01         0.04
...                     ...  ...          ...
54.01                     1 0.00         0.98
56.96                     1 0.00         0.99
70.50                     1 0.00         0.99
98.62                     1 0.00         1.00
121.00                    1 0.00         1.00

[243 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-24; Close
2.03                        2 0.01         0.01
1.45                        2 0.01         0.02
2.59                        2 0.01         0.02
2.21                        2 0.01         0.03
3.60                        2 0.01         0.04
...                       ...  ...          ...
54.13                       1 0.00         0.98
57.15                       1 0.00         0.99
71.25                       1 0.00         0.99
98.80                       1 0.00         1.00
121.00                      1 0.00         1.00

[242 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-24; Volume
65400                        2 0.01         0.01
256700                       2 0.01         0.02
7900                         1 0.00         0.02
9800                         1 0.00         0.02
12400                        1 0.00         0.03
...                        ...  ...          ...
38966100                     1 0.00         0.98
40560200                     1 0.00         0.99
44562300                     1 0.00         0.99
59306900                     1 0.00         1.00
63575900                     1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-24; Dividends
0.00                          245 0.97         0.97
0.04                            1 0.00         0.98
0.06                            1 0.00         0.98
0.08                            1 0.00         0.98
0.10                            1 0.00         0.99
0.11                            1 0.00         0.99
0.28                            1 0.00         1.00
0.31                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-24; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-24; HLC
5.52                      2 0.01         0.01
0.27                      1 0.00         0.01
0.09                      1 0.00         0.02
0.70                      1 0.00         0.02
0.90                      1 0.00         0.02
...                     ...  ...          ...
54.30                     1 0.00         0.98
57.45                     1 0.00         0.99
72.20                     1 0.00         0.99
99.74                     1 0.00         1.00
122.32                    1 0.00         1.00

[251 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-25; Open
1.45                       2 0.01         0.01
1.18                       2 0.01         0.02
2.23                       2 0.01         0.02
2.38                       2 0.01         0.03
2.17                       2 0.01         0.04
...                      ...  ...          ...
54.27                      1 0.00         0.98
57.32                      1 0.00         0.99
71.62                      1 0.00         0.99
100.40                     1 0.00         1.00
122.21                     1 0.00         1.00

[234 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-25; High
3.74                       2 0.01         0.01
2.28                       2 0.01         0.02
1.50                       2 0.01         0.02
5.42                       2 0.01         0.03
5.05                       2 0.01         0.04
...                      ...  ...          ...
55.00                      1 0.00         0.98
57.75                      1 0.00         0.99
72.00                      1 0.00         0.99
103.50                     1 0.00         1.00
122.98                     1 0.00         1.00

[243 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-25; Low
3.80                      3 0.01         0.01
9.60                      3 0.01         0.02
2.15                      2 0.01         0.03
2.38                      2 0.01         0.04
1.43                      2 0.01         0.05
...                     ...  ...          ...
53.63                     1 0.00         0.98
57.11                     1 0.00         0.99
69.40                     1 0.00         0.99
100.21                    1 0.00         1.00
118.00                    1 0.00         1.00

[234 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-25; Close
1.00                        2 0.01         0.01
1.14                        2 0.01         0.02
2.63                        2 0.01         0.02
2.59                        2 0.01         0.03
2.23                        2 0.01         0.04
...                       ...  ...          ...
54.22                       1 0.00         0.98
57.34                       1 0.00         0.99
69.74                       1 0.00         0.99
102.10                      1 0.00         1.00
120.55                      1 0.00         1.00

[239 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-25; Volume
153600                       2 0.01         0.01
610400                       2 0.01         0.02
3300                         1 0.00         0.02
5100                         1 0.00         0.02
6000                         1 0.00         0.03
...                        ...  ...          ...
40946400                     1 0.00         0.98
57871800                     1 0.00         0.99
63764400                     1 0.00         0.99
65755400                     1 0.00         1.00
88230000                     1 0.00         1.00

[250 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-25; Dividends
0.00                          248 0.98         0.98
0.05                            1 0.00         0.99
0.07                            1 0.00         0.99
0.12                            1 0.00         1.00
0.14                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-25; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-25; HLC
1.50                      2 0.01         0.01
8.63                      2 0.01         0.02
0.52                      1 0.00         0.02
0.70                      1 0.00         0.02
0.89                      1 0.00         0.03
...                     ...  ...          ...
54.28                     1 0.00         0.98
57.40                     1 0.00         0.99
70.38                     1 0.00         0.99
101.94                    1 0.00         1.00
120.51                    1 0.00         1.00

[250 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-26; Open
1.46                       2 0.01         0.01
1.01                       2 0.01         0.02
1.10                       2 0.01         0.02
5.90                       2 0.01         0.03
7.56                       2 0.01         0.04
...                      ...  ...          ...
54.22                      1 0.00         0.98
57.40                      1 0.00         0.99
69.98                      1 0.00         0.99
102.58                     1 0.00         1.00
119.82                     1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-26; High
5.32                       2 0.01         0.01
5.55                       2 0.01         0.02
7.33                       2 0.01         0.02
12.25                      2 0.01         0.03
10.33                      2 0.01         0.04
...                      ...  ...          ...
54.80                      1 0.00         0.98
58.04                      1 0.00         0.99
70.44                      1 0.00         0.99
102.60                     1 0.00         1.00
120.87                     1 0.00         1.00

[246 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-26; Low
0.99                      2 0.01         0.01
1.86                      2 0.01         0.02
2.18                      2 0.01         0.02
3.16                      2 0.01         0.03
3.80                      2 0.01         0.04
...                     ...  ...          ...
53.11                     1 0.00         0.98
57.39                     1 0.00         0.99
68.82                     1 0.00         0.99
101.40                    1 0.00         1.00
110.86                    1 0.00         1.00

[238 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-26; Close
1.46                        2 0.01         0.01
2.51                        2 0.01         0.02
7.21                        2 0.01         0.02
5.27                        2 0.01         0.03
3.73                        2 0.01         0.04
...                       ...  ...          ...
53.60                       1 0.00         0.98
57.69                       1 0.00         0.99
69.33                       1 0.00         0.99
101.58                      1 0.00         1.00
110.86                      1 0.00         1.00

[241 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-26; Volume
190900                       2 0.01         0.01
2100                         1 0.00         0.01
1200                         1 0.00         0.02
15000                        1 0.00         0.02
16600                        1 0.00         0.02
...                        ...  ...          ...
31903000                     1 0.00         0.98
32348200                     1 0.00         0.99
44332400                     1 0.00         0.99
49065500                     1 0.00         1.00
69332300                     1 0.00         1.00

[251 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-26; Dividends
0.00                          249 0.99         0.99
0.06                            1 0.00         0.99
0.19                            1 0.00         1.00
0.19                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-26; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-26; HLC
1.01                      2 0.01         0.01
2.24                      2 0.01         0.02
5.29                      2 0.01         0.02
5.46                      2 0.01         0.03
0.71                      1 0.00         0.04
...                     ...  ...          ...
53.63                     1 0.00         0.98
57.71                     1 0.00         0.99
69.53                     1 0.00         0.99
101.86                    1 0.00         1.00
114.20                    1 0.00         1.00

[248 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-27; Open
1.46                       2 0.01         0.01
3.95                       2 0.01         0.02
5.70                       2 0.01         0.02
7.10                       2 0.01         0.03
5.28                       2 0.01         0.04
...                      ...  ...          ...
53.80                      1 0.00         0.98
58.00                      1 0.00         0.99
70.00                      1 0.00         0.99
102.90                     1 0.00         1.00
115.85                     1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-27; High
1.07                       2 0.01         0.01
1.46                       2 0.01         0.02
2.64                       2 0.01         0.02
5.33                       2 0.01         0.03
5.38                       2 0.01         0.04
...                      ...  ...          ...
56.24                      1 0.00         0.98
58.45                      1 0.00         0.99
70.00                      1 0.00         0.99
104.49                     1 0.00         1.00
124.01                     1 0.00         1.00

[243 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-27; Low
1.00                      3 0.01         0.01
5.54                      3 0.01         0.02
1.90                      2 0.01         0.03
3.81                      2 0.01         0.04
5.07                      2 0.01         0.05
...                     ...  ...          ...
53.01                     1 0.00         0.98
57.61                     1 0.00         0.99
68.04                     1 0.00         0.99
102.36                    1 0.00         1.00
113.37                    1 0.00         1.00

[241 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-27; Close
1.02                        2 0.01         0.01
1.91                        2 0.01         0.02
1.46                        2 0.01         0.02
1.51                        2 0.01         0.03
1.73                        2 0.01         0.04
...                       ...  ...          ...
55.44                       1 0.00         0.98
58.15                       1 0.00         0.99
68.32                       1 0.00         0.99
104.01                      1 0.00         1.00
119.09                      1 0.00         1.00

[235 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-27; Volume
13900                        2 0.01         0.01
5700                         1 0.00         0.01
2600                         1 0.00         0.02
7800                         1 0.00         0.02
9400                         1 0.00         0.02
...                        ...  ...          ...
40588300                     1 0.00         0.98
50764800                     1 0.00         0.99
56716900                     1 0.00         0.99
72489300                     1 0.00         1.00
84639700                     1 0.00         1.00

[251 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-27; Dividends
0.00                          246 0.98         0.98
0.04                            1 0.00         0.98
0.05                            1 0.00         0.98
0.06                            1 0.00         0.99
0.09                            1 0.00         0.99
0.18                            1 0.00         1.00
0.46                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-27; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-27; HLC
1.36                      2 0.01         0.01
5.63                      2 0.01         0.02
5.35                      2 0.01         0.02
11.94                     2 0.01         0.03
0.89                      1 0.00         0.04
...                     ...  ...          ...
54.76                     1 0.00         0.98
58.07                     1 0.00         0.99
68.79                     1 0.00         0.99
103.62                    1 0.00         1.00
118.82                    1 0.00         1.00

[248 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-28; Open
1.46                       2 0.01         0.01
5.63                       2 0.01         0.02
5.36                       2 0.01         0.02
3.91                       2 0.01         0.03
12.15                      2 0.01         0.04
...                      ...  ...          ...
55.44                      1 0.00         0.98
58.10                      1 0.00         0.99
68.35                      1 0.00         0.99
104.00                     1 0.00         1.00
120.94                     1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-28; High
1.06                       2 0.01         0.01
4.17                       2 0.01         0.02
5.28                       2 0.01         0.02
8.05                       2 0.01         0.03
18.06                      2 0.01         0.04
...                      ...  ...          ...
55.57                      1 0.00         0.98
58.38                      1 0.00         0.99
69.07                      1 0.00         0.99
104.42                     1 0.00         1.00
122.25                     1 0.00         1.00

[246 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-28; Low
0.99                      2 0.01         0.01
1.01                      2 0.01         0.02
5.66                      2 0.01         0.02
7.46                      2 0.01         0.03
5.51                      2 0.01         0.04
...                     ...  ...          ...
54.10                     1 0.00         0.98
57.56                     1 0.00         0.99
66.08                     1 0.00         0.99
102.51                    1 0.00         1.00
117.56                    1 0.00         1.00

[240 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-28; Close
1.01                        2 0.01         0.01
1.04                        2 0.01         0.02
1.31                        2 0.01         0.02
3.47                        2 0.01         0.03
5.60                        2 0.01         0.04
...                       ...  ...          ...
54.93                       1 0.00         0.98
57.56                       1 0.00         0.99
66.36                       1 0.00         0.99
102.98                      1 0.00         1.00
120.10                      1 0.00         1.00

[240 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-28; Volume
47000                        2 0.01         0.01
172600                       2 0.01         0.02
465100                       2 0.01         0.02
27700                        1 0.00         0.03
24900                        1 0.00         0.03
...                        ...  ...          ...
40891100                     1 0.00         0.98
43119000                     1 0.00         0.99
63030500                     1 0.00         0.99
68474600                     1 0.00         1.00
131606600                    1 0.00         1.00

[249 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-28; Dividends
0.00                          250 0.99         0.99
0.07                            1 0.00         1.00
0.29                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-28; Stock Splits
0                                252 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-28; HLC
0.10                      1 0.00         0.00
0.25                      1 0.00         0.01
0.52                      1 0.00         0.01
0.72                      1 0.00         0.02
0.90                      1 0.00         0.02
...                     ...  ...          ...
54.87                     1 0.00         0.98
57.83                     1 0.00         0.99
67.17                     1 0.00         0.99
103.30                    1 0.00         1.00
119.97                    1 0.00         1.00

[252 rows x 3 columns]

                           Quantidade    %  % acumulado
Alfa HLC; últimos 13 dias
-1.33                               1 0.00         0.00
-0.64                               1 0.00         0.01
-0.33                               1 0.00         0.01
-0.29                               1 0.00         0.02
-0.25                               1 0.00         0.02
...                               ...  ...          ...
0.52                                1 0.00         0.98
0.59                                1 0.00         0.99
0.60                                1 0.00         0.99
0.68                                1 0.00         1.00
0.86                                1 0.00         1.00

[252 rows x 3 columns]

                           Quantidade    %  % acumulado
Alfa HLC; últimos 55 dias
-0.35                               1 0.00         0.00
-0.24                               1 0.00         0.01
-0.20                               1 0.00         0.01
-0.13                               1 0.00         0.02
-0.10                               1 0.00         0.02
...                               ...  ...          ...
0.17                                1 0.00         0.98
0.18                                1 0.00         0.99
0.19                                1 0.00         0.99
0.25                                1 0.00         1.00
0.46                                1 0.00         1.00

[252 rows x 3 columns]

,Quantidade,%,% acumulado
Martelos,,,
"2025-02-03, 2025-02-04, 2025-02-05, 2025-02-06, 2025-02-10, 2025-02-11, 2025-02-12, 2025-02-13, 2025-02-14, 2025-02-18, 2025-02-20, 2025-02-21, 2025-02-24, 2025-02-25, 2025-02-26, 2025-02-27, 2025-02-28, 2025-03-05, 2025-03-06, 2025-03-07, 2025-03-10, 2025-03-11, 2025-03-13, 2025-03-14, 2025-03-17, 2025-03-18, 2025-03-21, 2025-03-24, 2025-03-26,",1,0.00,0.00
"2025-02-03, 2025-02-04, 2025-02-05, 2025-02-07, 2025-02-10, 2025-02-17, 2025-02-18, 2025-02-19, 2025-02-25, 2025-02-27, 2025-02-28, 2025-03-05, 2025-03-07, 2025-03-10, 2025-03-19, 2025-03-20, 2025-03-21, 2025-03-25,",1,0.00,0.01
"2025-02-03, 2025-02-04, 2025-02-05, 2025-02-10, 2025-02-17, 2025-02-18, 2025-02-21, 2025-02-26, 2025-03-20,",1,0.00,0.01
"2025-02-03, 2025-02-04, 2025-02-05, 2025-02-14, 2025-02-17, 2025-02-19, 2025-02-20, 2025-03-10, 2025-03-11, 2025-03-14,",1,0.00,0.02
"2025-02-03, 2025-02-04, 2025-02-05, 2025-02-20, 2025-02-25, 2025-02-27, 2025-03-10, 2025-03-13, 2025-03-17, 2025-03-25, 2025-03-27, 2025-03-28,",1,0.00,0.02
...,...,...,...
"2025-02-26, 2025-03-13,",1,0.00,0.98
"2025-02-27, 2025-02-28, 2025-03-07, 2025-03-18, 2025-03-19, 2025-03-20, 2025-03-25, 2025-03-26,",1,0.00,0.99
"2025-02-27, 2025-03-06, 2025-03-10, 2025-03-11, 2025-03-21,",1,0.00,0.99
"2025-02-27, 2025-03-14, 2025-03-27,",1,0.00,1.00
"2025-03-06, 2025-03-18, 2025-03-24, 2025-03-26, 2025-03-27, 2025-03-28,",1,0.00,1.00

,Quantidade,%,% acumulado
Tipos de Martelos,,,
"Subida, Subida, Subida, Subida, Subida,",4,0.02,0.02
"Subida, Subida, Descida, Subida, Subida, Subida,",4,0.02,0.03
"Subida, Subida, Subida, Subida, Descida,",3,0.01,0.04
"Descida, Descida, Subida, Descida, Descida,",2,0.01,0.05
"Descida, Subida, Subida, Descida,",2,0.01,0.06
...,...,...,...
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Descida, Subida, Subida, Subida,",1,0.00,0.98
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida,",1,0.00,0.99
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida,",1,0.00,0.99
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida,",1,0.00,1.00
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida,",1,0.00,1.00

## Teste de variáveis específicas

In [17]:
display(len(bd_semNA))
display(len(bd_dados_completos))

252

252

In [18]:
colunas_parciais

['fullTimeEmployees',
 'dividendRate',
 'dividendYield',
 'exDividendDate',
 'payoutRatio',
 'beta',
 'trailingPE',
 'forwardPE',
 'priceToSalesTrailing12Months',
 'profitMargins',
 'trailingEps',
 'forwardEps',
 'lastSplitFactor',
 'lastSplitDate',
 'enterpriseToRevenue',
 'enterpriseToEbitda',
 'lastDividendValue',
 'lastDividendDate',
 'recommendationMean',
 'numberOfAnalystOpinions',
 'totalCash',
 'totalCashPerShare',
 'ebitda',
 'totalDebt',
 'quickRatio',
 'currentRatio',
 'totalRevenue',
 'debtToEquity',
 'revenuePerShare',
 'returnOnAssets',
 'returnOnEquity',
 'grossProfits',
 'freeCashflow',
 'operatingCashflow',
 'earningsGrowth',
 'revenueGrowth',
 'grossMargins',
 'ebitdaMargins',
 'epsTrailingTwelveMonths',
 'epsForward',
 'epsCurrentYear',
 'priceEpsCurrentYear']

In [19]:
# colunas_agrupadas.get("52WeekChange")

colunas_agrupadas.get(colunas_parciais[0])

                   Quantidade    %  % acumulado
fullTimeEmployees
 (vazio)                  163 0.65         0.65
6,047.00                    3 0.01         0.66
55,646.00                   3 0.01         0.67
4,396.00                    2 0.01         0.68
16,027.00                   2 0.01         0.69
...                       ...  ...          ...
64,616.00                   1 0.00         0.98
87,000.00                   1 0.00         0.99
100,000.00                  1 0.00         0.99
126,832.00                  1 0.00         1.00
190,000.00                  1 0.00         1.00

[78 rows x 3 columns]

In [20]:
campos_com_erro

[]

# Preparação de dados

## One hot encoding

## Balanceamento

## Separação treino e teste

In [ ]:
# train, test = train_test_split(dados, test_size=.3, random_state=7128)

## Normalização

# Primeiro modelo de IA basicão

In [134]:
var_coluna_objetivo = bd_dados_completos[[item for item in bd_dados_completos.columns.to_list() if "; Close" in item]]

var_coluna_objetivo = var_coluna_objetivo.columns[-1]

var_coluna_objetivo

'2025-03-28; Close'

In [141]:
# # SÓ CONSEGUI FAZER FUNCIONAR REMOVENDO O PARÂMETRO stratify

from sklearn.model_selection import train_test_split
dados = bd_dados_completos
colunas_treino = bd_dados_completos.drop(var_coluna_objetivo, axis = 1).columns
coluna_resultado = var_coluna_objetivo
proporcao = 0.25

# display(dados.loc[:, colunas_treino])
# list(dados.loc[:, coluna_resultado].values)
# dados.loc[:, [coluna_resultado]].iloc[:, 0]

[original_x_treino, original_x_teste, y_treino, y_teste] = train_test_split(
    dados.loc[:, colunas_treino],
    dados.loc[:, [coluna_resultado]],
    test_size = proporcao,
    # stratify = dados.loc[:, [coluna_resultado]] # mesma proporção de y
)

# # [original_x_treino, original_x_teste, y_treino, y_teste]
display(len(original_x_treino))
display(len(original_x_teste))
display(len(y_treino))
display(len(y_teste))

189

63

189

63

In [171]:
# [
#     modelo, 
#     [original_x_treino, original_x_teste, y_treino, y_teste], 
#     [x_treino, x_teste], 
#     feature_selection,
#     # previsoes, 
#     taxa_de_acerto
# ]

[
    [original_x_treino, original_x_teste, y_treino, y_teste], 
    [x_treino, x_teste],
    feature_selection
] = treina_e_roda_modelo(
    dados = bd_dados_completos,
    colunas_treino = bd_dados_completos.drop(var_coluna_objetivo, axis = 1).columns,
    coluna_resultado = var_coluna_objetivo,
    
    estimador = None)

var_treina_e_roda_modelo = treina_e_roda_modelo(
    dados = bd_dados_completos,
    colunas_treino = bd_dados_completos.drop(var_coluna_objetivo, axis = 1).columns,
    coluna_resultado = var_coluna_objetivo,
    
    estimador = "DecisionTreeClassifier",
    proporcao = 0.25,
    SEED = 42,
    print_tamanho = True,
    print_score = True,
    print_confusion_matrix = False,
    
    DummyClassifier__estrategia = None,
    
    DecisionTreeClassifier__retornar_visualizacao = False,
    DecisionTreeClassifier__max_depth = None,
    
    RandomForestClassifier__n_estimators = 100,
    
    feature_selection = None,
    scaler = None,
)

# type(var_treina_e_roda_modelo)
var_treina_e_roda_modelo[0]
var_treina_e_roda_modelo[1].fit(x_treino, y_treino)

Tamanho treino: 189
Tamanho teste: 63
Tamanho treino: 189
Tamanho teste: 63
Não foi possível treinar o modelo escolhido

ValueError: could not convert string to float: 'Tegma'