# Bibliotecas

## Sistema (os, makedirs, glob)

In [ ]:
from os import makedirs
import os
import glob
from os import listdir

import dotenv
def load_dotenv():
    """Load the .env file normally and also from the current directory."""
    dotenv.load_dotenv()
    dotenv.load_dotenv(dotenv.find_dotenv(usecwd=True))

load_dotenv()

## Básicos (numpy, math, display, locale, time, random, re)

In [2]:
# !python -m pip install jupyter


# !python -m pip install IPython
from IPython.display import display

import math

# !python -m pip install numpy
import numpy as np

import locale
# locale.setlocale(locale.LC_ALL, "pt_BR.UTF-8")  # Use "" for auto, or force e.g. to "en_US.UTF-8"

import time
from datetime import datetime, timedelta, date

from pandas.tseries.offsets import BDay # para os dias úteis
# today = datetime.datetime.today()
# print(today - BDay(4)) # 4 dias úteis atrás

# # !python -m pip install random
import random
random.seed(42)

# !python -m pip install regex
import re

## Leitura e análise de dados (Excel, Pandas, Spark)

In [3]:
# !python -m pip install findspark

# !python -m pip install openpyxl
# import openpyxl

# !python -m pip install xlsxwriter
# import xlsxwriter

# !python -m pip install xlrd
# import xlrd

# !python -m pip install python-calamine
# import python_calamine


# !python -m pip install pandas
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
# pd.set_option('display.float_format', lambda x: '%.2f' % x)

## Finanças (yfinance, mplfinance)

In [4]:
# https://pypi.org/project/yfinance/
# https://github.com/ranaroussi/yfinance/wiki/Ticker

!python -m pip install yfinance
import yfinance as yf

!python -m pip install mplfinance
import mplfinance as mpf

# # Em R
# # https://cran.r-project.org/web/packages/BatchGetSymbols/index.html

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: yfinance in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (0.2.54)
Requirement already satisfied: pandas>=1.3.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: requests>=2.31 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2025.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (3.17.9)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (4.13.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from pandas>=1.3.0->yfinance) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (2025.1.31)
Requirement already satisfied: six>=1.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mplfinance in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (0.12.10b0)
Requirement already satisfied: matplotlib in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from mplfinance) (3.10.1)
Requirement already satisfied: pandas in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from mplfinance) (2.2.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (2.2.3)
Requirement already satisfied: packaging>=20.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from pandas->mplfinance) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from pandas->mplfinance) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib->mplfinance) (1.17.0)

## Visualização (matplotlib, seaborn, plotly)

In [5]:
# !python -m pip install matplotlib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib import ticker
from matplotlib.ticker import FormatStrFormatter, StrMethodFormatter

# !python -m pip install seaborn
import seaborn as sns

# !python -m pip install plotly
# import plotly.graph_objects as go
# import plotly.express as px
# from plotly.subplots import make_subplots

# !python -m pip install graphviz
# import graphviz

# Funções

### Agrupar cada coluna (_agrupamento_cada_coluna_)

In [6]:
def agrupamento_cada_coluna(
    bd, 
    coluna_completa, 
    colunas_ignoradas = [], 
    ascending = False,
    imprime_tabelas = True,
    ):
    
    from IPython.display import display

    campos_com_erro = []
    dict_campos = {}

    colunas = bd.columns.drop(coluna_completa)

    if len(colunas_ignoradas) > 0:
        colunas = colunas.drop(colunas_ignoradas)
    
    for coluna in colunas:
        try: 
            temp_coluna = bd.fillna("(vazio)").groupby(coluna).count()[[coluna_completa]].rename(columns = {coluna_completa: "Quantidade"}).sort_values("Quantidade", ascending = ascending)

            if ascending == False:
                temp_coluna["%"] = temp_coluna["Quantidade"]/temp_coluna["Quantidade"].sum()
                temp_coluna["% acumulado"] = temp_coluna["%"].cumsum()
            
            if imprime_tabelas == True:
                display(temp_coluna)
                
            dict_campos[coluna] = temp_coluna
            # limpa(temp_coluna)
        
        except:
            campos_com_erro.append(coluna)
            #print("Campo " + coluna + " deu erro =/")
    
    return [campos_com_erro, dict_campos]

### Elimina colunas NA (_elimina_colunas_NA_)

In [7]:
def elimina_colunas_NA(
    base,
    imprime_colunas_vazias = False,
    imprime_colunas_completas = False,
    imprime_colunas_parciais = False,
    remove_da_base = True,
    retorna_parciais = False
    ):

    tamanho_da_base = len(base)

    colunas_vazias = []
    colunas_completas = []
    colunas_parciais = []

    for coluna in base.columns:
        tamanho_da_coluna = len(base[base[coluna].isna()])
        if tamanho_da_coluna == tamanho_da_base:
            # print(coluna)
            colunas_vazias.append(coluna)
        elif tamanho_da_coluna == 0:
            colunas_completas.append(coluna)
        else:
            colunas_parciais.append(coluna)

    if imprime_colunas_vazias == True:
        if len(colunas_vazias) == 0:
            print("Não há colunas NA")
        else:
            print("Colunas vazias: " + str(colunas_vazias))
            
    if imprime_colunas_completas == True:
        if len(colunas_completas) == 0:
            print("Não há colunas completas")
        else:
            print("Colunas completas: " + str(colunas_completas))
    
    if imprime_colunas_parciais == True:
        if len(colunas_parciais) == 0:
            print("Não há colunas parciais")
        else:
            print("Colunas parciais: " + str(colunas_parciais))

    if remove_da_base == True:
        base = base.drop(colunas_vazias, axis = 1)
    
    if retorna_parciais == True:
        return [base, colunas_parciais]
    else:
        return base

### Análise exploratória básica de todos os campos da base - MUITO ÚTIL (_analise_exploratoria_)

In [8]:
def analise_exploratoria(
    bd,
    imprime_todas_colunas = False,
    imprime_info_colunas = True,
    imprime_colunas_vazias = False,
    imprime_colunas_completas = False,
    imprime_colunas_parciais = False,
    remove_da_base = True,
    retorna_parciais = False,
    # detalhar_colunas_parciais = True,
    colunas_ignoradas = []
    ):

    # COMEÇANDO PELAS COLUNAS DISPONÍVEIS E INFO
    if imprime_todas_colunas == True:
        display(bd.columns)
    
    if imprime_info_colunas == True:
        for i in range(int(np.ceil(len(bd.columns)/20))):
            display(bd.iloc[:, (i*20):min((i+1)*20, len(bd.columns))].info())

    # DETALHAMENTO DE QUAIS COLUNAS SÃO NA OU PARCIAIS
    if retorna_parciais == True:
        [bd_semNA, colunas_parciais] = elimina_colunas_NA(
            bd,
            imprime_colunas_vazias = imprime_colunas_vazias,
            imprime_colunas_completas = imprime_colunas_completas,
            imprime_colunas_parciais = imprime_colunas_parciais,
            remove_da_base = remove_da_base,
            retorna_parciais = True
        )

        print(colunas_parciais)

        # if detalhar_colunas_parciais == True:
            # for coluna in colunas_parciais:
                # print(coluna)
                # print("# " + coluna + ": " + str(len(colunas_parciais[colunas_parciais[coluna].isna()])))
    else:
        colunas_parciais = []

        bd_semNA = elimina_colunas_NA(
            bd,
            imprime_colunas_vazias = imprime_colunas_vazias,
            imprime_colunas_completas = imprime_colunas_completas,
            imprime_colunas_parciais = imprime_colunas_parciais,
            remove_da_base = remove_da_base,
            retorna_parciais = retorna_parciais
        )

    [campos_com_erro, colunas_agrupadas] = agrupamento_cada_coluna(
        bd.reset_index(), 
        coluna_completa = bd_semNA.drop(colunas_parciais, axis = 1).reset_index().columns[0],
        colunas_ignoradas = colunas_ignoradas
    )
    
    if retorna_parciais == True:
        return [bd_semNA, colunas_parciais, colunas_agrupadas, campos_com_erro]
    else:
        return [bd_semNA, colunas_agrupadas, campos_com_erro]

## Treinamento de modelos (_treina_e_roda_modelo_)

In [9]:
def treina_e_roda_modelo(
    dados,
    colunas_treino,
    coluna_resultado,
    
    estimador = "SVC",
    proporcao = 0.25,
    SEED = 42,
    print_tamanho = True,
    print_score = True,
    print_confusion_matrix = False,
    
    DummyClassifier__estrategia = None,
    
    DecisionTreeClassifier__retornar_visualizacao = False,
    DecisionTreeClassifier__max_depth = None,
    
    RandomForestClassifier__n_estimators = 100,
    
    feature_selection = None,
    scaler = None,
):
    from sklearn.model_selection import train_test_split
    # from sklearn.preprocessing import StandardScaler
    
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier
    # from sklearn.svm import LinearSVC
    from sklearn.svm import SVC
    from sklearn.naive_bayes import MultinomialNB
    from sklearn.dummy import DummyClassifier
    
    # from sklearn.metrics import accuracy_score
    from sklearn.metrics import confusion_matrix
    from sklearn.tree import export_graphviz
    import graphviz
    import os
    os.environ["PATH"] += os.pathsep + 'C:/Program Files/Graphviz/bin' # https://stackoverflow.com/questions/35064304/runtimeerror-make-sure-the-graphviz-executables-are-on-your-systems-path-aft

    np.random.seed(SEED)


    # DIVIDE A BASE NAS PORÇÕES DE TESTE E TREINO, X E Y
    [original_x_treino, original_x_teste, y_treino, y_teste] = train_test_split(
        dados.loc[:, colunas_treino],
        dados.loc[:, coluna_resultado],
        test_size = proporcao,
        # stratify = dados.loc[:, coluna_resultado] # mesma proporção de y
    )
    
    
    # SELECIONA AS FEATURES COM BASE NO ARGUMENTO E REESCALA SE NECESSÁRIO
    if feature_selection is not None:
        feature_selection.fit(original_x_treino, y_treino)
        x_treino = feature_selection.transform(original_x_treino)
        x_teste = feature_selection.transform(original_x_teste)
        
    if (scaler is None) | ((estimador is not None) * (estimador != "DecisionTreeClassifier")): # Não é necessário reescalar para árvore de decisão
        if feature_selection is None:
            x_treino = original_x_treino
            x_teste = original_x_teste
    else:
        if feature_selection is None:
            scaler.fit(original_x_treino)
            x_treino = scaler.transform(original_x_treino)
            x_teste = scaler.transform(original_x_teste)
        else:
            scaler.fit(x_treino)
            x_treino = scaler.transform(x_treino)
            x_teste = scaler.transform(x_teste)


    # IMPRIME O TAMANHO DE CADA PORÇÃO
    if print_tamanho == True:
        print("Tamanho treino: " + str(len(x_treino)))
        print("Tamanho teste: " + str(len(x_teste)))

    

    # INSTANCIA O ESTIMADOR ESCOLHIDO. SE NÃO HOUVER ESTIMADOR, RETORNA APENAS AS PORÇÕES SELECIONADAS E REESCALADAS
    if estimador is None:
        return [
            [original_x_treino, original_x_teste, y_treino, y_teste], 
            [x_treino, x_teste],
            feature_selection
        ]

    elif estimador == "SVC":
        modelo = SVC(gamma = "auto")
    
    elif estimador == "RandomForestClassifier":
        # print(estimador)
        modelo = RandomForestClassifier(n_estimators = RandomForestClassifier__n_estimators)
        print(modelo)

    elif estimador == "DecisionTreeClassifier":
        if DecisionTreeClassifier__max_depth is None:
            modelo = DecisionTreeClassifier()
        else:
            modelo = DecisionTreeClassifier(max_depth = DecisionTreeClassifier__max_depth)

    elif estimador == "MultinomialNB":
        modelo = MultinomialNB()
        
    elif estimador == "Dummy":
        if DummyClassifier__estrategia is None:  
            modelo = DummyClassifier()
        else:
            modelo = DummyClassifier(strategy = DummyClassifier__estrategia)
        
    else:
        return print("Estimador " + estimador + " não encontrado")
    
    
    # TREINA O ESTIMADOR ESCOLHIDO
    try:
        modelo.fit(x_treino, y_treino)
        print(modelo)
    except ValueError:
        return [print("Não foi possível treinar o modelo escolhido"), modelo]

    # AVALIA O MODELO
    
    # previsoes = modelo.predict(x_teste)
    # taxa_de_acerto = accuracy_score(y_teste, previsoes)

    taxa_de_acerto = modelo.score(x_teste, y_teste)
    
    if print_score == True:
        print("Taxa de acerto do modelo " + estimador + ": {:.2%}".format(taxa_de_acerto))
        
    if print_confusion_matrix == True:
        matriz_confusao = confusion_matrix(y_teste, modelo.predict(x_teste))
        # print(matriz_confusao)
        sns.set(font_scale = 2)
        sns.heatmap(matriz_confusao, annot = True, fmt = "d").set(xlabel = "Predição", ylabel = "Real")
        plt.show()
    
    # RETORNA VISÃO GRÁFICA PARA O DECISION TREE CLASSIFIER
    if (DecisionTreeClassifier__retornar_visualizacao == True) * (estimador == "DecisionTreeClassifier"):
        # return export_graphviz(modelo, out_file = None)
        dot_data = export_graphviz(
            modelo, 
            feature_names = colunas_treino,
            filled = True,
            rounded = True,
            class_names = ["Não", "Sim"]
        )
        grafico = graphviz.Source(dot_data)
        return grafico
    
    # RETORNA BASES E MODELO PARA OUTROS ESTIMADORES
    return [
        modelo, 
        [original_x_treino, original_x_teste, y_treino, y_teste], 
        [x_treino, x_teste], 
        feature_selection,
        # previsoes, 
        taxa_de_acerto
    ]

# Leitura dos dados

In [ ]:
var_caminho = os.environ.get('var_caminho_fonte') + r"\Bases"
#f

# var_arquivo = r"\Bases\Lista de ações Análise 2025-03-16.xlsx"

lista_arquivos = listdir(var_caminho)
lista_arquivos_analises = []
for arquivo in lista_arquivos:
    if arquivo.find(" Análise") > 0:
        lista_arquivos_analises.append(datetime.strptime(arquivo.split(" Análise ")[1].split(".xls")[0], "%Y-%m-%d"))

var_arquivo_mais_recente = "/Lista de ações Análise " + max(lista_arquivos_analises).strftime("%Y-%m-%d") + ".xlsx"
# print(var_arquivo_mais_recente)

bd_dados_completos = pd.read_excel(var_caminho + var_arquivo_mais_recente).set_index("Ticker")
bd_dados_completos

,Nome da Empresa,Volume no último dia útil (lido em 19/04/2025),industry,sector,fullTimeEmployees,dividendRate,dividendYield,exDividendDate,payoutRatio,beta,...,2025-04-17; Low,2025-04-17; Close,2025-04-17; Volume,2025-04-17; Dividends,2025-04-17; Stock Splits,2025-04-17; HLC,Alfa HLC; últimos 13 dias,Alfa HLC; últimos 55 dias,Martelos,Tipos de Martelos
Ticker,,,,,,,,,,,,,,,,,,,,,
COGN3,Cogna,111753600,Education & Training Services,Consumer Defensive,"24,187.00",0.26,10.70,"1,745,884,800.00",0.00,0.64,...,2.15,2.45,111753600,0.00,0,2.36,0.03,0.02,"2025-02-27, 2025-02-28, 2025-03-06, 2025-03-17...","Descida, Descida, Subida, Subida, Subida, Subi..."
PETR4,Petrobras,65752700,Oil & Gas Integrated,Energy,"41,778.00",7.09,22.98,"1,744,848,000.00",2.01,0.49,...,30.46,30.85,65752700,0.71,0,30.83,-0.52,-0.11,"2025-02-27, 2025-03-10, 2025-03-12, 2025-03-18...","Subida, Subida, Descida, Subida, Subida, Subid..."
HAPV3,Hapvida,57331500,Insurance - Life,Financial Services,NaN,NaN,NaN,"1,640,649,600.00",0.00,0.59,...,2.15,2.16,57331500,0.00,0,2.18,0.00,0.00,"2025-02-27, 2025-02-28, 2025-03-11, 2025-03-13...","Subida, Subida, Subida, Subida, Subida, Subida..."
ABEV3,Ambev,56058800,Beverages - Brewers,Consumer Defensive,"43,000.00",0.80,5.68,"1,742,169,600.00",0.73,0.36,...,13.79,14.00,56058800,0.00,0,13.96,0.02,0.05,"2025-02-26, 2025-03-18, 2025-04-04, 2025-04-07...","Descida, Subida, Descida, Descida, Subida, Des..."
MGLU3,Magazine Luiza,26837300,Specialty Retail,Consumer Cyclical,NaN,0.31,2.99,"1,745,798,400.00",0.00,1.49,...,10.16,10.20,26856800,0.00,0,10.28,-0.05,0.10,"2025-02-27, 2025-02-28, 2025-03-06, 2025-03-11...","Descida, Descida, Subida, Subida, Descida, Des..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TASA3,Taurus,26300,Aerospace & Defense,Industrials,NaN,0.20,2.24,"1,745,971,200.00",0.50,1.19,...,9.00,9.12,26300,0.00,0,9.14,0.05,0.02,"2025-02-25, 2025-02-28, 2025-03-05, 2025-03-06...","Subida, Descida, Descida, Subida, Subida, Subi..."
LOGN3,Log-In,24500,Marine Shipping,Industrials,NaN,NaN,NaN,"1,237,334,400.00",0.00,0.47,...,21.19,21.25,24500,0.00,0,21.28,0.02,-0.01,"2025-03-06, 2025-03-07, 2025-03-20, 2025-03-31...","Subida, Subida, Descida, Descida, Descida, Sub..."
BIOM3,Biomm,23800,Biotechnology,Healthcare,NaN,NaN,NaN,NaN,0.00,0.67,...,9.75,9.75,23800,0.00,0,9.93,-0.01,-0.02,"2025-02-27, 2025-03-11, 2025-03-13, 2025-03-19...","Subida, Subida, Subida, Subida, Descida, Desci..."
PTNT4,Pettenati,21300,Apparel Manufacturing,Consumer Cyclical,NaN,0.27,4.20,"1,730,246,400.00",0.42,-0.02,...,6.45,6.45,21300,0.00,0,6.56,-0.11,-0.01,"2025-02-24, 2025-02-28, 2025-03-13, 2025-03-21...","Subida, Descida, Descida, Descida, Subida, Sub..."
ALUP4,Alupar,20200,Utilities - Renewable,Utilities,906.00,0.32,3.36,"1,744,848,000.00",0.42,0.25,...,9.45,9.51,20200,0.00,0,9.54,0.01,0.02,"2025-02-24, 2025-03-21, 2025-03-26, 2025-03-27...","Subida, Descida, Descida, Subida, Subida, Subi..."

# Análise Exploratória

## Confirmar se coluna Ticker está duplicada

In [56]:
# bd_dados_completos[[item for item in bd_dados_completos.columns.to_list() if "Ticker" in item]]

display(len(bd_dados_completos))
display(len(bd_dados_completos.index.unique()))

246

246

## Remover outras colunas que possam se repetir (uma para cada dia)

In [12]:
lista_ignorados_datas = ["Ticker" , "HLC" , "Stock Splits" , "Dividends" , "Volume" , "Close" , "Low" , "High" , "Open"]
# lista_ignorados_datas[0]

lista_colunas_ignoradas_datas = []
for ignorado_datas in lista_ignorados_datas:
    lista_colunas_ignoradas_datas.append([item for item in bd_dados_completos.columns.to_list() if ignorado_datas in item])
# lista_colunas_ignoradas_datas

In [13]:
## Essas colunas já foram removidas no arquivo 'receber_lista_atualizada_tickers.py'

# lista_ignorados = ["industryKey", "industryDisp", "sectorKey", "volume",
#                    "sectorDisp", "regularMarketVolume", "SandP52WeekChange"]

# # lista_colunas_ignoradas_datas = []
# for ignorado_datas in lista_ignorados_datas:
#     lista_ignorados = lista_ignorados + [item for item in bd_dados_completos.columns.to_list() if ignorado_datas in item]
# print(lista_ignorados)


[bd_semNA, colunas_parciais, colunas_agrupadas, campos_com_erro] = analise_exploratoria(
    # bd_dados_completos.drop(lista_ignorados, axis = 1),
    bd_dados_completos,
    imprime_todas_colunas = False,
    # imprime_info_colunas = True,
    imprime_info_colunas = False,
    imprime_colunas_vazias = False,
    imprime_colunas_completas = False,
    imprime_colunas_parciais = False,
    # remove_da_base = True,
    retorna_parciais = True,
    # detalhar_colunas_parciais = True,
    colunas_ignoradas = []
    )

['fullTimeEmployees', 'dividendRate', 'dividendYield', 'exDividendDate', 'payoutRatio', 'beta', 'trailingPE', 'forwardPE', 'priceToSalesTrailing12Months', 'profitMargins', 'forwardEps', 'lastSplitFactor', 'lastSplitDate', 'enterpriseToRevenue', 'enterpriseToEbitda', 'lastDividendValue', 'lastDividendDate', 'recommendationMean', 'numberOfAnalystOpinions', 'totalCash', 'totalCashPerShare', 'ebitda', 'totalDebt', 'quickRatio', 'currentRatio', 'totalRevenue', 'debtToEquity', 'revenuePerShare', 'returnOnAssets', 'returnOnEquity', 'grossProfits', 'freeCashflow', 'operatingCashflow', 'earningsGrowth', 'revenueGrowth', 'grossMargins', 'ebitdaMargins', 'epsForward', 'epsCurrentYear', 'priceEpsCurrentYear']

                     Quantidade    %  % acumulado
Nome da Empresa
Banco Santander               3 0.01         0.01
Taesa                         3 0.01         0.02
Sanepar                       3 0.01         0.04
Banco Bradesco                2 0.01         0.04
Azevedo & Travassos           2 0.01         0.05
...                         ...  ...          ...
Wilson Sons                   1 0.00         0.98
Wiz Soluções                  1 0.00         0.99
YDUQS                         1 0.00         0.99
Zamp                          1 0.00         1.00
Ânima Educação                1 0.00         1.00

[222 rows x 3 columns]

                                                Quantidade    %  % acumulado
Volume no último dia útil (lido em 19/04/2025)
96800                                                    2 0.01         0.01
21300                                                    1 0.00         0.01
23800                                                    1 0.00         0.02
24500                                                    1 0.00         0.02
20200                                                    1 0.00         0.02
...                                                    ...  ...          ...
26837300                                                 1 0.00         0.98
56058800                                                 1 0.00         0.99
57331500                                                 1 0.00         0.99
65752700                                                 1 0.00         1.00
111753600                                                1 0.00         1.00

[245 rows x 3 columns]

                                         Quantidade    %  % acumulado
industry
Banks - Regional                                 13 0.05         0.05
Real Estate Services                             12 0.05         0.10
Utilities - Renewable                            11 0.04         0.15
Real Estate - Development                        10 0.04         0.19
Utilities - Regulated Electric                    9 0.04         0.22
...                                             ...  ...          ...
Personal Services                                 1 0.00         0.98
Specialty Chemicals                               1 0.00         0.99
Utilities - Independent Power Producers           1 0.00         0.99
Travel Services                                   1 0.00         1.00
Trucking                                          1 0.00         1.00

[87 rows x 3 columns]

                        Quantidade    %  % acumulado
sector
Industrials                     48 0.20         0.20
Consumer Cyclical               38 0.15         0.35
Utilities                       29 0.12         0.47
Financial Services              23 0.09         0.56
Real Estate                     23 0.09         0.65
Basic Materials                 22 0.09         0.74
Consumer Defensive              19 0.08         0.82
Healthcare                      17 0.07         0.89
Communication Services          10 0.04         0.93
Technology                       9 0.04         0.97
Energy                           8 0.03         1.00

                   Quantidade    %  % acumulado
fullTimeEmployees
 (vazio)                  142 0.58         0.58
6,047.00                    3 0.01         0.59
854.00                      3 0.01         0.60
55,646.00                   3 0.01         0.61
6,000.00                    2 0.01         0.62
...                       ...  ...          ...
64,616.00                   1 0.00         0.98
87,000.00                   1 0.00         0.99
100,000.00                  1 0.00         0.99
126,832.00                  1 0.00         1.00
190,000.00                  1 0.00         1.00

[91 rows x 3 columns]

              Quantidade    %  % acumulado
dividendRate
 (vazio)              56 0.23         0.23
0.07                   6 0.02         0.25
0.80                   5 0.02         0.27
0.59                   5 0.02         0.29
0.31                   4 0.02         0.31
...                  ...  ...          ...
3.94                   1 0.00         0.98
4.64                   1 0.00         0.99
3.95                   1 0.00         0.99
4.94                   1 0.00         1.00
7.49                   1 0.00         1.00

[120 rows x 3 columns]

               Quantidade    %  % acumulado
dividendYield
 (vazio)               56 0.23         0.23
3.01                    3 0.01         0.24
2.42                    2 0.01         0.25
8.31                    2 0.01         0.26
7.57                    2 0.01         0.26
...                   ...  ...          ...
22.98                   1 0.00         0.98
27.44                   1 0.00         0.99
49.00                   1 0.00         0.99
62.92                   1 0.00         1.00
127.37                  1 0.00         1.00

[179 rows x 3 columns]

                  Quantidade    %  % acumulado
exDividendDate
 (vazio)                  18 0.07         0.07
1,746,144,000.00          15 0.06         0.13
1,745,971,200.00          15 0.06         0.20
1,745,280,000.00           8 0.03         0.23
1,745,798,400.00           8 0.03         0.26
...                      ...  ...          ...
1,747,094,400.00           1 0.00         0.98
1,747,958,400.00           1 0.00         0.99
1,747,872,000.00           1 0.00         0.99
1,748,217,600.00           1 0.00         1.00
1,751,241,600.00           1 0.00         1.00

[112 rows x 3 columns]

             Quantidade    %  % acumulado
payoutRatio
0.00                 69 0.28         0.28
 (vazio)              6 0.02         0.30
0.49                  2 0.01         0.31
0.51                  2 0.01         0.32
0.38                  2 0.01         0.33
...                 ...  ...          ...
2.30                  1 0.00         0.98
3.30                  1 0.00         0.99
31.95                 1 0.00         0.99
95.32                 1 0.00         1.00
162.73                1 0.00         1.00

[166 rows x 3 columns]

          Quantidade    %  % acumulado
beta
0.20               5 0.02         0.02
0.13               3 0.01         0.03
0.48               3 0.01         0.04
 (vazio)           3 0.01         0.06
0.50               3 0.01         0.07
...              ...  ...          ...
1.56               1 0.00         0.98
1.59               1 0.00         0.99
1.57               1 0.00         0.99
1.84               1 0.00         1.00
2.09               1 0.00         1.00

[206 rows x 3 columns]

            Quantidade    %  % acumulado
trailingPE
 (vazio)            59 0.24         0.24
inf                  3 0.01         0.25
7.00                 2 0.01         0.26
0.06                 1 0.00         0.26
0.08                 1 0.00         0.27
...                ...  ...          ...
80.23                1 0.00         0.98
131.62               1 0.00         0.99
105.00               1 0.00         0.99
623.50               1 0.00         1.00
178.38               1 0.00         1.00

[185 rows x 3 columns]

           Quantidade    %  % acumulado
forwardPE
 (vazio)           32 0.13         0.13
-33.19              1 0.00         0.13
-45.12              1 0.00         0.14
-18.55              1 0.00         0.14
-13.39              1 0.00         0.15
...               ...  ...          ...
27.35               1 0.00         0.98
38.70               1 0.00         0.99
49.12               1 0.00         0.99
51.75               1 0.00         1.00
108.20              1 0.00         1.00

[215 rows x 3 columns]

               Quantidade    %  % acumulado
averageVolume
6709                    1 0.00         0.00
9633                    1 0.00         0.01
13614                   1 0.00         0.01
24937                   1 0.00         0.02
27591                   1 0.00         0.02
...                   ...  ...          ...
37900975                1 0.00         0.98
41510324                1 0.00         0.99
45555412                1 0.00         0.99
54038432                1 0.00         1.00
100621951               1 0.00         1.00

[246 rows x 3 columns]

                     Quantidade    %  % acumulado
averageVolume10days
12110                         1 0.00         0.00
14800                         1 0.00         0.01
16610                         1 0.00         0.01
19440                         1 0.00         0.02
22120                         1 0.00         0.02
...                         ...  ...          ...
42149260                      1 0.00         0.98
42198210                      1 0.00         0.99
62252560                      1 0.00         0.99
73125810                      1 0.00         1.00
74166360                      1 0.00         1.00

[246 rows x 3 columns]

                         Quantidade    %  % acumulado
averageDailyVolume10Day
12110                             1 0.00         0.00
14800                             1 0.00         0.01
16610                             1 0.00         0.01
19440                             1 0.00         0.02
22120                             1 0.00         0.02
...                             ...  ...          ...
42149260                          1 0.00         0.98
42198210                          1 0.00         0.99
62252560                          1 0.00         0.99
73125810                          1 0.00         1.00
74166360                          1 0.00         1.00

[246 rows x 3 columns]

              Quantidade    %  % acumulado
marketCap
54360212               1 0.00         0.00
57996136               1 0.00         0.01
57996156               1 0.00         0.01
71394112               1 0.00         0.02
71394232               1 0.00         0.02
...                  ...  ...          ...
225733099520           1 0.00         0.98
330909122560           1 0.00         0.99
330909253632           1 0.00         0.99
414883151872           1 0.00         1.00
414883676160           1 0.00         1.00

[246 rows x 3 columns]

                              Quantidade    %  % acumulado
priceToSalesTrailing12Months
 (vazio)                               2 0.01         0.01
0.02                                   1 0.00         0.01
0.03                                   1 0.00         0.02
0.07                                   1 0.00         0.02
0.02                                   1 0.00         0.02
...                                  ...  ...          ...
13.17                                  1 0.00         0.98
16.22                                  1 0.00         0.99
20.09                                  1 0.00         0.99
416.24                                 1 0.00         1.00
416.24                                 1 0.00         1.00

[245 rows x 3 columns]

                 Quantidade    %  % acumulado
fiftyDayAverage
0.07                      1 0.00         0.00
0.26                      1 0.00         0.01
0.55                      1 0.00         0.01
0.71                      1 0.00         0.02
0.91                      1 0.00         0.02
...                     ...  ...          ...
54.99                     1 0.00         0.98
55.49                     1 0.00         0.99
66.50                     1 0.00         0.99
100.23                    1 0.00         1.00
125.15                    1 0.00         1.00

[246 rows x 3 columns]

                      Quantidade    %  % acumulado
twoHundredDayAverage
0.14                           1 0.00         0.00
0.30                           1 0.00         0.01
0.75                           1 0.00         0.01
0.88                           1 0.00         0.02
0.96                           1 0.00         0.02
...                          ...  ...          ...
54.72                          1 0.00         0.98
57.13                          1 0.00         0.99
57.36                          1 0.00         0.99
94.01                          1 0.00         1.00
116.60                         1 0.00         1.00

[246 rows x 3 columns]

                            Quantidade    %  % acumulado
trailingAnnualDividendRate
0.00                               121 0.49         0.49
0.28                                 3 0.01         0.50
0.85                                 3 0.01         0.52
2.61                                 3 0.01         0.53
0.07                                 2 0.01         0.54
...                                ...  ...          ...
2.79                                 1 0.00         0.98
3.04                                 1 0.00         0.99
2.86                                 1 0.00         0.99
3.66                                 1 0.00         1.00
4.76                                 1 0.00         1.00

[105 rows x 3 columns]

                             Quantidade    %  % acumulado
trailingAnnualDividendYield
0.00                                121 0.49         0.49
0.00                                  1 0.00         0.50
0.01                                  1 0.00         0.50
0.01                                  1 0.00         0.50
0.01                                  1 0.00         0.51
...                                 ...  ...          ...
0.18                                  1 0.00         0.98
0.19                                  1 0.00         0.99
0.19                                  1 0.00         0.99
0.23                                  1 0.00         1.00
0.23                                  1 0.00         1.00

[126 rows x 3 columns]

               Quantidade    %  % acumulado
profitMargins
0.00                    5 0.02         0.02
0.28                    3 0.01         0.03
0.46                    3 0.01         0.04
0.23                    3 0.01         0.06
-0.45                   2 0.01         0.07
...                   ...  ...          ...
0.72                    1 0.00         0.98
1.51                    1 0.00         0.99
0.85                    1 0.00         0.99
0.75                    1 0.00         1.00
 (vazio)                1 0.00         1.00

[218 rows x 3 columns]

             Quantidade    %  % acumulado
trailingEps
0.83                  4 0.02         0.02
-0.09                 3 0.01         0.03
1.09                  3 0.01         0.04
0.72                  3 0.01         0.05
0.00                  3 0.01         0.07
...                 ...  ...          ...
5.68                  1 0.00         0.98
8.45                  1 0.00         0.99
9.85                  1 0.00         0.99
12.29                 1 0.00         1.00
69.71                 1 0.00         1.00

[189 rows x 3 columns]

            Quantidade    %  % acumulado
forwardEps
 (vazio)            35 0.14         0.14
2.01                 5 0.02         0.16
0.78                 4 0.02         0.18
0.94                 4 0.02         0.20
1.04                 3 0.01         0.21
...                ...  ...          ...
7.84                 1 0.00         0.98
8.04                 1 0.00         0.99
8.52                 1 0.00         0.99
11.94                1 0.00         1.00
16.06                1 0.00         1.00

[169 rows x 3 columns]

                 Quantidade    %  % acumulado
lastSplitFactor
(vazio)                  96 0.39         0.39
2:1                      23 0.09         0.48
3:1                      20 0.08         0.57
11:10                    11 0.04         0.61
4:1                      11 0.04         0.65
1:10                      9 0.04         0.69
1:5                       7 0.03         0.72
5:1                       5 0.02         0.74
1:500                     4 0.02         0.76
1:55                      3 0.01         0.77
10:1                      3 0.01         0.78
110:100                   3 0.01         0.79
1:4                       3 0.01         0.80
5:4                       3 0.01         0.82
21:20                     3 0.01         0.83
11.295:10                 2 0.01         0.84
104:100                   2 0.01         0.85
1:6                       2 0.01         0.85
105:100                   2 0.01         0.86
12:10                     2 0.01         0.87
130:100                   2 0.01         0.88
1:1000                    2 0.01         0.89
1:20                      2 0.01         0.89
125:100                   1 0.00         0.90
100:1                     1 0.00         0.90
1.025076:1                1 0.00         0.91
121.2108:100              1 0.00         0.91
10:100                    1 0.00         0.91
111.5213:100              1 0.00         0.92
1.25:1                    1 0.00         0.92
1.142:1                   1 0.00         0.93
1.139045:1                1 0.00         0.93
1:17                      1 0.00         0.93
1:7                       1 0.00         0.94
1:250                     1 0.00         0.94
1:30                      1 0.00         0.95
1:25                      1 0.00         0.95
1:100                     1 0.00         0.96
1:15                      1 0.00         0.96
1:7.50476                 1 0.00         0.96
1:9                       1 0.00         0.97
30:1                      1 0.00         0.97
26:25                     1 0.00         0.98
20:1                      1 0.00         0.98
21:1                      1 0.00         0.98
6:1                       1 0.00         0.99
6:5                       1 0.00         0.99
80:40                     1 0.00         1.00
8:1                       1 0.00         1.00

                  Quantidade    %  % acumulado
lastSplitDate
 (vazio)                  96 0.39         0.39
1,615,507,200.00           3 0.01         0.40
1,717,113,600.00           3 0.01         0.41
1,585,526,400.00           3 0.01         0.43
1,401,667,200.00           3 0.01         0.44
...                      ...  ...          ...
1,716,768,000.00           1 0.00         0.98
1,733,961,600.00           1 0.00         0.99
1,724,716,800.00           1 0.00         0.99
1,746,489,600.00           1 0.00         1.00
1,744,675,200.00           1 0.00         1.00

[121 rows x 3 columns]

                     Quantidade    %  % acumulado
enterpriseToRevenue
0.41                          2 0.01         0.01
1.01                          2 0.01         0.02
1.10                          2 0.01         0.02
0.92                          2 0.01         0.03
0.70                          2 0.01         0.04
...                         ...  ...          ...
16.45                         1 0.00         0.98
225.50                        1 0.00         0.99
227.63                        1 0.00         0.99
388.58                        1 0.00         1.00
403.45                        1 0.00         1.00

[237 rows x 3 columns]

                    Quantidade    %  % acumulado
enterpriseToEbitda
 (vazio)                    18 0.07         0.07
7.16                         2 0.01         0.08
4.78                         2 0.01         0.09
-17.59                       1 0.00         0.09
-15.15                       1 0.00         0.10
...                        ...  ...          ...
71.50                        1 0.00         0.98
142.41                       1 0.00         0.99
645.25                       1 0.00         0.99
646.55                       1 0.00         1.00
707.01                       1 0.00         1.00

[227 rows x 3 columns]

              Quantidade    %  % acumulado
52WeekChange
-0.91                  1 0.00         0.00
-0.89                  1 0.00         0.01
-0.88                  1 0.00         0.01
-0.81                  1 0.00         0.02
-0.78                  1 0.00         0.02
...                  ...  ...          ...
0.86                   1 0.00         0.98
0.97                   1 0.00         0.99
1.01                   1 0.00         0.99
1.13                   1 0.00         1.00
11.58                  1 0.00         1.00

[246 rows x 3 columns]

                   Quantidade    %  % acumulado
lastDividendValue
 (vazio)                   20 0.08         0.08
0.02                        2 0.01         0.09
0.10                        2 0.01         0.10
0.29                        2 0.01         0.11
0.66                        2 0.01         0.11
...                       ...  ...          ...
2.32                        1 0.00         0.98
3.48                        1 0.00         0.99
62.10                       1 0.00         0.99
510.69                      1 0.00         1.00
901.72                      1 0.00         1.00

[218 rows x 3 columns]

                  Quantidade    %  % acumulado
lastDividendDate
 (vazio)                  20 0.08         0.08
1,746,144,000.00          14 0.06         0.14
1,745,971,200.00          14 0.06         0.20
1,745,798,400.00           8 0.03         0.23
1,745,280,000.00           6 0.02         0.25
...                      ...  ...          ...
1,747,094,400.00           1 0.00         0.98
1,751,241,600.00           1 0.00         0.99
1,750,377,600.00           1 0.00         0.99
1,747,958,400.00           1 0.00         1.00
1,766,102,400.00           1 0.00         1.00

[120 rows x 3 columns]

                    Quantidade    %  % acumulado
recommendationMean
 (vazio)                    83 0.34         0.34
2.00                         8 0.03         0.37
1.50                         6 0.02         0.39
2.33                         6 0.02         0.42
3.00                         5 0.02         0.44
...                        ...  ...          ...
3.46                         1 0.00         0.98
3.77                         1 0.00         0.99
3.80                         1 0.00         0.99
3.89                         1 0.00         1.00
4.00                         1 0.00         1.00

[92 rows x 3 columns]

                   Quantidade    %  % acumulado
recommendationKey
buy                        83 0.34         0.34
none                       83 0.34         0.67
hold                       43 0.17         0.85
strong_buy                 32 0.13         0.98
underperform                5 0.02         1.00

                         Quantidade    %  % acumulado
numberOfAnalystOpinions
 (vazio)                         54 0.22         0.22
13.00                            28 0.11         0.33
12.00                            16 0.07         0.40
9.00                             15 0.06         0.46
11.00                            15 0.06         0.52
3.00                             14 0.06         0.58
8.00                             13 0.05         0.63
1.00                             13 0.05         0.68
14.00                            12 0.05         0.73
10.00                            11 0.04         0.78
2.00                             10 0.04         0.82
5.00                              9 0.04         0.85
7.00                              9 0.04         0.89
6.00                              8 0.03         0.92
4.00                              8 0.03         0.96
15.00                             6 0.02         0.98
16.00                             4 0.02         1.00
18.00                             1 0.00         1.00

                    Quantidade    %  % acumulado
totalCash
750,976,000.00               3 0.01         0.01
192,756,236,288.00           3 0.01         0.02
1,800,756,992.00             3 0.01         0.04
447,000.00                   2 0.01         0.04
3,151,000.00                 2 0.01         0.05
...                        ...  ...          ...
24,173,735,936.00            1 0.00         0.98
21,990,365,184.00            1 0.00         0.99
38,637,752,320.00            1 0.00         0.99
424,292,319,232.00           1 0.00         1.00
343,738,056,704.00           1 0.00         1.00

[221 rows x 3 columns]

                   Quantidade    %  % acumulado
totalCashPerShare
2.18                        3 0.01         0.01
1.19                        3 0.01         0.02
25.84                       3 0.01         0.04
0.00                        2 0.01         0.04
0.60                        2 0.01         0.05
...                       ...  ...          ...
25.53                       1 0.00         0.98
45.46                       1 0.00         0.99
50.90                       1 0.00         0.99
72.25                       1 0.00         1.00
74.33                       1 0.00         1.00

[220 rows x 3 columns]

                   Quantidade    %  % acumulado
ebitda
 (vazio)                   17 0.07         0.07
2,223,948,032.00            3 0.01         0.08
2,608,715,008.00            3 0.01         0.09
-13,884,000.00              2 0.01         0.10
1,913,000.00                2 0.01         0.11
...                       ...  ...          ...
17,859,926,016.00           1 0.00         0.98
26,715,762,688.00           1 0.00         0.99
23,460,323,328.00           1 0.00         0.99
73,358,000,128.00           1 0.00         1.00
35,569,000,448.00           1 0.00         1.00

[211 rows x 3 columns]

                      Quantidade    %  % acumulado
totalDebt
6,631,334,912.00               3 0.01         0.01
314,459,914,240.00             3 0.01         0.02
9,894,993,920.00               3 0.01         0.04
0.00                           2 0.01         0.04
749,692,032.00                 2 0.01         0.05
...                          ...  ...          ...
72,965,177,344.00              1 0.00         0.98
134,926,999,552.00             1 0.00         0.99
287,504,105,472.00             1 0.00         0.99
1,032,465,481,728.00           1 0.00         1.00
 (vazio)                       1 0.00         1.00

[220 rows x 3 columns]

            Quantidade    %  % acumulado
quickRatio
 (vazio)            16 0.07         0.07
1.08                 3 0.01         0.08
1.68                 3 0.01         0.09
0.32                 2 0.01         0.10
0.11                 2 0.01         0.11
...                ...  ...          ...
3.11                 1 0.00         0.98
3.27                 1 0.00         0.99
3.85                 1 0.00         0.99
5.10                 1 0.00         1.00
5.89                 1 0.00         1.00

[206 rows x 3 columns]

              Quantidade    %  % acumulado
currentRatio
 (vazio)              16 0.07         0.07
2.04                   3 0.01         0.08
1.78                   3 0.01         0.09
1.23                   3 0.01         0.10
0.64                   2 0.01         0.11
...                  ...  ...          ...
4.32                   1 0.00         0.98
4.93                   1 0.00         0.99
5.21                   1 0.00         0.99
6.84                   1 0.00         1.00
7.10                   1 0.00         1.00

[205 rows x 3 columns]

                    Quantidade    %  % acumulado
totalRevenue
6,848,219,136.00             3 0.01         0.01
47,185,473,536.00            3 0.01         0.02
3,718,138,112.00             3 0.01         0.04
4,402,000.00                 2 0.01         0.04
259,226,000.00               2 0.01         0.05
...                        ...  ...          ...
148,860,960,768.00           1 0.00         0.98
206,004,994,048.00           1 0.00         0.99
172,271,992,832.00           1 0.00         0.99
416,951,992,320.00           1 0.00         1.00
251,226,357,760.00           1 0.00         1.00

[220 rows x 3 columns]

              Quantidade    %  % acumulado
debtToEquity
 (vazio)              30 0.12         0.12
61.24                  3 0.01         0.13
142.59                 3 0.01         0.15
0.03                   2 0.01         0.15
46.41                  2 0.01         0.16
...                  ...  ...          ...
615.34                 1 0.00         0.98
760.93                 1 0.00         0.99
844.71                 1 0.00         0.99
1,016.21               1 0.00         1.00
34,532.31              1 0.00         1.00

[200 rows x 3 columns]

                 Quantidade    %  % acumulado
revenuePerShare
 (vazio)                  4 0.02         0.02
6.33                      3 0.01         0.03
4.53                      3 0.01         0.04
10.79                     3 0.01         0.05
3.23                      2 0.01         0.06
...                     ...  ...          ...
121.13                    1 0.00         0.98
155.99                    1 0.00         0.99
164.76                    1 0.00         0.99
188.18                    1 0.00         1.00
286.30                    1 0.00         1.00

[219 rows x 3 columns]

                Quantidade    %  % acumulado
returnOnAssets
0.01                     3 0.01         0.01
0.07                     3 0.01         0.02
0.07                     3 0.01         0.04
-0.02                    2 0.01         0.04
-0.00                    2 0.01         0.05
...                    ...  ...          ...
0.15                     1 0.00         0.98
0.17                     1 0.00         0.99
0.19                     1 0.00         0.99
0.24                     1 0.00         1.00
0.31                     1 0.00         1.00

[219 rows x 3 columns]

                Quantidade    %  % acumulado
returnOnEquity
 (vazio)                13 0.05         0.05
0.11                     3 0.01         0.07
0.15                     3 0.01         0.08
0.25                     3 0.01         0.09
0.27                     3 0.01         0.10
...                    ...  ...          ...
0.50                     1 0.00         0.98
0.52                     1 0.00         0.99
0.61                     1 0.00         0.99
0.64                     1 0.00         1.00
0.89                     1 0.00         1.00

[212 rows x 3 columns]

                    Quantidade    %  % acumulado
grossProfits
2,476,240,896.00             3 0.01         0.01
46,307,082,240.00            3 0.01         0.02
3,957,832,960.00             3 0.01         0.04
-1,454,660,992.00            2 0.01         0.04
15,856,000.00                2 0.01         0.05
...                        ...  ...          ...
20,001,755,136.00            1 0.00         0.98
19,690,670,080.00            1 0.00         0.99
62,772,998,144.00            1 0.00         0.99
74,686,996,480.00            1 0.00         1.00
101,466,669,056.00           1 0.00         1.00

[220 rows x 3 columns]

                   Quantidade    %  % acumulado
freeCashflow
 (vazio)                   17 0.07         0.07
-360,252,864.00             3 0.01         0.08
1,199,795,200.00            3 0.01         0.09
-191,212,256.00             2 0.01         0.10
-3,755,497,984.00           2 0.01         0.11
...                       ...  ...          ...
9,815,608,320.00            1 0.00         0.98
19,344,275,456.00           1 0.00         0.99
11,183,279,104.00           1 0.00         0.99
41,687,126,016.00           1 0.00         1.00
41,630,875,648.00           1 0.00         1.00

[210 rows x 3 columns]

                    Quantidade    %  % acumulado
operatingCashflow
-21,131,266,048.00           3 0.01         0.01
2,775,021,056.00             3 0.01         0.02
1,540,337,024.00             3 0.01         0.04
-96,319,995,904.00           2 0.01         0.04
-91,326,291,968.00           2 0.01         0.05
...                        ...  ...          ...
20,604,426,240.00            1 0.00         0.98
26,099,034,112.00            1 0.00         0.99
23,556,999,168.00            1 0.00         0.99
62,312,546,304.00            1 0.00         1.00
50,198,999,040.00            1 0.00         1.00

[221 rows x 3 columns]

                Quantidade    %  % acumulado
earningsGrowth
 (vazio)                95 0.39         0.39
0.06                     3 0.01         0.40
0.13                     3 0.01         0.41
0.40                     3 0.01         0.42
0.63                     3 0.01         0.43
...                    ...  ...          ...
8.79                     1 0.00         0.98
25.79                    1 0.00         0.99
26.38                    1 0.00         0.99
34.88                    1 0.00         1.00
155.25                   1 0.00         1.00

[131 rows x 3 columns]

               Quantidade    %  % acumulado
revenueGrowth
 (vazio)                8 0.03         0.03
0.08                    4 0.02         0.05
0.13                    4 0.02         0.07
-0.01                   3 0.01         0.08
-0.16                   3 0.01         0.09
...                   ...  ...          ...
0.90                    1 0.00         0.98
1.25                    1 0.00         0.99
1.39                    1 0.00         0.99
1.54                    1 0.00         1.00
1.64                    1 0.00         1.00

[181 rows x 3 columns]

              Quantidade    %  % acumulado
grossMargins
0.00                  15 0.06         0.06
0.67                   3 0.01         0.07
0.58                   3 0.01         0.09
0.09                   2 0.01         0.09
0.02                   2 0.01         0.10
...                  ...  ...          ...
0.93                   1 0.00         0.98
0.96                   1 0.00         0.99
0.98                   1 0.00         0.99
0.98                   1 0.00         1.00
 (vazio)               1 0.00         1.00

[211 rows x 3 columns]

               Quantidade    %  % acumulado
ebitdaMargins
0.00                   19 0.08         0.08
0.38                    3 0.01         0.09
0.60                    3 0.01         0.10
-0.62                   2 0.01         0.11
-0.70                   2 0.01         0.12
...                   ...  ...          ...
0.73                    1 0.00         0.98
0.77                    1 0.00         0.99
0.84                    1 0.00         0.99
0.96                    1 0.00         1.00
 (vazio)                1 0.00         1.00

[209 rows x 3 columns]

                  Quantidade    %  % acumulado
operatingMargins
0.34                       3 0.01         0.01
0.54                       3 0.01         0.02
3.18                       3 0.01         0.04
-20.26                     2 0.01         0.04
-0.25                      2 0.01         0.05
...                      ...  ...          ...
0.67                       1 0.00         0.98
0.98                       1 0.00         0.99
0.93                       1 0.00         0.99
1.66                       1 0.00         1.00
1.84                       1 0.00         1.00

[220 rows x 3 columns]

                         Quantidade    %  % acumulado
epsTrailingTwelveMonths
0.83                              4 0.02         0.02
-0.09                             3 0.01         0.03
1.09                              3 0.01         0.04
0.72                              3 0.01         0.05
0.00                              3 0.01         0.07
...                             ...  ...          ...
5.68                              1 0.00         0.98
8.45                              1 0.00         0.99
9.85                              1 0.00         0.99
12.29                             1 0.00         1.00
69.71                             1 0.00         1.00

[189 rows x 3 columns]

            Quantidade    %  % acumulado
epsForward
 (vazio)            35 0.14         0.14
2.01                 5 0.02         0.16
0.78                 4 0.02         0.18
0.94                 4 0.02         0.20
1.04                 3 0.01         0.21
...                ...  ...          ...
7.84                 1 0.00         0.98
8.04                 1 0.00         0.99
8.52                 1 0.00         0.99
11.94                1 0.00         1.00
16.06                1 0.00         1.00

[169 rows x 3 columns]

                Quantidade    %  % acumulado
epsCurrentYear
 (vazio)                68 0.28         0.28
0.98                     2 0.01         0.28
0.84                     2 0.01         0.29
0.97                     2 0.01         0.30
0.77                     2 0.01         0.31
...                    ...  ...          ...
6.83                     1 0.00         0.98
7.77                     1 0.00         0.99
8.00                     1 0.00         0.99
8.01                     1 0.00         1.00
11.00                    1 0.00         1.00

[174 rows x 3 columns]

                     Quantidade    %  % acumulado
priceEpsCurrentYear
 (vazio)                     69 0.28         0.28
-49.09                        1 0.00         0.28
-33.19                        1 0.00         0.29
-19.31                        1 0.00         0.29
-16.27                        1 0.00         0.30
...                         ...  ...          ...
38.70                         1 0.00         0.98
108.20                        1 0.00         0.99
123.58                        1 0.00         0.99
177.42                        1 0.00         1.00
1,248.34                      1 0.00         1.00

[178 rows x 3 columns]

                       Quantidade    %  % acumulado
fiftyDayAverageChange
0.11                            2 0.01         0.01
0.33                            2 0.01         0.02
-4.34                           1 0.00         0.02
-5.59                           1 0.00         0.02
-3.35                           1 0.00         0.03
...                           ...  ...          ...
4.39                            1 0.00         0.98
7.18                            1 0.00         0.99
7.63                            1 0.00         0.99
8.78                            1 0.00         1.00
10.10                           1 0.00         1.00

[244 rows x 3 columns]

                              Quantidade    %  % acumulado
fiftyDayAverageChangePercent
-0.44                                  1 0.00         0.00
-0.44                                  1 0.00         0.01
-0.25                                  1 0.00         0.01
-0.22                                  1 0.00         0.02
-0.18                                  1 0.00         0.02
...                                  ...  ...          ...
0.34                                   1 0.00         0.98
0.36                                   1 0.00         0.99
0.37                                   1 0.00         0.99
0.43                                   1 0.00         1.00
0.69                                   1 0.00         1.00

[246 rows x 3 columns]

                            Quantidade    %  % acumulado
twoHundredDayAverageChange
-10.04                               1 0.00         0.00
-7.51                                1 0.00         0.01
-7.07                                1 0.00         0.01
-7.06                                1 0.00         0.02
-6.39                                1 0.00         0.02
...                                ...  ...          ...
6.24                                 1 0.00         0.98
8.36                                 1 0.00         0.99
8.43                                 1 0.00         0.99
15.00                                1 0.00         1.00
18.65                                1 0.00         1.00

[246 rows x 3 columns]

                                   Quantidade    %  % acumulado
twoHundredDayAverageChangePercent
-0.78                                       1 0.00         0.00
-0.56                                       1 0.00         0.01
-0.53                                       1 0.00         0.01
-0.47                                       1 0.00         0.02
-0.43                                       1 0.00         0.02
...                                       ...  ...          ...
0.30                                        1 0.00         0.98
0.35                                        1 0.00         0.99
0.43                                        1 0.00         0.99
0.52                                        1 0.00         1.00
0.66                                        1 0.00         1.00

[246 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-24; Open
1.25                       2 0.01         0.01
1.29                       2 0.01         0.02
3.60                       2 0.01         0.02
5.93                       2 0.01         0.03
8.40                       2 0.01         0.04
...                      ...  ...          ...
55.92                      1 0.00         0.98
57.55                      1 0.00         0.99
59.30                      1 0.00         0.99
99.30                      1 0.00         1.00
121.00                     1 0.00         1.00

[239 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-24; High
1.73                       2 0.01         0.01
2.38                       2 0.01         0.02
1.51                       2 0.01         0.02
5.43                       2 0.01         0.03
5.90                       2 0.01         0.04
...                      ...  ...          ...
56.37                      1 0.00         0.98
57.85                      1 0.00         0.99
60.15                      1 0.00         0.99
99.30                      1 0.00         1.00
125.87                     1 0.00         1.00

[240 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-24; Low
1.42                      3 0.01         0.01
4.34                      2 0.01         0.02
3.75                      2 0.01         0.03
27.63                     2 0.01         0.04
0.26                      1 0.00         0.04
...                     ...  ...          ...
55.32                     1 0.00         0.98
56.89                     1 0.00         0.99
57.88                     1 0.00         0.99
96.76                     1 0.00         1.00
121.00                    1 0.00         1.00

[241 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-24; Close
5.38                        2 0.01         0.01
4.37                        2 0.01         0.02
0.06                        1 0.00         0.02
0.26                        1 0.00         0.02
0.81                        1 0.00         0.03
...                       ...  ...          ...
55.47                       1 0.00         0.98
57.03                       1 0.00         0.99
59.89                       1 0.00         0.99
97.03                       1 0.00         1.00
121.73                      1 0.00         1.00

[244 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-24; Volume
10900                        2 0.01         0.01
8840                         1 0.00         0.01
9700                         1 0.00         0.02
10000                        1 0.00         0.02
13500                        1 0.00         0.02
...                        ...  ...          ...
37945600                     1 0.00         0.98
42173000                     1 0.00         0.99
45299900                     1 0.00         0.99
58518400                     1 0.00         1.00
119456400                    1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-24; Dividends
0.00                          245 1.00         1.00
0.02                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-24; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-24; HLC
3.82                      2 0.01         0.01
0.27                      1 0.00         0.01
0.54                      1 0.00         0.02
0.71                      1 0.00         0.02
0.06                      1 0.00         0.02
...                     ...  ...          ...
55.72                     1 0.00         0.98
57.26                     1 0.00         0.99
59.31                     1 0.00         0.99
97.70                     1 0.00         1.00
122.87                    1 0.00         1.00

[245 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-25; Open
3.42                       2 0.01         0.01
1.41                       2 0.01         0.02
1.42                       2 0.01         0.02
5.70                       2 0.01         0.03
6.98                       2 0.01         0.04
...                      ...  ...          ...
55.15                      1 0.00         0.98
57.64                      1 0.00         0.99
60.96                      1 0.00         0.99
97.79                      1 0.00         1.00
122.02                     1 0.00         1.00

[239 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-25; High
1.42                       3 0.01         0.01
8.59                       3 0.01         0.02
1.98                       2 0.01         0.03
1.23                       2 0.01         0.04
5.80                       2 0.01         0.05
...                      ...  ...          ...
56.31                      1 0.00         0.98
57.65                      1 0.00         0.99
62.85                      1 0.00         0.99
99.16                      1 0.00         1.00
123.06                     1 0.00         1.00

[236 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-25; Low
2.13                      2 0.01         0.01
1.77                      2 0.01         0.02
1.37                      2 0.01         0.02
6.87                      2 0.01         0.03
5.26                      2 0.01         0.04
...                     ...  ...          ...
54.75                     1 0.00         0.98
56.67                     1 0.00         0.99
60.46                     1 0.00         0.99
96.94                     1 0.00         1.00
117.33                    1 0.00         1.00

[239 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-25; Close
1.41                        2 0.01         0.01
1.90                        2 0.01         0.02
2.85                        2 0.01         0.02
8.30                        2 0.01         0.03
5.34                        2 0.01         0.04
...                       ...  ...          ...
54.93                       1 0.00         0.98
56.84                       1 0.00         0.99
60.62                       1 0.00         0.99
97.90                       1 0.00         1.00
120.20                      1 0.00         1.00

[237 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-25; Volume
303800                       2 0.01         0.01
3700                         1 0.00         0.01
7900                         1 0.00         0.02
9000                         1 0.00         0.02
2500                         1 0.00         0.02
...                        ...  ...          ...
36948900                     1 0.00         0.98
41440200                     1 0.00         0.99
47453300                     1 0.00         0.99
76158600                     1 0.00         1.00
105924100                    1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-25; Dividends
0.00                          245 1.00         1.00
0.06                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-25; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-25; HLC
1.39                      2 0.01         0.01
1.20                      2 0.01         0.02
28.13                     2 0.01         0.02
0.54                      1 0.00         0.03
0.26                      1 0.00         0.03
...                     ...  ...          ...
55.19                     1 0.00         0.98
57.05                     1 0.00         0.99
61.31                     1 0.00         0.99
98.00                     1 0.00         1.00
120.20                    1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-26; Open
1.91                       2 0.01         0.01
1.39                       2 0.01         0.02
1.41                       2 0.01         0.02
5.34                       2 0.01         0.03
5.95                       2 0.01         0.04
...                      ...  ...          ...
55.22                      1 0.00         0.98
57.20                      1 0.00         0.99
61.22                      1 0.00         0.99
98.54                      1 0.00         1.00
120.00                     1 0.00         1.00

[239 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-26; High
1.41                       3 0.01         0.01
1.14                       2 0.01         0.02
1.30                       2 0.01         0.03
1.44                       2 0.01         0.04
1.92                       2 0.01         0.04
...                      ...  ...          ...
55.52                      1 0.00         0.98
57.35                      1 0.00         0.99
62.49                      1 0.00         0.99
98.70                      1 0.00         1.00
122.04                     1 0.00         1.00

[236 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-26; Low
1.72                      2 0.01         0.01
1.31                      2 0.01         0.02
2.08                      2 0.01         0.02
7.20                      2 0.01         0.03
5.97                      2 0.01         0.04
...                     ...  ...          ...
54.59                     1 0.00         0.98
56.74                     1 0.00         0.99
60.71                     1 0.00         0.99
95.83                     1 0.00         1.00
119.03                    1 0.00         1.00

[238 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-26; Close
4.19                        3 0.01         0.01
1.10                        2 0.01         0.02
1.41                        2 0.01         0.03
0.81                        2 0.01         0.04
0.55                        1 0.00         0.04
...                       ...  ...          ...
54.59                       1 0.00         0.98
57.04                       1 0.00         0.99
61.45                       1 0.00         0.99
96.30                       1 0.00         1.00
120.64                      1 0.00         1.00

[241 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-26; Volume
1300                         1 0.00         0.00
6032                         1 0.00         0.01
6400                         1 0.00         0.01
13100                        1 0.00         0.02
15500                        1 0.00         0.02
...                        ...  ...          ...
40056600                     1 0.00         0.98
40355500                     1 0.00         0.99
51824900                     1 0.00         0.99
79612200                     1 0.00         1.00
134316800                    1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-26; Dividends
0.00                          244 0.99         0.99
0.03                            1 0.00         1.00
1.90                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-26; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-26; HLC
5.83                      2 0.01         0.01
0.26                      1 0.00         0.01
0.55                      1 0.00         0.02
0.69                      1 0.00         0.02
0.06                      1 0.00         0.02
...                     ...  ...          ...
54.90                     1 0.00         0.98
57.04                     1 0.00         0.99
61.55                     1 0.00         0.99
96.94                     1 0.00         1.00
120.57                    1 0.00         1.00

[245 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-27; Open
1.40                       3 0.01         0.01
1.10                       2 0.01         0.02
0.82                       2 0.01         0.03
2.09                       2 0.01         0.04
1.74                       2 0.01         0.04
...                      ...  ...          ...
54.33                      1 0.00         0.98
57.06                      1 0.00         0.99
64.21                      1 0.00         0.99
96.59                      1 0.00         1.00
120.64                     1 0.00         1.00

[235 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-27; High
2.20                       2 0.01         0.01
1.42                       2 0.01         0.02
7.45                       2 0.01         0.02
8.16                       2 0.01         0.03
5.48                       2 0.01         0.04
...                      ...  ...          ...
54.85                      1 0.00         0.98
57.84                      1 0.00         0.99
70.31                      1 0.00         0.99
97.10                      1 0.00         1.00
122.84                     1 0.00         1.00

[238 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-27; Low
1.10                      2 0.01         0.01
1.33                      2 0.01         0.02
2.09                      2 0.01         0.02
3.37                      2 0.01         0.03
1.72                      2 0.01         0.04
...                     ...  ...          ...
53.91                     1 0.00         0.98
56.84                     1 0.00         0.99
62.72                     1 0.00         0.99
95.57                     1 0.00         1.00
120.64                    1 0.00         1.00

[238 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-27; Close
1.11                        2 0.01         0.01
1.26                        2 0.01         0.02
1.36                        2 0.01         0.02
1.76                        2 0.01         0.03
5.06                        2 0.01         0.04
...                       ...  ...          ...
54.19                       1 0.00         0.98
57.17                       1 0.00         0.99
68.90                       1 0.00         0.99
95.82                       1 0.00         1.00
121.70                      1 0.00         1.00

[235 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-27; Volume
43500                        2 0.01         0.01
3900                         1 0.00         0.01
6000                         1 0.00         0.02
13000                        1 0.00         0.02
3600                         1 0.00         0.02
...                        ...  ...          ...
48084000                     1 0.00         0.98
53797700                     1 0.00         0.99
66169900                     1 0.00         0.99
96915200                     1 0.00         1.00
129693500                    1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-27; Dividends
0.00                          244 0.99         0.99
0.23                            2 0.01         1.00

                          Quantidade    %  % acumulado
2025-02-27; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-27; HLC
7.24                      2 0.01         0.01
0.26                      1 0.00         0.01
0.54                      1 0.00         0.02
0.68                      1 0.00         0.02
0.06                      1 0.00         0.02
...                     ...  ...          ...
54.31                     1 0.00         0.98
57.28                     1 0.00         0.99
67.31                     1 0.00         0.99
96.16                     1 0.00         1.00
121.73                    1 0.00         1.00

[245 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-28; Open
1.11                       3 0.01         0.01
1.39                       2 0.01         0.02
1.76                       2 0.01         0.03
4.07                       2 0.01         0.04
5.50                       2 0.01         0.04
...                      ...  ...          ...
53.84                      1 0.00         0.98
56.96                      1 0.00         0.99
68.03                      1 0.00         0.99
95.55                      1 0.00         1.00
123.01                     1 0.00         1.00

[236 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-02-28; High
1.41                       3 0.01         0.01
1.13                       2 0.01         0.02
1.27                       2 0.01         0.03
5.83                       2 0.01         0.04
7.00                       2 0.01         0.04
...                      ...  ...          ...
54.03                      1 0.00         0.98
57.28                      1 0.00         0.99
70.05                      1 0.00         0.99
96.34                      1 0.00         1.00
128.21                     1 0.00         1.00

[236 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-02-28; Low
10.91                     3 0.01         0.01
1.65                      2 0.01         0.02
5.20                      2 0.01         0.03
1.34                      2 0.01         0.04
5.66                      2 0.01         0.04
...                     ...  ...          ...
53.08                     1 0.00         0.98
56.05                     1 0.00         0.99
67.80                     1 0.00         0.99
94.37                     1 0.00         1.00
122.23                    1 0.00         1.00

[236 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-02-28; Close
1.98                        2 0.01         0.01
2.74                        2 0.01         0.02
3.12                        2 0.01         0.02
1.46                        2 0.01         0.03
1.35                        2 0.01         0.04
...                       ...  ...          ...
53.08                       1 0.00         0.98
56.31                       1 0.00         0.99
69.72                       1 0.00         0.99
94.98                       1 0.00         1.00
125.17                      1 0.00         1.00

[232 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-02-28; Volume
3800                         1 0.00         0.00
13400                        1 0.00         0.01
15600                        1 0.00         0.01
16952                        1 0.00         0.02
18200                        1 0.00         0.02
...                        ...  ...          ...
84387200                     1 0.00         0.98
91028700                     1 0.00         0.99
104972500                    1 0.00         0.99
226148900                    1 0.00         1.00
703389500                    1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-02-28; Dividends
0.00                          244 0.99         0.99
0.11                            1 0.00         1.00
0.19                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-02-28; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-02-28; HLC
1.68                      2 0.01         0.01
10.04                     2 0.01         0.02
0.54                      1 0.00         0.02
0.06                      1 0.00         0.02
0.76                      1 0.00         0.03
...                     ...  ...          ...
53.40                     1 0.00         0.98
56.55                     1 0.00         0.99
69.19                     1 0.00         0.99
95.23                     1 0.00         1.00
125.20                    1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-05; Open
5.68                       3 0.01         0.01
1.39                       2 0.01         0.02
2.74                       2 0.01         0.03
3.56                       2 0.01         0.04
1.24                       2 0.01         0.04
...                      ...  ...          ...
54.04                      1 0.00         0.98
56.19                      1 0.00         0.99
72.00                      1 0.00         0.99
94.80                      1 0.00         1.00
125.17                     1 0.00         1.00

[237 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-05; High
1.22                       2 0.01         0.01
1.72                       2 0.01         0.02
5.89                       2 0.01         0.02
5.17                       2 0.01         0.03
5.57                       2 0.01         0.04
...                      ...  ...          ...
54.11                      1 0.00         0.98
56.61                      1 0.00         0.99
76.15                      1 0.00         0.99
95.12                      1 0.00         1.00
132.04                     1 0.00         1.00

[239 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-05; Low
1.34                      3 0.01         0.01
1.13                      2 0.01         0.02
1.10                      2 0.01         0.03
4.98                      2 0.01         0.04
3.30                      2 0.01         0.04
...                     ...  ...          ...
53.31                     1 0.00         0.98
55.13                     1 0.00         0.99
71.61                     1 0.00         0.99
93.19                     1 0.00         1.00
123.59                    1 0.00         1.00

[237 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-05; Close
5.29                        3 0.01         0.01
1.37                        2 0.01         0.02
1.39                        2 0.01         0.03
1.23                        2 0.01         0.04
5.73                        2 0.01         0.04
...                       ...  ...          ...
53.50                       1 0.00         0.98
55.37                       1 0.00         0.99
75.85                       1 0.00         0.99
94.11                       1 0.00         1.00
126.29                      1 0.00         1.00

[233 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-05; Volume
4400                         1 0.00         0.00
10300                        1 0.00         0.01
11440                        1 0.00         0.01
11700                        1 0.00         0.02
11800                        1 0.00         0.02
...                        ...  ...          ...
41379800                     1 0.00         0.98
46942500                     1 0.00         0.99
48552000                     1 0.00         0.99
54086900                     1 0.00         1.00
77802900                     1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-05; Dividends
0.00                          241 0.98         0.98
0.02                            2 0.01         0.99
0.05                            2 0.01         1.00
0.30                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-05; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-05; HLC
1.69                      2 0.01         0.01
0.24                      1 0.00         0.01
0.52                      1 0.00         0.02
0.69                      1 0.00         0.02
0.06                      1 0.00         0.02
...                     ...  ...          ...
53.64                     1 0.00         0.98
55.70                     1 0.00         0.99
74.54                     1 0.00         0.99
94.14                     1 0.00         1.00
127.31                    1 0.00         1.00

[245 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-06; Open
1.04                       2 0.01         0.01
1.39                       2 0.01         0.02
1.67                       2 0.01         0.02
2.65                       2 0.01         0.03
5.25                       2 0.01         0.04
...                      ...  ...          ...
53.55                      1 0.00         0.98
55.64                      1 0.00         0.99
75.55                      1 0.00         0.99
94.69                      1 0.00         1.00
128.00                     1 0.00         1.00

[238 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-06; High
1.41                       3 0.01         0.01
5.47                       3 0.01         0.02
1.27                       2 0.01         0.03
0.86                       2 0.01         0.04
2.95                       2 0.01         0.05
...                      ...  ...          ...
54.40                      1 0.00         0.98
55.85                      1 0.00         0.99
76.37                      1 0.00         0.99
95.32                      1 0.00         1.00
139.34                     1 0.00         1.00

[237 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-06; Low
1.35                      2 0.01         0.01
2.60                      2 0.01         0.02
3.93                      2 0.01         0.02
5.33                      2 0.01         0.03
5.35                      2 0.01         0.04
...                     ...  ...          ...
53.46                     1 0.00         0.98
54.69                     1 0.00         0.99
74.09                     1 0.00         0.99
93.60                     1 0.00         1.00
125.27                    1 0.00         1.00

[239 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-06; Close
0.85                        2 0.01         0.01
1.15                        2 0.01         0.02
2.08                        2 0.01         0.02
1.78                        2 0.01         0.03
1.37                        2 0.01         0.04
...                       ...  ...          ...
54.09                       1 0.00         0.98
55.16                       1 0.00         0.99
74.72                       1 0.00         0.99
94.16                       1 0.00         1.00
127.50                      1 0.00         1.00

[241 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-06; Volume
18800                        2 0.01         0.01
75000                        2 0.01         0.02
8500                         1 0.00         0.02
2600                         1 0.00         0.02
8900                         1 0.00         0.03
...                        ...  ...          ...
40524500                     1 0.00         0.98
44187500                     1 0.00         0.99
47585600                     1 0.00         0.99
47749600                     1 0.00         1.00
66517100                     1 0.00         1.00

[244 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-06; Dividends
0.00                          238 0.97         0.97
0.01                            1 0.00         0.97
0.02                            1 0.00         0.98
0.02                            1 0.00         0.98
0.04                            1 0.00         0.98
0.05                            1 0.00         0.99
0.10                            1 0.00         0.99
0.27                            1 0.00         1.00
0.48                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-06; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-06; HLC
3.66                      2 0.01         0.01
9.18                      2 0.01         0.02
0.51                      1 0.00         0.02
0.06                      1 0.00         0.02
0.78                      1 0.00         0.03
...                     ...  ...          ...
53.98                     1 0.00         0.98
55.23                     1 0.00         0.99
75.06                     1 0.00         0.99
94.36                     1 0.00         1.00
130.70                    1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-07; Open
5.90                       3 0.01         0.01
2.08                       2 0.01         0.02
5.39                       2 0.01         0.03
3.65                       2 0.01         0.04
1.36                       2 0.01         0.04
...                      ...  ...          ...
53.88                      1 0.00         0.98
54.82                      1 0.00         0.99
74.57                      1 0.00         0.99
93.20                      1 0.00         1.00
129.15                     1 0.00         1.00

[237 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-07; High
1.06                       2 0.01         0.01
0.91                       2 0.01         0.02
1.43                       2 0.01         0.02
1.45                       2 0.01         0.03
5.97                       2 0.01         0.04
...                      ...  ...          ...
55.20                      1 0.00         0.98
55.65                      1 0.00         0.99
74.90                      1 0.00         0.99
96.82                      1 0.00         1.00
134.60                     1 0.00         1.00

[234 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-07; Low
5.07                      3 0.01         0.01
1.37                      2 0.01         0.02
1.17                      2 0.01         0.03
5.23                      2 0.01         0.04
0.86                      2 0.01         0.04
...                     ...  ...          ...
53.46                     1 0.00         0.98
54.45                     1 0.00         0.99
72.80                     1 0.00         0.99
92.95                     1 0.00         1.00
128.31                    1 0.00         1.00

[237 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-07; Close
1.40                        2 0.01         0.01
2.69                        2 0.01         0.02
1.87                        2 0.01         0.02
1.52                        2 0.01         0.03
1.16                        2 0.01         0.04
...                       ...  ...          ...
54.88                       1 0.00         0.98
55.34                       1 0.00         0.99
73.68                       1 0.00         0.99
96.19                       1 0.00         1.00
132.88                      1 0.00         1.00

[232 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-07; Volume
8200                         1 0.00         0.00
9400                         1 0.00         0.01
9600                         1 0.00         0.01
11500                        1 0.00         0.02
13500                        1 0.00         0.02
...                        ...  ...          ...
30190400                     1 0.00         0.98
36134200                     1 0.00         0.99
40884800                     1 0.00         0.99
41638200                     1 0.00         1.00
97225000                     1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-07; Dividends
0.00                          244 0.99         0.99
0.19                            1 0.00         1.00
0.47                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-07; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-07; HLC
0.06                      1 0.00         0.00
0.25                      1 0.00         0.01
0.53                      1 0.00         0.01
0.68                      1 0.00         0.02
0.78                      1 0.00         0.02
...                     ...  ...          ...
54.51                     1 0.00         0.98
55.15                     1 0.00         0.99
73.79                     1 0.00         0.99
95.32                     1 0.00         1.00
131.93                    1 0.00         1.00

[246 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-10; Open
1.18                       2 0.01         0.01
1.85                       2 0.01         0.02
1.20                       2 0.01         0.02
5.23                       2 0.01         0.03
4.15                       2 0.01         0.04
...                      ...  ...          ...
54.23                      1 0.00         0.98
55.01                      1 0.00         0.99
73.16                      1 0.00         0.99
95.58                      1 0.00         1.00
132.88                     1 0.00         1.00

[237 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-10; High
1.24                       2 0.01         0.01
1.47                       2 0.01         0.02
5.26                       2 0.01         0.02
3.89                       2 0.01         0.03
3.90                       2 0.01         0.04
...                      ...  ...          ...
54.55                      1 0.00         0.98
55.69                      1 0.00         0.99
74.82                      1 0.00         0.99
97.38                      1 0.00         1.00
137.00                     1 0.00         1.00

[241 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-10; Low
1.36                      3 0.01         0.01
1.14                      3 0.01         0.02
1.78                      2 0.01         0.03
5.14                      2 0.01         0.04
5.80                      2 0.01         0.05
...                     ...  ...          ...
53.25                     1 0.00         0.98
54.68                     1 0.00         0.99
72.92                     1 0.00         0.99
95.34                     1 0.00         1.00
131.65                    1 0.00         1.00

[232 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-10; Close
1.07                        2 0.01         0.01
1.18                        2 0.01         0.02
1.19                        2 0.01         0.02
0.88                        2 0.01         0.03
1.82                        2 0.01         0.04
...                       ...  ...          ...
53.99                       1 0.00         0.98
55.59                       1 0.00         0.99
74.25                       1 0.00         0.99
96.84                       1 0.00         1.00
134.95                      1 0.00         1.00

[236 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-10; Volume
126400                       2 0.01         0.01
4300                         1 0.00         0.01
6700                         1 0.00         0.02
7600                         1 0.00         0.02
800                          1 0.00         0.02
...                        ...  ...          ...
35037200                     1 0.00         0.98
39247100                     1 0.00         0.99
42234700                     1 0.00         0.99
50198700                     1 0.00         1.00
78062300                     1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-10; Dividends
0.00                          245 1.00         1.00
2.14                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-10; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-10; HLC
4.15                      2 0.01         0.01
0.25                      1 0.00         0.01
0.52                      1 0.00         0.02
0.69                      1 0.00         0.02
0.06                      1 0.00         0.02
...                     ...  ...          ...
53.93                     1 0.00         0.98
55.32                     1 0.00         0.99
74.00                     1 0.00         0.99
96.52                     1 0.00         1.00
134.53                    1 0.00         1.00

[245 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-11; Open
0.91                       2 0.01         0.01
1.40                       2 0.01         0.02
1.41                       2 0.01         0.02
1.21                       2 0.01         0.03
1.75                       2 0.01         0.04
...                      ...  ...          ...
54.08                      1 0.00         0.98
55.68                      1 0.00         0.99
74.35                      1 0.00         0.99
96.47                      1 0.00         1.00
135.04                     1 0.00         1.00

[236 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-11; High
1.76                       2 0.01         0.01
1.30                       2 0.01         0.02
2.10                       2 0.01         0.02
1.55                       2 0.01         0.03
1.21                       2 0.01         0.04
...                      ...  ...          ...
54.72                      1 0.00         0.98
56.10                      1 0.00         0.99
74.35                      1 0.00         0.99
96.80                      1 0.00         1.00
136.46                     1 0.00         1.00

[232 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-11; Low
1.35                      3 0.01         0.01
2.67                      2 0.01         0.02
1.15                      2 0.01         0.03
1.75                      2 0.01         0.04
5.70                      2 0.01         0.04
...                     ...  ...          ...
53.41                     1 0.00         0.98
54.74                     1 0.00         0.99
72.75                     1 0.00         0.99
94.96                     1 0.00         1.00
133.00                    1 0.00         1.00

[236 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-11; Close
1.19                        2 0.01         0.01
1.40                        2 0.01         0.02
1.37                        2 0.01         0.02
3.77                        2 0.01         0.03
5.27                        2 0.01         0.04
...                       ...  ...          ...
54.44                       1 0.00         0.98
55.13                       1 0.00         0.99
73.22                       1 0.00         0.99
95.94                       1 0.00         1.00
133.87                      1 0.00         1.00

[240 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-11; Volume
1500                         1 0.00         0.00
3500                         1 0.00         0.01
7200                         1 0.00         0.01
7700                         1 0.00         0.02
12300                        1 0.00         0.02
...                        ...  ...          ...
32659900                     1 0.00         0.98
35459700                     1 0.00         0.99
43087500                     1 0.00         0.99
47997200                     1 0.00         1.00
59563500                     1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-11; Dividends
0.00                          245 1.00         1.00
0.19                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-11; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-11; HLC
1.18                      2 0.01         0.01
3.78                      2 0.01         0.02
0.51                      1 0.00         0.02
0.06                      1 0.00         0.02
0.69                      1 0.00         0.03
...                     ...  ...          ...
54.19                     1 0.00         0.98
55.32                     1 0.00         0.99
73.44                     1 0.00         0.99
95.90                     1 0.00         1.00
134.44                    1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-12; Open
1.18                       2 0.01         0.01
2.76                       2 0.01         0.02
3.35                       2 0.01         0.02
6.14                       2 0.01         0.03
4.00                       2 0.01         0.04
...                      ...  ...          ...
54.50                      1 0.00         0.98
55.15                      1 0.00         0.99
73.13                      1 0.00         0.99
95.92                      1 0.00         1.00
133.30                     1 0.00         1.00

[238 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-12; High
1.40                       3 0.01         0.01
1.19                       2 0.01         0.02
0.90                       2 0.01         0.03
1.20                       2 0.01         0.04
4.41                       2 0.01         0.04
...                      ...  ...          ...
54.50                      1 0.00         0.98
55.35                      1 0.00         0.99
74.15                      1 0.00         0.99
97.24                      1 0.00         1.00
136.50                     1 0.00         1.00

[236 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-12; Low
1.17                      3 0.01         0.01
0.84                      2 0.01         0.02
1.23                      2 0.01         0.03
1.35                      2 0.01         0.04
1.16                      2 0.01         0.04
...                     ...  ...          ...
53.15                     1 0.00         0.98
54.48                     1 0.00         0.99
72.41                     1 0.00         0.99
95.29                     1 0.00         1.00
131.04                    1 0.00         1.00

[227 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-12; Close
1.86                        3 0.01         0.01
1.19                        2 0.01         0.02
1.18                        2 0.01         0.03
3.38                        2 0.01         0.04
6.09                        2 0.01         0.04
...                       ...  ...          ...
53.76                       1 0.00         0.98
54.75                       1 0.00         0.99
72.96                       1 0.00         0.99
95.77                       1 0.00         1.00
131.04                      1 0.00         1.00

[236 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-12; Volume
74500                        2 0.01         0.01
5300                         1 0.00         0.01
6656                         1 0.00         0.02
7100                         1 0.00         0.02
1900                         1 0.00         0.02
...                        ...  ...          ...
31708500                     1 0.00         0.98
38219900                     1 0.00         0.99
39894000                     1 0.00         0.99
46499100                     1 0.00         1.00
54749900                     1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-12; Dividends
0.00                          244 0.99         0.99
0.07                            1 0.00         1.00
0.67                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-12; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-12; HLC
1.25                      2 0.01         0.01
5.23                      2 0.01         0.02
0.51                      1 0.00         0.02
0.06                      1 0.00         0.02
0.68                      1 0.00         0.03
...                     ...  ...          ...
53.80                     1 0.00         0.98
54.86                     1 0.00         0.99
73.17                     1 0.00         0.99
96.10                     1 0.00         1.00
132.86                    1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-13; Open
1.17                       3 0.01         0.01
0.87                       2 0.01         0.02
1.00                       2 0.01         0.03
3.38                       2 0.01         0.04
1.84                       2 0.01         0.04
...                      ...  ...          ...
53.88                      1 0.00         0.98
54.70                      1 0.00         0.99
73.00                      1 0.00         0.99
96.33                      1 0.00         1.00
131.04                     1 0.00         1.00

[235 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-13; High
7.15                       3 0.01         0.01
0.89                       2 0.01         0.02
1.62                       2 0.01         0.03
1.38                       2 0.01         0.04
3.42                       2 0.01         0.04
...                      ...  ...          ...
54.86                      1 0.00         0.98
55.16                      1 0.00         0.99
74.50                      1 0.00         0.99
98.00                      1 0.00         1.00
131.31                     1 0.00         1.00

[234 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-13; Low
1.12                      2 0.01         0.01
1.84                      2 0.01         0.02
5.16                      2 0.01         0.02
5.18                      2 0.01         0.03
7.39                      2 0.01         0.04
...                     ...  ...          ...
53.70                     1 0.00         0.98
54.15                     1 0.00         0.99
72.83                     1 0.00         0.99
94.12                     1 0.00         1.00
125.50                    1 0.00         1.00

[240 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-13; Close
1.19                        2 0.01         0.01
1.16                        2 0.01         0.02
1.18                        2 0.01         0.02
1.61                        2 0.01         0.03
5.86                        2 0.01         0.04
...                       ...  ...          ...
54.31                       1 0.00         0.98
54.50                       1 0.00         0.99
73.85                       1 0.00         0.99
97.79                       1 0.00         1.00
130.99                      1 0.00         1.00

[240 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-13; Volume
500                          1 0.00         0.00
8400                         1 0.00         0.01
9600                         1 0.00         0.01
10500                        1 0.00         0.02
10800                        1 0.00         0.02
...                        ...  ...          ...
35174100                     1 0.00         0.98
35316500                     1 0.00         0.99
63416600                     1 0.00         0.99
111595000                    1 0.00         1.00
154407600                    1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-13; Dividends
0                             246 1.00         1.00

                          Quantidade    %  % acumulado
2025-03-13; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-13; HLC
1.19                      2 0.01         0.01
0.25                      1 0.00         0.01
0.51                      1 0.00         0.02
0.72                      1 0.00         0.02
0.07                      1 0.00         0.02
...                     ...  ...          ...
54.44                     1 0.00         0.98
54.45                     1 0.00         0.99
73.73                     1 0.00         0.99
96.64                     1 0.00         1.00
129.27                    1 0.00         1.00

[245 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-14; Open
1.63                       2 0.01         0.01
2.70                       2 0.01         0.02
5.43                       2 0.01         0.02
5.29                       2 0.01         0.03
3.88                       2 0.01         0.04
...                      ...  ...          ...
54.55                      1 0.00         0.98
55.20                      1 0.00         0.99
74.55                      1 0.00         0.99
98.83                      1 0.00         1.00
132.48                     1 0.00         1.00

[237 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-14; High
0.87                       2 0.01         0.01
1.22                       2 0.01         0.02
5.60                       2 0.01         0.02
4.05                       2 0.01         0.03
13.84                      2 0.01         0.04
...                      ...  ...          ...
54.68                      1 0.00         0.98
56.41                      1 0.00         0.99
76.13                      1 0.00         0.99
99.38                      1 0.00         1.00
132.48                     1 0.00         1.00

[240 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-14; Low
6.88                      3 0.01         0.01
0.85                      2 0.01         0.02
2.17                      2 0.01         0.03
1.38                      2 0.01         0.04
1.62                      2 0.01         0.04
...                     ...  ...          ...
53.97                     1 0.00         0.98
55.16                     1 0.00         0.99
73.69                     1 0.00         0.99
97.00                     1 0.00         1.00
128.33                    1 0.00         1.00

[234 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-14; Close
1.21                        2 0.01         0.01
1.19                        2 0.01         0.02
5.44                        2 0.01         0.02
5.82                        2 0.01         0.03
21.50                       2 0.01         0.04
...                       ...  ...          ...
54.14                       1 0.00         0.98
56.29                       1 0.00         0.99
74.88                       1 0.00         0.99
99.30                       1 0.00         1.00
130.44                      1 0.00         1.00

[239 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-14; Volume
3500                         1 0.00         0.00
4600                         1 0.00         0.01
4700                         1 0.00         0.01
6000                         1 0.00         0.02
11500                        1 0.00         0.02
...                        ...  ...          ...
65704800                     1 0.00         0.98
102081900                    1 0.00         0.99
105449100                    1 0.00         0.99
111755000                    1 0.00         1.00
126026800                    1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-14; Dividends
0                             246 1.00         1.00

                          Quantidade    %  % acumulado
2025-03-14; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-14; HLC
1.20                      2 0.01         0.01
1.18                      2 0.01         0.02
12.57                     2 0.01         0.02
0.51                      1 0.00         0.03
0.27                      1 0.00         0.03
...                     ...  ...          ...
54.26                     1 0.00         0.98
55.95                     1 0.00         0.99
74.90                     1 0.00         0.99
98.56                     1 0.00         1.00
130.42                    1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-17; Open
1.20                       3 0.01         0.01
1.45                       2 0.01         0.02
1.18                       2 0.01         0.03
1.73                       2 0.01         0.04
2.18                       2 0.01         0.04
...                      ...  ...          ...
54.23                      1 0.00         0.98
56.29                      1 0.00         0.99
75.44                      1 0.00         0.99
99.79                      1 0.00         1.00
131.51                     1 0.00         1.00

[232 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-17; High
1.54                       2 0.01         0.01
1.44                       2 0.01         0.02
5.84                       2 0.01         0.02
7.95                       2 0.01         0.03
7.55                       2 0.01         0.04
...                      ...  ...          ...
55.76                      1 0.00         0.98
57.24                      1 0.00         0.99
78.18                      1 0.00         0.99
100.80                     1 0.00         1.00
131.63                     1 0.00         1.00

[238 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-17; Low
0.86                      3 0.01         0.01
1.17                      2 0.01         0.02
1.18                      2 0.01         0.03
2.15                      2 0.01         0.04
5.33                      2 0.01         0.04
...                     ...  ...          ...
54.02                     1 0.00         0.98
56.14                     1 0.00         0.99
74.76                     1 0.00         0.99
98.76                     1 0.00         1.00
127.00                    1 0.00         1.00

[237 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-17; Close
0.91                        2 0.01         0.01
1.20                        2 0.01         0.02
1.76                        2 0.01         0.02
6.40                        2 0.01         0.03
4.08                        2 0.01         0.04
...                       ...  ...          ...
54.66                       1 0.00         0.98
57.10                       1 0.00         0.99
77.41                       1 0.00         0.99
100.60                      1 0.00         1.00
127.00                      1 0.00         1.00

[237 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-17; Volume
2000                         2 0.01         0.01
477400                       2 0.01         0.02
7200                         1 0.00         0.02
6800                         1 0.00         0.02
11200                        1 0.00         0.03
...                        ...  ...          ...
41312900                     1 0.00         0.98
49697100                     1 0.00         0.99
65684100                     1 0.00         0.99
87512900                     1 0.00         1.00
89758000                     1 0.00         1.00

[244 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-17; Dividends
0.00                          244 0.99         0.99
0.13                            1 0.00         1.00
0.22                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-17; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-17; HLC
30.00                     2 0.01         0.01
9.40                      2 0.01         0.02
0.06                      1 0.00         0.02
0.29                      1 0.00         0.02
0.88                      1 0.00         0.03
...                     ...  ...          ...
54.55                     1 0.00         0.98
56.83                     1 0.00         0.99
76.78                     1 0.00         0.99
100.05                    1 0.00         1.00
128.54                    1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-18; Open
12.12                      3 0.01         0.01
1.22                       2 0.01         0.02
2.20                       2 0.01         0.03
1.20                       2 0.01         0.04
3.56                       2 0.01         0.04
...                      ...  ...          ...
55.03                      1 0.00         0.98
57.20                      1 0.00         0.99
77.03                      1 0.00         0.99
100.60                     1 0.00         1.00
129.97                     1 0.00         1.00

[233 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-18; High
1.84                       3 0.01         0.01
5.92                       2 0.01         0.02
5.35                       2 0.01         0.03
5.72                       2 0.01         0.04
13.63                      2 0.01         0.04
...                      ...  ...          ...
56.39                      1 0.00         0.98
57.56                      1 0.00         0.99
78.38                      1 0.00         0.99
100.81                     1 0.00         1.00
139.68                     1 0.00         1.00

[240 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-18; Low
0.86                      3 0.01         0.01
1.21                      2 0.01         0.02
1.20                      2 0.01         0.03
1.39                      2 0.01         0.04
7.36                      2 0.01         0.04
...                     ...  ...          ...
54.20                     1 0.00         0.98
56.62                     1 0.00         0.99
77.03                     1 0.00         0.99
99.46                     1 0.00         1.00
127.00                    1 0.00         1.00

[236 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-18; Close
1.23                        3 0.01         0.01
1.83                        3 0.01         0.02
0.92                        2 0.01         0.03
1.48                        2 0.01         0.04
4.05                        2 0.01         0.05
...                       ...  ...          ...
55.01                       1 0.00         0.98
57.52                       1 0.00         0.99
78.03                       1 0.00         0.99
100.27                      1 0.00         1.00
130.53                      1 0.00         1.00

[237 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-18; Volume
623400                       2 0.01         0.01
3700                         1 0.00         0.01
5500                         1 0.00         0.02
5600                         1 0.00         0.02
3200                         1 0.00         0.02
...                        ...  ...          ...
41377000                     1 0.00         0.98
55635800                     1 0.00         0.99
112067000                    1 0.00         0.99
144028500                    1 0.00         1.00
160199000                    1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-18; Dividends
0.00                          243 0.99         0.99
0.01                            1 0.00         0.99
0.04                            1 0.00         1.00
0.18                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-18; Stock Splits
0.00                             244 0.99         0.99
1.10                               2 0.01         1.00

                 Quantidade    %  % acumulado
2025-03-18; HLC
1.24                      2 0.01         0.01
7.70                      2 0.01         0.02
3.93                      2 0.01         0.02
0.57                      1 0.00         0.03
0.73                      1 0.00         0.03
...                     ...  ...          ...
54.74                     1 0.00         0.98
57.23                     1 0.00         0.99
77.81                     1 0.00         0.99
100.18                    1 0.00         1.00
132.40                    1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-19; Open
1.83                       3 0.01         0.01
1.22                       2 0.01         0.02
1.41                       2 0.01         0.03
1.05                       2 0.01         0.04
5.50                       2 0.01         0.04
...                      ...  ...          ...
55.20                      1 0.00         0.98
57.35                      1 0.00         0.99
78.20                      1 0.00         0.99
100.99                     1 0.00         1.00
132.78                     1 0.00         1.00

[238 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-19; High
1.24                       2 0.01         0.01
1.06                       2 0.01         0.02
1.31                       2 0.01         0.02
1.43                       2 0.01         0.03
5.62                       2 0.01         0.04
...                      ...  ...          ...
56.17                      1 0.00         0.98
57.55                      1 0.00         0.99
79.83                      1 0.00         0.99
103.25                     1 0.00         1.00
132.78                     1 0.00         1.00

[235 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-19; Low
0.97                      2 0.01         0.01
0.90                      2 0.01         0.02
1.22                      2 0.01         0.02
2.20                      2 0.01         0.03
1.40                      2 0.01         0.04
...                     ...  ...          ...
54.80                     1 0.00         0.98
56.85                     1 0.00         0.99
77.97                     1 0.00         0.99
100.03                    1 0.00         1.00
123.01                    1 0.00         1.00

[239 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-19; Close
5.94                        3 0.01         0.01
1.32                        2 0.01         0.02
5.51                        2 0.01         0.03
1.41                        2 0.01         0.04
8.30                        2 0.01         0.04
...                       ...  ...          ...
55.50                       1 0.00         0.98
57.42                       1 0.00         0.99
79.29                       1 0.00         0.99
102.65                      1 0.00         1.00
124.27                      1 0.00         1.00

[236 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-19; Volume
198500                       2 0.01         0.01
391600                       2 0.01         0.02
5000                         1 0.00         0.02
3800                         1 0.00         0.02
9100                         1 0.00         0.03
...                        ...  ...          ...
49304200                     1 0.00         0.98
50241400                     1 0.00         0.99
51574700                     1 0.00         0.99
58590200                     1 0.00         1.00
202496800                    1 0.00         1.00

[244 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-19; Dividends
0.00                          244 0.99         0.99
0.12                            1 0.00         1.00
2.30                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-19; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-19; HLC
1.26                      2 0.01         0.01
0.29                      1 0.00         0.01
0.55                      1 0.00         0.02
0.74                      1 0.00         0.02
0.08                      1 0.00         0.02
...                     ...  ...          ...
55.27                     1 0.00         0.98
57.27                     1 0.00         0.99
79.03                     1 0.00         0.99
101.98                    1 0.00         1.00
126.69                    1 0.00         1.00

[245 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-20; Open
1.02                       2 0.01         0.01
0.90                       2 0.01         0.02
1.41                       2 0.01         0.02
1.40                       2 0.01         0.03
5.25                       2 0.01         0.04
...                      ...  ...          ...
55.50                      1 0.00         0.98
57.04                      1 0.00         0.99
79.30                      1 0.00         0.99
102.63                     1 0.00         1.00
123.00                     1 0.00         1.00

[240 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-20; High
1.26                       2 0.01         0.01
0.94                       2 0.01         0.02
1.35                       2 0.01         0.02
1.42                       2 0.01         0.03
1.43                       2 0.01         0.04
...                      ...  ...          ...
56.27                      1 0.00         0.98
57.49                      1 0.00         0.99
79.33                      1 0.00         0.99
103.07                     1 0.00         1.00
123.99                     1 0.00         1.00

[236 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-20; Low
0.90                      2 0.01         0.01
1.23                      2 0.01         0.02
5.86                      2 0.01         0.02
6.30                      2 0.01         0.03
7.75                      2 0.01         0.04
...                     ...  ...          ...
54.76                     1 0.00         0.98
56.78                     1 0.00         0.99
72.72                     1 0.00         0.99
101.44                    1 0.00         1.00
119.21                    1 0.00         1.00

[238 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-20; Close
11.86                       3 0.01         0.01
1.26                        2 0.01         0.02
0.94                        2 0.01         0.03
7.80                        2 0.01         0.04
5.57                        2 0.01         0.04
...                       ...  ...          ...
55.84                       1 0.00         0.98
57.24                       1 0.00         0.99
73.96                       1 0.00         0.99
101.93                      1 0.00         1.00
122.00                      1 0.00         1.00

[239 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-20; Volume
1200                         1 0.00         0.00
1800                         1 0.00         0.01
2500                         1 0.00         0.01
10400                        1 0.00         0.02
12300                        1 0.00         0.02
...                        ...  ...          ...
34125100                     1 0.00         0.98
34793900                     1 0.00         0.99
42754900                     1 0.00         0.99
46921900                     1 0.00         1.00
525875200                    1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-20; Dividends
0                             246 1.00         1.00

                          Quantidade    %  % acumulado
2025-03-20; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-20; HLC
1.40                      2 0.01         0.01
1.90                      2 0.01         0.02
10.54                     2 0.01         0.02
0.55                      1 0.00         0.03
0.74                      1 0.00         0.03
...                     ...  ...          ...
55.62                     1 0.00         0.98
57.17                     1 0.00         0.99
75.34                     1 0.00         0.99
102.15                    1 0.00         1.00
121.73                    1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-21; Open
1.27                       2 0.01         0.01
1.42                       2 0.01         0.02
5.69                       2 0.01         0.02
5.60                       2 0.01         0.03
3.82                       2 0.01         0.04
...                      ...  ...          ...
56.04                      1 0.00         0.98
56.95                      1 0.00         0.99
73.78                      1 0.00         0.99
102.34                     1 0.00         1.00
122.35                     1 0.00         1.00

[237 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-21; High
1.42                       2 0.01         0.01
1.46                       2 0.01         0.02
1.47                       2 0.01         0.02
1.30                       2 0.01         0.03
1.54                       2 0.01         0.04
...                      ...  ...          ...
56.16                      1 0.00         0.98
57.45                      1 0.00         0.99
75.99                      1 0.00         0.99
102.34                     1 0.00         1.00
125.68                     1 0.00         1.00

[236 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-21; Low
1.04                      2 0.01         0.01
1.06                      2 0.01         0.02
1.47                      2 0.01         0.02
3.50                      2 0.01         0.03
5.79                      2 0.01         0.04
...                     ...  ...          ...
54.26                     1 0.00         0.98
56.83                     1 0.00         0.99
73.23                     1 0.00         0.99
100.01                    1 0.00         1.00
120.33                    1 0.00         1.00

[236 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-21; Close
1.10                        2 0.01         0.01
1.08                        2 0.01         0.02
1.27                        2 0.01         0.02
5.63                        2 0.01         0.03
3.90                        2 0.01         0.04
...                       ...  ...          ...
54.35                       1 0.00         0.98
57.45                       1 0.00         0.99
74.76                       1 0.00         0.99
101.35                      1 0.00         1.00
122.23                      1 0.00         1.00

[237 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-21; Volume
261000                       2 0.01         0.01
4300                         1 0.00         0.01
4700                         1 0.00         0.02
5700                         1 0.00         0.02
3700                         1 0.00         0.02
...                        ...  ...          ...
56803000                     1 0.00         0.98
61175700                     1 0.00         0.99
66960300                     1 0.00         0.99
74318800                     1 0.00         1.00
104525400                    1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-21; Dividends
0.00                          245 1.00         1.00
0.14                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-21; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-21; HLC
5.67                      2 0.01         0.01
0.28                      1 0.00         0.01
0.55                      1 0.00         0.02
0.72                      1 0.00         0.02
0.08                      1 0.00         0.02
...                     ...  ...          ...
54.92                     1 0.00         0.98
57.24                     1 0.00         0.99
74.66                     1 0.00         0.99
101.23                    1 0.00         1.00
122.75                    1 0.00         1.00

[245 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-24; Open
3.62                       3 0.01         0.01
1.12                       2 0.01         0.02
7.56                       2 0.01         0.03
5.65                       2 0.01         0.04
5.07                       2 0.01         0.04
...                      ...  ...          ...
54.46                      1 0.00         0.98
57.95                      1 0.00         0.99
74.75                      1 0.00         0.99
101.80                     1 0.00         1.00
124.80                     1 0.00         1.00

[238 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-24; High
2.20                       2 0.01         0.01
3.66                       2 0.01         0.02
5.10                       2 0.01         0.02
5.96                       2 0.01         0.03
14.11                      2 0.01         0.04
...                      ...  ...          ...
54.77                      1 0.00         0.98
58.24                      1 0.00         0.99
74.85                      1 0.00         0.99
101.80                     1 0.00         1.00
124.96                     1 0.00         1.00

[238 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-24; Low
1.03                      2 0.01         0.01
1.11                      2 0.01         0.02
3.58                      2 0.01         0.02
1.43                      2 0.01         0.03
1.44                      2 0.01         0.04
...                     ...  ...          ...
54.01                     1 0.00         0.98
56.96                     1 0.00         0.99
70.50                     1 0.00         0.99
98.62                     1 0.00         1.00
121.00                    1 0.00         1.00

[237 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-24; Close
2.03                        2 0.01         0.01
1.45                        2 0.01         0.02
2.21                        2 0.01         0.02
5.57                        2 0.01         0.03
4.06                        2 0.01         0.04
...                       ...  ...          ...
54.13                       1 0.00         0.98
57.15                       1 0.00         0.99
71.25                       1 0.00         0.99
98.80                       1 0.00         1.00
121.00                      1 0.00         1.00

[238 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-24; Volume
5600                         2 0.01         0.01
65400                        2 0.01         0.02
256700                       2 0.01         0.02
6600                         1 0.00         0.03
12376                        1 0.00         0.03
...                        ...  ...          ...
38966100                     1 0.00         0.98
40560200                     1 0.00         0.99
44562300                     1 0.00         0.99
63575900                     1 0.00         1.00
72486211                     1 0.00         1.00

[243 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-24; Dividends
0.00                          240 0.98         0.98
0.04                            1 0.00         0.98
0.06                            1 0.00         0.98
0.08                            1 0.00         0.99
0.11                            1 0.00         0.99
0.28                            1 0.00         1.00
0.31                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-24; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-24; HLC
5.52                      2 0.01         0.01
0.27                      1 0.00         0.01
0.53                      1 0.00         0.02
0.70                      1 0.00         0.02
0.07                      1 0.00         0.02
...                     ...  ...          ...
54.30                     1 0.00         0.98
57.45                     1 0.00         0.99
72.20                     1 0.00         0.99
99.74                     1 0.00         1.00
122.32                    1 0.00         1.00

[245 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-25; Open
3.16                       2 0.01         0.01
2.38                       2 0.01         0.02
2.23                       2 0.01         0.02
2.17                       2 0.01         0.03
1.45                       2 0.01         0.04
...                      ...  ...          ...
54.27                      1 0.00         0.98
57.32                      1 0.00         0.99
71.62                      1 0.00         0.99
100.40                     1 0.00         1.00
122.21                     1 0.00         1.00

[231 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-25; High
2.28                       2 0.01         0.01
1.50                       2 0.01         0.02
5.05                       2 0.01         0.02
5.42                       2 0.01         0.03
4.00                       2 0.01         0.04
...                      ...  ...          ...
55.00                      1 0.00         0.98
57.75                      1 0.00         0.99
72.00                      1 0.00         0.99
103.50                     1 0.00         1.00
122.98                     1 0.00         1.00

[238 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-25; Low
0.97                      2 0.01         0.01
1.43                      2 0.01         0.02
2.15                      2 0.01         0.02
2.38                      2 0.01         0.03
5.18                      2 0.01         0.04
...                     ...  ...          ...
53.63                     1 0.00         0.98
57.11                     1 0.00         0.99
69.40                     1 0.00         0.99
100.21                    1 0.00         1.00
118.00                    1 0.00         1.00

[234 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-25; Close
1.14                        2 0.01         0.01
1.00                        2 0.01         0.02
1.45                        2 0.01         0.02
1.46                        2 0.01         0.03
2.23                        2 0.01         0.04
...                       ...  ...          ...
54.22                       1 0.00         0.98
57.34                       1 0.00         0.99
69.74                       1 0.00         0.99
102.10                      1 0.00         1.00
120.55                      1 0.00         1.00

[236 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-25; Volume
153600                       2 0.01         0.01
610400                       2 0.01         0.02
4700                         1 0.00         0.02
1700                         1 0.00         0.02
7592                         1 0.00         0.03
...                        ...  ...          ...
40946400                     1 0.00         0.98
57871800                     1 0.00         0.99
63764400                     1 0.00         0.99
80367711                     1 0.00         1.00
88230000                     1 0.00         1.00

[244 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-25; Dividends
0.00                          243 0.99         0.99
0.07                            1 0.00         0.99
0.12                            1 0.00         1.00
0.14                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-25; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-25; HLC
1.50                      2 0.01         0.01
7.73                      2 0.01         0.02
0.52                      1 0.00         0.02
0.07                      1 0.00         0.02
0.89                      1 0.00         0.03
...                     ...  ...          ...
54.28                     1 0.00         0.98
57.40                     1 0.00         0.99
70.38                     1 0.00         0.99
101.94                    1 0.00         1.00
120.51                    1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-26; Open
1.10                       2 0.01         0.01
1.01                       2 0.01         0.02
1.46                       2 0.01         0.02
5.90                       2 0.01         0.03
5.40                       2 0.01         0.04
...                      ...  ...          ...
54.22                      1 0.00         0.98
57.40                      1 0.00         0.99
69.98                      1 0.00         0.99
102.58                     1 0.00         1.00
119.82                     1 0.00         1.00

[237 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-26; High
5.55                       2 0.01         0.01
5.32                       2 0.01         0.02
7.33                       2 0.01         0.02
12.25                      2 0.01         0.03
10.33                      2 0.01         0.04
...                      ...  ...          ...
54.80                      1 0.00         0.98
58.04                      1 0.00         0.99
70.44                      1 0.00         0.99
102.60                     1 0.00         1.00
120.87                     1 0.00         1.00

[241 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-26; Low
0.99                      2 0.01         0.01
2.18                      2 0.01         0.02
1.86                      2 0.01         0.02
6.98                      2 0.01         0.03
7.89                      2 0.01         0.04
...                     ...  ...          ...
53.11                     1 0.00         0.98
57.39                     1 0.00         0.99
68.82                     1 0.00         0.99
101.40                    1 0.00         1.00
110.86                    1 0.00         1.00

[232 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-26; Close
1.46                        2 0.01         0.01
3.73                        2 0.01         0.02
5.27                        2 0.01         0.02
7.21                        2 0.01         0.03
14.29                       2 0.01         0.04
...                       ...  ...          ...
53.60                       1 0.00         0.98
57.69                       1 0.00         0.99
69.33                       1 0.00         0.99
101.58                      1 0.00         1.00
110.86                      1 0.00         1.00

[238 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-26; Volume
190900                       2 0.01         0.01
2700                         1 0.00         0.01
5400                         1 0.00         0.02
8000                         1 0.00         0.02
2100                         1 0.00         0.02
...                        ...  ...          ...
31903000                     1 0.00         0.98
32348200                     1 0.00         0.99
44332400                     1 0.00         0.99
49065500                     1 0.00         1.00
69332300                     1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-26; Dividends
0.00                          242 0.98         0.98
0.19                            2 0.01         0.99
0.06                            1 0.00         1.00
0.19                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-26; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-26; HLC
1.01                      2 0.01         0.01
2.24                      2 0.01         0.02
5.46                      2 0.01         0.02
5.29                      2 0.01         0.03
0.26                      1 0.00         0.04
...                     ...  ...          ...
53.63                     1 0.00         0.98
57.71                     1 0.00         0.99
69.53                     1 0.00         0.99
101.86                    1 0.00         1.00
114.20                    1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-27; Open
1.46                       2 0.01         0.01
5.70                       2 0.01         0.02
5.28                       2 0.01         0.02
7.10                       2 0.01         0.03
28.86                      2 0.01         0.04
...                      ...  ...          ...
53.80                      1 0.00         0.98
58.00                      1 0.00         0.99
70.00                      1 0.00         0.99
102.90                     1 0.00         1.00
115.85                     1 0.00         1.00

[239 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-27; High
1.07                       2 0.01         0.01
1.46                       2 0.01         0.02
5.33                       2 0.01         0.02
5.38                       2 0.01         0.03
10.79                      2 0.01         0.04
...                      ...  ...          ...
56.24                      1 0.00         0.98
58.45                      1 0.00         0.99
70.00                      1 0.00         0.99
104.49                     1 0.00         1.00
124.01                     1 0.00         1.00

[240 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-27; Low
1.00                      3 0.01         0.01
5.54                      3 0.01         0.02
1.90                      2 0.01         0.03
5.07                      2 0.01         0.04
6.65                      2 0.01         0.05
...                     ...  ...          ...
53.01                     1 0.00         0.98
57.61                     1 0.00         0.99
68.04                     1 0.00         0.99
102.36                    1 0.00         1.00
113.37                    1 0.00         1.00

[235 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-27; Close
1.02                        2 0.01         0.01
2.27                        2 0.01         0.02
1.46                        2 0.01         0.02
1.51                        2 0.01         0.03
1.91                        2 0.01         0.04
...                       ...  ...          ...
55.44                       1 0.00         0.98
58.15                       1 0.00         0.99
68.32                       1 0.00         0.99
104.01                      1 0.00         1.00
119.09                      1 0.00         1.00

[232 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-27; Volume
13900                        2 0.01         0.01
5700                         1 0.00         0.01
6000                         1 0.00         0.02
9256                         1 0.00         0.02
700                          1 0.00         0.02
...                        ...  ...          ...
40588300                     1 0.00         0.98
50764800                     1 0.00         0.99
56716900                     1 0.00         0.99
72489300                     1 0.00         1.00
84639700                     1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-27; Dividends
0.00                          240 0.98         0.98
0.04                            1 0.00         0.98
0.05                            1 0.00         0.98
0.06                            1 0.00         0.99
0.09                            1 0.00         0.99
0.18                            1 0.00         1.00
0.46                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-27; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-27; HLC
1.36                      2 0.01         0.01
5.63                      2 0.01         0.02
5.35                      2 0.01         0.02
11.94                     2 0.01         0.03
0.26                      1 0.00         0.04
...                     ...  ...          ...
54.76                     1 0.00         0.98
58.07                     1 0.00         0.99
68.79                     1 0.00         0.99
103.62                    1 0.00         1.00
118.82                    1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-28; Open
1.46                       2 0.01         0.01
1.44                       2 0.01         0.02
5.36                       2 0.01         0.02
3.91                       2 0.01         0.03
5.63                       2 0.01         0.04
...                      ...  ...          ...
55.44                      1 0.00         0.98
58.10                      1 0.00         0.99
68.35                      1 0.00         0.99
104.00                     1 0.00         1.00
120.94                     1 0.00         1.00

[240 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-28; High
1.06                       2 0.01         0.01
1.44                       2 0.01         0.02
8.05                       2 0.01         0.02
0.53                       1 0.00         0.03
0.26                       1 0.00         0.03
...                      ...  ...          ...
55.57                      1 0.00         0.98
58.38                      1 0.00         0.99
69.07                      1 0.00         0.99
104.42                     1 0.00         1.00
122.25                     1 0.00         1.00

[243 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-28; Low
0.99                      2 0.01         0.01
1.01                      2 0.01         0.02
1.38                      2 0.01         0.02
5.51                      2 0.01         0.03
5.52                      2 0.01         0.04
...                     ...  ...          ...
54.10                     1 0.00         0.98
57.56                     1 0.00         0.99
66.08                     1 0.00         0.99
102.51                    1 0.00         1.00
117.56                    1 0.00         1.00

[235 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-28; Close
1.01                        2 0.01         0.01
1.04                        2 0.01         0.02
1.31                        2 0.01         0.02
7.36                        2 0.01         0.03
5.22                        2 0.01         0.04
...                       ...  ...          ...
54.93                       1 0.00         0.98
57.56                       1 0.00         0.99
66.36                       1 0.00         0.99
102.98                      1 0.00         1.00
120.10                      1 0.00         1.00

[234 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-28; Volume
172600                       2 0.01         0.01
465100                       2 0.01         0.02
9100                         1 0.00         0.02
3800                         1 0.00         0.02
13800                        1 0.00         0.03
...                        ...  ...          ...
40891100                     1 0.00         0.98
43119000                     1 0.00         0.99
63030500                     1 0.00         0.99
68474600                     1 0.00         1.00
158112037                    1 0.00         1.00

[244 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-28; Dividends
0.00                          244 0.99         0.99
0.07                            1 0.00         1.00
0.29                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-03-28; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-28; HLC
0.09                      1 0.00         0.00
0.25                      1 0.00         0.01
0.52                      1 0.00         0.01
0.72                      1 0.00         0.02
0.90                      1 0.00         0.02
...                     ...  ...          ...
54.87                     1 0.00         0.98
57.83                     1 0.00         0.99
67.17                     1 0.00         0.99
103.30                    1 0.00         1.00
119.97                    1 0.00         1.00

[246 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-31; Open
1.03                       2 0.01         0.01
1.36                       2 0.01         0.02
2.15                       2 0.01         0.02
6.40                       2 0.01         0.03
6.20                       2 0.01         0.04
...                      ...  ...          ...
54.02                      1 0.00         0.98
56.72                      1 0.00         0.99
66.15                      1 0.00         0.99
102.33                     1 0.00         1.00
120.10                     1 0.00         1.00

[236 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-03-31; High
1.55                       2 0.01         0.01
1.37                       2 0.01         0.02
4.02                       2 0.01         0.02
3.94                       2 0.01         0.03
5.15                       2 0.01         0.04
...                      ...  ...          ...
55.18                      1 0.00         0.98
57.02                      1 0.00         0.99
66.23                      1 0.00         0.99
103.08                     1 0.00         1.00
132.10                     1 0.00         1.00

[236 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-03-31; Low
1.30                      2 0.01         0.01
1.36                      2 0.01         0.02
1.83                      2 0.01         0.02
5.58                      2 0.01         0.03
5.47                      2 0.01         0.04
...                     ...  ...          ...
53.54                     1 0.00         0.98
56.03                     1 0.00         0.99
63.81                     1 0.00         0.99
101.13                    1 0.00         1.00
120.10                    1 0.00         1.00

[234 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-03-31; Close
3.85                        3 0.01         0.01
0.97                        2 0.01         0.02
1.38                        2 0.01         0.03
1.48                        2 0.01         0.04
1.22                        2 0.01         0.04
...                       ...  ...          ...
54.86                       1 0.00         0.98
56.70                       1 0.00         0.99
65.75                       1 0.00         0.99
102.00                      1 0.00         1.00
122.84                      1 0.00         1.00

[230 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-03-31; Volume
1863200                      2 0.01         0.01
7700                         1 0.00         0.01
8424                         1 0.00         0.02
10000                        1 0.00         0.02
2000                         1 0.00         0.02
...                        ...  ...          ...
39181000                     1 0.00         0.98
41452600                     1 0.00         0.99
57729600                     1 0.00         0.99
76895800                     1 0.00         1.00
120676400                    1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-03-31; Dividends
0                             246 1.00         1.00

                          Quantidade    %  % acumulado
2025-03-31; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-03-31; HLC
3.32                      2 0.01         0.01
0.25                      1 0.00         0.01
0.52                      1 0.00         0.02
0.72                      1 0.00         0.02
0.13                      1 0.00         0.02
...                     ...  ...          ...
54.53                     1 0.00         0.98
56.58                     1 0.00         0.99
65.26                     1 0.00         0.99
102.07                    1 0.00         1.00
125.01                    1 0.00         1.00

[245 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-01; Open
1.48                       2 0.01         0.01
1.39                       2 0.01         0.02
2.30                       2 0.01         0.02
1.28                       2 0.01         0.03
4.05                       2 0.01         0.04
...                      ...  ...          ...
55.20                      1 0.00         0.98
57.10                      1 0.00         0.99
66.06                      1 0.00         0.99
101.24                     1 0.00         1.00
122.00                     1 0.00         1.00

[230 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-01; High
1.40                       3 0.01         0.01
5.65                       3 0.01         0.02
1.25                       2 0.01         0.03
1.47                       2 0.01         0.04
1.33                       2 0.01         0.05
...                      ...  ...          ...
56.87                      1 0.00         0.98
57.93                      1 0.00         0.99
66.06                      1 0.00         0.99
102.50                     1 0.00         1.00
127.98                     1 0.00         1.00

[231 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-01; Low
1.47                      2 0.01         0.01
5.65                      2 0.01         0.02
6.03                      2 0.01         0.02
3.80                      2 0.01         0.03
5.46                      2 0.01         0.04
...                     ...  ...          ...
54.81                     1 0.00         0.98
56.95                     1 0.00         0.99
64.00                     1 0.00         0.99
100.59                    1 0.00         1.00
119.99                    1 0.00         1.00

[236 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-01; Close
1.38                        2 0.01         0.01
1.25                        2 0.01         0.02
3.20                        2 0.01         0.02
5.74                        2 0.01         0.03
5.35                        2 0.01         0.04
...                       ...  ...          ...
56.80                       1 0.00         0.98
57.19                       1 0.00         0.99
65.74                       1 0.00         0.99
102.35                      1 0.00         1.00
120.00                      1 0.00         1.00

[234 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-01; Volume
3700                         1 0.00         0.00
7900                         1 0.00         0.01
9600                         1 0.00         0.01
13728                        1 0.00         0.02
14300                        1 0.00         0.02
...                        ...  ...          ...
35324200                     1 0.00         0.98
39531500                     1 0.00         0.99
47666200                     1 0.00         0.99
51210400                     1 0.00         1.00
52326800                     1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-01; Dividends
0.00                          239 0.97         0.97
0.02                            2 0.01         0.98
0.20                            1 0.00         0.98
0.21                            1 0.00         0.99
0.23                            1 0.00         0.99
0.23                            1 0.00         1.00
0.30                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-04-01; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-04-01; HLC
1.38                      2 0.01         0.01
2.14                      2 0.01         0.02
5.83                      2 0.01         0.02
7.33                      2 0.01         0.03
0.26                      1 0.00         0.04
...                     ...  ...          ...
56.16                     1 0.00         0.98
57.36                     1 0.00         0.99
65.27                     1 0.00         0.99
101.81                    1 0.00         1.00
122.66                    1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-02; Open
1.23                       2 0.01         0.01
1.38                       2 0.01         0.02
5.55                       2 0.01         0.02
5.74                       2 0.01         0.03
6.90                       2 0.01         0.04
...                      ...  ...          ...
56.50                      1 0.00         0.98
57.21                      1 0.00         0.99
66.13                      1 0.00         0.99
102.35                     1 0.00         1.00
120.39                     1 0.00         1.00

[235 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-02; High
2.22                       3 0.01         0.01
7.54                       3 0.01         0.02
1.30                       2 0.01         0.03
1.00                       2 0.01         0.04
5.22                       2 0.01         0.05
...                      ...  ...          ...
57.30                      1 0.00         0.98
57.99                      1 0.00         0.99
66.42                      1 0.00         0.99
103.10                     1 0.00         1.00
122.37                     1 0.00         1.00

[236 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-02; Low
1.82                      3 0.01         0.01
1.23                      3 0.01         0.02
0.95                      2 0.01         0.03
1.37                      2 0.01         0.04
3.21                      2 0.01         0.05
...                     ...  ...          ...
55.99                     1 0.00         0.98
56.60                     1 0.00         0.99
64.32                     1 0.00         0.99
101.65                    1 0.00         1.00
119.58                    1 0.00         1.00

[232 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-02; Close
0.98                        2 0.01         0.01
1.26                        2 0.01         0.02
3.51                        2 0.01         0.02
5.18                        2 0.01         0.03
4.08                        2 0.01         0.04
...                       ...  ...          ...
56.93                       1 0.00         0.98
57.70                       1 0.00         0.99
64.87                       1 0.00         0.99
102.21                      1 0.00         1.00
121.97                      1 0.00         1.00

[237 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-02; Volume
2800                         1 0.00         0.00
9500                         1 0.00         0.01
12300                        1 0.00         0.01
18000                        1 0.00         0.02
18800                        1 0.00         0.02
...                        ...  ...          ...
35788800                     1 0.00         0.98
37759600                     1 0.00         0.99
48394100                     1 0.00         0.99
52167300                     1 0.00         1.00
77246000                     1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-02; Dividends
0.00                          244 0.99         0.99
0.02                            1 0.00         1.00
0.02                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-04-02; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-04-02; HLC
3.25                      2 0.01         0.01
1.87                      2 0.01         0.02
5.99                      2 0.01         0.02
7.10                      2 0.01         0.03
0.53                      1 0.00         0.04
...                     ...  ...          ...
56.94                     1 0.00         0.98
57.23                     1 0.00         0.99
65.20                     1 0.00         0.99
102.32                    1 0.00         1.00
121.31                    1 0.00         1.00

[242 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-03; Open
2.17                       3 0.01         0.01
1.24                       2 0.01         0.02
1.39                       2 0.01         0.03
1.45                       2 0.01         0.04
1.89                       2 0.01         0.04
...                      ...  ...          ...
56.00                      1 0.00         0.98
57.17                      1 0.00         0.99
64.40                      1 0.00         0.99
102.23                     1 0.00         1.00
120.24                     1 0.00         1.00

[231 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-03; High
5.82                       3 0.01         0.01
1.00                       2 0.01         0.02
1.89                       2 0.01         0.03
2.29                       2 0.01         0.04
2.37                       2 0.01         0.04
...                      ...  ...          ...
56.44                      1 0.00         0.98
57.66                      1 0.00         0.99
67.94                      1 0.00         0.99
106.39                     1 0.00         1.00
125.92                     1 0.00         1.00

[232 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-03; Low
1.02                      2 0.01         0.01
1.34                      2 0.01         0.02
1.86                      2 0.01         0.02
1.82                      2 0.01         0.03
5.41                      2 0.01         0.04
...                     ...  ...          ...
54.76                     1 0.00         0.98
56.22                     1 0.00         0.99
63.09                     1 0.00         0.99
101.90                    1 0.00         1.00
120.24                    1 0.00         1.00

[234 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-03; Close
0.97                        3 0.01         0.01
5.45                        3 0.01         0.02
5.76                        3 0.01         0.04
7.58                        2 0.01         0.04
2.14                        2 0.01         0.05
...                       ...  ...          ...
54.87                       1 0.00         0.98
57.52                       1 0.00         0.99
63.36                       1 0.00         0.99
105.55                      1 0.00         1.00
122.06                      1 0.00         1.00

[234 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-03; Volume
2900                         1 0.00         0.00
8600                         1 0.00         0.01
12900                        1 0.00         0.01
13200                        1 0.00         0.02
14248                        1 0.00         0.02
...                        ...  ...          ...
46295700                     1 0.00         0.98
57239000                     1 0.00         0.99
62135700                     1 0.00         0.99
65896000                     1 0.00         1.00
77999600                     1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-03; Dividends
0.00                          245 1.00         1.00
0.10                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-04-03; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-04-03; HLC
5.47                      2 0.01         0.01
4.69                      2 0.01         0.02
0.10                      1 0.00         0.02
0.26                      1 0.00         0.02
0.81                      1 0.00         0.03
...                     ...  ...          ...
55.36                     1 0.00         0.98
57.13                     1 0.00         0.99
64.80                     1 0.00         0.99
104.61                    1 0.00         1.00
122.74                    1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-04; Open
1.26                       3 0.01         0.01
5.50                       3 0.01         0.02
3.32                       2 0.01         0.03
2.09                       2 0.01         0.04
3.00                       2 0.01         0.05
...                      ...  ...          ...
53.22                      1 0.00         0.98
57.00                      1 0.00         0.99
62.45                      1 0.00         0.99
105.00                     1 0.00         1.00
120.84                     1 0.00         1.00

[231 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-04; High
5.73                       3 0.01         0.01
4.19                       2 0.01         0.02
1.26                       2 0.01         0.03
5.55                       2 0.01         0.04
5.50                       2 0.01         0.04
...                      ...  ...          ...
53.52                      1 0.00         0.98
57.30                      1 0.00         0.99
62.60                      1 0.00         0.99
105.28                     1 0.00         1.00
125.64                     1 0.00         1.00

[235 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-04; Low
0.93                      2 0.01         0.01
0.90                      2 0.01         0.02
1.42                      2 0.01         0.02
1.80                      2 0.01         0.03
2.11                      2 0.01         0.04
...                     ...  ...          ...
51.60                     1 0.00         0.98
55.42                     1 0.00         0.99
59.75                     1 0.00         0.99
102.43                    1 0.00         1.00
119.32                    1 0.00         1.00

[234 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-04; Close
7.50                        3 0.01         0.01
2.13                        2 0.01         0.02
3.69                        2 0.01         0.03
3.95                        2 0.01         0.04
5.31                        2 0.01         0.04
...                       ...  ...          ...
52.68                       1 0.00         0.98
56.11                       1 0.00         0.99
60.01                       1 0.00         0.99
103.40                      1 0.00         1.00
123.68                      1 0.00         1.00

[233 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-04; Volume
2200                         1 0.00         0.00
7900                         1 0.00         0.01
10300                        1 0.00         0.01
10500                        1 0.00         0.02
15900                        1 0.00         0.02
...                        ...  ...          ...
55519300                     1 0.00         0.98
59559600                     1 0.00         0.99
63292200                     1 0.00         0.99
67506100                     1 0.00         1.00
87263200                     1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-04; Dividends
0.00                          242 0.98         0.98
0.03                            1 0.00         0.99
0.07                            1 0.00         0.99
0.17                            1 0.00         1.00
0.85                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-04-04; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-04-04; HLC
0.09                      1 0.00         0.00
0.25                      1 0.00         0.01
0.52                      1 0.00         0.01
0.71                      1 0.00         0.02
0.80                      1 0.00         0.02
...                     ...  ...          ...
52.60                     1 0.00         0.98
56.28                     1 0.00         0.99
60.79                     1 0.00         0.99
103.70                    1 0.00         1.00
122.88                    1 0.00         1.00

[246 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-07; Open
12.39                      3 0.01         0.01
1.28                       2 0.01         0.02
7.23                       2 0.01         0.03
1.03                       2 0.01         0.04
5.61                       2 0.01         0.04
...                      ...  ...          ...
51.71                      1 0.00         0.98
54.98                      1 0.00         0.99
58.53                      1 0.00         0.99
103.18                     1 0.00         1.00
123.00                     1 0.00         1.00

[232 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-07; High
1.83                       2 0.01         0.01
1.38                       2 0.01         0.02
1.24                       2 0.01         0.02
4.12                       2 0.01         0.03
4.00                       2 0.01         0.04
...                      ...  ...          ...
53.48                      1 0.00         0.98
55.91                      1 0.00         0.99
61.45                      1 0.00         0.99
104.00                     1 0.00         1.00
127.90                     1 0.00         1.00

[231 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-07; Low
1.43                      2 0.01         0.01
1.35                      2 0.01         0.02
1.88                      2 0.01         0.02
2.06                      2 0.01         0.03
3.70                      2 0.01         0.04
...                     ...  ...          ...
51.17                     1 0.00         0.98
53.52                     1 0.00         0.99
58.12                     1 0.00         0.99
101.02                    1 0.00         1.00
120.98                    1 0.00         1.00

[230 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-07; Close
0.88                        2 0.01         0.01
1.45                        2 0.01         0.02
1.28                        2 0.01         0.02
1.98                        2 0.01         0.03
4.90                        2 0.01         0.04
...                       ...  ...          ...
52.05                       1 0.00         0.98
55.36                       1 0.00         0.99
60.11                       1 0.00         0.99
101.85                      1 0.00         1.00
125.63                      1 0.00         1.00

[231 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-07; Volume
100200                       2 0.01         0.01
4800                         1 0.00         0.01
18500                        1 0.00         0.02
23296                        1 0.00         0.02
4000                         1 0.00         0.02
...                        ...  ...          ...
53530800                     1 0.00         0.98
53646600                     1 0.00         0.99
85724900                     1 0.00         0.99
85987200                     1 0.00         1.00
95366500                     1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-07; Dividends
0                             246 1.00         1.00

                          Quantidade    %  % acumulado
2025-04-07; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-04-07; HLC
2.10                      2 0.01         0.01
1.78                      2 0.01         0.02
0.10                      1 0.00         0.02
0.25                      1 0.00         0.02
0.76                      1 0.00         0.03
...                     ...  ...          ...
52.23                     1 0.00         0.98
54.93                     1 0.00         0.99
59.89                     1 0.00         0.99
102.29                    1 0.00         1.00
124.84                    1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-08; Open
5.45                       3 0.01         0.01
3.23                       2 0.01         0.02
2.07                       2 0.01         0.03
4.90                       2 0.01         0.04
5.90                       2 0.01         0.04
...                      ...  ...          ...
52.35                      1 0.00         0.98
55.01                      1 0.00         0.99
61.24                      1 0.00         0.99
102.11                     1 0.00         1.00
124.12                     1 0.00         1.00

[235 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-08; High
2.08                       2 0.01         0.01
2.09                       2 0.01         0.02
1.85                       2 0.01         0.02
1.43                       2 0.01         0.03
5.17                       2 0.01         0.04
...                      ...  ...          ...
52.81                      1 0.00         0.98
56.35                      1 0.00         0.99
62.24                      1 0.00         0.99
103.70                     1 0.00         1.00
131.84                     1 0.00         1.00

[236 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-08; Low
11.68                     3 0.01         0.01
0.85                      2 0.01         0.02
0.98                      2 0.01         0.03
1.99                      2 0.01         0.04
1.73                      2 0.01         0.04
...                     ...  ...          ...
50.40                     1 0.00         0.98
53.08                     1 0.00         0.99
60.07                     1 0.00         0.99
101.00                    1 0.00         1.00
123.95                    1 0.00         1.00

[234 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-08; Close
5.15                        3 0.01         0.01
0.72                        2 0.01         0.02
1.73                        2 0.01         0.03
1.40                        2 0.01         0.04
3.73                        2 0.01         0.04
...                       ...  ...          ...
50.71                       1 0.00         0.98
53.28                       1 0.00         0.99
60.60                       1 0.00         0.99
101.59                      1 0.00         1.00
130.90                      1 0.00         1.00

[232 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-08; Volume
1700                         1 0.00         0.00
6600                         1 0.00         0.01
8500                         1 0.00         0.01
13600                        1 0.00         0.02
23100                        1 0.00         0.02
...                        ...  ...          ...
53611700                     1 0.00         0.98
56053800                     1 0.00         0.99
62128500                     1 0.00         0.99
69049900                     1 0.00         1.00
81175900                     1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-08; Dividends
0                             246 1.00         1.00

                          Quantidade    %  % acumulado
2025-04-08; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-04-08; HLC
0.09                      1 0.00         0.00
0.24                      1 0.00         0.01
0.54                      1 0.00         0.01
0.70                      1 0.00         0.02
0.74                      1 0.00         0.02
...                     ...  ...          ...
51.07                     1 0.00         0.98
54.24                     1 0.00         0.99
60.97                     1 0.00         0.99
102.10                    1 0.00         1.00
128.90                    1 0.00         1.00

[246 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-09; Open
0.87                       3 0.01         0.01
1.38                       2 0.01         0.02
5.84                       2 0.01         0.03
4.61                       2 0.01         0.04
5.15                       2 0.01         0.04
...                      ...  ...          ...
50.87                      1 0.00         0.98
52.30                      1 0.00         0.99
59.86                      1 0.00         0.99
101.17                     1 0.00         1.00
130.90                     1 0.00         1.00

[237 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-09; High
1.45                       2 0.01         0.01
1.37                       2 0.01         0.02
2.28                       2 0.01         0.02
5.98                       2 0.01         0.03
6.00                       2 0.01         0.04
...                      ...  ...          ...
53.10                      1 0.00         0.98
55.89                      1 0.00         0.99
63.12                      1 0.00         0.99
104.00                     1 0.00         1.00
133.83                     1 0.00         1.00

[234 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-09; Low
3.72                      3 0.01         0.01
0.68                      2 0.01         0.02
1.94                      2 0.01         0.03
2.00                      2 0.01         0.04
1.35                      2 0.01         0.04
...                     ...  ...          ...
50.59                     1 0.00         0.98
52.21                     1 0.00         0.99
58.55                     1 0.00         0.99
99.91                     1 0.00         1.00
127.13                    1 0.00         1.00

[234 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-09; Close
2.16                        2 0.01         0.01
1.35                        2 0.01         0.02
3.07                        2 0.01         0.02
5.57                        2 0.01         0.03
3.70                        2 0.01         0.04
...                       ...  ...          ...
52.24                       1 0.00         0.98
55.89                       1 0.00         0.99
62.45                       1 0.00         0.99
103.02                      1 0.00         1.00
127.13                      1 0.00         1.00

[238 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-09; Volume
11900                        2 0.01         0.01
21200                        2 0.01         0.02
12600                        1 0.00         0.02
31720                        1 0.00         0.02
32700                        1 0.00         0.03
...                        ...  ...          ...
64688900                     1 0.00         0.98
71372100                     1 0.00         0.99
88987300                     1 0.00         0.99
106391600                    1 0.00         1.00
113136000                    1 0.00         1.00

[244 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-09; Dividends
0                             246 1.00         1.00

                          Quantidade    %  % acumulado
2025-04-09; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-04-09; HLC
1.33                      2 0.01         0.01
5.90                      2 0.01         0.02
0.56                      1 0.00         0.02
0.09                      1 0.00         0.02
0.70                      1 0.00         0.03
...                     ...  ...          ...
51.98                     1 0.00         0.98
54.66                     1 0.00         0.99
61.37                     1 0.00         0.99
102.31                    1 0.00         1.00
129.36                    1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-10; Open
1.35                       3 0.01         0.01
2.16                       2 0.01         0.02
1.44                       2 0.01         0.03
1.02                       2 0.01         0.04
5.88                       2 0.01         0.04
...                      ...  ...          ...
52.47                      1 0.00         0.98
55.01                      1 0.00         0.99
62.52                      1 0.00         0.99
103.28                     1 0.00         1.00
127.13                     1 0.00         1.00

[233 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-10; High
1.44                       3 0.01         0.01
2.25                       2 0.01         0.02
3.15                       2 0.01         0.03
1.02                       2 0.01         0.04
5.58                       2 0.01         0.04
...                      ...  ...          ...
53.24                      1 0.00         0.98
55.80                      1 0.00         0.99
62.60                      1 0.00         0.99
105.00                     1 0.00         1.00
129.46                     1 0.00         1.00

[237 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-10; Low
3.52                      2 0.01         0.01
2.14                      2 0.01         0.02
2.80                      2 0.01         0.02
5.11                      2 0.01         0.03
32.68                     2 0.01         0.04
...                     ...  ...          ...
51.46                     1 0.00         0.98
53.87                     1 0.00         0.99
60.26                     1 0.00         0.99
102.74                    1 0.00         1.00
125.25                    1 0.00         1.00

[240 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-10; Close
6.90                        3 0.01         0.01
1.00                        2 0.01         0.02
0.88                        2 0.01         0.03
2.24                        2 0.01         0.04
3.62                        2 0.01         0.04
...                       ...  ...          ...
52.78                       1 0.00         0.98
54.56                       1 0.00         0.99
60.92                       1 0.00         0.99
105.00                      1 0.00         1.00
126.43                      1 0.00         1.00

[235 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-10; Volume
573000                       2 0.01         0.01
10300                        1 0.00         0.01
11800                        1 0.00         0.02
14000                        1 0.00         0.02
6900                         1 0.00         0.02
...                        ...  ...          ...
41659100                     1 0.00         0.98
46430200                     1 0.00         0.99
60359900                     1 0.00         0.99
71250600                     1 0.00         1.00
74387400                     1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-10; Dividends
0.00                          245 1.00         1.00
0.59                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-04-10; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-04-10; HLC
8.30                      2 0.01         0.01
4.05                      2 0.01         0.02
0.09                      1 0.00         0.02
0.24                      1 0.00         0.02
0.72                      1 0.00         0.03
...                     ...  ...          ...
52.49                     1 0.00         0.98
54.74                     1 0.00         0.99
61.26                     1 0.00         0.99
104.25                    1 0.00         1.00
127.05                    1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-11; Open
1.20                       2 0.01         0.01
1.00                       2 0.01         0.02
5.15                       2 0.01         0.02
5.49                       2 0.01         0.03
3.68                       2 0.01         0.04
...                      ...  ...          ...
52.56                      1 0.00         0.98
54.20                      1 0.00         0.99
61.19                      1 0.00         0.99
105.50                     1 0.00         1.00
130.55                     1 0.00         1.00

[238 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-11; High
7.28                       2 0.01         0.01
7.11                       2 0.01         0.02
5.89                       2 0.01         0.02
7.70                       2 0.01         0.03
4.22                       2 0.01         0.04
...                      ...  ...          ...
54.15                      1 0.00         0.98
55.62                      1 0.00         0.99
61.88                      1 0.00         0.99
107.59                     1 0.00         1.00
130.55                     1 0.00         1.00

[238 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-11; Low
0.85                      2 0.01         0.01
1.68                      2 0.01         0.02
5.46                      2 0.01         0.02
5.12                      2 0.01         0.03
5.09                      2 0.01         0.04
...                     ...  ...          ...
52.56                     1 0.00         0.98
53.90                     1 0.00         0.99
59.65                     1 0.00         0.99
105.12                    1 0.00         1.00
125.85                    1 0.00         1.00

[237 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-11; Close
0.86                        2 0.01         0.01
2.01                        2 0.01         0.02
1.39                        2 0.01         0.02
1.76                        2 0.01         0.03
3.97                        2 0.01         0.04
...                       ...  ...          ...
53.66                       1 0.00         0.98
54.69                       1 0.00         0.99
60.71                       1 0.00         0.99
107.02                      1 0.00         1.00
127.94                      1 0.00         1.00

[235 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-11; Volume
26200                        2 0.01         0.01
316100                       2 0.01         0.02
8900                         1 0.00         0.02
4000                         1 0.00         0.02
12600                        1 0.00         0.03
...                        ...  ...          ...
40969000                     1 0.00         0.98
46094000                     1 0.00         0.99
46935100                     1 0.00         0.99
57266800                     1 0.00         1.00
65329400                     1 0.00         1.00

[244 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-11; Dividends
0.00                          244 0.99         0.99
0.08                            1 0.00         1.00
0.23                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-04-11; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-04-11; HLC
3.65                      2 0.01         0.01
0.24                      1 0.00         0.01
0.51                      1 0.00         0.02
0.54                      1 0.00         0.02
0.09                      1 0.00         0.02
...                     ...  ...          ...
53.46                     1 0.00         0.98
54.74                     1 0.00         0.99
60.75                     1 0.00         0.99
106.58                    1 0.00         1.00
128.11                    1 0.00         1.00

[245 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-14; Open
5.00                       3 0.01         0.01
1.09                       2 0.01         0.02
0.87                       2 0.01         0.03
2.27                       2 0.01         0.04
5.37                       2 0.01         0.04
...                      ...  ...          ...
54.40                      1 0.00         0.98
54.69                      1 0.00         0.99
61.85                      1 0.00         0.99
108.35                     1 0.00         1.00
128.99                     1 0.00         1.00

[235 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-14; High
1.43                       2 0.01         0.01
1.30                       2 0.01         0.02
2.35                       2 0.01         0.02
3.04                       2 0.01         0.03
4.06                       2 0.01         0.04
...                      ...  ...          ...
54.88                      1 0.00         0.98
55.80                      1 0.00         0.99
63.45                      1 0.00         0.99
108.95                     1 0.00         1.00
131.98                     1 0.00         1.00

[238 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-14; Low
1.06                      2 0.01         0.01
0.87                      2 0.01         0.02
3.24                      2 0.01         0.02
1.69                      2 0.01         0.03
2.92                      2 0.01         0.04
...                     ...  ...          ...
54.00                     1 0.00         0.98
54.19                     1 0.00         0.99
61.81                     1 0.00         0.99
106.88                    1 0.00         1.00
127.33                    1 0.00         1.00

[236 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-14; Close
7.20                        3 0.01         0.01
2.29                        2 0.01         0.02
1.33                        2 0.01         0.03
3.71                        2 0.01         0.04
3.98                        2 0.01         0.04
...                       ...  ...          ...
54.36                       1 0.00         0.98
54.89                       1 0.00         0.99
62.73                       1 0.00         0.99
108.40                      1 0.00         1.00
131.00                      1 0.00         1.00

[235 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-14; Volume
178300                       2 0.01         0.01
6000                         1 0.00         0.01
10900                        1 0.00         0.02
15200                        1 0.00         0.02
3000                         1 0.00         0.02
...                        ...  ...          ...
37200000                     1 0.00         0.98
47866600                     1 0.00         0.99
51628300                     1 0.00         0.99
56015200                     1 0.00         1.00
135910300                    1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-14; Dividends
0.00                          244 0.99         0.99
0.06                            1 0.00         1.00
0.07                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-04-14; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-04-14; HLC
20.57                     2 0.01         0.01
34.17                     2 0.01         0.02
0.09                      1 0.00         0.02
0.24                      1 0.00         0.02
0.72                      1 0.00         0.03
...                     ...  ...          ...
54.48                     1 0.00         0.98
54.90                     1 0.00         0.99
62.66                     1 0.00         0.99
108.08                    1 0.00         1.00
130.10                    1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-15; Open
0.87                       2 0.01         0.01
3.38                       2 0.01         0.02
3.74                       2 0.01         0.02
5.59                       2 0.01         0.03
4.07                       2 0.01         0.04
...                      ...  ...          ...
54.38                      1 0.00         0.98
54.92                      1 0.00         0.99
63.51                      1 0.00         0.99
107.99                     1 0.00         1.00
131.00                     1 0.00         1.00

[235 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-15; High
0.75                       2 0.01         0.01
0.90                       2 0.01         0.02
1.39                       2 0.01         0.02
1.85                       2 0.01         0.03
2.26                       2 0.01         0.04
...                      ...  ...          ...
54.65                      1 0.00         0.98
55.04                      1 0.00         0.99
65.56                      1 0.00         0.99
108.78                     1 0.00         1.00
149.40                     1 0.00         1.00

[235 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-15; Low
3.67                      3 0.01         0.01
3.24                      2 0.01         0.02
1.45                      2 0.01         0.03
1.22                      2 0.01         0.04
7.27                      2 0.01         0.04
...                     ...  ...          ...
53.38                     1 0.00         0.98
53.53                     1 0.00         0.99
63.51                     1 0.00         0.99
107.32                    1 0.00         1.00
129.03                    1 0.00         1.00

[233 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-15; Close
0.73                        2 0.01         0.01
2.01                        2 0.01         0.02
2.18                        2 0.01         0.02
3.96                        2 0.01         0.03
3.28                        2 0.01         0.04
...                       ...  ...          ...
53.66                       1 0.00         0.98
53.81                       1 0.00         0.99
64.65                       1 0.00         0.99
108.43                      1 0.00         1.00
142.10                      1 0.00         1.00

[230 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-15; Volume
1200                         1 0.00         0.00
4500                         1 0.00         0.01
5800                         1 0.00         0.01
7300                         1 0.00         0.02
9400                         1 0.00         0.02
...                        ...  ...          ...
30452400                     1 0.00         0.98
30568000                     1 0.00         0.99
31137500                     1 0.00         0.99
53925300                     1 0.00         1.00
58276900                     1 0.00         1.00

[246 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-15; Dividends
0                             246 1.00         1.00

                          Quantidade    %  % acumulado
2025-04-15; Stock Splits
0                                245 1.00         1.00
2                                  1 0.00         1.00

                 Quantidade    %  % acumulado
2025-04-15; HLC
1.36                      2 0.01         0.01
1.24                      2 0.01         0.02
12.35                     2 0.01         0.02
0.52                      1 0.00         0.03
0.24                      1 0.00         0.03
...                     ...  ...          ...
54.00                     1 0.00         0.98
54.03                     1 0.00         0.99
64.57                     1 0.00         0.99
108.18                    1 0.00         1.00
140.18                    1 0.00         1.00

[243 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-16; Open
0.86                       2 0.01         0.01
1.81                       2 0.01         0.02
2.20                       2 0.01         0.02
4.30                       2 0.01         0.03
5.74                       2 0.01         0.04
...                      ...  ...          ...
53.52                      1 0.00         0.98
54.29                      1 0.00         0.99
65.00                      1 0.00         0.99
108.03                     1 0.00         1.00
142.10                     1 0.00         1.00

[236 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-16; High
0.87                       2 0.01         0.01
2.63                       2 0.01         0.02
5.43                       2 0.01         0.02
5.59                       2 0.01         0.03
6.37                       2 0.01         0.04
...                      ...  ...          ...
53.64                      1 0.00         0.98
54.29                      1 0.00         0.99
65.08                      1 0.00         0.99
108.29                     1 0.00         1.00
151.00                     1 0.00         1.00

[239 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-16; Low
0.85                      2 0.01         0.01
2.15                      2 0.01         0.02
2.14                      2 0.01         0.02
7.73                      2 0.01         0.03
7.11                      2 0.01         0.04
...                     ...  ...          ...
52.42                     1 0.00         0.98
53.07                     1 0.00         0.99
62.17                     1 0.00         0.99
106.40                    1 0.00         1.00
142.10                    1 0.00         1.00

[234 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-16; Close
1.57                        2 0.01         0.01
1.35                        2 0.01         0.02
3.03                        2 0.01         0.02
2.63                        2 0.01         0.03
7.38                        2 0.01         0.04
...                       ...  ...          ...
52.56                       1 0.00         0.98
53.40                       1 0.00         0.99
62.41                       1 0.00         0.99
107.30                      1 0.00         1.00
143.08                      1 0.00         1.00

[238 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-16; Volume
7400                         2 0.01         0.01
41000                        2 0.01         0.02
3846200                      2 0.01         0.02
15900                        1 0.00         0.03
19000                        1 0.00         0.03
...                        ...  ...          ...
51905100                     1 0.00         0.98
60471500                     1 0.00         0.99
66518200                     1 0.00         0.99
73227700                     1 0.00         1.00
98791900                     1 0.00         1.00

[243 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-16; Dividends
0.00                          245 1.00         1.00
0.07                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-04-16; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-04-16; HLC
21.93                     2 0.01         0.01
10.26                     2 0.01         0.02
0.09                      1 0.00         0.02
0.24                      1 0.00         0.02
0.71                      1 0.00         0.03
...                     ...  ...          ...
52.87                     1 0.00         0.98
53.59                     1 0.00         0.99
63.22                     1 0.00         0.99
107.33                    1 0.00         1.00
145.39                    1 0.00         1.00

[244 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-17; Open
8.39                       3 0.01         0.01
6.09                       2 0.01         0.02
1.31                       2 0.01         0.03
7.15                       2 0.01         0.04
5.47                       2 0.01         0.04
...                      ...  ...          ...
52.78                      1 0.00         0.98
53.40                      1 0.00         0.99
62.65                      1 0.00         0.99
106.86                     1 0.00         1.00
143.40                     1 0.00         1.00

[231 rows x 3 columns]

                  Quantidade    %  % acumulado
2025-04-17; High
1.45                       3 0.01         0.01
0.89                       2 0.01         0.02
4.07                       2 0.01         0.03
3.99                       2 0.01         0.04
7.20                       2 0.01         0.04
...                      ...  ...          ...
53.32                      1 0.00         0.98
53.79                      1 0.00         0.99
63.66                      1 0.00         0.99
109.24                     1 0.00         1.00
151.00                     1 0.00         1.00

[233 rows x 3 columns]

                 Quantidade    %  % acumulado
2025-04-17; Low
2.15                      3 0.01         0.01
1.55                      2 0.01         0.02
3.22                      2 0.01         0.03
0.85                      2 0.01         0.04
7.29                      2 0.01         0.04
...                     ...  ...          ...
52.56                     1 0.00         0.98
53.00                     1 0.00         0.99
62.12                     1 0.00         0.99
106.71                    1 0.00         1.00
135.25                    1 0.00         1.00

[233 rows x 3 columns]

                   Quantidade    %  % acumulado
2025-04-17; Close
1.45                        2 0.01         0.01
2.68                        2 0.01         0.02
5.65                        2 0.01         0.02
5.59                        2 0.01         0.03
5.50                        2 0.01         0.04
...                       ...  ...          ...
52.88                       1 0.00         0.98
53.00                       1 0.00         0.99
63.15                       1 0.00         0.99
109.01                      1 0.00         1.00
135.25                      1 0.00         1.00

[237 rows x 3 columns]

                    Quantidade    %  % acumulado
2025-04-17; Volume
96800                        2 0.01         0.01
21300                        1 0.00         0.01
23800                        1 0.00         0.02
24500                        1 0.00         0.02
20200                        1 0.00         0.02
...                        ...  ...          ...
26856800                     1 0.00         0.98
56058800                     1 0.00         0.99
57331500                     1 0.00         0.99
65752700                     1 0.00         1.00
111753600                    1 0.00         1.00

[245 rows x 3 columns]

                       Quantidade    %  % acumulado
2025-04-17; Dividends
0.00                          242 0.98         0.98
0.71                            2 0.01         0.99
0.04                            1 0.00         1.00
0.50                            1 0.00         1.00

                          Quantidade    %  % acumulado
2025-04-17; Stock Splits
0                                246 1.00         1.00

                 Quantidade    %  % acumulado
2025-04-17; HLC
3.73                      2 0.01         0.01
5.31                      2 0.01         0.02
27.50                     2 0.01         0.02
0.61                      1 0.00         0.03
0.72                      1 0.00         0.03
...                     ...  ...          ...
52.92                     1 0.00         0.98
53.26                     1 0.00         0.99
62.98                     1 0.00         0.99
108.32                    1 0.00         1.00
140.50                    1 0.00         1.00

[243 rows x 3 columns]

                           Quantidade    %  % acumulado
Alfa HLC; últimos 13 dias
-0.66                               1 0.00         0.00
-0.59                               1 0.00         0.01
-0.52                               1 0.00         0.01
-0.43                               1 0.00         0.02
-0.39                               1 0.00         0.02
...                               ...  ...          ...
0.24                                1 0.00         0.98
0.37                                1 0.00         0.99
0.38                                1 0.00         0.99
0.56                                1 0.00         1.00
1.78                                1 0.00         1.00

[246 rows x 3 columns]

                           Quantidade    %  % acumulado
Alfa HLC; últimos 55 dias
-0.26                               1 0.00         0.00
-0.24                               1 0.00         0.01
-0.16                               1 0.00         0.01
-0.14                               1 0.00         0.02
-0.13                               1 0.00         0.02
...                               ...  ...          ...
0.20                                1 0.00         0.98
0.34                                1 0.00         0.99
0.35                                1 0.00         0.99
0.36                                1 0.00         1.00
0.41                                1 0.00         1.00

[246 rows x 3 columns]

,Quantidade,%,% acumulado
Martelos,,,
"2025-02-24, 2025-02-25, 2025-02-26, 2025-02-27, 2025-02-28, 2025-03-05, 2025-03-06, 2025-03-07, 2025-03-10, 2025-03-11, 2025-03-13, 2025-03-14, 2025-03-17, 2025-03-18, 2025-03-21, 2025-03-24, 2025-03-26, 2025-04-01, 2025-04-03, 2025-04-07, 2025-04-08, 2025-04-09, 2025-04-10, 2025-04-11, 2025-04-14, 2025-04-17,",1,0.00,0.00
"2025-02-24, 2025-02-25, 2025-02-26, 2025-02-28, 2025-03-06, 2025-03-10, 2025-03-14, 2025-03-18, 2025-03-28, 2025-04-01, 2025-04-04, 2025-04-07, 2025-04-08, 2025-04-14, 2025-04-15,",1,0.00,0.01
"2025-02-24, 2025-02-25, 2025-02-28, 2025-03-10, 2025-03-11, 2025-03-19, 2025-03-21, 2025-03-24, 2025-03-25, 2025-04-07, 2025-04-11,",1,0.00,0.01
"2025-02-24, 2025-02-25, 2025-03-05, 2025-03-20,",1,0.00,0.02
"2025-02-24, 2025-02-25, 2025-03-06, 2025-03-11, 2025-04-14,",1,0.00,0.02
...,...,...,...
"2025-03-25, 2025-03-26, 2025-04-02, 2025-04-07, 2025-04-11,",1,0.00,0.98
"2025-03-26, 2025-04-02, 2025-04-03, 2025-04-07, 2025-04-16,",1,0.00,0.99
"2025-03-27, 2025-04-04,",1,0.00,0.99
"2025-04-08,",1,0.00,1.00
"2025-04-14,",1,0.00,1.00

,Quantidade,%,% acumulado
Tipos de Martelos,,,
"Descida, Descida, Subida, Subida, Descida, Subida, Subida,",3,0.01,0.01
"Descida, Subida, Subida, Subida,",3,0.01,0.02
"Descida, Descida, Subida, Subida, Subida, Subida, Subida,",2,0.01,0.03
"Subida, Descida,",2,0.01,0.04
"Descida, Descida, Subida, Subida, Descida, Subida,",2,0.01,0.05
...,...,...,...
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Descida, Subida,",1,0.00,0.98
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida,",1,0.00,0.99
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida,",1,0.00,0.99
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida,",1,0.00,1.00
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida,",1,0.00,1.00

## Teste de variáveis específicas

In [18]:
display(len(bd_semNA))
display(len(bd_dados_completos))

246

246

In [19]:
colunas_parciais

['fullTimeEmployees',
 'dividendRate',
 'dividendYield',
 'exDividendDate',
 'payoutRatio',
 'beta',
 'trailingPE',
 'forwardPE',
 'priceToSalesTrailing12Months',
 'profitMargins',
 'forwardEps',
 'lastSplitFactor',
 'lastSplitDate',
 'enterpriseToRevenue',
 'enterpriseToEbitda',
 'lastDividendValue',
 'lastDividendDate',
 'recommendationMean',
 'numberOfAnalystOpinions',
 'totalCash',
 'totalCashPerShare',
 'ebitda',
 'totalDebt',
 'quickRatio',
 'currentRatio',
 'totalRevenue',
 'debtToEquity',
 'revenuePerShare',
 'returnOnAssets',
 'returnOnEquity',
 'grossProfits',
 'freeCashflow',
 'operatingCashflow',
 'earningsGrowth',
 'revenueGrowth',
 'grossMargins',
 'ebitdaMargins',
 'epsForward',
 'epsCurrentYear',
 'priceEpsCurrentYear']

In [20]:
# colunas_agrupadas
colunas_parciais[0]

# colunas_agrupadas.get("52WeekChange")

colunas_agrupadas.get(colunas_parciais[0])

                   Quantidade    %  % acumulado
fullTimeEmployees
 (vazio)                  142 0.58         0.58
6,047.00                    3 0.01         0.59
854.00                      3 0.01         0.60
55,646.00                   3 0.01         0.61
6,000.00                    2 0.01         0.62
...                       ...  ...          ...
64,616.00                   1 0.00         0.98
87,000.00                   1 0.00         0.99
100,000.00                  1 0.00         0.99
126,832.00                  1 0.00         1.00
190,000.00                  1 0.00         1.00

[91 rows x 3 columns]

In [21]:
campos_com_erro

[]

### _recommendationKey_

In [62]:
display(bd_dados_completos[bd_dados_completos["recommendationKey"] == 'buy'].sort_index().index)
display(bd_dados_completos[bd_dados_completos["recommendationKey"] == 'strong_buy'].sort_index().index)

Index(['AGRO3', 'ALOS3', 'ALUP11', 'ANIM3', 'ARML3', 'ASAI3', 'B3SA3', 'BBAS3',
       'BBSE3', 'BLAU3', 'BMGB4', 'BMOB3', 'BPAC11', 'BPAN4', 'BRAP4', 'BRAV3',
       'BRFS3', 'BRKM5', 'CAML3', 'CBAV3', 'CCRO3', 'COGN3', 'CSAN3', 'CSED3',
       'CVCB3', 'CXSE3', 'CYRE3', 'DXCO3', 'ECOR3', 'ELMD3', 'ENGI11', 'FIQE3',
       'FRAS3', 'GGBR4', 'GMAT3', 'GOAU4', 'GUAR3', 'HAPV3', 'HBSA3', 'HYPE3',
       'INTB3', 'IRBR3', 'KLBN11', 'LJQQ3', 'LOGG3', 'LREN3', 'LWSA3', 'MATD3',
       'MOVI3', 'MRFG3', 'MRVE3', 'MULT3', 'MYPK3', 'NEOE3', 'NTCO3', 'PNVL3',
       'PSSA3', 'RADL3', 'RAIL3', 'RAPT4', 'RDOR3', 'RECV3', 'SBFG3', 'SBSP3',
       'SEER3', 'SLCE3', 'SMTO3', 'STBP3', 'SUZB3', 'SYNE3', 'TEND3', 'TFCO4',
       'TIMS3', 'TOTS3', 'TTEN3', 'VALE3', 'VAMO3', 'VBBR3', 'VIVT3', 'VTRU3',
       'WEGE3', 'YDUQ3', 'ZAMP3'],
      dtype='object', name='Ticker')

Index(['AZZA3', 'CEAB3', 'CPLE3', 'CPLE6', 'CURY3', 'DIRR3', 'ELET3', 'EQTL3',
       'GGPS3', 'ITSA4', 'ITUB4', 'JALL3', 'JBSS3', 'JHSF3', 'LAVV3', 'MDNE3',
       'MELK3', 'ORVR3', 'PETR3', 'PETR4', 'PLPL3', 'POMO4', 'PRIO3', 'PRNR3',
       'RAIZ4', 'RANI3', 'RENT3', 'SMFT3', 'SOJA3', 'SRNA3', 'VIVA3', 'VULC3'],
      dtype='object', name='Ticker')

# Preparação de dados

## Remover todas as colunas parciais

In [130]:
bd_dados_completos_sem_colunas_parciais = bd_dados_completos.drop(colunas_parciais, axis = 1).copy()
bd_dados_completos_sem_colunas_parciais.columns

Index(['Nome da Empresa', 'Volume no último dia útil (lido em 19/04/2025)',
       'industry', 'sector', 'averageVolume', 'averageVolume10days',
       'averageDailyVolume10Day', 'marketCap', 'fiftyDayAverage',
       'twoHundredDayAverage',
       ...
       '2025-04-17; Low', '2025-04-17; Close', '2025-04-17; Volume',
       '2025-04-17; Dividends', '2025-04-17; Stock Splits', '2025-04-17; HLC',
       'Alfa HLC; últimos 13 dias', 'Alfa HLC; últimos 55 dias', 'Martelos',
       'Tipos de Martelos'],
      dtype='object', length=321)

## One hot encoding

In [131]:
## VER OS TIPOS DE TODAS AS COLUNAS

# var_tamanho_print = 22

# for var_contador in range(round(len(bd_dados_completos_sem_colunas_parciais.columns)/22)):
#     # display((var_contador*var_tamanho_print + 1))
#     # display(((var_contador+1)*var_tamanho_print))
#     display(bd_dados_completos_sem_colunas_parciais.iloc[:, (var_contador*var_tamanho_print + 1):((var_contador+1)*var_tamanho_print)].info())

# bd_dados_completos_sem_colunas_parciais.select_dtypes("object")#.columns

In [132]:
for var_coluna in bd_dados_completos_sem_colunas_parciais.select_dtypes("object").columns:
    display(colunas_agrupadas.get(var_coluna))

                     Quantidade    %  % acumulado
Nome da Empresa
Banco Santander               3 0.01         0.01
Taesa                         3 0.01         0.02
Sanepar                       3 0.01         0.04
Banco Bradesco                2 0.01         0.04
Azevedo & Travassos           2 0.01         0.05
...                         ...  ...          ...
Wilson Sons                   1 0.00         0.98
Wiz Soluções                  1 0.00         0.99
YDUQS                         1 0.00         0.99
Zamp                          1 0.00         1.00
Ânima Educação                1 0.00         1.00

[222 rows x 3 columns]

                                         Quantidade    %  % acumulado
industry
Banks - Regional                                 13 0.05         0.05
Real Estate Services                             12 0.05         0.10
Utilities - Renewable                            11 0.04         0.15
Real Estate - Development                        10 0.04         0.19
Utilities - Regulated Electric                    9 0.04         0.22
...                                             ...  ...          ...
Personal Services                                 1 0.00         0.98
Specialty Chemicals                               1 0.00         0.99
Utilities - Independent Power Producers           1 0.00         0.99
Travel Services                                   1 0.00         1.00
Trucking                                          1 0.00         1.00

[87 rows x 3 columns]

                        Quantidade    %  % acumulado
sector
Industrials                     48 0.20         0.20
Consumer Cyclical               38 0.15         0.35
Utilities                       29 0.12         0.47
Financial Services              23 0.09         0.56
Real Estate                     23 0.09         0.65
Basic Materials                 22 0.09         0.74
Consumer Defensive              19 0.08         0.82
Healthcare                      17 0.07         0.89
Communication Services          10 0.04         0.93
Technology                       9 0.04         0.97
Energy                           8 0.03         1.00

                   Quantidade    %  % acumulado
recommendationKey
buy                        83 0.34         0.34
none                       83 0.34         0.67
hold                       43 0.17         0.85
strong_buy                 32 0.13         0.98
underperform                5 0.02         1.00

,Quantidade,%,% acumulado
Martelos,,,
"2025-02-24, 2025-02-25, 2025-02-26, 2025-02-27, 2025-02-28, 2025-03-05, 2025-03-06, 2025-03-07, 2025-03-10, 2025-03-11, 2025-03-13, 2025-03-14, 2025-03-17, 2025-03-18, 2025-03-21, 2025-03-24, 2025-03-26, 2025-04-01, 2025-04-03, 2025-04-07, 2025-04-08, 2025-04-09, 2025-04-10, 2025-04-11, 2025-04-14, 2025-04-17,",1,0.00,0.00
"2025-02-24, 2025-02-25, 2025-02-26, 2025-02-28, 2025-03-06, 2025-03-10, 2025-03-14, 2025-03-18, 2025-03-28, 2025-04-01, 2025-04-04, 2025-04-07, 2025-04-08, 2025-04-14, 2025-04-15,",1,0.00,0.01
"2025-02-24, 2025-02-25, 2025-02-28, 2025-03-10, 2025-03-11, 2025-03-19, 2025-03-21, 2025-03-24, 2025-03-25, 2025-04-07, 2025-04-11,",1,0.00,0.01
"2025-02-24, 2025-02-25, 2025-03-05, 2025-03-20,",1,0.00,0.02
"2025-02-24, 2025-02-25, 2025-03-06, 2025-03-11, 2025-04-14,",1,0.00,0.02
...,...,...,...
"2025-03-25, 2025-03-26, 2025-04-02, 2025-04-07, 2025-04-11,",1,0.00,0.98
"2025-03-26, 2025-04-02, 2025-04-03, 2025-04-07, 2025-04-16,",1,0.00,0.99
"2025-03-27, 2025-04-04,",1,0.00,0.99
"2025-04-08,",1,0.00,1.00
"2025-04-14,",1,0.00,1.00

,Quantidade,%,% acumulado
Tipos de Martelos,,,
"Descida, Descida, Subida, Subida, Descida, Subida, Subida,",3,0.01,0.01
"Descida, Subida, Subida, Subida,",3,0.01,0.02
"Descida, Descida, Subida, Subida, Subida, Subida, Subida,",2,0.01,0.03
"Subida, Descida,",2,0.01,0.04
"Descida, Descida, Subida, Subida, Descida, Subida,",2,0.01,0.05
...,...,...,...
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Descida, Subida,",1,0.00,0.98
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida,",1,0.00,0.99
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida,",1,0.00,0.99
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida,",1,0.00,1.00
"Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida, Subida,",1,0.00,1.00

In [133]:
lista_remover_colunas_object = bd_dados_completos_sem_colunas_parciais.select_dtypes("object").columns
lista_remover_colunas_object

bd_dados_completos_limpar_object = bd_dados_completos_sem_colunas_parciais.drop(lista_remover_colunas_object, axis = 1).copy()

bd_dados_completos_limpar_object

,Volume no último dia útil (lido em 19/04/2025),averageVolume,averageVolume10days,averageDailyVolume10Day,marketCap,fiftyDayAverage,twoHundredDayAverage,trailingAnnualDividendRate,trailingAnnualDividendYield,trailingEps,...,2025-04-17; Open,2025-04-17; High,2025-04-17; Low,2025-04-17; Close,2025-04-17; Volume,2025-04-17; Dividends,2025-04-17; Stock Splits,2025-04-17; HLC,Alfa HLC; últimos 13 dias,Alfa HLC; últimos 55 dias
Ticker,,,,,,,,,,,,,,,,,,,,,
COGN3,111753600,54038432,74166360,74166360,4430286336,1.85,1.48,0.07,0.03,0.46,...,2.26,2.48,2.15,2.45,111753600,0.00,0,2.36,0.03,0.02
PETR4,65752700,37900975,73125810,73125810,414883151872,35.65,36.94,5.73,0.19,3.40,...,30.67,31.18,30.46,30.85,65752700,0.71,0,30.83,-0.52,-0.11
HAPV3,57331500,100621951,62252560,62252560,16026746880,2.23,3.13,0.00,0.00,-0.09,...,2.22,2.22,2.15,2.16,57331500,0.00,0,2.18,0.00,0.00
ABEV3,56058800,35657248,42149260,42149260,219060797440,12.70,12.50,0.67,0.05,0.91,...,13.90,14.10,13.79,14.00,56058800,0.00,0,13.96,0.02,0.05
MGLU3,26837300,29897058,36728390,36728390,7513472512,8.91,9.49,0.00,0.00,0.61,...,10.41,10.48,10.16,10.20,26856800,0.00,0,10.28,-0.05,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TASA3,26300,9633,14800,14800,1151837696,8.26,9.71,0.20,0.02,0.61,...,9.01,9.29,9.00,9.12,26300,0.00,0,9.14,0.05,0.02
LOGN3,24500,40854,19440,19440,2254370048,21.35,27.04,0.00,0.00,1.41,...,21.24,21.39,21.19,21.25,24500,0.00,0,21.28,0.02,-0.01
BIOM3,23800,66737,16610,16610,1236709504,9.85,9.54,0.00,0.00,-0.63,...,10.00,10.30,9.75,9.75,23800,0.00,0,9.93,-0.01,-0.02
PTNT4,21300,6709,12110,12110,350743264,7.36,6.62,0.33,0.05,0.65,...,6.71,6.79,6.45,6.45,21300,0.00,0,6.56,-0.11,-0.01
ALUP4,20200,13614,22120,22120,9911132160,9.52,9.64,0.84,0.09,1.11,...,9.56,9.67,9.45,9.51,20200,0.00,0,9.54,0.01,0.02

## Balanceamento

In [134]:
# # # SÓ CONSEGUI FAZER FUNCIONAR REMOVENDO O PARÂMETRO stratify

# from sklearn.model_selection import train_test_split
# dados = bd_dados_completos_limpar_object
# colunas_treino = bd_dados_completos_limpar_object.drop(var_coluna_objetivo, axis = 1).columns
# coluna_resultado = var_coluna_objetivo
# proporcao = 0.10

# # display(dados.loc[:, colunas_treino])
# # list(dados.loc[:, coluna_resultado].values)
# # dados.loc[:, [coluna_resultado]].iloc[:, 0]

# [original_x_treino, original_x_teste, y_treino, y_teste] = train_test_split(
#     dados.loc[:, colunas_treino],
#     dados.loc[:, [coluna_resultado]],
#     test_size = proporcao,
#     # stratify = dados.loc[:, [coluna_resultado]] # mesma proporção de y
# )

# # # [original_x_treino, original_x_teste, y_treino, y_teste]
# display(len(original_x_treino))
# display(len(original_x_teste))
# display(len(y_treino))
# display(len(y_teste))

## Normalização

## Removendo todas as variáveis relacionadas a dados dos últimos 13 dias

In [202]:
lista_variaveis_diarias = [
    "; Open",
    "; High",
    "; Low",
    "; Close",
    "; Volume",
    "; Dividends",
    "; Stock Splits",
    "; HLC"]
lista_colunas_variaveis_diarias_remover = ["Alfa HLC; últimos 55 dias"]
# lista_colunas_variaveis_diarias_remover = []

for var_coluna in bd_dados_completos_limpar_object.columns:
    for var_diaria in lista_variaveis_diarias:
        if (var_diaria in var_coluna):
            if (datetime.strptime(var_coluna.split("; ")[0], "%Y-%m-%d") > (datetime.today() - timedelta(days=13))):
                # display(var_coluna)
                lista_colunas_variaveis_diarias_remover.append(var_coluna)


# display(lista_colunas_variaveis_diarias_remover)
bd_dados_completos_limpar_colunas_diarias = bd_dados_completos_limpar_object.drop(lista_colunas_variaveis_diarias_remover, axis = 1).copy()
# bd_dados_completos_limpar_colunas_diarias

bd_dados_completos_limpar_colunas_diarias.iloc[:5, -20:]

,2025-04-02; Dividends,2025-04-02; Stock Splits,2025-04-02; HLC,2025-04-03; Open,2025-04-03; High,2025-04-03; Low,2025-04-03; Close,2025-04-03; Volume,2025-04-03; Dividends,2025-04-03; Stock Splits,2025-04-03; HLC,2025-04-04; Open,2025-04-04; High,2025-04-04; Low,2025-04-04; Close,2025-04-04; Volume,2025-04-04; Dividends,2025-04-04; Stock Splits,2025-04-04; HLC,Alfa HLC; últimos 13 dias
Ticker,,,,,,,,,,,,,,,,,,,,
COGN3,0.00,0,2.11,2.07,2.22,2.07,2.18,77999600,0.00,0,2.16,2.11,2.11,2.01,2.06,63292200,0.00,0,2.06,0.03
PETR4,0.00,0,36.26,35.32,35.47,34.79,35.18,65896000,0.00,0,35.15,33.94,34.21,33.04,33.76,87263200,0.00,0,33.67,-0.52
HAPV3,0.00,0,2.21,2.17,2.29,2.17,2.25,62135700,0.00,0,2.24,2.20,2.21,2.11,2.13,67506100,0.00,0,2.15,0.00
ABEV3,0.00,0,13.60,13.64,14.14,13.61,13.85,44926800,0.00,0,13.87,13.73,13.90,13.56,13.71,59559600,0.00,0,13.72,0.02
MGLU3,0.00,0,10.92,11.16,11.85,11.14,11.80,32976900,0.00,0,11.60,11.34,11.49,10.74,10.83,40210300,0.00,0,11.02,-0.05

# [MODELO 1] Decision Tree Classifier

## Definição da variável objetivo

In [193]:
## SE A VARIÁVEL OBJETIVO FOR CATEGÓRICA, PODEMOS USAR SE O PREÇO AUMENTOU, SUBIU OU FICOU ESTÁVEL

bd_dados_analises = bd_dados_completos_limpar_colunas_diarias.copy()

# var_margem_estavel = 0.02
var_margem_estavel = 0
var_coluna_objetivo = "Resultado"

bd_dados_analises.loc[bd_dados_analises["Alfa HLC; últimos 13 dias"] > var_margem_estavel, var_coluna_objetivo] = "Subiu"
bd_dados_analises.loc[bd_dados_analises["Alfa HLC; últimos 13 dias"] < -1*var_margem_estavel, var_coluna_objetivo] = "Desceu"
bd_dados_analises.loc[
    (bd_dados_analises["Alfa HLC; últimos 13 dias"] <= var_margem_estavel) * (bd_dados_analises["Alfa HLC; últimos 13 dias"] >= -1*var_margem_estavel), 
    var_coluna_objetivo] = "Estável"

display(bd_dados_analises[["Alfa HLC; últimos 13 dias", "Resultado"]].head(20))
bd_dados_analises = bd_dados_analises.drop(["Alfa HLC; últimos 13 dias"], axis = 1)

display(bd_dados_analises["Resultado"].value_counts())

        Alfa HLC; últimos 13 dias Resultado
Ticker
COGN3                        0.03     Subiu
PETR4                       -0.52    Desceu
HAPV3                        0.00     Subiu
ABEV3                        0.02     Subiu
MGLU3                       -0.05    Desceu
LWSA3                        0.05     Subiu
ITSA4                        0.05     Subiu
BBDC4                        0.03     Subiu
ANIM3                        0.04     Subiu
PCAR3                        0.06     Subiu
VALE3                       -0.23    Desceu
MRVE3                        0.00     Subiu
HBSA3                        0.02     Subiu
CSAN3                       -0.04    Desceu
ITUB4                        0.12     Subiu
BBAS3                       -0.06    Desceu
CVCB3                        0.01     Subiu
B3SA3                       -0.02    Desceu
BEEF3                        0.06     Subiu
YDUQ3                        0.16     Subiu

Resultado
Subiu     134
Desceu    112
Name: count, dtype: int64

## Treinamento e score

In [194]:
var_modelo_treinado_DecisionTreeClassifier = treina_e_roda_modelo(
    dados = bd_dados_analises,
    colunas_treino = bd_dados_analises.drop(var_coluna_objetivo, axis = 1).columns,
    coluna_resultado = var_coluna_objetivo,
    
    estimador = "DecisionTreeClassifier",
    proporcao = 0.10,
    SEED = 42,
    print_tamanho = True,
    print_score = True,
    print_confusion_matrix = False,
    
    DummyClassifier__estrategia = None,
    
    DecisionTreeClassifier__retornar_visualizacao = False,
    DecisionTreeClassifier__max_depth = None,
    
    RandomForestClassifier__n_estimators = 100,
    
    feature_selection = None,
    scaler = None,
)

# type(modelo)
# modelo.fit(x_treino, y_treino)

Tamanho treino: 221
Tamanho teste: 25
DecisionTreeClassifier()
Taxa de acerto do modelo DecisionTreeClassifier: 76.00%

## Análise do modelo

In [195]:
# [
#     modelo, 
#     [original_x_treino, original_x_teste, y_treino, y_teste], 
#     [x_treino, x_teste], 
#     feature_selection,
#     taxa_de_acerto
# ]

tabela_resultado = pd.DataFrame(var_modelo_treinado_DecisionTreeClassifier[1][3])
tabela_resultado = tabela_resultado.rename(columns = {"Resultado": "Resultado esperado"})

tabela_resultado["Resultado gerado"] = list(var_modelo_treinado_DecisionTreeClassifier[0].predict(
    var_modelo_treinado_DecisionTreeClassifier[1][1]))

sum(tabela_resultado["Resultado gerado"] == tabela_resultado["Resultado esperado"])/len(tabela_resultado)

# tabela_resultado

0.76

# [MODELO 2] Dummy

## Treinamento e score

In [196]:
var_modelo_treinado_Dummy = treina_e_roda_modelo(
    dados = bd_dados_analises,
    colunas_treino = bd_dados_analises.drop(var_coluna_objetivo, axis = 1).columns,
    coluna_resultado = var_coluna_objetivo,
    
    estimador = "Dummy",
    proporcao = 0.10,
    SEED = 42,
    print_tamanho = True,
    print_score = True,
    print_confusion_matrix = False,
    
    DummyClassifier__estrategia = None,
    
    DecisionTreeClassifier__retornar_visualizacao = False,
    DecisionTreeClassifier__max_depth = None,
    
    RandomForestClassifier__n_estimators = 100,
    
    feature_selection = None,
    scaler = None,
)

# type(modelo)
# modelo.fit(x_treino, y_treino)

Tamanho treino: 221
Tamanho teste: 25
DummyClassifier()
Taxa de acerto do modelo Dummy: 52.00%

## Análise do modelo

In [197]:
# [
#     modelo, 
#     [original_x_treino, original_x_teste, y_treino, y_teste], 
#     [x_treino, x_teste], 
#     feature_selection,
#     taxa_de_acerto
# ]

tabela_resultado = pd.DataFrame(var_modelo_treinado_Dummy[1][3])
tabela_resultado = tabela_resultado.rename(columns = {"Resultado": "Resultado esperado"})

tabela_resultado["Resultado gerado"] = list(var_modelo_treinado_Dummy[0].predict(
    var_modelo_treinado_Dummy[1][1]))

# sum(tabela_resultado["Resultado gerado"] == tabela_resultado["Resultado esperado"])/len(tabela_resultado)

tabela_resultado

       Resultado esperado Resultado gerado
Ticker
POMO4               Subiu            Subiu
ITSA4               Subiu            Subiu
AGXY3              Desceu            Subiu
OIBR3              Desceu            Subiu
BLAU3              Desceu            Subiu
KLBN3              Desceu            Subiu
WIZC3              Desceu            Subiu
AZZA3               Subiu            Subiu
PCAR3               Subiu            Subiu
FICT3              Desceu            Subiu
OIBR4              Desceu            Subiu
TAEE4               Subiu            Subiu
RNEW3              Desceu            Subiu
LEVE3               Subiu            Subiu
RCSL4               Subiu            Subiu
SANB4               Subiu            Subiu
BRAP3              Desceu            Subiu
BBAS3              Desceu            Subiu
BMOB3              Desceu            Subiu
AZUL4              Desceu            Subiu
KEPL3               Subiu            Subiu
YDUQ3               Subiu            Subiu
CAML3               Subiu            Subiu
JBSS3               Subiu            Subiu
EUCA4               Subiu            Subiu

# [MODELO 3] RandomForestClassifier

## Treinamento e score

In [198]:
var_modelo_treinado_RandomForestClassifier = treina_e_roda_modelo(
    dados = bd_dados_analises,
    colunas_treino = bd_dados_analises.drop(var_coluna_objetivo, axis = 1).columns,
    coluna_resultado = var_coluna_objetivo,
    
    estimador = "RandomForestClassifier",
    proporcao = 0.10,
    SEED = 42,
    print_tamanho = True,
    print_score = True,
    print_confusion_matrix = False,
    
    DummyClassifier__estrategia = None,
    
    DecisionTreeClassifier__retornar_visualizacao = False,
    DecisionTreeClassifier__max_depth = None,
    
    RandomForestClassifier__n_estimators = 100,
    
    feature_selection = None,
    scaler = None,
)

# type(modelo)
# modelo.fit(x_treino, y_treino)

Tamanho treino: 221
Tamanho teste: 25
RandomForestClassifier()
RandomForestClassifier()
Taxa de acerto do modelo RandomForestClassifier: 72.00%

## Análise do modelo

In [199]:
# [
#     modelo, 
#     [original_x_treino, original_x_teste, y_treino, y_teste], 
#     [x_treino, x_teste], 
#     feature_selection,
#     taxa_de_acerto
# ]

tabela_resultado = pd.DataFrame(var_modelo_treinado_RandomForestClassifier[1][3])
tabela_resultado = tabela_resultado.rename(columns = {"Resultado": "Resultado esperado"})

tabela_resultado["Resultado gerado"] = list(var_modelo_treinado_RandomForestClassifier[0].predict(
    var_modelo_treinado_RandomForestClassifier[1][1]))

# sum(tabela_resultado["Resultado gerado"] == tabela_resultado["Resultado esperado"])/len(tabela_resultado)

tabela_resultado

       Resultado esperado Resultado gerado
Ticker
POMO4               Subiu           Desceu
ITSA4               Subiu            Subiu
AGXY3              Desceu           Desceu
OIBR3              Desceu           Desceu
BLAU3              Desceu           Desceu
KLBN3              Desceu           Desceu
WIZC3              Desceu           Desceu
AZZA3               Subiu            Subiu
PCAR3               Subiu            Subiu
FICT3              Desceu           Desceu
OIBR4              Desceu           Desceu
TAEE4               Subiu            Subiu
RNEW3              Desceu           Desceu
LEVE3               Subiu            Subiu
RCSL4               Subiu           Desceu
SANB4               Subiu           Desceu
BRAP3              Desceu           Desceu
BBAS3              Desceu            Subiu
BMOB3              Desceu            Subiu
AZUL4              Desceu           Desceu
KEPL3               Subiu           Desceu
YDUQ3               Subiu            Subiu
CAML3               Subiu            Subiu
JBSS3               Subiu            Subiu
EUCA4               Subiu           Desceu

# Modelo com regressão

In [ ]:
# # SE A VARIÁVEL OBJETIVO FOR CONTÍNUA, PODEMOS USAR O PREÇO, COMO NESSE CASO

# var_coluna_objetivo = bd_dados_completos_limpar_object[[item for item in bd_dados_completos_limpar_object.columns.to_list() if "; Close" in item]]

# var_coluna_objetivo = var_coluna_objetivo.columns[-1]

# var_coluna_objetivo