# Bibliotecas

## Sistema (os, makedirs, glob)

In [5]:
from os import makedirs
import os
import glob

## Básicos (numpy, math, display, locale, time, random, re)

In [6]:
# !python -m pip install jupyter


# !python -m pip install IPython
from IPython.display import display

import math

# !python -m pip install numpy
import numpy as np

import locale
# locale.setlocale(locale.LC_ALL, "pt_BR.UTF-8")  # Use "" for auto, or force e.g. to "en_US.UTF-8"

import time
from datetime import datetime, timedelta, date

from pandas.tseries.offsets import BDay # para os dias úteis
# today = datetime.datetime.today()
# print(today - BDay(4)) # 4 dias úteis atrás

# # !python -m pip install random
import random
random.seed(42)

# !python -m pip install regex
import re

## Leitura e análise de dados (Excel, Pandas, Spark)

In [7]:
# !python -m pip install findspark

# !python -m pip install openpyxl
# import openpyxl

# !python -m pip install xlsxwriter
# import xlsxwriter

# !python -m pip install xlrd
# import xlrd

# !python -m pip install python-calamine
# import python_calamine


# !python -m pip install pandas
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
# pd.set_option('display.float_format', lambda x: '%.2f' % x)

## Finanças (yfinance, mplfinance)

In [131]:
# https://pypi.org/project/yfinance/
# https://github.com/ranaroussi/yfinance/wiki/Ticker

# !python -m pip install yfinance
import yfinance as yf

# !python -m pip install mplfinance
# import mplfinance as mpf

# # Em R
# # https://cran.r-project.org/web/packages/BatchGetSymbols/index.html

# Funções

## _criar_regressao_bd_acao_, _processar_regressao_e_lista_de_indicadores_, _candle_plot_, _plota_candlestick_acha_martelos_

In [9]:
# https://stackoverflow.com/questions/4383571/importing-files-from-different-folder

import sys
# caution: path[0] is reserved for script path (or '' in REPL)
sys.path.insert(1, r'C:\Users\ricardopeloi\OneDrive - falconi365\Data Science\O_Mais_Novo_Day_Trader_do_Brasil\o_mais_novo_day_trader_do_brasil')

# Refazendo arquivos

## 1. ler_listaB3 e bd_lista_acoes

In [ ]:
# import importlib
# try:
    # importlib.reload(sys.modules['receber_lista_atualizada_tickers'])
# except:
    # pass
# from receber_lista_atualizada_tickers import ler_lista_B3

# var_caminho = r"C:\Users\ricardopeloi\OneDrive - falconi365\Data Science\O_Mais_Novo_Day_Trader_do_Brasil\o_mais_novo_day_trader_do_brasil\Bases"
# bd_lista_acoes = ler_lista_B3(var_caminho)

# bd_lista_acoes

In [ ]:
# bd_lista_acoes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 403 entries, AZUL4 to BAUH4
Data columns (total 3 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Nome da Empresa                    403 non-null    object
 1   Volume no último dia útil          403 non-null    int64
 2   Data da leitura (último dia útil)  403 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(1), object(1)
memory usage: 12.6+ KB

## 2. tratar_lista_B3 e bd_lista_acoes_tratada

In [ ]:
# bd_lista_acoes_tratada_original = pd.read_excel(var_caminho + '/Lista de ações Tratada.xlsx')

# # var_coluna_volume = [item for item in bd_lista_acoes_tratada_original.columns if item.startswith("Volume no último dia útil")][0]

# # var_data_ultima_leitura = datetime.strptime(var_coluna_volume.split("lido em")[1].split(")")[0].strip(), "%d/%m/%Y")

# # bd_lista_acoes_tratada_original = bd_lista_acoes_tratada_original.rename(columns = {var_coluna_volume: "Volume no último dia útil"})
# # bd_lista_acoes_tratada_original["Data da leitura (último dia útil)"] = var_data_ultima_leitura

# bd_lista_acoes_tratada_original#.info()

,Ticker,Nome da Empresa,Volume no último dia útil,industry,sector,fullTimeEmployees,dividendRate,dividendYield,exDividendDate,payoutRatio,...,operatingMargins,epsTrailingTwelveMonths,epsForward,epsCurrentYear,priceEpsCurrentYear,fiftyDayAverageChange,fiftyDayAverageChangePercent,twoHundredDayAverageChange,twoHundredDayAverageChangePercent,Data da leitura (último dia útil)
0,COGN3,Cogna,111753600,Education & Training Services,Consumer Defensive,"24,187.00",0.26,10.70,"1,745,884,800.00",0.00,...,0.35,0.46,0.18,0.26,9.31,0.59,0.31,0.97,0.65,2025-04-19
1,PETR4,Petrobras,65752700,Oil & Gas Integrated,Energy,"41,778.00",7.09,22.98,"1,744,848,000.00",2.01,...,0.10,3.40,8.04,8.01,3.85,-4.69,-0.13,-6.05,-0.16,2025-04-19
2,HAPV3,Hapvida,57331500,Insurance - Life,Financial Services,NaN,NaN,NaN,"1,640,649,600.00",0.00,...,-0.01,-0.09,0.29,0.20,10.76,-0.06,-0.03,-0.96,-0.31,2025-04-19
3,ABEV3,Ambev,56058800,Beverages - Brewers,Consumer Defensive,"43,000.00",0.80,5.68,"1,742,169,600.00",0.73,...,0.28,0.91,0.97,1.00,13.97,1.24,0.10,1.49,0.12,2025-04-19
4,MGLU3,Magazine Luiza,26837300,Specialty Retail,Consumer Cyclical,NaN,0.31,2.99,"1,745,798,400.00",0.00,...,0.03,0.61,0.61,0.49,20.67,1.23,0.14,0.73,0.08,2025-04-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,LOGN3,Log-In,24500,Marine Shipping,Industrials,NaN,NaN,NaN,"1,237,334,400.00",0.00,...,0.17,1.41,2.22,0.86,24.71,-0.10,-0.00,-5.79,-0.21,2025-04-19
244,BIOM3,Biomm,23700,Biotechnology,Healthcare,NaN,NaN,NaN,NaN,0.00,...,-0.61,-0.63,NaN,NaN,NaN,-0.10,-0.01,0.23,0.02,2025-04-19
245,PTNT4,Pettenati,21300,Apparel Manufacturing,Consumer Cyclical,NaN,0.27,4.20,"1,730,246,400.00",0.42,...,0.07,0.65,NaN,NaN,NaN,-0.90,-0.12,-0.17,-0.03,2025-04-19
246,ALUP4,Alupar,20200,Utilities - Renewable,Utilities,906.00,0.32,3.36,"1,744,848,000.00",0.42,...,0.61,1.11,NaN,NaN,NaN,0.33,0.04,0.26,0.03,2025-04-19
247,KRSA3,Kora Saúde,20000,Medical Care Facilities,Healthcare,NaN,NaN,NaN,NaN,0.00,...,0.10,-0.23,1.03,NaN,NaN,0.14,0.02,1.77,0.25,2025-04-19

In [ ]:
# import importlib
# try:
    # importlib.reload(sys.modules['receber_lista_atualizada_tickers'])
# except:
    # pass
# from receber_lista_atualizada_tickers import tratar_lista_B3

# # bd_lista_acoes_tratada = tratar_lista_B3(bd_lista_acoes.iloc[:5, :], var_caminho)
# bd_lista_acoes_tratada = tratar_lista_B3(bd_lista_acoes, var_caminho)

# bd_lista_acoes_tratada
# # bd_lista_acoes_tratada.info()

=== LENDO DADOS DA AÇÃO ===
1 de 403; AZUL4
2 de 403; CRFB3
3 de 403; HAPV3
4 de 403; COGN3
5 de 403; B3SA3
6 de 403; ITSA4
7 de 403; PETR4
8 de 403; ITUB4
9 de 403; BEEF3
10 de 403; BBDC4
11 de 403; VALE3
12 de 403; CMIG4
13 de 403; ABEV3
14 de 403; RAIZ4
15 de 403; MGLU3
16 de 403; BBAS3
17 de 403; USIM5
18 de 403; CYRE3
19 de 403; LREN3
20 de 403; CPLE6
21 de 403; PCAR3
22 de 403; GGBR4
23 de 403; CSAN3
24 de 403; CCRO3
25 de 403; POMO4
26 de 403; PRIO3
27 de 403; SUZB3
28 de 403; CVCB3
29 de 403; RENT3
30 de 403; RAIL3
31 de 403; LWSA3
32 de 403; IFCM3
33 de 403; BRFS3
34 de 403; MRVE3
35 de 403; VAMO3
36 de 403; WEGE3
37 de 403; MULT3
38 de 403; PETR3
39 de 403; TIMS3
40 de 403; PETZ3
41 de 403; JBSS3
42 de 403; VBBR3
43 de 403; ELET3
44 de 403; CASH3
45 de 403; MRFG3
46 de 403; SRNA3
47 de 403; BRAP4
48 de 403; BPAC11
49 de 403; GOAU4
50 de 403; EQTL3
51 de 403; ENEV3
52 de 403; ANIM3
53 de 403; ASAI3
54 de 403; MOVI3
55 de 403; KLBN11
56 de 403; CSNA3
57 de 403; RDOR3
58 de 403; AZEV4
59 de 403; CPLE3
60 de 403; NTCO3
61 de 403; RADL3
62 de 403; CXSE3
63 de 403; AZTE3
64 de 403; AURE3
65 de 403; BBDC3
66 de 403; RECV3
67 de 403; CMIN3
68 de 403; GFSA3
69 de 403; ALOS3
70 de 403; BRAV3
71 de 403; HYPE3
72 de 403; VIVT3
73 de 403; AMOB3
74 de 403; ECOR3
75 de 403; YDUQ3
76 de 403; OIBR3
77 de 403; JHSF3
78 de 403; TEND3
79 de 403; GMAT3
80 de 403; ENGI11
81 de 403; SIMH3
82 de 403; UGPA3
83 de 403; VIVA3
84 de 403; SBSP3
85 de 403; STBP3
86 de 403; CEAB3
87 de 403; EMBR3
88 de 403; BBSE3
89 de 403; SLCE3
90 de 403; BRKM5
91 de 403; SMFT3
92 de 403; CBAV3
93 de 403; BHIA3
94 de 403; ONCO3
95 de 403; ISAE4
96 de 403; CURY3
97 de 403; EZTC3
98 de 403; TAEE11
99 de 403; KEPL3
100 de 403; SAPR4
101 de 403; RCSL4
102 de 403; SANB11
103 de 403; RAPT4
104 de 403; FLRY3
105 de 403; TOTS3
106 de 403; AZZA3
107 de 403; GOLL4
108 de 403; SMTO3
109 de 403; HBSA3
110 de 403; ENJU3
111 de 403; SBFG3
112 de 403; AMER3
113 de 403; DIRR3
114 de 403; IGTI11
115 de 403; PMAM3
116 de 403; TTEN3
117 de 403; AZEV3
118 de 403; CAML3
119 de 403; GGPS3
120 de 403; SEER3
121 de 403; GRND3
122 de 403; TUPY3
123 de 403; SAPR11
124 de 403; ELET6
125 de 403; PSSA3
126 de 403; QUAL3
127 de 403; BRSR6
128 de 403; EGIE3
129 de 403; ODPV3
130 de 403; ALPA4
131 de 403; CSMG3
132 de 403; INTB3
133 de 403; DXCO3
134 de 403; ZAMP3
135 de 403; MLAS3
136 de 403; KLBN4
137 de 403; GUAR3
138 de 403; ALUP11
139 de 403; IRBR3
140 de 403; CPFE3
141 de 403; LAVV3
142 de 403; CSED3
143 de 403; EVEN3
144 de 403; BMOB3
145 de 403; TFCO4
146 de 403; LJQQ3
147 de 403; MYPK3
148 de 403; VVEO3
149 de 403; PLPL3
150 de 403; NEOE3
151 de 403; MTRE3
152 de 403; HBOR3
153 de 403; SHUL4
154 de 403; MELK3
155 de 403; MDNE3
156 de 403; MILS3
157 de 403; ABCB4
158 de 403; RANI3
159 de 403; POSI3
160 de 403; ORVR3
161 de 403; MDIA3
162 de 403; JALL3
163 de 403; FIQE3
164 de 403; PTBL3
165 de 403; BPAN4
166 de 403; SOJA3
167 de 403; ITUB3
168 de 403; PGMN3
169 de 403; JSLG3
170 de 403; SHOW3
171 de 403; VULC3
172 de 403; PDGR3
173 de 403; ARML3
174 de 403; POMO3
175 de 403; USIM3
176 de 403; ELMD3
177 de 403; LIGT3
178 de 403; TRIS3
179 de 403; VTRU3
180 de 403; KLBN3
181 de 403; PRNR3
182 de 403; PINE4
183 de 403; SEQL3
184 de 403; WIZC3
185 de 403; MATD3
186 de 403; RNEW4
187 de 403; SYNE3
188 de 403; PFRM3
189 de 403; MEAL3
190 de 403; RCSL3
191 de 403; ESPA3
192 de 403; BRAP3
193 de 403; PNVL3
194 de 403; OPCT3
195 de 403; LEVE3
196 de 403; DESK3
197 de 403; PORT3
198 de 403; TGMA3
199 de 403; CMIG3
200 de 403; LOGG3
201 de 403; FRAS3
202 de 403; AERI3
203 de 403; TCSA3
204 de 403; SAPR3
205 de 403; TAEE4
206 de 403; DASA3
207 de 403; TASA4
208 de 403; BLAU3
209 de 403; FESA4
210 de 403; BRBI11
211 de 403; BRST3
212 de 403; VITT3
213 de 403; BMGB4
214 de 403; HBRE3
215 de 403; AGRO3
216 de 403; MBLY3
217 de 403; VLID3
218 de 403; INEP3
219 de 403; RNEW3
220 de 403; AGXY3
221 de 403; SANB4
222 de 403; AMAR3
223 de 403; ROMI3
224 de 403; TAEE3
225 de 403; LPSB3
226 de 403; IGTI3
227 de 403; DEXP3
228 de 403; TECN3
229 de 403; INEP4
230 de 403; ALPK3
231 de 403; AALR3
232 de 403; VSTE3
233 de 403; SANB3
234 de 403; RNEW11
235 de 403; VIVR3
236 de 403; CSUD3
237 de 403; ITSA3
238 de 403; AMBP3
239 de 403; DMVF3
240 de 403; ALLD3
241 de 403; OIBR4
242 de 403; EUCA4
243 de 403; PDTC3
244 de 403; ENGI4
245 de 403; UNIP6
246 de 403; TRAD3
247 de 403; GOAU3
248 de 403; ETER3
249 de 403; TPIS3
250 de 403; CAMB3
251 de 403; LVTC3
252 de 403; SCAR3
253 de 403; LUPA3
254 de 403; BIOM3
255 de 403; BOBR4
256 de 403; PTNT4
257 de 403; DEXP4
258 de 403; UCAS3
259 de 403; ATED3
260 de 403; RSID3
261 de 403; CTSA4
262 de 403; GGBR3
263 de 403; OFSA3
264 de 403; COCE5
265 de 403; BEES3
266 de 403; ALUP4
267 de 403; BRKM3
268 de 403; LAND3
269 de 403; EQPA3
270 de 403; BRSR3
271 de 403; ENGI3
272 de 403; BMEB4
273 de 403; CEBR6
274 de 403; CEBR5
275 de 403; RAPT3
276 de 403; CEBR3
277 de 403; EALT4
278 de 403; EPAR3
279 de 403; DOTZ3
280 de 403; TASA3
281 de 403; ATMP3
282 de 403; AMAR11
283 de 403; ALPA3
284 de 403; ALUP3
285 de 403; NGRD3
286 de 403; BPAC5
287 de 403; OSXB3
288 de 403; WLMM4
289 de 403; HAGA4
290 de 403; LOGN3
291 de 403; CGRA4
292 de 403; BPAC3
293 de 403; JFEN3
294 de 403; UNIP3
295 de 403; WHRL4
296 de 403; FHER3
297 de 403; EMAE4
298 de 403; BSLI3
299 de 403; HOOT4
300 de 403; RDNI3
301 de 403; BIED3
302 de 403; BGIP4
303 de 403; NEXP3
304 de 403; AZEV11
305 de 403; CLSC4
306 de 403; ISAE3
307 de 403; AVLL3
308 de 403; CGRA3
309 de 403; RPMG3
310 de 403; BAZA3
311 de 403; BSLI4
312 de 403; REDE3
313 de 403; SNSY5
314 de 403; PINE3
315 de 403; DOHL4
316 de 403; CTSA3
317 de 403; TELB4
318 de 403; REAG3
319 de 403; FICT3
320 de 403; MOAR3
321 de 403; BEES4
322 de 403; NUTR3
323 de 403; WEST3
324 de 403; MTSA4
325 de 403; CRPG5
326 de 403; MNDL3
327 de 403; FIEI3
328 de 403; BMEB3
329 de 403; HAGA3
330 de 403; PATI4
331 de 403; RPAD3
332 de 403; WHRL3
333 de 403; DTCY3
334 de 403; PEAB3
335 de 403; GEPA3
336 de 403; HBTS5
337 de 403; MGEL4
338 de 403; CRPG6
339 de 403; FRIO3
340 de 403; CGAS5
341 de 403; RSUL4
342 de 403; SOND6
343 de 403; CTKA4
344 de 403; JOPA3
345 de 403; BMIN3
346 de 403; BRSR5
347 de 403; BALM3
348 de 403; TELB3
349 de 403; BALM4
350 de 403; CPLE5
351 de 403; AFLT3
352 de 403; GSHP3
353 de 403; NORD3
354 de 403; ESTR4
355 de 403; BMKS3
356 de 403; PPLA11
357 de 403; EQPA5
358 de 403; CEDO4
359 de 403; CEEB3
360 de 403; MNPR3
361 de 403; EUCA3
362 de 403; IGTI4
363 de 403; RPAD5
364 de 403; GEPA4
365 de 403; CEDO3
366 de 403; EALT3
367 de 403; SNSY3
368 de 403; MAPT4
369 de 403; BNBR3
370 de 403; CLSC3
371 de 403; UNIP5
372 de 403; EKTR4
373 de 403; SOND5
374 de 403; MRSA3B
375 de 403; BDLL3
376 de 403; ENMT3
377 de 403; MWET4
378 de 403; WLMM3
379 de 403; PLAS3
380 de 403; PATI3
381 de 403; MRSA5B
382 de 403; CRPG3
383 de 403; PTNT3
384 de 403; HETA4
385 de 403; MERC4
386 de 403; RPAD6
387 de 403; BMIN4
388 de 403; DASA11

404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/DASA11.SA?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=DASA11.SA&crumb=dA.Qhj35YWw

389 de 403; FESA3
390 de 403; ENMT4
391 de 403; EQMA3B
392 de 403; AHEB3
393 de 403; COCE3
394 de 403; BDLL4
395 de 403; USIM6
396 de 403; MAPT3
397 de 403; TKNO4
398 de 403; GPAR3
399 de 403; CGAS3
400 de 403; AHEB6
401 de 403; LUXM4
402 de 403; KRSA3
403 de 403; BAUH4
=== FIM LEITURA DOS DADOS DA AÇÃO ===

,Ticker,Nome da Empresa,Volume no último dia útil,Data da leitura (último dia útil),industry,sector,fullTimeEmployees,dividendRate,dividendYield,exDividendDate,...,ebitdaMargins,operatingMargins,epsTrailingTwelveMonths,epsForward,epsCurrentYear,priceEpsCurrentYear,fiftyDayAverageChange,fiftyDayAverageChangePercent,twoHundredDayAverageChange,twoHundredDayAverageChangePercent
0,AZUL4,Azul,282174900,2025-04-26 13:14:47.711249,Airlines,Industrials,"15,367.00",NaN,NaN,NaN,...,0.18,0.18,-0.35,-0.96,-1.53,-1.28,-1.52,-0.44,-2.95,-0.60
1,CRFB3,Carrefour Brasil,65204900,2025-04-26 13:14:47.711249,Department Stores,Consumer Cyclical,NaN,0.10,1.11,"1,745,971,200.00",...,0.05,0.04,0.83,0.79,0.59,14.70,0.95,0.12,1.07,0.14
2,HAPV3,Hapvida,64731600,2025-04-26 13:14:47.711249,Insurance - Life,Financial Services,NaN,NaN,NaN,"1,640,649,600.00",...,0.07,-0.01,-0.09,0.29,0.20,12.01,0.20,0.09,-0.67,-0.22
3,COGN3,Cogna,37935400,2025-04-26 13:14:47.711249,Education & Training Services,Consumer Defensive,"24,187.00",0.26,10.48,"1,745,884,800.00",...,0.24,0.35,0.46,0.18,0.28,9.07,0.55,0.28,1.00,0.67
4,B3SA3,B3,37609700,2025-04-26 13:14:47.711249,Financial Data & Stock Exchanges,Financial Services,NaN,0.25,1.88,"1,742,947,200.00",...,0.66,0.63,0.83,0.93,0.90,14.86,1.62,0.14,2.27,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,BIOM3,Biomm,27500,2025-04-26 13:14:47.711249,Biotechnology,Healthcare,NaN,NaN,NaN,NaN,...,-0.49,-0.61,-0.63,NaN,NaN,NaN,0.26,0.03,0.70,0.07
254,BOBR4,Bombril,25300,2025-04-26 13:14:47.711249,Household & Personal Products,Consumer Defensive,"2,390.00",NaN,NaN,NaN,...,0.14,0.11,0.28,NaN,NaN,NaN,0.00,0.00,-0.39,-0.19
255,PTNT4,Pettenati,23100,2025-04-26 13:14:47.711249,Apparel Manufacturing,Consumer Cyclical,NaN,0.27,4.46,"1,730,246,400.00",...,0.10,0.07,0.65,NaN,NaN,NaN,-1.21,-0.17,-0.55,-0.08
256,DEXP4,Dexxos,20200,2025-04-26 13:14:47.711249,Chemicals,Basic Materials,NaN,0.86,10.95,"1,745,884,800.00",...,0.14,0.09,1.41,NaN,NaN,NaN,-0.26,-0.03,-0.90,-0.10
257,UCAS3,Unicasa,20100,2025-04-26 13:14:47.711249,"Furnishings, Fixtures & Appliances",Consumer Cyclical,516.00,0.18,11.49,"1,733,443,200.00",...,0.07,-0.02,0.19,0.30,NaN,NaN,0.09,0.06,-0.33,-0.17

In [ ]:
# bd_lista_acoes_tratada_original = pd.read_excel(var_caminho + '/Lista de ações Tratada.xlsx')

# bd_lista_acoes_tratada_empilhada = pd.concat([bd_lista_acoes_tratada_original, bd_lista_acoes_tratada]).drop_duplicates(subset = ["Ticker", "Data da leitura (último dia útil)"]) \

# # bd_lista_acoes_tratada_empilhada.to_excel(var_caminho + '/Lista de ações Tratada.xlsx', index = False)

# bd_lista_acoes_tratada_empilhada

,Ticker,Nome da Empresa,Volume no último dia útil,industry,sector,fullTimeEmployees,dividendRate,dividendYield,exDividendDate,payoutRatio,...,operatingMargins,epsTrailingTwelveMonths,epsForward,epsCurrentYear,priceEpsCurrentYear,fiftyDayAverageChange,fiftyDayAverageChangePercent,twoHundredDayAverageChange,twoHundredDayAverageChangePercent,Data da leitura (último dia útil)
0,COGN3,Cogna,111753600,Education & Training Services,Consumer Defensive,"24,187.00",0.26,10.70,"1,745,884,800.00",0.00,...,0.35,0.46,0.18,0.26,9.31,0.59,0.31,0.97,0.65,2025-04-19 00:00:00.000000
1,PETR4,Petrobras,65752700,Oil & Gas Integrated,Energy,"41,778.00",7.09,22.98,"1,744,848,000.00",2.01,...,0.10,3.40,8.04,8.01,3.85,-4.69,-0.13,-6.05,-0.16,2025-04-19 00:00:00.000000
2,HAPV3,Hapvida,57331500,Insurance - Life,Financial Services,NaN,NaN,NaN,"1,640,649,600.00",0.00,...,-0.01,-0.09,0.29,0.20,10.76,-0.06,-0.03,-0.96,-0.31,2025-04-19 00:00:00.000000
3,ABEV3,Ambev,56058800,Beverages - Brewers,Consumer Defensive,"43,000.00",0.80,5.68,"1,742,169,600.00",0.73,...,0.28,0.91,0.97,1.00,13.97,1.24,0.10,1.49,0.12,2025-04-19 00:00:00.000000
4,MGLU3,Magazine Luiza,26837300,Specialty Retail,Consumer Cyclical,NaN,0.31,2.99,"1,745,798,400.00",0.00,...,0.03,0.61,0.61,0.49,20.67,1.23,0.14,0.73,0.08,2025-04-19 00:00:00.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,BIOM3,Biomm,27500,Biotechnology,Healthcare,NaN,NaN,NaN,NaN,0.00,...,-0.61,-0.63,NaN,NaN,NaN,0.26,0.03,0.70,0.07,2025-04-26 13:14:47.711249
254,BOBR4,Bombril,25300,Household & Personal Products,Consumer Defensive,"2,390.00",NaN,NaN,NaN,0.00,...,0.11,0.28,NaN,NaN,NaN,0.00,0.00,-0.39,-0.19,2025-04-26 13:14:47.711249
255,PTNT4,Pettenati,23100,Apparel Manufacturing,Consumer Cyclical,NaN,0.27,4.46,"1,730,246,400.00",0.42,...,0.07,0.65,NaN,NaN,NaN,-1.21,-0.17,-0.55,-0.08,2025-04-26 13:14:47.711249
256,DEXP4,Dexxos,20200,Chemicals,Basic Materials,NaN,0.86,10.95,"1,745,884,800.00",0.52,...,0.09,1.41,NaN,NaN,NaN,-0.26,-0.03,-0.90,-0.10,2025-04-26 13:14:47.711249
257,UCAS3,Unicasa,20100,"Furnishings, Fixtures & Appliances",Consumer Cyclical,516.00,0.18,11.49,"1,733,443,200.00",0.96,...,-0.02,0.19,0.30,NaN,NaN,0.09,0.06,-0.33,-0.17,2025-04-26 13:14:47.711249

### Check da base gerada

In [ ]:
# bd_lista_acoes_tratada_empilhada_import = pd.read_excel(var_caminho + "/Lista de ações Tratada.xlsx")
# bd_lista_acoes_tratada_empilhada_import

,Ticker,Nome da Empresa,Volume no último dia útil,Data da leitura (último dia útil),industry,sector,fullTimeEmployees,dividendRate,dividendYield,exDividendDate,...,ebitdaMargins,operatingMargins,epsTrailingTwelveMonths,epsForward,epsCurrentYear,priceEpsCurrentYear,fiftyDayAverageChange,fiftyDayAverageChangePercent,twoHundredDayAverageChange,twoHundredDayAverageChangePercent
0,COGN3,Cogna,111753600,2025-04-19,Education & Training Services,Consumer Defensive,"24,187.00",0.26,10.70,"1,745,884,800.00",...,0.24,0.35,0.46,0.18,0.26,9.31,0.59,0.31,0.97,0.65
1,PETR4,Petrobras,65752700,2025-04-19,Oil & Gas Integrated,Energy,"41,778.00",7.09,22.98,"1,744,848,000.00",...,0.40,0.10,3.40,8.04,8.01,3.85,-4.69,-0.13,-6.05,-0.16
2,HAPV3,Hapvida,57331500,2025-04-19,Insurance - Life,Financial Services,NaN,NaN,NaN,"1,640,649,600.00",...,0.07,-0.01,-0.09,0.29,0.20,10.76,-0.06,-0.03,-0.96,-0.31
3,ABEV3,Ambev,56058800,2025-04-19,Beverages - Brewers,Consumer Defensive,"43,000.00",0.80,5.68,"1,742,169,600.00",...,0.30,0.28,0.91,0.97,1.00,13.97,1.24,0.10,1.49,0.12
4,MGLU3,Magazine Luiza,26837300,2025-04-19,Specialty Retail,Consumer Cyclical,NaN,0.31,2.99,"1,745,798,400.00",...,0.04,0.03,0.61,0.61,0.49,20.67,1.23,0.14,0.73,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,LOGN3,Log-In,24500,2025-04-19,Marine Shipping,Industrials,NaN,NaN,NaN,"1,237,334,400.00",...,0.19,0.17,1.41,2.22,0.86,24.71,-0.10,-0.00,-5.79,-0.21
244,BIOM3,Biomm,23700,2025-04-19,Biotechnology,Healthcare,NaN,NaN,NaN,NaN,...,-0.49,-0.61,-0.63,NaN,NaN,NaN,-0.10,-0.01,0.23,0.02
245,PTNT4,Pettenati,21300,2025-04-19,Apparel Manufacturing,Consumer Cyclical,NaN,0.27,4.20,"1,730,246,400.00",...,0.10,0.07,0.65,NaN,NaN,NaN,-0.90,-0.12,-0.17,-0.03
246,ALUP4,Alupar,20200,2025-04-19,Utilities - Renewable,Utilities,906.00,0.32,3.36,"1,744,848,000.00",...,0.73,0.61,1.11,NaN,NaN,NaN,0.33,0.04,0.26,0.03
247,KRSA3,Kora Saúde,20000,2025-04-19,Medical Care Facilities,Healthcare,NaN,NaN,NaN,NaN,...,0.18,0.10,-0.23,1.03,NaN,NaN,0.14,0.02,1.77,0.25

In [ ]:
# bd_lista_acoes_tratada_empilhada_import["Data da leitura (último dia útil)"].unique()

# bd_lista_acoes_tratada_empilhada_import = bd_lista_acoes_tratada_empilhada_import[~(bd_lista_acoes_tratada_empilhada_import["Data da leitura (último dia útil)"].isin(["2025-04-26 14:47:13.250000", "2025-04-26 13:14:47.711000"]))]

# bd_lista_acoes_tratada_empilhada_export = bd_lista_acoes_tratada_empilhada_import.copy()

# bd_lista_acoes_tratada_empilhada_export.to_excel(var_caminho + '/Lista de ações Tratada.xlsx', index = False)

C:\Users\ricardopeloi\AppData\Local\Temp\ipykernel_1732\1536113762.py:3: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  bd_lista_acoes_tratada_empilhada_import = bd_lista_acoes_tratada_empilhada_import[~(bd_lista_acoes_tratada_empilhada_import["Data da leitura (último dia útil)"].isin(["2025-04-26 14:47:13.250000", "2025-04-26 13:14:47.711000"]))]

In [ ]:
# # bd_lista_acoes_tratada_empilhada

# bd_lista_acoes_tratada_empilhada_check = pd.pivot_table(
#     # data = bd_lista_acoes_tratada_empilhada[["Ticker", "Volume no último dia útil", "Data da leitura (último dia útil)"]],
#     data = bd_lista_acoes_tratada_empilhada_import[["Ticker", "Volume no último dia útil", "Data da leitura (último dia útil)"]],
#     index = "Ticker",
#     columns = "Data da leitura (último dia útil)",
#     values = "Volume no último dia útil",
#     aggfunc = "sum"
# )

# bd_lista_acoes_tratada_empilhada_check

# # for coluna in bd_lista_acoes_tratada_empilhada_check.columns:
#     # display(bd_lista_acoes_tratada_empilhada_check[bd_lista_acoes_tratada_empilhada_check[coluna].isna()])

Data da leitura (último dia útil)  2025-04-19
Ticker
AALR3                                  166800
ABCB4                                  419600
ABEV3                                56058800
AERI3                                  212100
AGRO3                                  408300
...                                       ...
VVEO3                                 1862900
WEGE3                                 3543500
WIZC3                                  219500
YDUQ3                                16381600
ZAMP3                                  513800

[248 rows x 1 columns]

### Check final com as funções já ajustadas

In [ ]:
# import importlib
# try:
    # importlib.reload(sys.modules['receber_lista_atualizada_tickers'])
# except:
    # pass
# from receber_lista_atualizada_tickers import tratar_lista_B3, ler_lista_B3

# bd_lista_acoes_tratada, bd_lista_acoes_tratada_empilhada = tratar_lista_B3(ler_lista_B3(var_caminho), var_caminho)

# # bd_lista_acoes_tratada
# bd_lista_acoes_tratada_empilhada

=== IDENTIFICANDO AÇÕES ===
AZUL4: Azul
CRFB3: Carrefour Brasil
HAPV3: Hapvida
COGN3: Cogna
B3SA3: B3
ITSA4: Itaúsa
PETR4: Petrobras
ITUB4: Itaú Unibanco
BEEF3: Minerva
BBDC4: Banco Bradesco
VALE3: Vale
CMIG4: Cemig
ABEV3: Ambev
RAIZ4: Raízen
MGLU3: Magazine Luiza
BBAS3: Banco do Brasil
USIM5: Usiminas
CYRE3: Cyrela
LREN3: Lojas Renner
CPLE6: Copel
PCAR3: Grupo Pão de Açúcar
GGBR4: Gerdau
CSAN3: Cosan
CCRO3: Grupo CCR
POMO4: Marcopolo
PRIO3: PetroRio
SUZB3: Suzano
CVCB3: CVC
RENT3: Localiza
RAIL3: Rumo
LWSA3: Locaweb
IFCM3: Infracommerce
BRFS3: BRF
MRVE3: MRV
VAMO3: Grupo Vamos
WEGE3: WEG
MULT3: Multiplan
PETR3: Petrobras
TIMS3: TIM
PETZ3: Petz
JBSS3: JBS
VBBR3: Vibra Energia
ELET3: Eletrobras
CASH3: Méliuz
MRFG3: Marfrig
SRNA3: Serena Energia
BRAP4: Bradespar
BPAC11: Banco BTG Pactual
GOAU4: Metalúrgica Gerdau
EQTL3: Equatorial Energia
ENEV3: Eneva
ANIM3: Ânima Educação
ASAI3: Assaí
MOVI3: Movida
KLBN11: Klabin
CSNA3: Siderúrgica Nacional
RDOR3: Rede D'Or
AZEV4: Azevedo & Travassos
CPLE3: Copel
NTCO3: Natura
RADL3: RaiaDrogasil
CXSE3: Caixa Seguridade
AZTE3: AZT Energia
AURE3: Auren Energia
BBDC3: Banco Bradesco
RECV3: PetroRecôncavo
CMIN3: CSN Mineração
GFSA3: Gafisa
ALOS3: Allos
BRAV3: 3R Petroleum
HYPE3: Hypera
VIVT3: Vivo
AMOB3: Automob
ECOR3: EcoRodovias
YDUQ3: YDUQS
OIBR3: Oi
JHSF3: JHSF
TEND3: Construtora Tenda
GMAT3: Grupo Mateus
ENGI11: Energisa
SIMH3: Simpar
UGPA3: Ultrapar
VIVA3: Vivara
SBSP3: Sabesp
STBP3: Santos Brasil
CEAB3: C&A
EMBR3: Embraer
BBSE3: BB Seguridade
SLCE3: SLC Agrícola
BRKM5: Braskem
SMFT3: Smart Fit
CBAV3: CBA
BHIA3: Casas Bahia
ONCO3: Oncoclínicas
ISAE4: ISA Energia
CURY3: Cury
EZTC3: EZTEC
TAEE11: Taesa
KEPL3: Kepler Weber
SAPR4: Sanepar
RCSL4: Recrusul
SANB11: Banco Santander
RAPT4: Randon
FLRY3: Fleury
TOTS3: Totvs
AZZA3: Arezzo
GOLL4: GOL
SMTO3: São Martinho
HBSA3: Hidrovias do Brasil
ENJU3: Enjoei
SBFG3: Grupo SBF
AMER3: Americanas
DIRR3: Direcional
IGTI11: Iguatemi
IGTI11: Jereissati Participações
PMAM3: Paranapanema
TTEN3: 3tentos
AZEV3: Azevedo & Travassos
CAML3: Camil Alimentos
GGPS3: GPS
SEER3: Ser Educacional
GRND3: Grendene
TUPY3: Tupy
SAPR11: Sanepar
ELET6: Eletrobras
PSSA3: Porto Seguro
QUAL3: Qualicorp
BRSR6: Banrisul
EGIE3: Engie
ODPV3: Odontoprev
ALPA4: Alpargatas
CSMG3: COPASA
INTB3: Intelbras
DXCO3: Dexco
ZAMP3: Zamp
MLAS3: Multilaser
KLBN4: Klabin
GUAR3: Guararapes
ALUP11: Alupar
IRBR3: IRB Brasil RE
CPFE3: CPFL Energia
LAVV3: Lavvi Incorporadora
CSED3: Cruzeiro do Sul Educacional
EVEN3: Even
BMOB3: Bemobi
TFCO4: Track & Field
LJQQ3: Lojas Quero-Quero
MYPK3: Iochpe-Maxion
VVEO3: Viveo
PLPL3: Plano&Plano
NEOE3: Neoenergia
MTRE3: Mitre Realty
HBOR3: Helbor
SHUL4: Schulz
MELK3: Melnick
MDNE3: Moura Dubeux
MILS3: Mills
ABCB4: Banco ABC Brasil
RANI3: Irani
POSI3: Positivo
ORVR3: Orizon
MDIA3: M. Dias Branco
JALL3: Jalles Machado
FIQE3: Unifique
PTBL3: Portobello
BPAN4: Banco Pan
SOJA3: Boa Safra Sementes
ITUB3: Itaú Unibanco
PGMN3: Pague Menos
JSLG3: JSL
SHOW3: Time For Fun
VULC3: Vulcabras
PDGR3: PDG Realty
ARML3: Armac
POMO3: Marcopolo
USIM3: Usiminas
ELMD3: Eletromidia
LIGT3: Light
TRIS3: Trisul
VTRU3: VITRUBREPCOM
KLBN3: Klabin
PRNR3: Priner
PINE4: Banco Pine
SEQL3: Sequoia Logística
WIZC3: Wiz Soluções
MATD3: Mater Dei
RNEW4: Renova Energia
SYNE3: SYN
PFRM3: Profarma
MEAL3: IMC Alimentação
RCSL3: Recrusul
ESPA3: Espaçolaser
BRAP3: Bradespar
PNVL3: Dimed
OPCT3: OceanPact
LEVE3: Mahle Metal Leve
DESK3: Desktop
PORT3: Wilson Sons
TGMA3: Tegma
CMIG3: Cemig
LOGG3: LOG CP
FRAS3: Fras-le
AERI3: Aeris Energy
TCSA3: Tecnisa
SAPR3: Sanepar
TAEE4: Taesa
DASA3: Dasa
TASA4: Taurus
BLAU3: Blau Farmacêutica
FESA4: Ferbasa
BRBI11: BR Partners
BRST3: Brisanet
VITT3: Vittia
BMGB4: Banco BMG
HBRE3: HBR Realty
AGRO3: BrasilAgro
MBLY3: Mobly
VLID3: Valid
INEP3: Inepar
RNEW3: Renova Energia
AGXY3: AgroGalaxy
SANB4: Banco Santander
AMAR3: Lojas Marisa
ROMI3: Indústrias ROMI
TAEE3: Taesa
LPSB3: Lopes
IGTI3: Iguatemi
IGTI3: Jereissati Participações
DEXP3: Dexxos
TECN3: Technos
INEP4: Inepar
ALPK3: Estapar
AALR3: Alliança
VSTE3: LE LIS BLANC
SANB3: Banco Santander
RNEW11: Renova Energia
VIVR3: Viver
CSUD3: CSU Cardsystem
ITSA3: Itaúsa
AMBP3: Ambipar
DMVF3: D1000 Varejo Farma
ALLD3: Allied
OIBR4: Oi
EUCA4: Eucatex
PDTC3: Padtec
ENGI4: Energisa
UNIP6: Unipar
TRAD3: Traders Club
GOAU3: Metalúrgica Gerdau
ETER3: Eternit
TPIS3: Triunfo
CAMB3: Cambuci
LVTC3: WDC Networks
SCAR3: São Carlos
LUPA3: Lupatech
BIOM3: Biomm
BOBR4: Bombril
PTNT4: Pettenati
DEXP4: Dexxos
UCAS3: Unicasa
ATED3: ATOM EDUCAÇÃO E EDITORA S.A.
RSID3: Rossi Residencial
CTSA4: Santanense
GGBR3: Gerdau
OFSA3: Ourofino Saúde Animal
COCE5: Coelce
BEES3: Banestes
ALUP4: Alupar
BRKM3: Braskem
LAND3: Terra Santa
EQPA3: Equatorial Energia Pará
BRSR3: Banrisul
ENGI3: Energisa
BMEB4: Banco Mercantil do Brasil
CEBR6: CEB
CEBR5: CEB
RAPT3: Randon
CEBR3: CEB
EALT4: Electro Aço Altona
EPAR3: Embpar Participações
DOTZ3: Dotz
TASA3: Taurus
ATMP3: Atma
AMAR11: Lojas Marisa
ALPA3: Alpargatas
ALUP3: Alupar
NGRD3: Neogrid
BPAC5: Banco BTG Pactual
OSXB3: OSX Brasil
WLMM4: WLM
HAGA4: Haga
LOGN3: Log-In
CGRA4: Grazziotin
BPAC3: Banco BTG Pactual
JFEN3: João Fortes
UNIP3: Unipar
WHRL4: Whirlpool
FHER3: Fertilizantes Heringer
EMAE4: EMAE
BSLI3: Banco de Brasília
HOOT4: Hotéis Othon
RDNI3: RNI
BIED3: BIED3
BGIP4: Banese
NEXP3: Brasil Brokers
AZEV11: Azevedo & Travassos
CLSC4: Celesc
ISAE3: ISA Energia
AVLL3: Alphaville
CGRA3: Grazziotin
RPMG3: Refinaria de Manguinhos
BAZA3: Banco da Amazônia
BSLI4: Banco de Brasília
REDE3: Rede Energia
SNSY5: Sansuy
PINE3: Banco Pine
DOHL4: Döhler
CTSA3: Santanense
TELB4: Telebras
REAG3: REAG3
FICT3: Fictor Alimentos
MOAR3: Monteiro Aranha
BEES4: Banestes
NUTR3: Nutriplant
WEST3: Westwing
MTSA4: Metisa
CRPG5: Tronox Pigmentos
MNDL3: Mundial
FIEI3: Fica
BMEB3: Banco Mercantil do Brasil
HAGA3: Haga
PATI4: Panatlântica
RPAD3: Alfa Holdings
WHRL3: Whirlpool
DTCY3: Dtcom
PEAB3: Participações Aliança da Bahia
GEPA3: Rio Paranapanema Energia
HBTS5: Habitasul
MGEL4: Mangels
CRPG6: Tronox Pigmentos
FRIO3: Metalfrio
CGAS5: Comgás
RSUL4: Metalúrgica Riosulense
SOND6: Sondotécnica
CTKA4: Karsten
JOPA3: Josapar
BMIN3: Banco Mercantil de Investimentos
BRSR5: Banrisul
BALM3: Baumer
TELB3: Telebras
BALM4: Baumer
CPLE5: Copel
AFLT3: Afluente T
GSHP3: General Shopping & Outlets
NORD3: Nordon
ESTR4: Estrela
BMKS3: Monark
PPLA11: PPLA
EQPA5: Equatorial Energia Pará
CEDO4: Cedro Têxtil
CEEB3: COELBA
MNPR3: Minupar
EUCA3: Eucatex
IGTI4: Jereissati Participações
IGTI4: Iguatemi
RPAD5: Alfa Holdings
GEPA4: Rio Paranapanema Energia
CEDO3: Cedro Têxtil
EALT3: Electro Aço Altona
SNSY3: Sansuy
MAPT4: Cemepe
BNBR3: Banco do Nordeste
CLSC3: Celesc
UNIP5: Unipar
EKTR4: Elektro
SOND5: Sondotécnica
MRSA3B: MRS Logística
BDLL3: Bardella
ENMT3: Energisa MT
MWET4: Wetzel
WLMM3: WLM
PLAS3: Plascar
PATI3: Panatlântica
MRSA5B: MRS Logística
CRPG3: Tronox Pigmentos
PTNT3: Pettenati
HETA4: Hercules
MERC4: Mercantil do Brasil Financeira
RPAD6: Alfa Holdings
BMIN4: Banco Mercantil de Investimentos
DASA11: DASA11
FESA3: Ferbasa
ENMT4: Energisa MT
EQMA3B: Equatorial Maranhão
AHEB3: São Paulo Turismo
COCE3: Coelce
BDLL4: Bardella
USIM6: Usiminas
MAPT3: Cemepe
TKNO4: Tekno
GPAR3: CELGPAR
CGAS3: Comgás
AHEB6: São Paulo Turismo
LUXM4: Trevisa
KRSA3: Kora Saúde
BAUH4: Excelsior
=== 406 AÇÕES IDENTIFICADAS ===
=== LENDO DADOS DA AÇÃO ===
1 de 403; AZUL4
2 de 403; CRFB3
3 de 403; HAPV3
4 de 403; COGN3
5 de 403; B3SA3
6 de 403; ITSA4
7 de 403; PETR4
8 de 403; ITUB4
9 de 403; BEEF3
10 de 403; BBDC4
11 de 403; VALE3
12 de 403; CMIG4
13 de 403; ABEV3
14 de 403; RAIZ4
15 de 403; MGLU3
16 de 403; BBAS3
17 de 403; USIM5
18 de 403; CYRE3
19 de 403; LREN3
20 de 403; CPLE6
21 de 403; PCAR3
22 de 403; GGBR4
23 de 403; CSAN3
24 de 403; CCRO3
25 de 403; POMO4
26 de 403; PRIO3
27 de 403; SUZB3
28 de 403; CVCB3
29 de 403; RENT3
30 de 403; RAIL3
31 de 403; LWSA3
32 de 403; IFCM3
33 de 403; BRFS3
34 de 403; MRVE3
35 de 403; VAMO3
36 de 403; WEGE3
37 de 403; MULT3
38 de 403; PETR3
39 de 403; TIMS3
40 de 403; PETZ3
41 de 403; JBSS3
42 de 403; VBBR3
43 de 403; ELET3
44 de 403; CASH3
45 de 403; MRFG3
46 de 403; SRNA3
47 de 403; BRAP4
48 de 403; BPAC11
49 de 403; GOAU4
50 de 403; EQTL3
51 de 403; ENEV3
52 de 403; ANIM3
53 de 403; ASAI3
54 de 403; MOVI3
55 de 403; KLBN11
56 de 403; CSNA3
57 de 403; RDOR3
58 de 403; AZEV4
59 de 403; CPLE3
60 de 403; NTCO3
61 de 403; RADL3
62 de 403; CXSE3
63 de 403; AZTE3
64 de 403; AURE3
65 de 403; BBDC3
66 de 403; RECV3
67 de 403; CMIN3
68 de 403; GFSA3
69 de 403; ALOS3
70 de 403; BRAV3
71 de 403; HYPE3
72 de 403; VIVT3
73 de 403; AMOB3
74 de 403; ECOR3
75 de 403; YDUQ3
76 de 403; OIBR3
77 de 403; JHSF3
78 de 403; TEND3
79 de 403; GMAT3
80 de 403; ENGI11
81 de 403; SIMH3
82 de 403; UGPA3
83 de 403; VIVA3
84 de 403; SBSP3
85 de 403; STBP3
86 de 403; CEAB3
87 de 403; EMBR3
88 de 403; BBSE3
89 de 403; SLCE3
90 de 403; BRKM5
91 de 403; SMFT3
92 de 403; CBAV3
93 de 403; BHIA3
94 de 403; ONCO3
95 de 403; ISAE4
96 de 403; CURY3
97 de 403; EZTC3
98 de 403; TAEE11
99 de 403; KEPL3
100 de 403; SAPR4
101 de 403; RCSL4
102 de 403; SANB11
103 de 403; RAPT4
104 de 403; FLRY3
105 de 403; TOTS3
106 de 403; AZZA3
107 de 403; GOLL4
108 de 403; SMTO3
109 de 403; HBSA3
110 de 403; ENJU3
111 de 403; SBFG3
112 de 403; AMER3
113 de 403; DIRR3
114 de 403; IGTI11
115 de 403; PMAM3
116 de 403; TTEN3
117 de 403; AZEV3
118 de 403; CAML3
119 de 403; GGPS3
120 de 403; SEER3
121 de 403; GRND3
122 de 403; TUPY3
123 de 403; SAPR11
124 de 403; ELET6
125 de 403; PSSA3
126 de 403; QUAL3
127 de 403; BRSR6
128 de 403; EGIE3
129 de 403; ODPV3
130 de 403; ALPA4
131 de 403; CSMG3
132 de 403; INTB3
133 de 403; DXCO3
134 de 403; ZAMP3
135 de 403; MLAS3
136 de 403; KLBN4
137 de 403; GUAR3
138 de 403; ALUP11
139 de 403; IRBR3
140 de 403; CPFE3
141 de 403; LAVV3
142 de 403; CSED3
143 de 403; EVEN3
144 de 403; BMOB3
145 de 403; TFCO4
146 de 403; LJQQ3
147 de 403; MYPK3
148 de 403; VVEO3
149 de 403; PLPL3
150 de 403; NEOE3
151 de 403; MTRE3
152 de 403; HBOR3
153 de 403; SHUL4
154 de 403; MELK3
155 de 403; MDNE3
156 de 403; MILS3
157 de 403; ABCB4
158 de 403; RANI3
159 de 403; POSI3
160 de 403; ORVR3
161 de 403; MDIA3
162 de 403; JALL3
163 de 403; FIQE3
164 de 403; PTBL3
165 de 403; BPAN4
166 de 403; SOJA3
167 de 403; ITUB3
168 de 403; PGMN3
169 de 403; JSLG3
170 de 403; SHOW3
171 de 403; VULC3
172 de 403; PDGR3
173 de 403; ARML3
174 de 403; POMO3
175 de 403; USIM3
176 de 403; ELMD3
177 de 403; LIGT3
178 de 403; TRIS3
179 de 403; VTRU3
180 de 403; KLBN3
181 de 403; PRNR3
182 de 403; PINE4
183 de 403; SEQL3
184 de 403; WIZC3
185 de 403; MATD3
186 de 403; RNEW4
187 de 403; SYNE3
188 de 403; PFRM3
189 de 403; MEAL3
190 de 403; RCSL3
191 de 403; ESPA3
192 de 403; BRAP3
193 de 403; PNVL3
194 de 403; OPCT3
195 de 403; LEVE3
196 de 403; DESK3
197 de 403; PORT3
198 de 403; TGMA3
199 de 403; CMIG3
200 de 403; LOGG3
201 de 403; FRAS3
202 de 403; AERI3
203 de 403; TCSA3
204 de 403; SAPR3
205 de 403; TAEE4
206 de 403; DASA3
207 de 403; TASA4
208 de 403; BLAU3
209 de 403; FESA4
210 de 403; BRBI11
211 de 403; BRST3
212 de 403; VITT3
213 de 403; BMGB4
214 de 403; HBRE3
215 de 403; AGRO3
216 de 403; MBLY3
217 de 403; VLID3
218 de 403; INEP3
219 de 403; RNEW3
220 de 403; AGXY3
221 de 403; SANB4
222 de 403; AMAR3
223 de 403; ROMI3
224 de 403; TAEE3
225 de 403; LPSB3
226 de 403; IGTI3
227 de 403; DEXP3
228 de 403; TECN3
229 de 403; INEP4
230 de 403; ALPK3
231 de 403; AALR3
232 de 403; VSTE3
233 de 403; SANB3
234 de 403; RNEW11
235 de 403; VIVR3
236 de 403; CSUD3
237 de 403; ITSA3
238 de 403; AMBP3
239 de 403; DMVF3
240 de 403; ALLD3
241 de 403; OIBR4
242 de 403; EUCA4
243 de 403; PDTC3
244 de 403; ENGI4
245 de 403; UNIP6
246 de 403; TRAD3
247 de 403; GOAU3
248 de 403; ETER3
249 de 403; TPIS3
250 de 403; CAMB3
251 de 403; LVTC3
252 de 403; SCAR3
253 de 403; LUPA3
254 de 403; BIOM3
255 de 403; BOBR4
256 de 403; PTNT4
257 de 403; DEXP4
258 de 403; UCAS3
259 de 403; ATED3
260 de 403; RSID3
261 de 403; CTSA4
262 de 403; GGBR3
263 de 403; OFSA3
264 de 403; COCE5
265 de 403; BEES3
266 de 403; ALUP4
267 de 403; BRKM3
268 de 403; LAND3
269 de 403; EQPA3
270 de 403; BRSR3
271 de 403; ENGI3
272 de 403; BMEB4
273 de 403; CEBR6
274 de 403; CEBR5
275 de 403; RAPT3
276 de 403; CEBR3
277 de 403; EALT4
278 de 403; EPAR3
279 de 403; DOTZ3
280 de 403; TASA3
281 de 403; ATMP3
282 de 403; AMAR11
283 de 403; ALPA3
284 de 403; ALUP3
285 de 403; NGRD3
286 de 403; BPAC5
287 de 403; OSXB3
288 de 403; WLMM4
289 de 403; HAGA4
290 de 403; LOGN3
291 de 403; CGRA4
292 de 403; BPAC3
293 de 403; JFEN3
294 de 403; UNIP3
295 de 403; WHRL4
296 de 403; FHER3
297 de 403; EMAE4
298 de 403; BSLI3
299 de 403; HOOT4
300 de 403; RDNI3
301 de 403; BIED3
302 de 403; BGIP4
303 de 403; NEXP3
304 de 403; AZEV11
305 de 403; CLSC4
306 de 403; ISAE3
307 de 403; AVLL3
308 de 403; CGRA3
309 de 403; RPMG3
310 de 403; BAZA3
311 de 403; BSLI4
312 de 403; REDE3
313 de 403; SNSY5
314 de 403; PINE3
315 de 403; DOHL4
316 de 403; CTSA3
317 de 403; TELB4
318 de 403; REAG3
319 de 403; FICT3
320 de 403; MOAR3
321 de 403; BEES4
322 de 403; NUTR3
323 de 403; WEST3
324 de 403; MTSA4
325 de 403; CRPG5
326 de 403; MNDL3
327 de 403; FIEI3
328 de 403; BMEB3
329 de 403; HAGA3
330 de 403; PATI4
331 de 403; RPAD3
332 de 403; WHRL3
333 de 403; DTCY3
334 de 403; PEAB3
335 de 403; GEPA3
336 de 403; HBTS5
337 de 403; MGEL4
338 de 403; CRPG6
339 de 403; FRIO3
340 de 403; CGAS5
341 de 403; RSUL4
342 de 403; SOND6
343 de 403; CTKA4
344 de 403; JOPA3
345 de 403; BMIN3
346 de 403; BRSR5
347 de 403; BALM3
348 de 403; TELB3
349 de 403; BALM4
350 de 403; CPLE5
351 de 403; AFLT3
352 de 403; GSHP3
353 de 403; NORD3
354 de 403; ESTR4
355 de 403; BMKS3
356 de 403; PPLA11
357 de 403; EQPA5
358 de 403; CEDO4
359 de 403; CEEB3
360 de 403; MNPR3
361 de 403; EUCA3
362 de 403; IGTI4
363 de 403; RPAD5
364 de 403; GEPA4
365 de 403; CEDO3
366 de 403; EALT3
367 de 403; SNSY3
368 de 403; MAPT4
369 de 403; BNBR3
370 de 403; CLSC3
371 de 403; UNIP5
372 de 403; EKTR4
373 de 403; SOND5
374 de 403; MRSA3B
375 de 403; BDLL3
376 de 403; ENMT3
377 de 403; MWET4
378 de 403; WLMM3
379 de 403; PLAS3
380 de 403; PATI3
381 de 403; MRSA5B
382 de 403; CRPG3
383 de 403; PTNT3
384 de 403; HETA4
385 de 403; MERC4
386 de 403; RPAD6
387 de 403; BMIN4
388 de 403; DASA11

404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/DASA11.SA?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=DASA11.SA&crumb=dA.Qhj35YWw

389 de 403; FESA3
390 de 403; ENMT4
391 de 403; EQMA3B
392 de 403; AHEB3
393 de 403; COCE3
394 de 403; BDLL4
395 de 403; USIM6
396 de 403; MAPT3
397 de 403; TKNO4
398 de 403; GPAR3
399 de 403; CGAS3
400 de 403; AHEB6
401 de 403; LUXM4
402 de 403; KRSA3
403 de 403; BAUH4
=== FIM LEITURA DOS DADOS DA AÇÃO ===

,Ticker,Nome da Empresa,Volume no último dia útil,Data da leitura (último dia útil),industry,sector,fullTimeEmployees,dividendRate,dividendYield,exDividendDate,...,ebitdaMargins,operatingMargins,epsTrailingTwelveMonths,epsForward,epsCurrentYear,priceEpsCurrentYear,fiftyDayAverageChange,fiftyDayAverageChangePercent,twoHundredDayAverageChange,twoHundredDayAverageChangePercent
0,AZUL4,Azul,282174900,2025-04-26,Airlines,Industrials,"15,367.00",NaN,NaN,NaN,...,0.18,0.18,-0.35,-0.96,-1.53,-1.28,-1.52,-0.44,-2.95,-0.60
1,CRFB3,Carrefour Brasil,65204900,2025-04-26,Department Stores,Consumer Cyclical,NaN,0.10,1.11,"1,745,971,200.00",...,0.05,0.04,0.83,0.79,0.59,14.70,0.95,0.12,1.07,0.14
2,HAPV3,Hapvida,64731600,2025-04-26,Insurance - Life,Financial Services,NaN,NaN,NaN,"1,640,649,600.00",...,0.07,-0.01,-0.09,0.29,0.20,12.01,0.20,0.09,-0.67,-0.22
3,COGN3,Cogna,37935400,2025-04-26,Education & Training Services,Consumer Defensive,"24,187.00",0.26,10.48,"1,745,884,800.00",...,0.24,0.35,0.46,0.18,0.28,9.07,0.55,0.28,1.00,0.67
4,B3SA3,B3,37609700,2025-04-26,Financial Data & Stock Exchanges,Financial Services,NaN,0.25,1.88,"1,742,947,200.00",...,0.66,0.63,0.83,0.93,0.90,14.86,1.62,0.14,2.27,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1251,LOGN3,Log-In,24500,2025-04-19,Marine Shipping,Industrials,NaN,NaN,NaN,"1,237,334,400.00",...,0.19,0.17,1.41,2.22,0.86,24.71,-0.10,-0.00,-5.79,-0.21
1252,BIOM3,Biomm,23700,2025-04-19,Biotechnology,Healthcare,NaN,NaN,NaN,NaN,...,-0.49,-0.61,-0.63,NaN,NaN,NaN,-0.10,-0.01,0.23,0.02
1253,PTNT4,Pettenati,21300,2025-04-19,Apparel Manufacturing,Consumer Cyclical,NaN,0.27,4.20,"1,730,246,400.00",...,0.10,0.07,0.65,NaN,NaN,NaN,-0.90,-0.12,-0.17,-0.03
1254,ALUP4,Alupar,20200,2025-04-19,Utilities - Renewable,Utilities,906.00,0.32,3.36,"1,744,848,000.00",...,0.73,0.61,1.11,NaN,NaN,NaN,0.33,0.04,0.26,0.03
1255,KRSA3,Kora Saúde,20000,2025-04-19,Medical Care Facilities,Healthcare,NaN,NaN,NaN,NaN,...,0.18,0.10,-0.23,1.03,NaN,NaN,0.14,0.02,1.77,0.25

In [ ]:
# bd_lista_acoes_tratada_empilhada = bd_lista_acoes_tratada_empilhada[~(bd_lista_acoes_tratada_empilhada["Data da leitura (último dia útil)"].isin(["2025-04-26 14:58:12.306", "2025-04-26 15:00:00.000", "2025-04-26 15:06:24.698"]))]

C:\Users\ricardopeloi\AppData\Local\Temp\ipykernel_1732\208725787.py:1: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  bd_lista_acoes_tratada_empilhada = bd_lista_acoes_tratada_empilhada[~(bd_lista_acoes_tratada_empilhada["Data da leitura (último dia útil)"].isin(["2025-04-26 14:58:12.306", "2025-04-26 15:00:00.000", "2025-04-26 15:06:24.698"]))]

In [ ]:
# bd_lista_acoes_tratada_empilhada_check = pd.pivot_table(
#     data = bd_lista_acoes_tratada_empilhada[["Ticker", "Volume no último dia útil", "Data da leitura (último dia útil)"]],
#     # data = bd_lista_acoes_tratada_empilhada_import[["Ticker", "Volume no último dia útil", "Data da leitura (último dia útil)"]],
#     index = "Ticker",
#     columns = "Data da leitura (último dia útil)",
#     values = "Volume no último dia útil",
#     aggfunc = "sum"
# )

# bd_lista_acoes_tratada_empilhada_check

Data da leitura (último dia útil)    2025-04-19    2025-04-26
Ticker
AALR3                                166,800.00     69,900.00
ABCB4                                419,600.00    602,100.00
ABEV3                             56,058,800.00 24,151,500.00
AERI3                                212,100.00    206,900.00
AGRO3                                408,300.00    164,700.00
...                                         ...           ...
VVEO3                              1,862,900.00    874,800.00
WEGE3                              3,543,500.00 10,397,200.00
WIZC3                                219,500.00    326,400.00
YDUQ3                             16,381,600.00  4,671,300.00
ZAMP3                                513,800.00  1,156,800.00

[258 rows x 2 columns]

In [ ]:
# bd_lista_acoes_tratada_empilhada

# bd_lista_acoes_tratada_empilhada.to_excel(var_caminho + '/Lista de ações Tratada.xlsx', index = False)

## 3. detectar_martelos_todos_os_tickers e bd_acoes

In [151]:
import importlib
try:
    importlib.reload(sys.modules['detectar_martelos'])
except:
    pass
from detectar_martelos import detectar_martelos_todos_os_tickers

# bd_arquivo_original = pd.read_excel(r"C:\Users\ricardopeloi\OneDrive - falconi365\Data Science\O_Mais_Novo_Day_Trader_do_Brasil\o_mais_novo_day_trader_do_brasil\Bases\Lista de ações Tratada.xlsx").set_index("Ticker")
# bd_arquivo_original[bd_arquivo_original["Data da leitura (último dia útil)"] == max(bd_arquivo_original["Data da leitura (último dia útil)"])]

bd_acao_historico, bd_acoes = detectar_martelos_todos_os_tickers()

=== LENDO DADOS DE HISTÓRICO ===
1 de 252; AZUL4
2 de 252; CRFB3
3 de 252; HAPV3
4 de 252; COGN3
5 de 252; B3SA3
6 de 252; ITSA4
7 de 252; PETR4
8 de 252; ITUB4
9 de 252; BEEF3
10 de 252; BBDC4
11 de 252; VALE3
12 de 252; CMIG4
13 de 252; ABEV3
14 de 252; RAIZ4
15 de 252; MGLU3
16 de 252; BBAS3
17 de 252; USIM5
18 de 252; CYRE3
19 de 252; LREN3
20 de 252; CPLE6
21 de 252; PCAR3
22 de 252; GGBR4
23 de 252; CSAN3
24 de 252; CCRO3
25 de 252; POMO4
26 de 252; PRIO3
27 de 252; SUZB3
28 de 252; CVCB3
29 de 252; RENT3
30 de 252; RAIL3
31 de 252; LWSA3
32 de 252; IFCM3
33 de 252; BRFS3
34 de 252; MRVE3
35 de 252; VAMO3
36 de 252; WEGE3
37 de 252; MULT3
38 de 252; PETR3
39 de 252; TIMS3
40 de 252; PETZ3
41 de 252; JBSS3
42 de 252; VBBR3
43 de 252; ELET3
44 de 252; CASH3
45 de 252; MRFG3
46 de 252; SRNA3
47 de 252; BRAP4
48 de 252; BPAC11
49 de 252; GOAU4
50 de 252; EQTL3
51 de 252; ENEV3
52 de 252; ANIM3
53 de 252; ASAI3
54 de 252; MOVI3
55 de 252; KLBN11
56 de 252; CSNA3
57 de 252; RDOR3
58 de 252; AZEV4
59 de 252; CPLE3
60 de 252; NTCO3
61 de 252; RADL3
62 de 252; CXSE3
63 de 252; AZTE3
64 de 252; AURE3
65 de 252; BBDC3
66 de 252; RECV3
67 de 252; CMIN3
68 de 252; GFSA3
69 de 252; ALOS3
70 de 252; BRAV3
71 de 252; HYPE3
72 de 252; VIVT3
73 de 252; AMOB3
74 de 252; ECOR3
75 de 252; YDUQ3
76 de 252; OIBR3
77 de 252; JHSF3
78 de 252; TEND3
79 de 252; GMAT3
80 de 252; ENGI11
81 de 252; SIMH3
82 de 252; UGPA3
83 de 252; VIVA3
84 de 252; SBSP3
85 de 252; STBP3
86 de 252; CEAB3
87 de 252; EMBR3
88 de 252; BBSE3
89 de 252; SLCE3
90 de 252; BRKM5
91 de 252; SMFT3
92 de 252; CBAV3
93 de 252; BHIA3
94 de 252; ONCO3
95 de 252; ISAE4
96 de 252; CURY3
97 de 252; EZTC3
98 de 252; TAEE11
99 de 252; KEPL3
100 de 252; SAPR4
101 de 252; RCSL4
102 de 252; SANB11
103 de 252; RAPT4
104 de 252; FLRY3
105 de 252; TOTS3
106 de 252; AZZA3
107 de 252; GOLL4
108 de 252; SMTO3
109 de 252; HBSA3
110 de 252; ENJU3
111 de 252; SBFG3
112 de 252; AMER3
113 de 252; DIRR3
114 de 252; PMAM3
115 de 252; TTEN3
116 de 252; AZEV3
117 de 252; CAML3
118 de 252; GGPS3
119 de 252; SEER3
120 de 252; GRND3
121 de 252; TUPY3
122 de 252; SAPR11
123 de 252; ELET6
124 de 252; PSSA3
125 de 252; QUAL3
126 de 252; BRSR6
127 de 252; EGIE3
128 de 252; ODPV3
129 de 252; ALPA4
130 de 252; CSMG3
131 de 252; INTB3
132 de 252; DXCO3
133 de 252; ZAMP3
134 de 252; MLAS3
135 de 252; KLBN4
136 de 252; GUAR3
137 de 252; ALUP11
138 de 252; IRBR3
139 de 252; CPFE3
140 de 252; LAVV3
141 de 252; CSED3
142 de 252; EVEN3
143 de 252; BMOB3
144 de 252; TFCO4
145 de 252; LJQQ3
146 de 252; MYPK3
147 de 252; VVEO3
148 de 252; PLPL3
149 de 252; NEOE3
150 de 252; MTRE3
151 de 252; HBOR3
152 de 252; SHUL4
153 de 252; MELK3
154 de 252; MDNE3
155 de 252; MILS3
156 de 252; ABCB4
157 de 252; RANI3
158 de 252; POSI3
159 de 252; ORVR3
160 de 252; MDIA3
161 de 252; JALL3
162 de 252; FIQE3
163 de 252; PTBL3
164 de 252; BPAN4
165 de 252; SOJA3
166 de 252; ITUB3
167 de 252; PGMN3
168 de 252; JSLG3
169 de 252; VULC3
170 de 252; ARML3
171 de 252; POMO3
172 de 252; USIM3
173 de 252; ELMD3
174 de 252; LIGT3
175 de 252; TRIS3
176 de 252; VTRU3
177 de 252; KLBN3
178 de 252; PRNR3
179 de 252; PINE4
180 de 252; SEQL3
181 de 252; WIZC3
182 de 252; MATD3
183 de 252; RNEW4
184 de 252; SYNE3
185 de 252; PFRM3
186 de 252; MEAL3
187 de 252; RCSL3
188 de 252; ESPA3
189 de 252; BRAP3
190 de 252; PNVL3
191 de 252; OPCT3
192 de 252; LEVE3
193 de 252; DESK3
194 de 252; PORT3
195 de 252; TGMA3
196 de 252; CMIG3
197 de 252; LOGG3
198 de 252; FRAS3
199 de 252; AERI3
200 de 252; TCSA3
201 de 252; SAPR3
202 de 252; TAEE4
203 de 252; DASA3
204 de 252; TASA4
205 de 252; BLAU3
206 de 252; FESA4
207 de 252; VITT3
208 de 252; BMGB4
209 de 252; HBRE3
210 de 252; AGRO3
211 de 252; MBLY3
212 de 252; VLID3
213 de 252; INEP3
214 de 252; RNEW3
215 de 252; AGXY3
216 de 252; SANB4
217 de 252; AMAR3
218 de 252; ROMI3
219 de 252; TAEE3
220 de 252; LPSB3
221 de 252; IGTI3
222 de 252; DEXP3
223 de 252; TECN3
224 de 252; INEP4
225 de 252; ALPK3
226 de 252; AALR3
227 de 252; VSTE3
228 de 252; SANB3
229 de 252; RNEW11
230 de 252; CSUD3
231 de 252; ITSA3
232 de 252; AMBP3
233 de 252; DMVF3
234 de 252; ALLD3
235 de 252; OIBR4
236 de 252; EUCA4
237 de 252; PDTC3
238 de 252; ENGI4
239 de 252; UNIP6
240 de 252; TRAD3
241 de 252; GOAU3
242 de 252; ETER3
243 de 252; TPIS3
244 de 252; CAMB3
245 de 252; LVTC3
246 de 252; SCAR3
247 de 252; LUPA3
248 de 252; BIOM3
249 de 252; BOBR4
250 de 252; PTNT4
251 de 252; DEXP4
252 de 252; UCAS3
=== FIM DA LEITURA DOS DADOS DE HISTÓRICO ===

In [104]:
bd_acoes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          180 non-null    datetime64[ns]
 1   Open          180 non-null    float64
 2   High          180 non-null    float64
 3   Low           180 non-null    float64
 4   Close         180 non-null    float64
 5   Volume        180 non-null    int64
 6   Dividends     180 non-null    float64
 7   Stock Splits  180 non-null    float64
 8   HLC           180 non-null    float64
 9   Ticker        180 non-null    object
dtypes: datetime64[ns](1), float64(7), int64(1), object(1)
memory usage: 14.2+ KB

In [148]:
bd_acoes_import = pd.read_excel(r"C:\Users\ricardopeloi\OneDrive - falconi365\Data Science\O_Mais_Novo_Day_Trader_do_Brasil\o_mais_novo_day_trader_do_brasil\Bases\Base de Dados Histórico.xlsx",index_col = 0).reset_index()

bd_acoes_import.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9416 entries, 0 to 9415
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          9416 non-null   datetime64[ns]
 1   Open          9410 non-null   float64
 2   High          9410 non-null   float64
 3   Low           9410 non-null   float64
 4   Close         9410 non-null   float64
 5   Volume        9416 non-null   int64
 6   Dividends     9416 non-null   float64
 7   Stock Splits  9416 non-null   float64
 8   HLC           9410 non-null   float64
 9   Ticker        9416 non-null   object
dtypes: datetime64[ns](1), float64(7), int64(1), object(1)
memory usage: 735.8+ KB

In [141]:
# display(datetime.today())
display(datetime.now().replace(hour=0, minute=0, second=0, microsecond=0))
# type(max(bd_acoes_import["Date"]).date())

display(datetime.now().replace(hour=0, minute=0, second=0, microsecond=0))
display(max(bd_acoes_import["Date"]).date())

acao = bd_acoes_import["Ticker"][0]
yf.Ticker(acao + ".SA").history(
    # start = max(bd_acoes_import["Date"]).date(),
    start = datetime.today(),
    end = datetime.today(),
    interval = "1d"
)

datetime.datetime(2025, 4, 26, 0, 0)

datetime.datetime(2025, 4, 26, 0, 0)

datetime.date(2025, 4, 25)

$HAPV3.SA: possibly delisted; no price data found  (1d 2025-04-26 18:36:11.466739 -> 2025-04-26 18:36:11.466743)

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [152]:
bd_acoes_empilhada = pd.concat([bd_acoes_import, bd_acoes]).drop_duplicates(subset = ["Date", "Ticker"])

display(bd_acoes_empilhada[bd_acoes_empilhada["Open"].isna()])
display(bd_acoes_empilhada)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,HLC,Ticker
665,2025-04-25,NaN,NaN,NaN,NaN,0,0.20,0.00,NaN,CPLE6
1576,2025-04-25,NaN,NaN,NaN,NaN,0,0.05,0.00,NaN,ANIM3
2137,2025-04-25,NaN,NaN,NaN,NaN,0,0.21,0.00,NaN,CPLE3
2768,2025-04-25,NaN,NaN,NaN,NaN,0,0.06,0.00,NaN,AURE3
6094,2025-04-25,NaN,NaN,NaN,NaN,0,0.69,0.00,NaN,BMOB3
8853,2025-04-25,NaN,NaN,NaN,NaN,0,0.07,0.00,NaN,LAND3

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,HLC,Ticker
0,2025-03-05,2.07,2.14,1.98,2.13,77802900,0.00,0.00,2.08,HAPV3
1,2025-03-06,2.13,2.16,2.07,2.08,66517100,0.00,0.00,2.10,HAPV3
2,2025-03-07,2.08,2.22,2.06,2.17,97225000,0.00,0.00,2.15,HAPV3
3,2025-03-10,2.14,2.15,2.05,2.05,78062300,0.00,0.00,2.08,HAPV3
4,2025-03-11,2.06,2.09,2.03,2.06,59563500,0.00,0.00,2.06,HAPV3
...,...,...,...,...,...,...,...,...,...,...
9411,2025-04-22,7.59,7.70,7.59,7.63,3900,0.00,0.00,7.64,DEXP4
9412,2025-04-23,7.68,7.70,7.63,7.69,14200,0.00,0.00,7.67,DEXP4
9413,2025-04-24,7.68,7.80,7.68,7.80,8700,0.00,0.00,7.76,DEXP4
9414,2025-04-25,7.79,7.85,7.79,7.81,20700,0.00,0.00,7.82,DEXP4
9415,2025-04-25,1.58,1.63,1.58,1.58,20100,0.00,0.00,1.60,UCAS3

In [154]:
import importlib
try:
    importlib.reload(sys.modules['detectar_martelos'])
except:
    pass
from detectar_martelos import candle_plot

# var_acao = "HAPV3"
var_acao = "VAMO3"

display(bd_acoes_empilhada[bd_acoes_empilhada["Ticker"] == var_acao])

candle_plot( # Usa o navegador para criar o gráfico interativo
    bd_acoes_empilhada[bd_acoes_empilhada["Ticker"] == var_acao].set_index("Date"),
    volume = True,
    mav = np.nan,
    colors = ["orange", "yellow", "blue"],
    titulo = "",
)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,HLC,Ticker
1016,2025-03-05,3.85,3.90,3.68,3.70,7801900,0.00,0.00,3.76,VAMO3
1017,2025-03-06,3.75,3.78,3.59,3.65,11312000,0.00,0.00,3.67,VAMO3
1018,2025-03-07,3.65,3.95,3.59,3.82,13260500,0.00,0.00,3.79,VAMO3
1019,2025-03-10,3.77,3.90,3.71,3.75,8562400,0.00,0.00,3.79,VAMO3
1020,2025-03-11,3.77,3.84,3.70,3.77,8460700,0.00,0.00,3.77,VAMO3
1021,2025-03-12,3.76,3.86,3.67,3.71,6936900,0.00,0.00,3.75,VAMO3
1022,2025-03-13,3.70,3.72,3.54,3.58,10969800,0.00,0.00,3.61,VAMO3
1023,2025-03-14,3.62,3.95,3.61,3.95,20638800,0.00,0.00,3.84,VAMO3
1024,2025-03-17,3.96,4.30,3.93,4.19,13598800,0.00,0.00,4.14,VAMO3
1025,2025-03-18,4.23,4.26,4.02,4.08,9378100,0.00,0.00,4.12,VAMO3
1026,2025-03-19,4.11,4.32,4.01,4.30,5881900,0.00,0.00,4.21,VAMO3
1027,2025-03-20,4.25,4.33,4.17,4.24,4703700,0.00,0.00,4.25,VAMO3
1028,2025-03-21,4.25,4.50,4.20,4.37,9827300,0.00,0.00,4.36,VAMO3
1029,2025-03-24,4.38,4.46,4.29,4.29,7771800,0.00,0.00,4.35,VAMO3
1030,2025-03-25,4.71,5.05,4.68,4.96,18547600,0.00,0.00,4.90,VAMO3
1031,2025-03-26,5.02,5.32,4.94,5.27,21751900,0.00,0.00,5.18,VAMO3
1032,2025-03-27,5.28,5.34,5.15,5.15,10559900,0.00,0.00,5.21,VAMO3
1033,2025-03-28,5.10,5.10,4.67,4.67,34351000,0.00,0.00,4.81,VAMO3
1034,2025-03-31,4.62,4.62,4.36,4.39,18166200,0.00,0.00,4.46,VAMO3
1035,2025-04-01,4.35,4.57,4.31,4.43,17051900,0.00,0.00,4.44,VAMO3
1036,2025-04-02,4.42,4.86,4.40,4.74,19691500,0.00,0.00,4.67,VAMO3
1037,2025-04-03,4.69,5.08,4.68,4.84,19909000,0.00,0.00,4.87,VAMO3
1038,2025-04-04,4.64,4.64,4.32,4.36,16756300,0.00,0.00,4.44,VAMO3
1039,2025-04-07,4.18,4.46,4.13,4.23,11947600,0.00,0.00,4.27,VAMO3
1040,2025-04-08,4.30,4.42,4.09,4.13,11753300,0.00,0.00,4.21,VAMO3
1041,2025-04-09,3.99,4.45,3.97,4.35,14177600,0.00,0.00,4.26,VAMO3
1042,2025-04-10,4.37,4.37,4.15,4.32,9614600,0.00,0.00,4.28,VAMO3
1043,2025-04-11,4.45,4.92,4.41,4.87,16814500,0.00,0.00,4.73,VAMO3
1044,2025-04-14,4.96,5.05,4.69,4.85,13698700,0.00,0.00,4.86,VAMO3
1045,2025-04-15,4.81,4.96,4.74,4.89,6920700,0.00,0.00,4.86,VAMO3
1046,2025-04-16,4.84,5.02,4.79,4.82,6577900,0.00,0.00,4.88,VAMO3
1047,2025-04-17,4.86,5.04,4.76,4.99,6084100,0.00,0.00,4.93,VAMO3
1048,2025-04-22,4.92,5.14,4.85,4.97,9491500,0.00,0.00,4.99,VAMO3
1049,2025-04-23,5.10,5.22,5.01,5.05,12155400,0.00,0.00,5.09,VAMO3
1050,2025-04-24,5.07,5.53,5.05,5.43,12722500,0.00,0.00,5.34,VAMO3
8922,2025-04-25,5.44,5.49,5.32,5.36,10483000,0.00,0.00,5.39,VAMO3

## 4. detectar_martelos_todos_os_tickers e gerar_arquivo_historico

In [155]:
import importlib
try:
    importlib.reload(sys.modules['detectar_martelos'])
except:
    pass
from detectar_martelos import gerar_arquivo_historico

gerar_arquivo_historico()

=== LENDO DADOS DE HISTÓRICO ===
1 de 252; AZUL4
2 de 252; CRFB3
3 de 252; HAPV3
4 de 252; COGN3
5 de 252; B3SA3
6 de 252; ITSA4
7 de 252; PETR4
8 de 252; ITUB4
9 de 252; BEEF3
10 de 252; BBDC4
11 de 252; VALE3
12 de 252; CMIG4
13 de 252; ABEV3
14 de 252; RAIZ4
15 de 252; MGLU3
16 de 252; BBAS3
17 de 252; USIM5
18 de 252; CYRE3
19 de 252; LREN3
20 de 252; CPLE6
21 de 252; PCAR3
22 de 252; GGBR4
23 de 252; CSAN3
24 de 252; CCRO3
25 de 252; POMO4
26 de 252; PRIO3
27 de 252; SUZB3
28 de 252; CVCB3
29 de 252; RENT3
30 de 252; RAIL3
31 de 252; LWSA3
32 de 252; IFCM3
33 de 252; BRFS3
34 de 252; MRVE3
35 de 252; VAMO3
36 de 252; WEGE3
37 de 252; MULT3
38 de 252; PETR3
39 de 252; TIMS3
40 de 252; PETZ3
41 de 252; JBSS3
42 de 252; VBBR3
43 de 252; ELET3
44 de 252; CASH3
45 de 252; MRFG3
46 de 252; SRNA3
47 de 252; BRAP4
48 de 252; BPAC11
49 de 252; GOAU4
50 de 252; EQTL3
51 de 252; ENEV3
52 de 252; ANIM3
53 de 252; ASAI3
54 de 252; MOVI3
55 de 252; KLBN11
56 de 252; CSNA3
57 de 252; RDOR3
58 de 252; AZEV4
59 de 252; CPLE3
60 de 252; NTCO3
61 de 252; RADL3
62 de 252; CXSE3
63 de 252; AZTE3
64 de 252; AURE3
65 de 252; BBDC3
66 de 252; RECV3
67 de 252; CMIN3
68 de 252; GFSA3
69 de 252; ALOS3
70 de 252; BRAV3
71 de 252; HYPE3
72 de 252; VIVT3
73 de 252; AMOB3
74 de 252; ECOR3
75 de 252; YDUQ3
76 de 252; OIBR3
77 de 252; JHSF3
78 de 252; TEND3
79 de 252; GMAT3
80 de 252; ENGI11
81 de 252; SIMH3
82 de 252; UGPA3
83 de 252; VIVA3
84 de 252; SBSP3
85 de 252; STBP3
86 de 252; CEAB3
87 de 252; EMBR3
88 de 252; BBSE3
89 de 252; SLCE3
90 de 252; BRKM5
91 de 252; SMFT3
92 de 252; CBAV3
93 de 252; BHIA3
94 de 252; ONCO3
95 de 252; ISAE4
96 de 252; CURY3
97 de 252; EZTC3
98 de 252; TAEE11
99 de 252; KEPL3
100 de 252; SAPR4
101 de 252; RCSL4
102 de 252; SANB11
103 de 252; RAPT4
104 de 252; FLRY3
105 de 252; TOTS3
106 de 252; AZZA3
107 de 252; GOLL4
108 de 252; SMTO3
109 de 252; HBSA3
110 de 252; ENJU3
111 de 252; SBFG3
112 de 252; AMER3
113 de 252; DIRR3
114 de 252; PMAM3
115 de 252; TTEN3
116 de 252; AZEV3
117 de 252; CAML3
118 de 252; GGPS3
119 de 252; SEER3
120 de 252; GRND3
121 de 252; TUPY3
122 de 252; SAPR11
123 de 252; ELET6
124 de 252; PSSA3
125 de 252; QUAL3
126 de 252; BRSR6
127 de 252; EGIE3
128 de 252; ODPV3
129 de 252; ALPA4
130 de 252; CSMG3
131 de 252; INTB3
132 de 252; DXCO3
133 de 252; ZAMP3
134 de 252; MLAS3
135 de 252; KLBN4
136 de 252; GUAR3
137 de 252; ALUP11
138 de 252; IRBR3
139 de 252; CPFE3
140 de 252; LAVV3
141 de 252; CSED3
142 de 252; EVEN3
143 de 252; BMOB3
144 de 252; TFCO4
145 de 252; LJQQ3
146 de 252; MYPK3
147 de 252; VVEO3
148 de 252; PLPL3
149 de 252; NEOE3
150 de 252; MTRE3
151 de 252; HBOR3
152 de 252; SHUL4
153 de 252; MELK3
154 de 252; MDNE3
155 de 252; MILS3
156 de 252; ABCB4
157 de 252; RANI3
158 de 252; POSI3
159 de 252; ORVR3
160 de 252; MDIA3
161 de 252; JALL3
162 de 252; FIQE3
163 de 252; PTBL3
164 de 252; BPAN4
165 de 252; SOJA3
166 de 252; ITUB3
167 de 252; PGMN3
168 de 252; JSLG3
169 de 252; VULC3
170 de 252; ARML3
171 de 252; POMO3
172 de 252; USIM3
173 de 252; ELMD3
174 de 252; LIGT3
175 de 252; TRIS3
176 de 252; VTRU3
177 de 252; KLBN3
178 de 252; PRNR3
179 de 252; PINE4
180 de 252; SEQL3
181 de 252; WIZC3
182 de 252; MATD3
183 de 252; RNEW4
184 de 252; SYNE3
185 de 252; PFRM3
186 de 252; MEAL3
187 de 252; RCSL3
188 de 252; ESPA3
189 de 252; BRAP3
190 de 252; PNVL3
191 de 252; OPCT3
192 de 252; LEVE3
193 de 252; DESK3
194 de 252; PORT3
195 de 252; TGMA3
196 de 252; CMIG3
197 de 252; LOGG3
198 de 252; FRAS3
199 de 252; AERI3
200 de 252; TCSA3
201 de 252; SAPR3
202 de 252; TAEE4
203 de 252; DASA3
204 de 252; TASA4
205 de 252; BLAU3
206 de 252; FESA4
207 de 252; VITT3
208 de 252; BMGB4
209 de 252; HBRE3
210 de 252; AGRO3
211 de 252; MBLY3
212 de 252; VLID3
213 de 252; INEP3
214 de 252; RNEW3
215 de 252; AGXY3
216 de 252; SANB4
217 de 252; AMAR3
218 de 252; ROMI3
219 de 252; TAEE3
220 de 252; LPSB3
221 de 252; IGTI3
222 de 252; DEXP3
223 de 252; TECN3
224 de 252; INEP4
225 de 252; ALPK3
226 de 252; AALR3
227 de 252; VSTE3
228 de 252; SANB3
229 de 252; RNEW11
230 de 252; CSUD3
231 de 252; ITSA3
232 de 252; AMBP3
233 de 252; DMVF3
234 de 252; ALLD3
235 de 252; OIBR4
236 de 252; EUCA4
237 de 252; PDTC3
238 de 252; ENGI4
239 de 252; UNIP6
240 de 252; TRAD3
241 de 252; GOAU3
242 de 252; ETER3
243 de 252; TPIS3
244 de 252; CAMB3
245 de 252; LVTC3
246 de 252; SCAR3
247 de 252; LUPA3
248 de 252; BIOM3
249 de 252; BOBR4
250 de 252; PTNT4
251 de 252; DEXP4
252 de 252; UCAS3
=== FIM DA LEITURA DOS DADOS DE HISTÓRICO ===

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,HLC,Ticker
0,2025-04-25,2.33,2.40,1.94,1.95,281053900,0.00,0.00,2.10,AZUL4
1,2025-04-25,8.66,8.76,8.53,8.64,65204100,0.00,0.00,8.64,CRFB3
2,2025-04-25,2.44,2.45,2.37,2.41,63722300,0.00,0.00,2.41,HAPV3
3,2025-04-25,2.53,2.56,2.48,2.50,37880500,0.00,0.00,2.51,COGN3
4,2025-04-25,13.11,13.44,13.04,13.39,37600600,0.00,0.00,13.29,B3SA3
...,...,...,...,...,...,...,...,...,...,...
247,2025-04-25,10.00,10.20,9.80,10.14,25700,0.00,0.00,10.05,BIOM3
248,2025-04-25,1.65,1.70,1.63,1.68,25200,0.00,0.00,1.67,BOBR4
249,2025-04-25,6.30,6.36,6.07,6.07,22900,0.00,0.00,6.17,PTNT4
250,2025-04-25,7.79,7.85,7.79,7.81,19200,0.00,0.00,7.82,DEXP4
251,2025-04-25,1.58,1.63,1.58,1.58,18700,0.00,0.00,1.60,UCAS3

In [157]:
bd_acoes_import = pd.read_excel(r"C:\Users\ricardopeloi\OneDrive - falconi365\Data Science\O_Mais_Novo_Day_Trader_do_Brasil\o_mais_novo_day_trader_do_brasil\Bases\Base de Dados Histórico.xlsx",index_col = 0).reset_index()

# bd_acoes_import.info()

import importlib
try:
    importlib.reload(sys.modules['detectar_martelos'])
except:
    pass
from detectar_martelos import candle_plot

var_acao = "HAPV3"
# var_acao = "VAMO3"

# display(bd_acoes_import[bd_acoes_import["Ticker"] == var_acao])

candle_plot( # Usa o navegador para criar o gráfico interativo
    bd_acoes_import[bd_acoes_import["Ticker"] == var_acao].set_index("Date"),
    volume = True,
    mav = np.nan,
    colors = ["orange", "yellow", "blue"],
    titulo = "",
)

## 5. detectar_martelos_todos_os_tickers e bd_acao_historico

In [106]:
bd_acao_historico

,Ticker,Nome da Empresa,Volume no último dia útil,Data da leitura (último dia útil),industry,sector,fullTimeEmployees,dividendRate,dividendYield,exDividendDate,...,2025-04-25; Low,2025-04-25; Close,2025-04-25; Volume,2025-04-25; Dividends,2025-04-25; Stock Splits,2025-04-25; HLC,Alfa HLC; últimos 13 dias,Alfa HLC; últimos 55 dias,Martelos,Tipos de Martelos
0,AZUL4,Azul,282174900,2025-04-26,Airlines,Industrials,"15,367.00",NaN,NaN,NaN,...,1.94,1.95,282174900,0.00,0.00,2.10,-0.04,-0.03,"2025-03-05, 2025-03-10, 2025-03-12, 2025-03-19...","Descida, Descida, Descida, Subida, Descida, Su..."
1,CRFB3,Carrefour Brasil,65204900,2025-04-26,Department Stores,Consumer Cyclical,NaN,0.10,1.11,"1,745,971,200.00",...,8.53,8.64,65204900,0.00,0.00,8.64,0.04,0.04,"2025-03-11, 2025-03-17, 2025-04-02, 2025-04-08...","Subida, Subida, Descida, Subida, Descida, Desc..."
2,HAPV3,Hapvida,64731600,2025-04-26,Insurance - Life,Financial Services,NaN,NaN,NaN,"1,640,649,600.00",...,2.37,2.41,64738600,0.00,0.00,2.41,0.02,0.00,"2025-03-11, 2025-03-13, 2025-03-26, 2025-04-01...","Subida, Subida, Subida, Subida, Subida, Subida..."
3,COGN3,Cogna,37935400,2025-04-26,Education & Training Services,Consumer Defensive,"24,187.00",0.26,10.48,"1,745,884,800.00",...,2.48,2.50,37935400,0.00,0.00,2.51,0.04,0.03,"2025-03-06, 2025-03-17, 2025-03-20, 2025-03-21...","Subida, Subida, Subida, Subida, Subida, Subida..."
4,B3SA3,B3,37609700,2025-04-26,Financial Data & Stock Exchanges,Financial Services,NaN,0.25,1.88,"1,742,947,200.00",...,13.04,13.39,37617800,0.00,0.00,13.29,0.10,0.05,"2025-03-21, 2025-03-26, 2025-03-27, 2025-03-28...","Subida, Descida, Descida, Descida, Subida, Sub..."